#' Retrieve effrs afscms data from afs database
#' 
#' @param STATE_COUNTY_COMPLIANCE_SOURCE e.g. '0100100001'. See Details.
#' @param EPA_PLANT_ID e.g. '110011734935'. See Details.
#' @param PLANT_ID e.g. '0013025'. See Details.
#' @param REGION_CODE e.g. '04'. See Details.
#' @param STATE_ABBREV e.g. 'AL'. See Details.
#' @param STATE_NAME e.g. 'ALABAMA'. See Details.
#' @param COUNTY_NAME e.g. 'AUTAUGA'. See Details.
#' @param DUN_BRADSTREET_NUMBER e.g. '039044318'. See Details.
#' @param CMS_SOURCE_CATEGORY e.g. 'A'. See Details.
#' @param CMS_START_DATE e.g. '01-OCT-01'. See Details.
#' @param FY2008_CMS_IND e.g. 'A'. See Details.
#' @param FY2008_CMS_IND_DESC e.g. 'TITLE V MAJOR'. See Details.
#' @param FY2009_CMS_IND e.g. 'A'. See Details.
#' @param FY2009_CMS_IND_DESC e.g. 'TITLE V MAJOR'. See Details.
#' @param FY2010_CMS_IND e.g. 'A'. See Details.
#' @param FY2010_CMS_IND_DESC e.g. 'TITLE V MAJOR'. See Details.
#' @param FY2011_CMS_IND e.g. 'A'. See Details.
#' @param FY2011_CMS_IND_DESC e.g. 'TITLE V MAJOR'. See Details.
#' @param FY2012_CMS_IND e.g. 'A'. See Details.
#' @param FY2012_CMS_IND_DESC e.g. 'TITLE V MAJOR'. See Details.
#' @param FY2013_CMS_IND e.g. 'A'. See Details.
#' @param FY2013_CMS_IND_DESC e.g. 'TITLE V MAJOR'. See Details.
#' @param FY2014_CMS_IND e.g. 'NA'. See Details.
#' @param FY2014_CMS_IND_DESC e.g. 'NA'. See Details.
#' @param FY2015_CMS_IND e.g. 'NA'. See Details.
#' @param FY2015_CMS_IND_DESC e.g. 'NA'. See Details.
#' @export

afs_effrs_afscms <- function(STATE_COUNTY_COMPLIANCE_SOURCE = NULL, EPA_PLANT_ID = NULL, 
    PLANT_ID = NULL, REGION_CODE = NULL, STATE_ABBREV = NULL, STATE_NAME = NULL, 
    COUNTY_NAME = NULL, DUN_BRADSTREET_NUMBER = NULL, CMS_SOURCE_CATEGORY = NULL, 
    CMS_START_DATE = NULL, FY2008_CMS_IND = NULL, FY2008_CMS_IND_DESC = NULL, FY2009_CMS_IND = NULL, 
    FY2009_CMS_IND_DESC = NULL, FY2010_CMS_IND = NULL, FY2010_CMS_IND_DESC = NULL, 
    FY2011_CMS_IND = NULL, FY2011_CMS_IND_DESC = NULL, FY2012_CMS_IND = NULL, FY2012_CMS_IND_DESC = NULL, 
    FY2013_CMS_IND = NULL, FY2013_CMS_IND_DESC = NULL, FY2014_CMS_IND = NULL, FY2014_CMS_IND_DESC = NULL, 
    FY2015_CMS_IND = NULL, FY2015_CMS_IND_DESC = NULL) {
    
    args <- list(STATE_COUNTY_COMPLIANCE_SOURCE = STATE_COUNTY_COMPLIANCE_SOURCE, 
        EPA_PLANT_ID = EPA_PLANT_ID, PLANT_ID = PLANT_ID, REGION_CODE = REGION_CODE, 
        STATE_ABBREV = STATE_ABBREV, STATE_NAME = STATE_NAME, COUNTY_NAME = COUNTY_NAME, 
        DUN_BRADSTREET_NUMBER = DUN_BRADSTREET_NUMBER, CMS_SOURCE_CATEGORY = CMS_SOURCE_CATEGORY, 
        CMS_START_DATE = CMS_START_DATE, FY2008_CMS_IND = FY2008_CMS_IND, FY2008_CMS_IND_DESC = FY2008_CMS_IND_DESC, 
        FY2009_CMS_IND = FY2009_CMS_IND, FY2009_CMS_IND_DESC = FY2009_CMS_IND_DESC, 
        FY2010_CMS_IND = FY2010_CMS_IND, FY2010_CMS_IND_DESC = FY2010_CMS_IND_DESC, 
        FY2011_CMS_IND = FY2011_CMS_IND, FY2011_CMS_IND_DESC = FY2011_CMS_IND_DESC, 
        FY2012_CMS_IND = FY2012_CMS_IND, FY2012_CMS_IND_DESC = FY2012_CMS_IND_DESC, 
        FY2013_CMS_IND = FY2013_CMS_IND, FY2013_CMS_IND_DESC = FY2013_CMS_IND_DESC, 
        FY2014_CMS_IND = FY2014_CMS_IND, FY2014_CMS_IND_DESC = FY2014_CMS_IND_DESC, 
        FY2015_CMS_IND = FY2015_CMS_IND, FY2015_CMS_IND_DESC = FY2015_CMS_IND_DESC)
    ret <- envir_get(effrs_afscms, args)
    
    ret
} 
