#' Retrieve effrs afsap data from afs database
#' 
#' @param STATE_COUNTY_COMPLIANCE_SOURCE e.g. '0100100001'. See Details.
#' @param AIR_PROGRAM_CODE e.g. '9'. See Details.
#' @param AIR_PROGRAM_DESC e.g. 'NSPS'. See Details.
#' @param AIR_PROGRAM_STATUS e.g. 'O'. See Details.
#' @param AIR_PROGRAM_STATUS_DESC e.g. 'OPERATING'. See Details.
#' @param AIR_PROGRAM_SUBPART e.g. 'BB'. See Details.
#' @param AIR_PROGRAM_SUBPART_DESC e.g. 'KRAFT PULP MILLS'. See Details.
#' @param ES_CLASS_CODE e.g. 'C'. See Details.
#' @param ES_CLASS_CODE_DESC e.g. 'CLASS IS UNKNOWN.'. See Details.
#' @param ES_COMPLIANCE_STATUS e.g. '3'. See Details.
#' @param ES_COMPLIANCE_STATUS_DESC e.g. 'IN COMPLIANCE - INSPECTIO'. See Details.
#' @param EPA_CLASS_CODE e.g. 'NA'. See Details.
#' @param EPA_CLASS_CODE_DESC e.g. 'NA'. See Details.
#' @param EPA_COMPLIANCE_STATUS e.g. 'NA'. See Details.
#' @param EPA_COMPLIANCE_STATUS_DESC e.g. 'NA'. See Details.
#' @param STATE_CLASS_CODE e.g. 'C'. See Details.
#' @param STATE_CLASS_CODE_DESC e.g. 'CLASS IS UNKNOWN.'. See Details.
#' @param STATE_COMPLIANCE_STATUS e.g. '3'. See Details.
#' @param STATE_COMPLIANCE_STATUS_DESC e.g. 'IN COMPLIANCE - INSPECTIO'. See Details.
#' @param AIR_PROGRAMS e.g. 'AMV069'. See Details.
#' @export

afs_effrs_afsap <- function(STATE_COUNTY_COMPLIANCE_SOURCE = NULL, AIR_PROGRAM_CODE = NULL, 
    AIR_PROGRAM_DESC = NULL, AIR_PROGRAM_STATUS = NULL, AIR_PROGRAM_STATUS_DESC = NULL, 
    AIR_PROGRAM_SUBPART = NULL, AIR_PROGRAM_SUBPART_DESC = NULL, ES_CLASS_CODE = NULL, 
    ES_CLASS_CODE_DESC = NULL, ES_COMPLIANCE_STATUS = NULL, ES_COMPLIANCE_STATUS_DESC = NULL, 
    EPA_CLASS_CODE = NULL, EPA_CLASS_CODE_DESC = NULL, EPA_COMPLIANCE_STATUS = NULL, 
    EPA_COMPLIANCE_STATUS_DESC = NULL, STATE_CLASS_CODE = NULL, STATE_CLASS_CODE_DESC = NULL, 
    STATE_COMPLIANCE_STATUS = NULL, STATE_COMPLIANCE_STATUS_DESC = NULL, AIR_PROGRAMS = NULL) {
    
    args <- list(STATE_COUNTY_COMPLIANCE_SOURCE = STATE_COUNTY_COMPLIANCE_SOURCE, 
        AIR_PROGRAM_CODE = AIR_PROGRAM_CODE, AIR_PROGRAM_DESC = AIR_PROGRAM_DESC, 
        AIR_PROGRAM_STATUS = AIR_PROGRAM_STATUS, AIR_PROGRAM_STATUS_DESC = AIR_PROGRAM_STATUS_DESC, 
        AIR_PROGRAM_SUBPART = AIR_PROGRAM_SUBPART, AIR_PROGRAM_SUBPART_DESC = AIR_PROGRAM_SUBPART_DESC, 
        ES_CLASS_CODE = ES_CLASS_CODE, ES_CLASS_CODE_DESC = ES_CLASS_CODE_DESC, ES_COMPLIANCE_STATUS = ES_COMPLIANCE_STATUS, 
        ES_COMPLIANCE_STATUS_DESC = ES_COMPLIANCE_STATUS_DESC, EPA_CLASS_CODE = EPA_CLASS_CODE, 
        EPA_CLASS_CODE_DESC = EPA_CLASS_CODE_DESC, EPA_COMPLIANCE_STATUS = EPA_COMPLIANCE_STATUS, 
        EPA_COMPLIANCE_STATUS_DESC = EPA_COMPLIANCE_STATUS_DESC, STATE_CLASS_CODE = STATE_CLASS_CODE, 
        STATE_CLASS_CODE_DESC = STATE_CLASS_CODE_DESC, STATE_COMPLIANCE_STATUS = STATE_COMPLIANCE_STATUS, 
        STATE_COMPLIANCE_STATUS_DESC = STATE_COMPLIANCE_STATUS_DESC, AIR_PROGRAMS = AIR_PROGRAMS)
    ret <- envir_get(effrs_afsap, args)
    
    ret
} 
