#' Retrieve effrs afsplt1 data from afs database
#' 
#' @param EPA_PLANT_ID e.g. '110000307695'. See Details.
#' @param PLANT_ID e.g. '1011473'. See Details.
#' @param REGION_CODE e.g. '02'. See Details.
#' @param STATE_ABBREV e.g. 'PR'. See Details.
#' @param STATE_NAME e.g. 'PUERTO RICO'. See Details.
#' @param COUNTY_NAME e.g. 'BAYAMON'. See Details.
#' @param DUN_BRADSTREET_NUMBER e.g. 'NA'. See Details.
#' @param STATE_COUNTY_COMPLIANCE_SOURCE e.g. '7202100240'. See Details.
#' @param STATE_CODE e.g. '72'. See Details.
#' @param COUNTY_CODE e.g. '021'. See Details.
#' @param CDS_PLANT_ID e.g. '00240'. See Details.
#' @param PLANT_NAME e.g. 'TEEN CHALLENGE CLEANERS'. See Details.
#' @param PLANT_STREET_ADDRESS e.g. 'MARGINAL C-21 URB. STA. CRUZ'. See Details.
#' @param PLANT_CITY e.g. 'BAYAMON'. See Details.
#' @param ZIP_CODE e.g. '00956'. See Details.
#' @param PRIMARY_SIC_CODE e.g. '7216'. See Details.
#' @param PRIMARY_SIC_DESCRIPTION e.g. 'DRY CLEANING PLANTS, EXCE'. See Details.
#' @param SECONDARY_SIC_CODE e.g. 'NA'. See Details.
#' @param TERTIARY_SIC_CODE e.g. 'NA'. See Details.
#' @param SIC_EQUIVALENT_NAICS e.g. 'PRIV'. See Details.
#' @param NAICS_EQUIVALENT_SIC e.g. 'ATELY'. See Details.
#' @param GOVT_FACILITY_CODE_DESC e.g. 'PRIVATELY OWNED/OPERATED'. See Details.
#' @param NAICS_CODE e.g. '812320'. See Details.
#' @param NAICS_CODE_DESCRIPTION e.g. 'Drycleaning and Laundry Services (except Coin-Operated)'. See Details.
#' @param STATE_REGISTRATION_NUMBER e.g. '1001-2240'. See Details.
#' @param LOCAL_CONTROL_REGION e.g. 'NA'. See Details.
#' @param LOCAL_CONTROL_REGION_DESC e.g. 'NA'. See Details.
#' @param OPERATING_STATUS e.g. 'O'. See Details.
#' @param OPERATING_STATUS_DESCRIPTION e.g. 'OPERATING'. See Details.
#' @param HPV_FLAG e.g. 'NA'. See Details.
#' @param DATE_PLANT_INFO_LAST_UPDATED e.g. '14-MAR-14'. See Details.
#' @param NAT_INIT_AIR_TOXICS e.g. 'NA'. See Details.
#' @param NAT_INIT_AIR_TOXICS_DESC e.g. 'NA'. See Details.
#' @param AFS_PLANT_ID e.g. 'NA'. See Details.
#' @export

afs_effrs_afsplt1 <- function(EPA_PLANT_ID = NULL, PLANT_ID = NULL, REGION_CODE = NULL, 
    STATE_ABBREV = NULL, STATE_NAME = NULL, COUNTY_NAME = NULL, DUN_BRADSTREET_NUMBER = NULL, 
    STATE_COUNTY_COMPLIANCE_SOURCE = NULL, STATE_CODE = NULL, COUNTY_CODE = NULL, 
    CDS_PLANT_ID = NULL, PLANT_NAME = NULL, PLANT_STREET_ADDRESS = NULL, PLANT_CITY = NULL, 
    ZIP_CODE = NULL, PRIMARY_SIC_CODE = NULL, PRIMARY_SIC_DESCRIPTION = NULL, SECONDARY_SIC_CODE = NULL, 
    TERTIARY_SIC_CODE = NULL, SIC_EQUIVALENT_NAICS = NULL, NAICS_EQUIVALENT_SIC = NULL, 
    GOVT_FACILITY_CODE_DESC = NULL, NAICS_CODE = NULL, NAICS_CODE_DESCRIPTION = NULL, 
    STATE_REGISTRATION_NUMBER = NULL, LOCAL_CONTROL_REGION = NULL, LOCAL_CONTROL_REGION_DESC = NULL, 
    OPERATING_STATUS = NULL, OPERATING_STATUS_DESCRIPTION = NULL, HPV_FLAG = NULL, 
    DATE_PLANT_INFO_LAST_UPDATED = NULL, NAT_INIT_AIR_TOXICS = NULL, NAT_INIT_AIR_TOXICS_DESC = NULL, 
    AFS_PLANT_ID = NULL) {
    
    args <- list(EPA_PLANT_ID = EPA_PLANT_ID, PLANT_ID = PLANT_ID, REGION_CODE = REGION_CODE, 
        STATE_ABBREV = STATE_ABBREV, STATE_NAME = STATE_NAME, COUNTY_NAME = COUNTY_NAME, 
        DUN_BRADSTREET_NUMBER = DUN_BRADSTREET_NUMBER, STATE_COUNTY_COMPLIANCE_SOURCE = STATE_COUNTY_COMPLIANCE_SOURCE, 
        STATE_CODE = STATE_CODE, COUNTY_CODE = COUNTY_CODE, CDS_PLANT_ID = CDS_PLANT_ID, 
        PLANT_NAME = PLANT_NAME, PLANT_STREET_ADDRESS = PLANT_STREET_ADDRESS, PLANT_CITY = PLANT_CITY, 
        ZIP_CODE = ZIP_CODE, PRIMARY_SIC_CODE = PRIMARY_SIC_CODE, PRIMARY_SIC_DESCRIPTION = PRIMARY_SIC_DESCRIPTION, 
        SECONDARY_SIC_CODE = SECONDARY_SIC_CODE, TERTIARY_SIC_CODE = TERTIARY_SIC_CODE, 
        SIC_EQUIVALENT_NAICS = SIC_EQUIVALENT_NAICS, NAICS_EQUIVALENT_SIC = NAICS_EQUIVALENT_SIC, 
        GOVT_FACILITY_CODE_DESC = GOVT_FACILITY_CODE_DESC, NAICS_CODE = NAICS_CODE, 
        NAICS_CODE_DESCRIPTION = NAICS_CODE_DESCRIPTION, STATE_REGISTRATION_NUMBER = STATE_REGISTRATION_NUMBER, 
        LOCAL_CONTROL_REGION = LOCAL_CONTROL_REGION, LOCAL_CONTROL_REGION_DESC = LOCAL_CONTROL_REGION_DESC, 
        OPERATING_STATUS = OPERATING_STATUS, OPERATING_STATUS_DESCRIPTION = OPERATING_STATUS_DESCRIPTION, 
        HPV_FLAG = HPV_FLAG, DATE_PLANT_INFO_LAST_UPDATED = DATE_PLANT_INFO_LAST_UPDATED, 
        NAT_INIT_AIR_TOXICS = NAT_INIT_AIR_TOXICS, NAT_INIT_AIR_TOXICS_DESC = NAT_INIT_AIR_TOXICS_DESC, 
        AFS_PLANT_ID = AFS_PLANT_ID)
    ret <- envir_get(effrs_afsplt1, args)
    
    ret
} 
