#' Retrieve effrs afsapp data from afs database
#' 
#' @param STATE_COUNTY_COMPLIANCE_SOURCE e.g. '0100100001'. See Details.
#' @param AIR_PROGRAM_CODE e.g. '0'. See Details.
#' @param POLLUTANT_CODE e.g. 'PM10'. See Details.
#' @param POLLUTANT_CODE_DESC e.g. 'PARTICULATE MATTER %3C 10 UM'. See Details.
#' @param CHEMICAL_ABSTRACT_SERVICE_NUM e.g. 'NA'. See Details.
#' @param CHEMICAL_ABSTRACT_SERVICE_DESC e.g. 'NA'. See Details.
#' @param ES_ATTAIN_IND_DESC e.g. 'ATTAINMENT AREA FOR A GIV'. See Details.
#' @param ES_ATTAIN_IND e.g. 'A'. See Details.
#' @param ES_PLLT_COMPLIANCE_STATUS e.g. '4'. See Details.
#' @param ES_PLLT_COMPLIANCE_DESC e.g. 'IN COMPLIANCE - CERTIFICA'. See Details.
#' @param ES_PLLT_CLASS_CODE e.g. 'A'. See Details.
#' @param ES_PLLT_CLASS_DESC e.g. 'ACTUAL OR POTENTIAL EMISS'. See Details.
#' @param STATE_ATTAIN_IND e.g. 'A'. See Details.
#' @param STATE_ATTAIN_IND_DESC e.g. 'ATTAINMENT AREA FOR A GIV'. See Details.
#' @param STATE_PLLT_COMPLIANCE_STATUS e.g. '4'. See Details.
#' @param STATE_PLLT_COMPLIANCE_DESC e.g. 'IN COMPLIANCE - CERTIFICA'. See Details.
#' @param STATE_PLLT_CLASS_CODE e.g. 'A'. See Details.
#' @param STATE_PLLT_CLASS_DESC e.g. 'ACTUAL OR POTENTIAL EMISS'. See Details.
#' @param EPA_ATTAIN_IND e.g. 'NA'. See Details.
#' @param EPA_ATTAIN_IND_DESC e.g. 'NA'. See Details.
#' @param EPA_PLLT_COMPLIANCE_STATUS e.g. 'NA'. See Details.
#' @param EPA_PLLT_COMPLIANCE_DESC e.g. 'NA'. See Details.
#' @param EPA_PLLT_CLASS_CODE e.g. 'NA'. See Details.
#' @param EPA_PLLT_CLASS_DESC e.g. 'NA'. See Details.
#' @param DATE_RECORD_UPDATED e.g. '21-JUN-99'. See Details.
#' @param AIR_PROGRAMS e.g. 'AMV069'. See Details.
#' @export

afs_effrs_afsapp <- function(STATE_COUNTY_COMPLIANCE_SOURCE = NULL, AIR_PROGRAM_CODE = NULL, 
    POLLUTANT_CODE = NULL, POLLUTANT_CODE_DESC = NULL, CHEMICAL_ABSTRACT_SERVICE_NUM = NULL, 
    CHEMICAL_ABSTRACT_SERVICE_DESC = NULL, ES_ATTAIN_IND_DESC = NULL, ES_ATTAIN_IND = NULL, 
    ES_PLLT_COMPLIANCE_STATUS = NULL, ES_PLLT_COMPLIANCE_DESC = NULL, ES_PLLT_CLASS_CODE = NULL, 
    ES_PLLT_CLASS_DESC = NULL, STATE_ATTAIN_IND = NULL, STATE_ATTAIN_IND_DESC = NULL, 
    STATE_PLLT_COMPLIANCE_STATUS = NULL, STATE_PLLT_COMPLIANCE_DESC = NULL, STATE_PLLT_CLASS_CODE = NULL, 
    STATE_PLLT_CLASS_DESC = NULL, EPA_ATTAIN_IND = NULL, EPA_ATTAIN_IND_DESC = NULL, 
    EPA_PLLT_COMPLIANCE_STATUS = NULL, EPA_PLLT_COMPLIANCE_DESC = NULL, EPA_PLLT_CLASS_CODE = NULL, 
    EPA_PLLT_CLASS_DESC = NULL, DATE_RECORD_UPDATED = NULL, AIR_PROGRAMS = NULL) {
    
    args <- list(STATE_COUNTY_COMPLIANCE_SOURCE = STATE_COUNTY_COMPLIANCE_SOURCE, 
        AIR_PROGRAM_CODE = AIR_PROGRAM_CODE, POLLUTANT_CODE = POLLUTANT_CODE, POLLUTANT_CODE_DESC = POLLUTANT_CODE_DESC, 
        CHEMICAL_ABSTRACT_SERVICE_NUM = CHEMICAL_ABSTRACT_SERVICE_NUM, CHEMICAL_ABSTRACT_SERVICE_DESC = CHEMICAL_ABSTRACT_SERVICE_DESC, 
        ES_ATTAIN_IND_DESC = ES_ATTAIN_IND_DESC, ES_ATTAIN_IND = ES_ATTAIN_IND, ES_PLLT_COMPLIANCE_STATUS = ES_PLLT_COMPLIANCE_STATUS, 
        ES_PLLT_COMPLIANCE_DESC = ES_PLLT_COMPLIANCE_DESC, ES_PLLT_CLASS_CODE = ES_PLLT_CLASS_CODE, 
        ES_PLLT_CLASS_DESC = ES_PLLT_CLASS_DESC, STATE_ATTAIN_IND = STATE_ATTAIN_IND, 
        STATE_ATTAIN_IND_DESC = STATE_ATTAIN_IND_DESC, STATE_PLLT_COMPLIANCE_STATUS = STATE_PLLT_COMPLIANCE_STATUS, 
        STATE_PLLT_COMPLIANCE_DESC = STATE_PLLT_COMPLIANCE_DESC, STATE_PLLT_CLASS_CODE = STATE_PLLT_CLASS_CODE, 
        STATE_PLLT_CLASS_DESC = STATE_PLLT_CLASS_DESC, EPA_ATTAIN_IND = EPA_ATTAIN_IND, 
        EPA_ATTAIN_IND_DESC = EPA_ATTAIN_IND_DESC, EPA_PLLT_COMPLIANCE_STATUS = EPA_PLLT_COMPLIANCE_STATUS, 
        EPA_PLLT_COMPLIANCE_DESC = EPA_PLLT_COMPLIANCE_DESC, EPA_PLLT_CLASS_CODE = EPA_PLLT_CLASS_CODE, 
        EPA_PLLT_CLASS_DESC = EPA_PLLT_CLASS_DESC, DATE_RECORD_UPDATED = DATE_RECORD_UPDATED, 
        AIR_PROGRAMS = AIR_PROGRAMS)
    ret <- envir_get(effrs_afsapp, args)
    
    ret
} 
