#' Retrieve effrs afsact2 data from afs database
#' 
#' @param STATE_COUNTY_COMPLIANCE_SOURCE e.g. '0100100001'. See Details.
#' @param ACTION_NUMBER e.g. '00239'. See Details.
#' @param AIR_PROGRAM_CODES e.g. '0'. See Details.
#' @param NATIONAL_ACTION_TYPE e.g. '2E'. See Details.
#' @param ACTION_TYPE e.g. '04'. See Details.
#' @param DATE_ACHIEVED e.g. '11-MAY-00'. See Details.
#' @param LEAD_AGENCY e.g. 'S'. See Details.
#' @param LEAD_AGENCY_DESC e.g. 'STATE LEAD FOR HPV'. See Details.
#' @param HPV_DAY_ZERO_ACTION_DATE e.g. '11-MAY-00'. See Details.
#' @param HPV_DAY_ZERO_ACTION_TYPE e.g. '04'. See Details.
#' @param HPV_DAY_ZERO_ACTION_DESC e.g. 'STATE DAY ZERO'. See Details.
#' @param HPV_DISCOVERY_DATE e.g. 'NA'. See Details.
#' @param HPV_DISCOVERY_ACTION_TYPE e.g. 'NA'. See Details.
#' @param HPV_DISCOVERY_ACTION_DESC e.g. 'NA'. See Details.
#' @param HPV_ADDRESSING_ACTION_DATE e.g. '21-AUG-00'. See Details.
#' @param HPV_ADDRESSING_ACTION_TYPE e.g. 'AW'. See Details.
#' @param HPV_ADDRESSING_ACTION_DESC e.g. 'COMPL BY STATE/LOCAL, NO ACT REQ'. See Details.
#' @param HPV_ADDRESSING_ACTION_PENALTY e.g. '000000000'. See Details.
#' @param HPV_RESOLUTION_DATE e.g. '21-AUG-00'. See Details.
#' @param HPV_RESOLUTION_ACTION_TYPE e.g. 'VR'. See Details.
#' @param HPV_RESOLUTION_ACTION_DESC e.g. 'VIOLATION RESOLVED'. See Details.
#' @param VIOLATION_POLLUTANTS e.g. 'NA'. See Details.
#' @param VIOLATION_TYPE_CODES e.g. 'NA'. See Details.
#' @param VIOLATION_IDENTIFIER e.g. 'NA'. See Details.
#' @param DATE_CREATED e.g. 'NA'. See Details.
#' @export

afs_effrs_afsact2 <- function(STATE_COUNTY_COMPLIANCE_SOURCE = NULL, ACTION_NUMBER = NULL, 
    AIR_PROGRAM_CODES = NULL, NATIONAL_ACTION_TYPE = NULL, ACTION_TYPE = NULL, DATE_ACHIEVED = NULL, 
    LEAD_AGENCY = NULL, LEAD_AGENCY_DESC = NULL, HPV_DAY_ZERO_ACTION_DATE = NULL, 
    HPV_DAY_ZERO_ACTION_TYPE = NULL, HPV_DAY_ZERO_ACTION_DESC = NULL, HPV_DISCOVERY_DATE = NULL, 
    HPV_DISCOVERY_ACTION_TYPE = NULL, HPV_DISCOVERY_ACTION_DESC = NULL, HPV_ADDRESSING_ACTION_DATE = NULL, 
    HPV_ADDRESSING_ACTION_TYPE = NULL, HPV_ADDRESSING_ACTION_DESC = NULL, HPV_ADDRESSING_ACTION_PENALTY = NULL, 
    HPV_RESOLUTION_DATE = NULL, HPV_RESOLUTION_ACTION_TYPE = NULL, HPV_RESOLUTION_ACTION_DESC = NULL, 
    VIOLATION_POLLUTANTS = NULL, VIOLATION_TYPE_CODES = NULL, VIOLATION_IDENTIFIER = NULL, 
    DATE_CREATED = NULL) {
    
    args <- list(STATE_COUNTY_COMPLIANCE_SOURCE = STATE_COUNTY_COMPLIANCE_SOURCE, 
        ACTION_NUMBER = ACTION_NUMBER, AIR_PROGRAM_CODES = AIR_PROGRAM_CODES, NATIONAL_ACTION_TYPE = NATIONAL_ACTION_TYPE, 
        ACTION_TYPE = ACTION_TYPE, DATE_ACHIEVED = DATE_ACHIEVED, LEAD_AGENCY = LEAD_AGENCY, 
        LEAD_AGENCY_DESC = LEAD_AGENCY_DESC, HPV_DAY_ZERO_ACTION_DATE = HPV_DAY_ZERO_ACTION_DATE, 
        HPV_DAY_ZERO_ACTION_TYPE = HPV_DAY_ZERO_ACTION_TYPE, HPV_DAY_ZERO_ACTION_DESC = HPV_DAY_ZERO_ACTION_DESC, 
        HPV_DISCOVERY_DATE = HPV_DISCOVERY_DATE, HPV_DISCOVERY_ACTION_TYPE = HPV_DISCOVERY_ACTION_TYPE, 
        HPV_DISCOVERY_ACTION_DESC = HPV_DISCOVERY_ACTION_DESC, HPV_ADDRESSING_ACTION_DATE = HPV_ADDRESSING_ACTION_DATE, 
        HPV_ADDRESSING_ACTION_TYPE = HPV_ADDRESSING_ACTION_TYPE, HPV_ADDRESSING_ACTION_DESC = HPV_ADDRESSING_ACTION_DESC, 
        HPV_ADDRESSING_ACTION_PENALTY = HPV_ADDRESSING_ACTION_PENALTY, HPV_RESOLUTION_DATE = HPV_RESOLUTION_DATE, 
        HPV_RESOLUTION_ACTION_TYPE = HPV_RESOLUTION_ACTION_TYPE, HPV_RESOLUTION_ACTION_DESC = HPV_RESOLUTION_ACTION_DESC, 
        VIOLATION_POLLUTANTS = VIOLATION_POLLUTANTS, VIOLATION_TYPE_CODES = VIOLATION_TYPE_CODES, 
        VIOLATION_IDENTIFIER = VIOLATION_IDENTIFIER, DATE_CREATED = DATE_CREATED)
    ret <- envir_get(effrs_afsact2, args)
    
    ret
} 
