#' Retrieve effrs afsact1 data from afs database
#' 
#' @param STATE_COUNTY_COMPLIANCE_SOURCE e.g. '0100100001'. See Details.
#' @param ACTION_NUMBER e.g. '00460'. See Details.
#' @param KEY_ACTION_NUMBERS e.g. 'NA'. See Details.
#' @param AIR_PROGRAM_CODES e.g. 'M'. See Details.
#' @param NATIONAL_ACTION_TYPE e.g. 'TS'. See Details.
#' @param NATIONAL_ACTION_DESC e.g. 'STATE/LOCAL RECEIPT OF STACK TEST REPORT'. See Details.
#' @param ACTION_TYPE e.g. 'TS'. See Details.
#' @param ACTION_DESC e.g. 'STATE RECEIPT OF STACK TEST REPORT'. See Details.
#' @param DATE_ACHIEVED e.g. '21-JUL-10'. See Details.
#' @param PENALTY_AMT e.g. 'NA'. See Details.
#' @param RESULTS_CODE e.g. 'PP'. See Details.
#' @param RESULTS_CODE_DESC e.g. 'STACK TEST PASSED'. See Details.
#' @param POLLUTANT_CODE e.g. 'PT'. See Details.
#' @param REGIONAL_DATA_ELEMENT e.g. 'NA'. See Details.
#' @param REGIONAL_DATA_ELEMENT_16 e.g. 'NA'. See Details.
#' @param HPV_ADDRESSING_ACTION_DESC e.g. 'NA'. See Details.
#' @param CREATION_DATE e.g. '18-AUG-10'. See Details.
#' @export

afs_effrs_afsact1 <- function(STATE_COUNTY_COMPLIANCE_SOURCE = NULL, ACTION_NUMBER = NULL, 
    KEY_ACTION_NUMBERS = NULL, AIR_PROGRAM_CODES = NULL, NATIONAL_ACTION_TYPE = NULL, 
    NATIONAL_ACTION_DESC = NULL, ACTION_TYPE = NULL, ACTION_DESC = NULL, DATE_ACHIEVED = NULL, 
    PENALTY_AMT = NULL, RESULTS_CODE = NULL, RESULTS_CODE_DESC = NULL, POLLUTANT_CODE = NULL, 
    REGIONAL_DATA_ELEMENT = NULL, REGIONAL_DATA_ELEMENT_16 = NULL, HPV_ADDRESSING_ACTION_DESC = NULL, 
    CREATION_DATE = NULL) {
    
    args <- list(STATE_COUNTY_COMPLIANCE_SOURCE = STATE_COUNTY_COMPLIANCE_SOURCE, 
        ACTION_NUMBER = ACTION_NUMBER, KEY_ACTION_NUMBERS = KEY_ACTION_NUMBERS, AIR_PROGRAM_CODES = AIR_PROGRAM_CODES, 
        NATIONAL_ACTION_TYPE = NATIONAL_ACTION_TYPE, NATIONAL_ACTION_DESC = NATIONAL_ACTION_DESC, 
        ACTION_TYPE = ACTION_TYPE, ACTION_DESC = ACTION_DESC, DATE_ACHIEVED = DATE_ACHIEVED, 
        PENALTY_AMT = PENALTY_AMT, RESULTS_CODE = RESULTS_CODE, RESULTS_CODE_DESC = RESULTS_CODE_DESC, 
        POLLUTANT_CODE = POLLUTANT_CODE, REGIONAL_DATA_ELEMENT = REGIONAL_DATA_ELEMENT, 
        REGIONAL_DATA_ELEMENT_16 = REGIONAL_DATA_ELEMENT_16, HPV_ADDRESSING_ACTION_DESC = HPV_ADDRESSING_ACTION_DESC, 
        CREATION_DATE = CREATION_DATE)
    ret <- envir_get("effrs_afsact1", args)
    
    ret
} 
