#' Retrieve effrs afsplt2 data from afs database
#' 
#' @param STATE_COUNTY_COMPLIANCE_SOURCE e.g. '0100100001'. See Details.
#' @param ES_CLASS_CODE e.g. 'A'. See Details.
#' @param ES_CLASS_CODE_DESC e.g. 'ACTUAL OR POTENTIAL EMISS'. See Details.
#' @param ES_COMPLIANCE_STATUS e.g. '4'. See Details.
#' @param ES_COMPLIANCE_STATUS_DESC e.g. 'IN COMPLIANCE - CERTIFICA'. See Details.
#' @param EPA_CLASS_CODE e.g. 'NA'. See Details.
#' @param EPA_CLASS_CODE_DESC e.g. 'NA'. See Details.
#' @param EPA_COMPLIANCE_STATUS e.g. '4'. See Details.
#' @param EPA_COMPLIANCE_STATUS_DESC e.g. 'IN COMPLIANCE - CERTIFICA'. See Details.
#' @param STATE_CLASS_CODE e.g. 'A'. See Details.
#' @param STATE_CLASS_CODE_DESC e.g. 'ACTUAL OR POTENTIAL EMISS'. See Details.
#' @param STATE_COMPLIANCE_STATUS e.g. '4'. See Details.
#' @param STATE_COMPLIANCE_STATUS_DESC e.g. 'IN COMPLIANCE - CERTIFICA'. See Details.
#' @param ES_LATEST_FCE_DATE_ACHIEVED e.g. '30-SEP-13'. See Details.
#' @param ES_LATEST_FCE_ACTION_TYPE e.g. 'FS'. See Details.
#' @param STATE_LATEST_FCE_DATE_ACHIEVED e.g. '30-SEP-13'. See Details.
#' @param STATE_LATEST_FCE_ACTION_TYPE e.g. 'FS'. See Details.
#' @param EPA_LATEST_FCE_DATE_ACHIEVED e.g. 'NA'. See Details.
#' @param EPA_LATEST_FCE_ACTION_TYPE e.g. 'NA'. See Details.
#' @param CONTACT_PERSION_COMPLIANCE e.g. 'NA'. See Details.
#' @param PHONE_AREA_CODE_COMPLIANCE e.g. 'NA'. See Details.
#' @param PHONE_COMPLIANCE e.g. 'NA'. See Details.
#' @param MAILING_CITY e.g. 'NA'. See Details.
#' @param MAILING_PLANT_NAME e.g. 'NA'. See Details.
#' @param MAILING_STATE_ABBREV e.g. 'NA'. See Details.
#' @param MAILING_STATE_NAME e.g. 'NA'. See Details.
#' @param MAILING_STREET_ADDRESS e.g. 'NA'. See Details.
#' @param MAILING_ZIP e.g. 'NA'. See Details.
#' @export

afs_effrs_afsplt2 <- function(STATE_COUNTY_COMPLIANCE_SOURCE = NULL, ES_CLASS_CODE = NULL, 
    ES_CLASS_CODE_DESC = NULL, ES_COMPLIANCE_STATUS = NULL, ES_COMPLIANCE_STATUS_DESC = NULL, 
    EPA_CLASS_CODE = NULL, EPA_CLASS_CODE_DESC = NULL, EPA_COMPLIANCE_STATUS = NULL, 
    EPA_COMPLIANCE_STATUS_DESC = NULL, STATE_CLASS_CODE = NULL, STATE_CLASS_CODE_DESC = NULL, 
    STATE_COMPLIANCE_STATUS = NULL, STATE_COMPLIANCE_STATUS_DESC = NULL, ES_LATEST_FCE_DATE_ACHIEVED = NULL, 
    ES_LATEST_FCE_ACTION_TYPE = NULL, STATE_LATEST_FCE_DATE_ACHIEVED = NULL, STATE_LATEST_FCE_ACTION_TYPE = NULL, 
    EPA_LATEST_FCE_DATE_ACHIEVED = NULL, EPA_LATEST_FCE_ACTION_TYPE = NULL, CONTACT_PERSION_COMPLIANCE = NULL, 
    PHONE_AREA_CODE_COMPLIANCE = NULL, PHONE_COMPLIANCE = NULL, MAILING_CITY = NULL, 
    MAILING_PLANT_NAME = NULL, MAILING_STATE_ABBREV = NULL, MAILING_STATE_NAME = NULL, 
    MAILING_STREET_ADDRESS = NULL, MAILING_ZIP = NULL) {
    
    args <- list(STATE_COUNTY_COMPLIANCE_SOURCE = STATE_COUNTY_COMPLIANCE_SOURCE, 
        ES_CLASS_CODE = ES_CLASS_CODE, ES_CLASS_CODE_DESC = ES_CLASS_CODE_DESC, ES_COMPLIANCE_STATUS = ES_COMPLIANCE_STATUS, 
        ES_COMPLIANCE_STATUS_DESC = ES_COMPLIANCE_STATUS_DESC, EPA_CLASS_CODE = EPA_CLASS_CODE, 
        EPA_CLASS_CODE_DESC = EPA_CLASS_CODE_DESC, EPA_COMPLIANCE_STATUS = EPA_COMPLIANCE_STATUS, 
        EPA_COMPLIANCE_STATUS_DESC = EPA_COMPLIANCE_STATUS_DESC, STATE_CLASS_CODE = STATE_CLASS_CODE, 
        STATE_CLASS_CODE_DESC = STATE_CLASS_CODE_DESC, STATE_COMPLIANCE_STATUS = STATE_COMPLIANCE_STATUS, 
        STATE_COMPLIANCE_STATUS_DESC = STATE_COMPLIANCE_STATUS_DESC, ES_LATEST_FCE_DATE_ACHIEVED = ES_LATEST_FCE_DATE_ACHIEVED, 
        ES_LATEST_FCE_ACTION_TYPE = ES_LATEST_FCE_ACTION_TYPE, STATE_LATEST_FCE_DATE_ACHIEVED = STATE_LATEST_FCE_DATE_ACHIEVED, 
        STATE_LATEST_FCE_ACTION_TYPE = STATE_LATEST_FCE_ACTION_TYPE, EPA_LATEST_FCE_DATE_ACHIEVED = EPA_LATEST_FCE_DATE_ACHIEVED, 
        EPA_LATEST_FCE_ACTION_TYPE = EPA_LATEST_FCE_ACTION_TYPE, CONTACT_PERSION_COMPLIANCE = CONTACT_PERSION_COMPLIANCE, 
        PHONE_AREA_CODE_COMPLIANCE = PHONE_AREA_CODE_COMPLIANCE, PHONE_COMPLIANCE = PHONE_COMPLIANCE, 
        MAILING_CITY = MAILING_CITY, MAILING_PLANT_NAME = MAILING_PLANT_NAME, MAILING_STATE_ABBREV = MAILING_STATE_ABBREV, 
        MAILING_STATE_NAME = MAILING_STATE_NAME, MAILING_STREET_ADDRESS = MAILING_STREET_ADDRESS, 
        MAILING_ZIP = MAILING_ZIP)
    ret <- envir_get(effrs_afsplt2, args)
    
    ret
} 
