#' Retrieve rcr hhandler data from br database
#'
#' @param HANDLER_ID e.g. 'AK0000000323'. See Details.
#' @param ACTIVITY_LOCATION e.g. 'AK'. See Details.
#' @param SOURCE_TYPE e.g. 'N'. See Details.
#' @param SEQ_NUMBER e.g. '1'. See Details.
#' @param RECEIVE_DATE e.g. '17-SEP-93'. See Details.
#' @param HANDLER_NAME e.g. 'USDA FS CHUGACH NF CORDOVA FOREST WORK C'. See Details.
#' @param NON_NOTIFIER e.g. 'NA'. See Details.
#' @param ACKNOWLEDGE_DATE e.g. '07-JAN-94'. See Details.
#' @param ACKNOWLEDGE_FLAG e.g. 'N'. See Details.
#' @param ACCESSIBILITY e.g. 'NA'. See Details.
#' @param LOCATION_STREET_NO e.g. 'NA'. See Details.
#' @param LOCATION_STREET1 e.g. 'COR LEFEVRE ST & COPPER RIV HW'. See Details.
#' @param LOCATION_STREET2 e.g. 'Y'. See Details.
#' @param LOCATION_CITY e.g. 'CORDOVA'. See Details.
#' @param LOCATION_STATE e.g. 'AK'. See Details.
#' @param LOCATION_ZIP e.g. '99574'. See Details.
#' @param COUNTY_CODE e.g. 'AK261'. See Details.
#' @param STATE_DISTRICT e.g. 'NA'. See Details.
#' @param LAND_TYPE e.g. 'F'. See Details.
#' @param MAIL_STREET_NO e.g. 'NA'. See Details.
#' @param MAIL_STREET1 e.g. 'PO BOX 280'. See Details.
#' @param MAIL_STREET2 e.g. 'NA'. See Details.
#' @param MAIL_CITY e.g. 'CORDOVA'. See Details.
#' @param MAIL_STATE e.g. 'AK'. See Details.
#' @param MAIL_ZIP e.g. '99574'. See Details.
#' @param MAIL_COUNTRY e.g. 'US'. See Details.
#' @param CONTACT_FIRST_NAME e.g. 'SARAH'. See Details.
#' @param CONTACT_MIDDLE_INITIAL e.g. 'NA'. See Details.
#' @param CONTACT_LAST_NAME e.g. 'BAKER'. See Details.
#' @param CONTACT_STREET_NO e.g. 'NA'. See Details.
#' @param CONTACT_STREET1 e.g. '3301 C ST STE 300'. See Details.
#' @param CONTACT_STREET2 e.g. 'NA'. See Details.
#' @param CONTACT_CITY e.g. 'ANCHORAGE'. See Details.
#' @param CONTACT_STATE e.g. 'AK'. See Details.
#' @param CONTACT_ZIP e.g. '995033998'. See Details.
#' @param CONTACT_COUNTRY e.g. 'US'. See Details.
#' @param CONTACT_PHONE e.g. '9072712556'. See Details.
#' @param CONTACT_PHONE_EXT e.g. 'NA'. See Details.
#' @param CONTACT_FAX e.g. 'NA'. See Details.
#' @param CONTACT_EMAIL_ADDRESS e.g. 'NA'. See Details.
#' @param CONTACT_TITLE e.g. 'NA'. See Details.
#' @param FED_WASTE_GENERATOR_OWNER e.g. 'HQ'. See Details.
#' @param FED_WASTE_GENERATOR e.g. '3'. See Details.
#' @param STATE_WASTE_GENERATOR_OWNER e.g. 'NA'. See Details.
#' @param STATE_WASTE_GENERATOR e.g. 'NA'. See Details.
#' @param SHORT_TERM_GENERATOR e.g. 'N'. See Details.
#' @param IMPORTER_ACTIVITY e.g. 'N'. See Details.
#' @param MIXED_WASTE_GENERATOR e.g. 'N'. See Details.
#' @param TRANSPORTER e.g. 'N'. See Details.
#' @param TRANSFER_FACILITY e.g. 'N'. See Details.
#' @param TSD_ACTIVITY e.g. 'N'. See Details.
#' @param RECYCLER_ACTIVITY e.g. 'N'. See Details.
#' @param ONSITE_BURNER_EXEMPTION e.g. 'N'. See Details.
#' @param FURNACE_EXEMPTION e.g. 'N'. See Details.
#' @param UNDERGROUND_INJECTION_ACTIVITY e.g. 'N'. See Details.
#' @param OFF_SITE_RECEIPT e.g. 'N'. See Details.
#' @param UNIVERSAL_WASTE_DEST_FACILITY e.g. 'N'. See Details.
#' @param USED_OIL_TRANSPORTER e.g. 'N'. See Details.
#' @param USED_OIL_TRANSFER_FACILITY e.g. 'N'. See Details.
#' @param USED_OIL_PROCESSOR e.g. 'N'. See Details.
#' @param USED_OIL_REFINER e.g. 'N'. See Details.
#' @param USED_OIL_BURNER e.g. 'N'. See Details.
#' @param USED_OIL_MARKET_BURNER e.g. 'N'. See Details.
#' @param USED_OIL_SPEC_MARKETER e.g. 'N'. See Details.
#' @param SUBPART_K_COLLEGE e.g. 'NA'. See Details.
#' @param SUBPART_K_HOSPITAL e.g. 'NA'. See Details.
#' @param SUBPART_K_NONPROFIT e.g. 'NA'. See Details.
#' @param SUBPART_K_WITHDRAWAL e.g. 'NA'. See Details.
#' @param INCLUDE_IN_NATIONAL_REPORT e.g. 'NA'. See Details.
#' @param REPORT_CYCLE e.g. 'NA'. See Details.
#' @param CDX_TRANSACTION_ID e.g. 'NA'. See Details.
#' @export

br_rcr_hhandler <- function(HANDLER_ID = NULL, ACTIVITY_LOCATION = NULL, SOURCE_TYPE = NULL,
    SEQ_NUMBER = NULL, RECEIVE_DATE = NULL, HANDLER_NAME = NULL, NON_NOTIFIER = NULL,
    ACKNOWLEDGE_DATE = NULL, ACKNOWLEDGE_FLAG = NULL, ACCESSIBILITY = NULL, LOCATION_STREET_NO = NULL,
    LOCATION_STREET1 = NULL, LOCATION_STREET2 = NULL, LOCATION_CITY = NULL, LOCATION_STATE = NULL,
    LOCATION_ZIP = NULL, COUNTY_CODE = NULL, STATE_DISTRICT = NULL, LAND_TYPE = NULL,
    MAIL_STREET_NO = NULL, MAIL_STREET1 = NULL, MAIL_STREET2 = NULL, MAIL_CITY = NULL,
    MAIL_STATE = NULL, MAIL_ZIP = NULL, MAIL_COUNTRY = NULL, CONTACT_FIRST_NAME = NULL,
    CONTACT_MIDDLE_INITIAL = NULL, CONTACT_LAST_NAME = NULL, CONTACT_STREET_NO = NULL,
    CONTACT_STREET1 = NULL, CONTACT_STREET2 = NULL, CONTACT_CITY = NULL, CONTACT_STATE = NULL,
    CONTACT_ZIP = NULL, CONTACT_COUNTRY = NULL, CONTACT_PHONE = NULL, CONTACT_PHONE_EXT = NULL,
    CONTACT_FAX = NULL, CONTACT_EMAIL_ADDRESS = NULL, CONTACT_TITLE = NULL, FED_WASTE_GENERATOR_OWNER = NULL,
    FED_WASTE_GENERATOR = NULL, STATE_WASTE_GENERATOR_OWNER = NULL, STATE_WASTE_GENERATOR = NULL,
    SHORT_TERM_GENERATOR = NULL, IMPORTER_ACTIVITY = NULL, MIXED_WASTE_GENERATOR = NULL,
    TRANSPORTER = NULL, TRANSFER_FACILITY = NULL, TSD_ACTIVITY = NULL, RECYCLER_ACTIVITY = NULL,
    ONSITE_BURNER_EXEMPTION = NULL, FURNACE_EXEMPTION = NULL, UNDERGROUND_INJECTION_ACTIVITY = NULL,
    OFF_SITE_RECEIPT = NULL, UNIVERSAL_WASTE_DEST_FACILITY = NULL, USED_OIL_TRANSPORTER = NULL,
    USED_OIL_TRANSFER_FACILITY = NULL, USED_OIL_PROCESSOR = NULL, USED_OIL_REFINER = NULL,
    USED_OIL_BURNER = NULL, USED_OIL_MARKET_BURNER = NULL, USED_OIL_SPEC_MARKETER = NULL,
    SUBPART_K_COLLEGE = NULL, SUBPART_K_HOSPITAL = NULL, SUBPART_K_NONPROFIT = NULL,
    SUBPART_K_WITHDRAWAL = NULL, INCLUDE_IN_NATIONAL_REPORT = NULL, REPORT_CYCLE = NULL,
    CDX_TRANSACTION_ID = NULL) {

    args <- list(HANDLER_ID = HANDLER_ID, ACTIVITY_LOCATION = ACTIVITY_LOCATION,
        SOURCE_TYPE = SOURCE_TYPE, SEQ_NUMBER = SEQ_NUMBER, RECEIVE_DATE = RECEIVE_DATE,
        HANDLER_NAME = HANDLER_NAME, NON_NOTIFIER = NON_NOTIFIER, ACKNOWLEDGE_DATE = ACKNOWLEDGE_DATE,
        ACKNOWLEDGE_FLAG = ACKNOWLEDGE_FLAG, ACCESSIBILITY = ACCESSIBILITY, LOCATION_STREET_NO = LOCATION_STREET_NO,
        LOCATION_STREET1 = LOCATION_STREET1, LOCATION_STREET2 = LOCATION_STREET2,
        LOCATION_CITY = LOCATION_CITY, LOCATION_STATE = LOCATION_STATE, LOCATION_ZIP = LOCATION_ZIP,
        COUNTY_CODE = COUNTY_CODE, STATE_DISTRICT = STATE_DISTRICT, LAND_TYPE = LAND_TYPE,
        MAIL_STREET_NO = MAIL_STREET_NO, MAIL_STREET1 = MAIL_STREET1, MAIL_STREET2 = MAIL_STREET2,
        MAIL_CITY = MAIL_CITY, MAIL_STATE = MAIL_STATE, MAIL_ZIP = MAIL_ZIP, MAIL_COUNTRY = MAIL_COUNTRY,
        CONTACT_FIRST_NAME = CONTACT_FIRST_NAME, CONTACT_MIDDLE_INITIAL = CONTACT_MIDDLE_INITIAL,
        CONTACT_LAST_NAME = CONTACT_LAST_NAME, CONTACT_STREET_NO = CONTACT_STREET_NO,
        CONTACT_STREET1 = CONTACT_STREET1, CONTACT_STREET2 = CONTACT_STREET2, CONTACT_CITY = CONTACT_CITY,
        CONTACT_STATE = CONTACT_STATE, CONTACT_ZIP = CONTACT_ZIP, CONTACT_COUNTRY = CONTACT_COUNTRY,
        CONTACT_PHONE = CONTACT_PHONE, CONTACT_PHONE_EXT = CONTACT_PHONE_EXT, CONTACT_FAX = CONTACT_FAX,
        CONTACT_EMAIL_ADDRESS = CONTACT_EMAIL_ADDRESS, CONTACT_TITLE = CONTACT_TITLE,
        FED_WASTE_GENERATOR_OWNER = FED_WASTE_GENERATOR_OWNER, FED_WASTE_GENERATOR = FED_WASTE_GENERATOR,
        STATE_WASTE_GENERATOR_OWNER = STATE_WASTE_GENERATOR_OWNER, STATE_WASTE_GENERATOR = STATE_WASTE_GENERATOR,
        SHORT_TERM_GENERATOR = SHORT_TERM_GENERATOR, IMPORTER_ACTIVITY = IMPORTER_ACTIVITY,
        MIXED_WASTE_GENERATOR = MIXED_WASTE_GENERATOR, TRANSPORTER = TRANSPORTER,
        TRANSFER_FACILITY = TRANSFER_FACILITY, TSD_ACTIVITY = TSD_ACTIVITY, RECYCLER_ACTIVITY = RECYCLER_ACTIVITY,
        ONSITE_BURNER_EXEMPTION = ONSITE_BURNER_EXEMPTION, FURNACE_EXEMPTION = FURNACE_EXEMPTION,
        UNDERGROUND_INJECTION_ACTIVITY = UNDERGROUND_INJECTION_ACTIVITY, OFF_SITE_RECEIPT = OFF_SITE_RECEIPT,
        UNIVERSAL_WASTE_DEST_FACILITY = UNIVERSAL_WASTE_DEST_FACILITY, USED_OIL_TRANSPORTER = USED_OIL_TRANSPORTER,
        USED_OIL_TRANSFER_FACILITY = USED_OIL_TRANSFER_FACILITY, USED_OIL_PROCESSOR = USED_OIL_PROCESSOR,
        USED_OIL_REFINER = USED_OIL_REFINER, USED_OIL_BURNER = USED_OIL_BURNER, USED_OIL_MARKET_BURNER = USED_OIL_MARKET_BURNER,
        USED_OIL_SPEC_MARKETER = USED_OIL_SPEC_MARKETER, SUBPART_K_COLLEGE = SUBPART_K_COLLEGE,
        SUBPART_K_HOSPITAL = SUBPART_K_HOSPITAL, SUBPART_K_NONPROFIT = SUBPART_K_NONPROFIT,
        SUBPART_K_WITHDRAWAL = SUBPART_K_WITHDRAWAL, INCLUDE_IN_NATIONAL_REPORT = INCLUDE_IN_NATIONAL_REPORT,
        REPORT_CYCLE = REPORT_CYCLE, CDX_TRANSACTION_ID = CDX_TRANSACTION_ID)
    ret <- envir_get("rcr_hhandler", args)

    ret
}
