#' Retrieve frs interest ref data from fii database
#' 
#' @param INTEREST_TYPE e.g. '401 CERTIFICATION'. See Details.
#' @param INTEREST_DESC e.g. 'UNDER SECTION 401 OF THE CLEAN WATER ACT (CWA), STATES AND TRIBES HAVE THE AUTHORITY TO REVIEW AND THEN DENY, CERTIFY, OR CONDITION FEDERAL PERMITS OR LICENSES THAT MIGHT RESULT IN A DISCHARGE TO STATE OR TRIBAL WATERS, INCLUDING WETLANDS, TO ENSURE COMPLIANCE WITH STATE WATER QUALITY STANDARDS.  THE MAJOR FEDERAL LICENSES AND PERMITS SUBJECT TO SECTION 401 ARE SECTION 402 AND 404 PERMITS (IN NONDELEGATED STATES), FEDERAL ENERGY REGULATORY COMMISSION (FERC) HYDROPOWER LICENSES, AND RIVERS AND HARBORS ACT SECTION 9 AND 10 PERMITS.'. See Details.
#' @param PROGRAM_CATEGORY e.g. 'WASTE WATER PROGRAMS'. See Details.
#' @param PROGRAM_CATEGORY_DESC e.g. 'ENVIRONMENTAL PROGRAMS THAT REGULATE DISCHARGES OF POLLUTANTS TO WATERS OF THE UNITED STATES, AS REQUIRED BY THE CLEAN WATER ACT.'. See Details.
#' @param QUERY_FLAG e.g. 'N'. See Details.
#' @param PUBLIC_IND e.g. 'Y'. See Details.
#' @param CREATE_DATE e.g. '10-MAR-04'. See Details.
#' @param UPDATE_DATE e.g. '27-MAR-12'. See Details.
#' @export

fii_frs_interest_ref <- function(INTEREST_TYPE = NULL, INTEREST_DESC = NULL, PROGRAM_CATEGORY = NULL, 
    PROGRAM_CATEGORY_DESC = NULL, QUERY_FLAG = NULL, PUBLIC_IND = NULL, CREATE_DATE = NULL, 
    UPDATE_DATE = NULL) {
    
    args <- list(INTEREST_TYPE = INTEREST_TYPE, INTEREST_DESC = INTEREST_DESC, PROGRAM_CATEGORY = PROGRAM_CATEGORY, 
        PROGRAM_CATEGORY_DESC = PROGRAM_CATEGORY_DESC, QUERY_FLAG = QUERY_FLAG, PUBLIC_IND = PUBLIC_IND, 
        CREATE_DATE = CREATE_DATE, UPDATE_DATE = UPDATE_DATE)
    ret <- envir_get("frs_interest_ref", args)
    
    ret
} 
