#' Retrieve frs facility site data from fii database
#' 
#' @param REGISTRY_ID e.g. '110000307668'. See Details.
#' @param PRIMARY_NAME e.g. 'HB FULLER COMPANY HBF PUERTO RICO'. See Details.
#' @param LOCATION_ADDRESS e.g. 'CALLE C NUMBER 26 LUCHETTI INDUSTRIAL PARK'. See Details.
#' @param SUPPLEMENTAL_LOCATION e.g. 'NA'. See Details.
#' @param CITY_NAME e.g. 'BAYAMON'. See Details.
#' @param COUNTY_NAME e.g. 'BAYAMON'. See Details.
#' @param FIPS_CODE e.g. '72021'. See Details.
#' @param STATE_CODE e.g. 'PR'. See Details.
#' @param STATE_NAME e.g. 'PUERTO RICO'. See Details.
#' @param COUNTRY_NAME e.g. 'USA'. See Details.
#' @param POSTAL_CODE e.g. '00961'. See Details.
#' @param FEDERAL_FACILITY_CODE e.g. 'N'. See Details.
#' @param FEDERAL_AGENCY_CODE e.g. 'NA'. See Details.
#' @param TRIBAL_LAND_CODE e.g. 'N'. See Details.
#' @param TRIBAL_LAND_NAME e.g. 'NA'. See Details.
#' @param LEGISLATIVE_DIST_NUM e.g. '- '. See Details.
#' @param EPA_REGION_CODE e.g. '02'. See Details.
#' @param SITE_TYPE_NAME e.g. 'STATIONARY'. See Details.
#' @param INTEREST_STATUS_CODE e.g. 'A'. See Details.
#' @param DATA_QUALITY_CODE e.g. 'V'. See Details.
#' @param LOCATION_DESCRIPTION e.g. 'NA'. See Details.
#' @param STD_NAME e.g. 'HAMBGR FULLER HBF PR'. See Details.
#' @param STD_LOC_ADDRESS e.g. 'CLL C NUMBER 26 LUCHETTI INDUSTRIAL PARK'. See Details.
#' @param STD_HOUSE_NUMBER e.g. 'NA'. See Details.
#' @param STD_STREET_NAME e.g. 'NA'. See Details.
#' @param STD_BASE_NAME e.g. 'NA'. See Details.
#' @param STD_PREFIX e.g. 'NA'. See Details.
#' @param STD_SUFFIX e.g. 'NA'. See Details.
#' @param STD_STYPE_BEFORE e.g. 'NA'. See Details.
#' @param STD_STYPE_AFTER e.g. 'NA'. See Details.
#' @param STD_POSTAL_CODE e.g. '00739'. See Details.
#' @param STD_STATE_CODE e.g. 'PR'. See Details.
#' @param STD_CITY_NAME e.g. 'CIDRA'. See Details.
#' @param STD_COUNTY_NAME e.g. 'CIDRA MUNICIPIO'. See Details.
#' @param STD_COUNTY_FIPS e.g. '72041'. See Details.
#' @param STD_COUNTRY e.g. 'PR'. See Details.
#' @param STD_FULL_ADDRESS e.g. 'CLL C NUMBER 26 LUCHETTI INDUSTRIAL PARK, CIDRA, PR  00739 PR'. See Details.
#' @param ADDR_TYPE e.g. 'REGULAR URBAN'. See Details.
#' @param LAST_REPORTED_DATE e.g. 'NA'. See Details.
#' @param CREATE_DATE e.g. '01-MAR-00'. See Details.
#' @param UPDATE_DATE e.g. '31-DEC-15'. See Details.
#' @param USER_ID e.g. 'DSMITH04'. See Details.
#' @param PARENT_REGISTRY_ID e.g. 'NA'. See Details.
#' @param SENSITIVE_IND e.g. 'N'. See Details.
#' @param REVIEW_FLAG e.g. 'NA'. See Details.
#' @param REVIEW_REASON e.g. 'NA'. See Details.
#' @param SMALL_BUS_IND e.g. 'NA'. See Details.
#' @param ENV_JUSTICE_CODE e.g. 'NA'. See Details.
#' @param PUBLIC_IND e.g. 'Y'. See Details.
#' @param ICIS_IDENTIFIER e.g. 'NA'. See Details.
#' @param REFRESH_DATE e.g. 'NA'. See Details.
#' @param STAND_ALONE_FLAG e.g. 'N'. See Details.
#' @export

fii_frs_facility_site <- function(REGISTRY_ID = NULL, PRIMARY_NAME = NULL, LOCATION_ADDRESS = NULL, 
    SUPPLEMENTAL_LOCATION = NULL, CITY_NAME = NULL, COUNTY_NAME = NULL, FIPS_CODE = NULL, 
    STATE_CODE = NULL, STATE_NAME = NULL, COUNTRY_NAME = NULL, POSTAL_CODE = NULL, 
    FEDERAL_FACILITY_CODE = NULL, FEDERAL_AGENCY_CODE = NULL, TRIBAL_LAND_CODE = NULL, 
    TRIBAL_LAND_NAME = NULL, LEGISLATIVE_DIST_NUM = NULL, EPA_REGION_CODE = NULL, 
    SITE_TYPE_NAME = NULL, INTEREST_STATUS_CODE = NULL, DATA_QUALITY_CODE = NULL, 
    LOCATION_DESCRIPTION = NULL, STD_NAME = NULL, STD_LOC_ADDRESS = NULL, STD_HOUSE_NUMBER = NULL, 
    STD_STREET_NAME = NULL, STD_BASE_NAME = NULL, STD_PREFIX = NULL, STD_SUFFIX = NULL, 
    STD_STYPE_BEFORE = NULL, STD_STYPE_AFTER = NULL, STD_POSTAL_CODE = NULL, STD_STATE_CODE = NULL, 
    STD_CITY_NAME = NULL, STD_COUNTY_NAME = NULL, STD_COUNTY_FIPS = NULL, STD_COUNTRY = NULL, 
    STD_FULL_ADDRESS = NULL, ADDR_TYPE = NULL, LAST_REPORTED_DATE = NULL, CREATE_DATE = NULL, 
    UPDATE_DATE = NULL, USER_ID = NULL, PARENT_REGISTRY_ID = NULL, SENSITIVE_IND = NULL, 
    REVIEW_FLAG = NULL, REVIEW_REASON = NULL, SMALL_BUS_IND = NULL, ENV_JUSTICE_CODE = NULL, 
    PUBLIC_IND = NULL, ICIS_IDENTIFIER = NULL, REFRESH_DATE = NULL, STAND_ALONE_FLAG = NULL) {
    
    args <- list(REGISTRY_ID = REGISTRY_ID, PRIMARY_NAME = PRIMARY_NAME, LOCATION_ADDRESS = LOCATION_ADDRESS, 
        SUPPLEMENTAL_LOCATION = SUPPLEMENTAL_LOCATION, CITY_NAME = CITY_NAME, COUNTY_NAME = COUNTY_NAME, 
        FIPS_CODE = FIPS_CODE, STATE_CODE = STATE_CODE, STATE_NAME = STATE_NAME, 
        COUNTRY_NAME = COUNTRY_NAME, POSTAL_CODE = POSTAL_CODE, FEDERAL_FACILITY_CODE = FEDERAL_FACILITY_CODE, 
        FEDERAL_AGENCY_CODE = FEDERAL_AGENCY_CODE, TRIBAL_LAND_CODE = TRIBAL_LAND_CODE, 
        TRIBAL_LAND_NAME = TRIBAL_LAND_NAME, LEGISLATIVE_DIST_NUM = LEGISLATIVE_DIST_NUM, 
        EPA_REGION_CODE = EPA_REGION_CODE, SITE_TYPE_NAME = SITE_TYPE_NAME, INTEREST_STATUS_CODE = INTEREST_STATUS_CODE, 
        DATA_QUALITY_CODE = DATA_QUALITY_CODE, LOCATION_DESCRIPTION = LOCATION_DESCRIPTION, 
        STD_NAME = STD_NAME, STD_LOC_ADDRESS = STD_LOC_ADDRESS, STD_HOUSE_NUMBER = STD_HOUSE_NUMBER, 
        STD_STREET_NAME = STD_STREET_NAME, STD_BASE_NAME = STD_BASE_NAME, STD_PREFIX = STD_PREFIX, 
        STD_SUFFIX = STD_SUFFIX, STD_STYPE_BEFORE = STD_STYPE_BEFORE, STD_STYPE_AFTER = STD_STYPE_AFTER, 
        STD_POSTAL_CODE = STD_POSTAL_CODE, STD_STATE_CODE = STD_STATE_CODE, STD_CITY_NAME = STD_CITY_NAME, 
        STD_COUNTY_NAME = STD_COUNTY_NAME, STD_COUNTY_FIPS = STD_COUNTY_FIPS, STD_COUNTRY = STD_COUNTRY, 
        STD_FULL_ADDRESS = STD_FULL_ADDRESS, ADDR_TYPE = ADDR_TYPE, LAST_REPORTED_DATE = LAST_REPORTED_DATE, 
        CREATE_DATE = CREATE_DATE, UPDATE_DATE = UPDATE_DATE, USER_ID = USER_ID, 
        PARENT_REGISTRY_ID = PARENT_REGISTRY_ID, SENSITIVE_IND = SENSITIVE_IND, REVIEW_FLAG = REVIEW_FLAG, 
        REVIEW_REASON = REVIEW_REASON, SMALL_BUS_IND = SMALL_BUS_IND, ENV_JUSTICE_CODE = ENV_JUSTICE_CODE, 
        PUBLIC_IND = PUBLIC_IND, ICIS_IDENTIFIER = ICIS_IDENTIFIER, REFRESH_DATE = REFRESH_DATE, 
        STAND_ALONE_FLAG = STAND_ALONE_FLAG)
    ret <- envir_get(frs_facility_site, args)
    
    ret
} 
