#' Retrieve ff well and shaft data from ghg database
#' 
#' @param FACILITY_ID e.g. '1001681'. See Details.
#' @param REPORTING_YEAR e.g. '2011'. See Details.
#' @param WELL_SHAFT_DAYS_IN_OPERATION e.g. 'NA'. See Details.
#' @param WELL_SHAFT_CLOSE_DATE e.g. 'NA'. See Details.
#' @param WELL_SHAFT_START_DATE e.g. 'NA'. See Details.
#' @param CENTRALIZD_MONITORING_POINT_ID e.g. 'NA'. See Details.
#' @param FACILITY_NAME e.g. 'WILLOW LAKE MINE'. See Details.
#' @param WELL_SHAFT_ID e.g. 'WILLOW LAKE SOUTH EXHAUST FAN'. See Details.
#' @param IS_THIS_WELL_OR_SHAFT e.g. 'SHAFT'. See Details.
#' @param GAS_SYSTEM_UNIT_ID e.g. 'NA'. See Details.
#' @param DESCRIPTION e.g. 'EXHAUST VENT SHAFT'. See Details.
#' @param ADDITIONAL_DESCRIPTION e.g. 'NA'. See Details.
#' @param WELL_SHAFT_MONITORED_STATUS e.g. 'MONITORED INDIVIDUALLY'. See Details.
#' @param MON_POINT_NAME e.g. 'NA'. See Details.
#' @export

ghg_ff_well_and_shaft <- function(FACILITY_ID = NULL, REPORTING_YEAR = NULL, WELL_SHAFT_DAYS_IN_OPERATION = NULL, 
    WELL_SHAFT_CLOSE_DATE = NULL, WELL_SHAFT_START_DATE = NULL, CENTRALIZD_MONITORING_POINT_ID = NULL, 
    FACILITY_NAME = NULL, WELL_SHAFT_ID = NULL, IS_THIS_WELL_OR_SHAFT = NULL, GAS_SYSTEM_UNIT_ID = NULL, 
    DESCRIPTION = NULL, ADDITIONAL_DESCRIPTION = NULL, WELL_SHAFT_MONITORED_STATUS = NULL, 
    MON_POINT_NAME = NULL) {
    
    args <- list(FACILITY_ID = FACILITY_ID, REPORTING_YEAR = REPORTING_YEAR, WELL_SHAFT_DAYS_IN_OPERATION = WELL_SHAFT_DAYS_IN_OPERATION, 
        WELL_SHAFT_CLOSE_DATE = WELL_SHAFT_CLOSE_DATE, WELL_SHAFT_START_DATE = WELL_SHAFT_START_DATE, 
        CENTRALIZD_MONITORING_POINT_ID = CENTRALIZD_MONITORING_POINT_ID, FACILITY_NAME = FACILITY_NAME, 
        WELL_SHAFT_ID = WELL_SHAFT_ID, IS_THIS_WELL_OR_SHAFT = IS_THIS_WELL_OR_SHAFT, 
        GAS_SYSTEM_UNIT_ID = GAS_SYSTEM_UNIT_ID, DESCRIPTION = DESCRIPTION, ADDITIONAL_DESCRIPTION = ADDITIONAL_DESCRIPTION, 
        WELL_SHAFT_MONITORED_STATUS = WELL_SHAFT_MONITORED_STATUS, MON_POINT_NAME = MON_POINT_NAME)
    ret <- envir_get(ff_well_and_shaft, args)
    
    ret
} 
