#' Retrieve v nitric acid train data from ghg database
#' 
#' @param FACILITY_ID e.g. '1001781'. See Details.
#' @param REPORTING_YEAR e.g. '2013'. See Details.
#' @param FACILITY_NAME e.g. 'INVISTA S.a r.l.'. See Details.
#' @param NITRIC_ACID_TRAIN_ID e.g. 'AOP-2'. See Details.
#' @param NUM_MONTH_MISS_DATA_PROCS_USED e.g. '2'. See Details.
#' @param IS_ADMIN_APPROV_ALT_METHD_USED e.g. 'No'. See Details.
#' @param ALT_METHOD_NAME e.g. 'NA'. See Details.
#' @param ALT_METHOD_DESC e.g. 'NA'. See Details.
#' @param ALT_METHOD_REQUEST_DATE e.g. 'NA'. See Details.
#' @param ALT_METHOD_APPROVAL_DATE e.g. 'NA'. See Details.
#' @param NUM_PERFOMANCE_TESTS_REPEATED e.g. '0'. See Details.
#' @param PERFORMANCE_TEST_ID_1 e.g. '7/16/2013 %26 7/17/2013 AOP GHG Emission Factor Test'. See Details.
#' @param PERFORMANCE_TEST_METHOD_1 e.g. 'EPA Method 320'. See Details.
#' @param PERFORMANCE_TEST_ID_2 e.g. 'NA'. See Details.
#' @param PERFORMANCE_TEST_METHOD_2 e.g. 'NA'. See Details.
#' @param PERFORMANCE_TEST_ID_3 e.g. 'NA'. See Details.
#' @param PERFORMANCE_TEST_METHOD_3 e.g. 'NA'. See Details.
#' @param DOES_NITRIC_ACID_TRAIN_EXHAUST e.g. 'No'. See Details.
#' @param IS_NSCR_USED e.g. 'NA'. See Details.
#' @param OTH_ABATEMENT_TECH_USED e.g. 'NA'. See Details.
#' @param OTH_ABATEMENT_TECH_DESC e.g. 'NA'. See Details.
#' @param ANNUAL_UNROUNDED_N2O_EMISS e.g. '1808'. See Details.
#' @export

ghg_v_nitric_acid_train <- function(FACILITY_ID = NULL, REPORTING_YEAR = NULL, FACILITY_NAME = NULL, 
    NITRIC_ACID_TRAIN_ID = NULL, NUM_MONTH_MISS_DATA_PROCS_USED = NULL, IS_ADMIN_APPROV_ALT_METHD_USED = NULL, 
    ALT_METHOD_NAME = NULL, ALT_METHOD_DESC = NULL, ALT_METHOD_REQUEST_DATE = NULL, 
    ALT_METHOD_APPROVAL_DATE = NULL, NUM_PERFOMANCE_TESTS_REPEATED = NULL, PERFORMANCE_TEST_ID_1 = NULL, 
    PERFORMANCE_TEST_METHOD_1 = NULL, PERFORMANCE_TEST_ID_2 = NULL, PERFORMANCE_TEST_METHOD_2 = NULL, 
    PERFORMANCE_TEST_ID_3 = NULL, PERFORMANCE_TEST_METHOD_3 = NULL, DOES_NITRIC_ACID_TRAIN_EXHAUST = NULL, 
    IS_NSCR_USED = NULL, OTH_ABATEMENT_TECH_USED = NULL, OTH_ABATEMENT_TECH_DESC = NULL, 
    ANNUAL_UNROUNDED_N2O_EMISS = NULL) {
    
    args <- list(FACILITY_ID = FACILITY_ID, REPORTING_YEAR = REPORTING_YEAR, FACILITY_NAME = FACILITY_NAME, 
        NITRIC_ACID_TRAIN_ID = NITRIC_ACID_TRAIN_ID, NUM_MONTH_MISS_DATA_PROCS_USED = NUM_MONTH_MISS_DATA_PROCS_USED, 
        IS_ADMIN_APPROV_ALT_METHD_USED = IS_ADMIN_APPROV_ALT_METHD_USED, ALT_METHOD_NAME = ALT_METHOD_NAME, 
        ALT_METHOD_DESC = ALT_METHOD_DESC, ALT_METHOD_REQUEST_DATE = ALT_METHOD_REQUEST_DATE, 
        ALT_METHOD_APPROVAL_DATE = ALT_METHOD_APPROVAL_DATE, NUM_PERFOMANCE_TESTS_REPEATED = NUM_PERFOMANCE_TESTS_REPEATED, 
        PERFORMANCE_TEST_ID_1 = PERFORMANCE_TEST_ID_1, PERFORMANCE_TEST_METHOD_1 = PERFORMANCE_TEST_METHOD_1, 
        PERFORMANCE_TEST_ID_2 = PERFORMANCE_TEST_ID_2, PERFORMANCE_TEST_METHOD_2 = PERFORMANCE_TEST_METHOD_2, 
        PERFORMANCE_TEST_ID_3 = PERFORMANCE_TEST_ID_3, PERFORMANCE_TEST_METHOD_3 = PERFORMANCE_TEST_METHOD_3, 
        DOES_NITRIC_ACID_TRAIN_EXHAUST = DOES_NITRIC_ACID_TRAIN_EXHAUST, IS_NSCR_USED = IS_NSCR_USED, 
        OTH_ABATEMENT_TECH_USED = OTH_ABATEMENT_TECH_USED, OTH_ABATEMENT_TECH_DESC = OTH_ABATEMENT_TECH_DESC, 
        ANNUAL_UNROUNDED_N2O_EMISS = ANNUAL_UNROUNDED_N2O_EMISS)
    ret <- envir_get(v_nitric_acid_train, args)
    
    ret
} 
