#' Retrieve ff degas weekly data from ghg database
#' 
#' @param FACILITY_ID e.g. '1003058'. See Details.
#' @param REPORTING_YEAR e.g. '2014'. See Details.
#' @param GAS_SYSTEM_UNIT_ID e.g. 'DE-GAS #1'. See Details.
#' @param QUARTER e.g. '4'. See Details.
#' @param WEEK e.g. '6'. See Details.
#' @param DEGAS_FLOW_RATE_METHOD e.g. 'MONITORED USING 98.324(C)(2)'. See Details.
#' @param TIME_SUB_DATA_WK_DEGAS_VOL_FLO e.g. '0.01'. See Details.
#' @param START_DATE_MONIT_EQUIP_NOT_FUN e.g. 'NA'. See Details.
#' @param STOP_DATE_MONIT_EQUIP_NOT_FUNC e.g. 'NA'. See Details.
#' @param WKLY_CH4_LIBER_MONITORING_PT e.g. '1.29'. See Details.
#' @param WEEKLY_VOLUMETRIC_FLOW_RATE e.g. '162'. See Details.
#' @param WKLY_VOLUMETRIC_FLOW_RATE_UNIT e.g. 'ACFM'. See Details.
#' @param FACILITY_NAME e.g. 'OAKTOWN FUELS MINE NO.1'. See Details.
#' @export

ghg_ff_degas_weekly <- function(FACILITY_ID = NULL, REPORTING_YEAR = NULL, GAS_SYSTEM_UNIT_ID = NULL, 
    QUARTER = NULL, WEEK = NULL, DEGAS_FLOW_RATE_METHOD = NULL, TIME_SUB_DATA_WK_DEGAS_VOL_FLO = NULL, 
    START_DATE_MONIT_EQUIP_NOT_FUN = NULL, STOP_DATE_MONIT_EQUIP_NOT_FUNC = NULL, 
    WKLY_CH4_LIBER_MONITORING_PT = NULL, WEEKLY_VOLUMETRIC_FLOW_RATE = NULL, WKLY_VOLUMETRIC_FLOW_RATE_UNIT = NULL, 
    FACILITY_NAME = NULL) {
    
    args <- list(FACILITY_ID = FACILITY_ID, REPORTING_YEAR = REPORTING_YEAR, GAS_SYSTEM_UNIT_ID = GAS_SYSTEM_UNIT_ID, 
        QUARTER = QUARTER, WEEK = WEEK, DEGAS_FLOW_RATE_METHOD = DEGAS_FLOW_RATE_METHOD, 
        TIME_SUB_DATA_WK_DEGAS_VOL_FLO = TIME_SUB_DATA_WK_DEGAS_VOL_FLO, START_DATE_MONIT_EQUIP_NOT_FUN = START_DATE_MONIT_EQUIP_NOT_FUN, 
        STOP_DATE_MONIT_EQUIP_NOT_FUNC = STOP_DATE_MONIT_EQUIP_NOT_FUNC, WKLY_CH4_LIBER_MONITORING_PT = WKLY_CH4_LIBER_MONITORING_PT, 
        WEEKLY_VOLUMETRIC_FLOW_RATE = WEEKLY_VOLUMETRIC_FLOW_RATE, WKLY_VOLUMETRIC_FLOW_RATE_UNIT = WKLY_VOLUMETRIC_FLOW_RATE_UNIT, 
        FACILITY_NAME = FACILITY_NAME)
    ret <- envir_get("ff_degas_weekly", args)
    
    ret
} 
