#' Retrieve c configuration level info data from ghg database
#' 
#' @param FACILITY_ID e.g. '1000001'. See Details.
#' @param REPORTING_YEAR e.g. '2010'. See Details.
#' @param FACILITY_NAME e.g. 'PSE Ferndale Generating Station'. See Details.
#' @param UNIT_NAME e.g. 'GT-1A'. See Details.
#' @param UNIT_TYPE e.g. 'CCCT (CC (Turbine, combined cycle))'. See Details.
#' @param UNIT_TYPE_OTHER e.g. 'NA'. See Details.
#' @param IND_UNIT_HEAT_INPUT_CAPACITY e.g. '1019.7'. See Details.
#' @param IND_UNIT_HEATINPUTCAPACITY_UOM e.g. 'mmBtu/hr'. See Details.
#' @param IND_UNIT_HEATCAPACITY_UOM_OTHR e.g. 'NA'. See Details.
#' @param AGGR_HIGH_HEAT_CAPACITY e.g. 'NA'. See Details.
#' @param AGGR_HIGH_HEAT_CAPACITY_UOM e.g. 'NA'. See Details.
#' @param COMMON_PIPE_HEAT_CAPACITY e.g. 'NA'. See Details.
#' @param COMMON_PIPE_HEAT_CAPACITY_UOM e.g. 'NA'. See Details.
#' @param COMMON_STACK_NUMBER_OF_UNITS e.g. 'NA'. See Details.
#' @param SORBENT_MOLECULAR_WEIGHT e.g. 'NA'. See Details.
#' @param SORBENT_RATIO e.g. 'NA'. See Details.
#' @param COMMON_STACK_COMBINED_HEAT e.g. 'NA'. See Details.
#' @param COMMON_STACK_COMBINED_HEAT_UOM e.g. 'NA'. See Details.
#' @param TIER_123_SORBENT_CO2_EMISSIONS e.g. '0'. See Details.
#' @param TIER123_BIOGENIC_CO2_EMISSIONS e.g. '0'. See Details.
#' @param TIER_1_2_3_FOSSIL_CO2_EMISSION e.g. 'NA'. See Details.
#' @param TIER_4_OPERATING_HOURS e.g. 'NA'. See Details.
#' @param TIER_4_OP_HRS_CO2_CONC_SUB e.g. 'NA'. See Details.
#' @param TIER_4_OP_HRS_STACK_FLOWRT_SUB e.g. 'NA'. See Details.
#' @param TIER_4_OP_HRS_STACK_MOIST_SUB e.g. 'NA'. See Details.
#' @param TIER4_NONBIOGENIC_CO2EMISSION e.g. 'NA'. See Details.
#' @param TIER_4_BIOGENIC_CO2_EMISSIONS e.g. 'NA'. See Details.
#' @param TIER_4_TOTAL_CO2_EMISSIONS e.g. 'NA'. See Details.
#' @param TIER_4_METHODOLOGY_START_DATE e.g. 'NA'. See Details.
#' @param TIER_4_METHODOLOGY_END_DATE e.g. 'NA'. See Details.
#' @param TIER4_VFF e.g. 'NA'. See Details.
#' @param TIER4_V_TOTAL e.g. 'NA'. See Details.
#' @param TIER4_V_BIO e.g. 'NA'. See Details.
#' @param TIER4_ANNUAL_BIO_CO2_EMISSION e.g. 'NA'. See Details.
#' @param PART_75_CO2_EMISSIONS_METHOD e.g. 'NA'. See Details.
#' @param PART_75_METHOD_STARTDATE e.g. 'NA'. See Details.
#' @param PART_75_METHODOLOGY_ENDDATE e.g. 'NA'. See Details.
#' @param PART_75_HEAT_INPUT_METHOD e.g. 'NA'. See Details.
#' @param PART_75_CO2_METHOD e.g. 'NA'. See Details.
#' @param PART_75_OP_HRS_FUEL_FLOWRATE e.g. 'NA'. See Details.
#' @param PART_75_OP_HRS_HHV_SUB e.g. 'NA'. See Details.
#' @param PART_75_OP_HRS_CO2_CONC_SUB e.g. 'NA'. See Details.
#' @param PART_75_OP_HRS_FLOWRATE_SUB e.g. 'NA'. See Details.
#' @param PART_75_OP_HRS_MOISTURE_SUB e.g. 'NA'. See Details.
#' @param BIOGENIC_CO2_MASS_EMISS_MSW e.g. 'NA'. See Details.
#' @param TOTAL_AMT_SORBENT_USED e.g. 'NA'. See Details.
#' @param PLANT_CODE e.g. 'NA'. See Details.
#' @param CP_USEIVTIND e.g. 'NA'. See Details.
#' @param CS_USEIVTIND e.g. 'NA'. See Details.
#' @param IND_USE_IVT_IND e.g. 'NA'. See Details.
#' @param AGG_USEIVTIND e.g. 'NA'. See Details.
#' @export

ghg_c_configuration_level_info <- function(FACILITY_ID = NULL, REPORTING_YEAR = NULL, 
    FACILITY_NAME = NULL, UNIT_NAME = NULL, UNIT_TYPE = NULL, UNIT_TYPE_OTHER = NULL, 
    IND_UNIT_HEAT_INPUT_CAPACITY = NULL, IND_UNIT_HEATINPUTCAPACITY_UOM = NULL, IND_UNIT_HEATCAPACITY_UOM_OTHR = NULL, 
    AGGR_HIGH_HEAT_CAPACITY = NULL, AGGR_HIGH_HEAT_CAPACITY_UOM = NULL, COMMON_PIPE_HEAT_CAPACITY = NULL, 
    COMMON_PIPE_HEAT_CAPACITY_UOM = NULL, COMMON_STACK_NUMBER_OF_UNITS = NULL, SORBENT_MOLECULAR_WEIGHT = NULL, 
    SORBENT_RATIO = NULL, COMMON_STACK_COMBINED_HEAT = NULL, COMMON_STACK_COMBINED_HEAT_UOM = NULL, 
    TIER_123_SORBENT_CO2_EMISSIONS = NULL, TIER123_BIOGENIC_CO2_EMISSIONS = NULL, 
    TIER_1_2_3_FOSSIL_CO2_EMISSION = NULL, TIER_4_OPERATING_HOURS = NULL, TIER_4_OP_HRS_CO2_CONC_SUB = NULL, 
    TIER_4_OP_HRS_STACK_FLOWRT_SUB = NULL, TIER_4_OP_HRS_STACK_MOIST_SUB = NULL, 
    TIER4_NONBIOGENIC_CO2EMISSION = NULL, TIER_4_BIOGENIC_CO2_EMISSIONS = NULL, TIER_4_TOTAL_CO2_EMISSIONS = NULL, 
    TIER_4_METHODOLOGY_START_DATE = NULL, TIER_4_METHODOLOGY_END_DATE = NULL, TIER4_VFF = NULL, 
    TIER4_V_TOTAL = NULL, TIER4_V_BIO = NULL, TIER4_ANNUAL_BIO_CO2_EMISSION = NULL, 
    PART_75_CO2_EMISSIONS_METHOD = NULL, PART_75_METHOD_STARTDATE = NULL, PART_75_METHODOLOGY_ENDDATE = NULL, 
    PART_75_HEAT_INPUT_METHOD = NULL, PART_75_CO2_METHOD = NULL, PART_75_OP_HRS_FUEL_FLOWRATE = NULL, 
    PART_75_OP_HRS_HHV_SUB = NULL, PART_75_OP_HRS_CO2_CONC_SUB = NULL, PART_75_OP_HRS_FLOWRATE_SUB = NULL, 
    PART_75_OP_HRS_MOISTURE_SUB = NULL, BIOGENIC_CO2_MASS_EMISS_MSW = NULL, TOTAL_AMT_SORBENT_USED = NULL, 
    PLANT_CODE = NULL, CP_USEIVTIND = NULL, CS_USEIVTIND = NULL, IND_USE_IVT_IND = NULL, 
    AGG_USEIVTIND = NULL) {
    
    args <- list(FACILITY_ID = FACILITY_ID, REPORTING_YEAR = REPORTING_YEAR, FACILITY_NAME = FACILITY_NAME, 
        UNIT_NAME = UNIT_NAME, UNIT_TYPE = UNIT_TYPE, UNIT_TYPE_OTHER = UNIT_TYPE_OTHER, 
        IND_UNIT_HEAT_INPUT_CAPACITY = IND_UNIT_HEAT_INPUT_CAPACITY, IND_UNIT_HEATINPUTCAPACITY_UOM = IND_UNIT_HEATINPUTCAPACITY_UOM, 
        IND_UNIT_HEATCAPACITY_UOM_OTHR = IND_UNIT_HEATCAPACITY_UOM_OTHR, AGGR_HIGH_HEAT_CAPACITY = AGGR_HIGH_HEAT_CAPACITY, 
        AGGR_HIGH_HEAT_CAPACITY_UOM = AGGR_HIGH_HEAT_CAPACITY_UOM, COMMON_PIPE_HEAT_CAPACITY = COMMON_PIPE_HEAT_CAPACITY, 
        COMMON_PIPE_HEAT_CAPACITY_UOM = COMMON_PIPE_HEAT_CAPACITY_UOM, COMMON_STACK_NUMBER_OF_UNITS = COMMON_STACK_NUMBER_OF_UNITS, 
        SORBENT_MOLECULAR_WEIGHT = SORBENT_MOLECULAR_WEIGHT, SORBENT_RATIO = SORBENT_RATIO, 
        COMMON_STACK_COMBINED_HEAT = COMMON_STACK_COMBINED_HEAT, COMMON_STACK_COMBINED_HEAT_UOM = COMMON_STACK_COMBINED_HEAT_UOM, 
        TIER_123_SORBENT_CO2_EMISSIONS = TIER_123_SORBENT_CO2_EMISSIONS, TIER123_BIOGENIC_CO2_EMISSIONS = TIER123_BIOGENIC_CO2_EMISSIONS, 
        TIER_1_2_3_FOSSIL_CO2_EMISSION = TIER_1_2_3_FOSSIL_CO2_EMISSION, TIER_4_OPERATING_HOURS = TIER_4_OPERATING_HOURS, 
        TIER_4_OP_HRS_CO2_CONC_SUB = TIER_4_OP_HRS_CO2_CONC_SUB, TIER_4_OP_HRS_STACK_FLOWRT_SUB = TIER_4_OP_HRS_STACK_FLOWRT_SUB, 
        TIER_4_OP_HRS_STACK_MOIST_SUB = TIER_4_OP_HRS_STACK_MOIST_SUB, TIER4_NONBIOGENIC_CO2EMISSION = TIER4_NONBIOGENIC_CO2EMISSION, 
        TIER_4_BIOGENIC_CO2_EMISSIONS = TIER_4_BIOGENIC_CO2_EMISSIONS, TIER_4_TOTAL_CO2_EMISSIONS = TIER_4_TOTAL_CO2_EMISSIONS, 
        TIER_4_METHODOLOGY_START_DATE = TIER_4_METHODOLOGY_START_DATE, TIER_4_METHODOLOGY_END_DATE = TIER_4_METHODOLOGY_END_DATE, 
        TIER4_VFF = TIER4_VFF, TIER4_V_TOTAL = TIER4_V_TOTAL, TIER4_V_BIO = TIER4_V_BIO, 
        TIER4_ANNUAL_BIO_CO2_EMISSION = TIER4_ANNUAL_BIO_CO2_EMISSION, PART_75_CO2_EMISSIONS_METHOD = PART_75_CO2_EMISSIONS_METHOD, 
        PART_75_METHOD_STARTDATE = PART_75_METHOD_STARTDATE, PART_75_METHODOLOGY_ENDDATE = PART_75_METHODOLOGY_ENDDATE, 
        PART_75_HEAT_INPUT_METHOD = PART_75_HEAT_INPUT_METHOD, PART_75_CO2_METHOD = PART_75_CO2_METHOD, 
        PART_75_OP_HRS_FUEL_FLOWRATE = PART_75_OP_HRS_FUEL_FLOWRATE, PART_75_OP_HRS_HHV_SUB = PART_75_OP_HRS_HHV_SUB, 
        PART_75_OP_HRS_CO2_CONC_SUB = PART_75_OP_HRS_CO2_CONC_SUB, PART_75_OP_HRS_FLOWRATE_SUB = PART_75_OP_HRS_FLOWRATE_SUB, 
        PART_75_OP_HRS_MOISTURE_SUB = PART_75_OP_HRS_MOISTURE_SUB, BIOGENIC_CO2_MASS_EMISS_MSW = BIOGENIC_CO2_MASS_EMISS_MSW, 
        TOTAL_AMT_SORBENT_USED = TOTAL_AMT_SORBENT_USED, PLANT_CODE = PLANT_CODE, 
        CP_USEIVTIND = CP_USEIVTIND, CS_USEIVTIND = CS_USEIVTIND, IND_USE_IVT_IND = IND_USE_IVT_IND, 
        AGG_USEIVTIND = AGG_USEIVTIND)
    ret <- envir_get("c_configuration_level_info", args)
    
    ret
} 
