#' Retrieve x cems details data from ghg database
#' 
#' @param FACILITY_ID e.g. '1004900'. See Details.
#' @param REPORTING_YEAR e.g. '2012'. See Details.
#' @param CEMS_CO2_COMBUSTION_EMISSIONS e.g. 'NA'. See Details.
#' @param CML_NAME e.g. 'Chlorine Destruct Tower'. See Details.
#' @param CML_DESCRIPTION e.g. 'NA'. See Details.
#' @param CML_CONFIGURATION_TYPE e.g. 'Process/stationary combustion units share common stack'. See Details.
#' @param CEMS_BIOGENIC_CO2_EMISSIONS e.g. '0'. See Details.
#' @param CEMS_NONBIOGENIC_CO2_EMISSIONS e.g. '31334'. See Details.
#' @param CEMS_CO2_EMISSIONS e.g. '31334'. See Details.
#' @param CEMS_CH4_EMISSIONS e.g. '1.59'. See Details.
#' @param CEMS_N2O_EMISSIONS e.g. '0.319'. See Details.
#' @param TIER4_SUB_OPER_HRS_CO2_CONC e.g. '0'. See Details.
#' @param TIER4_SUB_OPER_HRS_GAS_FLOW_RT e.g. '0'. See Details.
#' @param TIER4_SUB_OPER_HRS_MOIST_CONT e.g. '0'. See Details.
#' @param CEMS_METHODOLOGY_START_DATE e.g. '01-JAN-12'. See Details.
#' @param CEMS_METHODOLOGY_END_DATE e.g. '31-DEC-12'. See Details.
#' @param FUEL_TYPE e.g. 'Natural Gas and Process Vent Gas'. See Details.
#' @param CEMS_QUARTER_NAME e.g. 'First Quarter'. See Details.
#' @param CEMS_CO2_EMISSIONS_BY_QUARTER e.g. '7011'. See Details.
#' @export

ghg_x_cems_details <- function(FACILITY_ID = NULL, REPORTING_YEAR = NULL, CEMS_CO2_COMBUSTION_EMISSIONS = NULL, 
    CML_NAME = NULL, CML_DESCRIPTION = NULL, CML_CONFIGURATION_TYPE = NULL, CEMS_BIOGENIC_CO2_EMISSIONS = NULL, 
    CEMS_NONBIOGENIC_CO2_EMISSIONS = NULL, CEMS_CO2_EMISSIONS = NULL, CEMS_CH4_EMISSIONS = NULL, 
    CEMS_N2O_EMISSIONS = NULL, TIER4_SUB_OPER_HRS_CO2_CONC = NULL, TIER4_SUB_OPER_HRS_GAS_FLOW_RT = NULL, 
    TIER4_SUB_OPER_HRS_MOIST_CONT = NULL, CEMS_METHODOLOGY_START_DATE = NULL, CEMS_METHODOLOGY_END_DATE = NULL, 
    FUEL_TYPE = NULL, CEMS_QUARTER_NAME = NULL, CEMS_CO2_EMISSIONS_BY_QUARTER = NULL) {
    
    args <- list(FACILITY_ID = FACILITY_ID, REPORTING_YEAR = REPORTING_YEAR, CEMS_CO2_COMBUSTION_EMISSIONS = CEMS_CO2_COMBUSTION_EMISSIONS, 
        CML_NAME = CML_NAME, CML_DESCRIPTION = CML_DESCRIPTION, CML_CONFIGURATION_TYPE = CML_CONFIGURATION_TYPE, 
        CEMS_BIOGENIC_CO2_EMISSIONS = CEMS_BIOGENIC_CO2_EMISSIONS, CEMS_NONBIOGENIC_CO2_EMISSIONS = CEMS_NONBIOGENIC_CO2_EMISSIONS, 
        CEMS_CO2_EMISSIONS = CEMS_CO2_EMISSIONS, CEMS_CH4_EMISSIONS = CEMS_CH4_EMISSIONS, 
        CEMS_N2O_EMISSIONS = CEMS_N2O_EMISSIONS, TIER4_SUB_OPER_HRS_CO2_CONC = TIER4_SUB_OPER_HRS_CO2_CONC, 
        TIER4_SUB_OPER_HRS_GAS_FLOW_RT = TIER4_SUB_OPER_HRS_GAS_FLOW_RT, TIER4_SUB_OPER_HRS_MOIST_CONT = TIER4_SUB_OPER_HRS_MOIST_CONT, 
        CEMS_METHODOLOGY_START_DATE = CEMS_METHODOLOGY_START_DATE, CEMS_METHODOLOGY_END_DATE = CEMS_METHODOLOGY_END_DATE, 
        FUEL_TYPE = FUEL_TYPE, CEMS_QUARTER_NAME = CEMS_QUARTER_NAME, CEMS_CO2_EMISSIONS_BY_QUARTER = CEMS_CO2_EMISSIONS_BY_QUARTER)
    ret <- envir_get(x_cems_details, args)
    
    ret
} 
