#' Retrieve hh ann waste disposal qty data from ghg database
#' 
#' @param FACILITY_ID e.g. '1000010'. See Details.
#' @param REPORTING_YEAR e.g. '2014'. See Details.
#' @param WASTE_DISPOSAL_QTY_RY_BY_MTHD e.g. '117582'. See Details.
#' @param FACILITY_NAME e.g. 'SANTA ROSA CENTRAL LANDFILL'. See Details.
#' @param WASTE_DISP_REPORTING_YEAR e.g. '2010'. See Details.
#' @param TOTAL_WASTE_DISPOSAL_QTY_RY e.g. '117582'. See Details.
#' @param METHOD_USED_TO_FIND_QTY e.g. 'USED SCALES TO WEIGH LOADS BEFORE OFF-LOADING AND EITHER USED SCALES TO WEIGH INDIVIDUAL LOADS AFTER OFF-LOADING OR USED REPRESENTATIVE TARE VEHICLE/CONTAINER WEIGHTS'. See Details.
#' @export

ghg_hh_ann_waste_disposal_qty <- function(FACILITY_ID = NULL, REPORTING_YEAR = NULL, 
    WASTE_DISPOSAL_QTY_RY_BY_MTHD = NULL, FACILITY_NAME = NULL, WASTE_DISP_REPORTING_YEAR = NULL, 
    TOTAL_WASTE_DISPOSAL_QTY_RY = NULL, METHOD_USED_TO_FIND_QTY = NULL) {
    
    args <- list(FACILITY_ID = FACILITY_ID, REPORTING_YEAR = REPORTING_YEAR, WASTE_DISPOSAL_QTY_RY_BY_MTHD = WASTE_DISPOSAL_QTY_RY_BY_MTHD, 
        FACILITY_NAME = FACILITY_NAME, WASTE_DISP_REPORTING_YEAR = WASTE_DISP_REPORTING_YEAR, 
        TOTAL_WASTE_DISPOSAL_QTY_RY = TOTAL_WASTE_DISPOSAL_QTY_RY, METHOD_USED_TO_FIND_QTY = METHOD_USED_TO_FIND_QTY)
    ret <- envir_get("hh_ann_waste_disposal_qty", args)
    
    ret
} 
