#' Retrieve y crackingcokingreforming info data from ghg database
#' 
#' @param FACILITY_ID e.g. '1000025'. See Details.
#' @param REPORTING_YEAR e.g. '2012'. See Details.
#' @param CH4_EMISSION_FACTOR_BASIS_OTHR e.g. 'NA'. See Details.
#' @param N2O_EMISSIONS e.g. '0'. See Details.
#' @param N2O_CALCULATION_METHOD e.g. 'Equation Y-10 with a default emission factor'. See Details.
#' @param N2O_EMISSION_FACTOR_BASIS e.g. 'NA'. See Details.
#' @param N2O_EMISSION_FACTOR_BASIS_OTHR e.g. 'NA'. See Details.
#' @param FLEXICOKER_EMISS_IN_SUBPART_C e.g. 'NA'. See Details.
#' @param VOLUMETRIC_FLOW_RT_EXHAUST_GAS e.g. 'NA'. See Details.
#' @param PERCENT_CO2_EXHAUST_GAS_METHOD e.g. 'NA'. See Details.
#' @param PERCENT_CO_EXHAUST_GAS_METHOD e.g. 'NA'. See Details.
#' @param PERCENT_O2_EXHAUST_GAS_METHOD e.g. 'NA'. See Details.
#' @param PERCENT_N2_EXHAUST_GAS_METHOD e.g. 'NA'. See Details.
#' @param PCT_N2_EXHAUST_GAS_MTHD_OTHR e.g. 'NA'. See Details.
#' @param PERCENT_N2_INLET_GAS_METHOD e.g. 'NA'. See Details.
#' @param FACILITY_NAME e.g. 'PLACID REFINING CO LLC - PORT ALLEN REFINERY'. See Details.
#' @param UNIT_NAME e.g. 'Reformer'. See Details.
#' @param UNIT_TYPE e.g. 'Catalytic Reforming Unit'. See Details.
#' @param CO2_EMISSIONS e.g. '28.6'. See Details.
#' @param CO2_CALCULATION_METHOD e.g. 'Equation Y-11 - 98.253(e)(3)'. See Details.
#' @param CH4_EMISSIONS e.g. '0'. See Details.
#' @param CH4_CALCULATION_METHOD e.g. 'Equation Y-9 with a default emission factor'. See Details.
#' @param CH4_EMISSION_FACTOR_BASIS e.g. 'NA'. See Details.
#' @param PERCENT_N2_INLET_GAS_MTHD_OTHR e.g. 'NA'. See Details.
#' @param C_CONTENT_BASIS_Y8 e.g. 'NA'. See Details.
#' @param C_CONTENT_BASIS_Y8_OTHER e.g. 'NA'. See Details.
#' @param COKE_BURN_OFF_QUANTITY e.g. '8287'. See Details.
#' @param COKE_BURN_OFF_QUANTITY_UOM e.g. 'kg/cycle or kg/measurement period'. See Details.
#' @export

ghg_y_crackingcokingreforming_info <- function(FACILITY_ID = NULL, REPORTING_YEAR = NULL, 
    CH4_EMISSION_FACTOR_BASIS_OTHR = NULL, N2O_EMISSIONS = NULL, N2O_CALCULATION_METHOD = NULL, 
    N2O_EMISSION_FACTOR_BASIS = NULL, N2O_EMISSION_FACTOR_BASIS_OTHR = NULL, FLEXICOKER_EMISS_IN_SUBPART_C = NULL, 
    VOLUMETRIC_FLOW_RT_EXHAUST_GAS = NULL, PERCENT_CO2_EXHAUST_GAS_METHOD = NULL, 
    PERCENT_CO_EXHAUST_GAS_METHOD = NULL, PERCENT_O2_EXHAUST_GAS_METHOD = NULL, PERCENT_N2_EXHAUST_GAS_METHOD = NULL, 
    PCT_N2_EXHAUST_GAS_MTHD_OTHR = NULL, PERCENT_N2_INLET_GAS_METHOD = NULL, FACILITY_NAME = NULL, 
    UNIT_NAME = NULL, UNIT_TYPE = NULL, CO2_EMISSIONS = NULL, CO2_CALCULATION_METHOD = NULL, 
    CH4_EMISSIONS = NULL, CH4_CALCULATION_METHOD = NULL, CH4_EMISSION_FACTOR_BASIS = NULL, 
    PERCENT_N2_INLET_GAS_MTHD_OTHR = NULL, C_CONTENT_BASIS_Y8 = NULL, C_CONTENT_BASIS_Y8_OTHER = NULL, 
    COKE_BURN_OFF_QUANTITY = NULL, COKE_BURN_OFF_QUANTITY_UOM = NULL) {
    
    args <- list(FACILITY_ID = FACILITY_ID, REPORTING_YEAR = REPORTING_YEAR, CH4_EMISSION_FACTOR_BASIS_OTHR = CH4_EMISSION_FACTOR_BASIS_OTHR, 
        N2O_EMISSIONS = N2O_EMISSIONS, N2O_CALCULATION_METHOD = N2O_CALCULATION_METHOD, 
        N2O_EMISSION_FACTOR_BASIS = N2O_EMISSION_FACTOR_BASIS, N2O_EMISSION_FACTOR_BASIS_OTHR = N2O_EMISSION_FACTOR_BASIS_OTHR, 
        FLEXICOKER_EMISS_IN_SUBPART_C = FLEXICOKER_EMISS_IN_SUBPART_C, VOLUMETRIC_FLOW_RT_EXHAUST_GAS = VOLUMETRIC_FLOW_RT_EXHAUST_GAS, 
        PERCENT_CO2_EXHAUST_GAS_METHOD = PERCENT_CO2_EXHAUST_GAS_METHOD, PERCENT_CO_EXHAUST_GAS_METHOD = PERCENT_CO_EXHAUST_GAS_METHOD, 
        PERCENT_O2_EXHAUST_GAS_METHOD = PERCENT_O2_EXHAUST_GAS_METHOD, PERCENT_N2_EXHAUST_GAS_METHOD = PERCENT_N2_EXHAUST_GAS_METHOD, 
        PCT_N2_EXHAUST_GAS_MTHD_OTHR = PCT_N2_EXHAUST_GAS_MTHD_OTHR, PERCENT_N2_INLET_GAS_METHOD = PERCENT_N2_INLET_GAS_METHOD, 
        FACILITY_NAME = FACILITY_NAME, UNIT_NAME = UNIT_NAME, UNIT_TYPE = UNIT_TYPE, 
        CO2_EMISSIONS = CO2_EMISSIONS, CO2_CALCULATION_METHOD = CO2_CALCULATION_METHOD, 
        CH4_EMISSIONS = CH4_EMISSIONS, CH4_CALCULATION_METHOD = CH4_CALCULATION_METHOD, 
        CH4_EMISSION_FACTOR_BASIS = CH4_EMISSION_FACTOR_BASIS, PERCENT_N2_INLET_GAS_MTHD_OTHR = PERCENT_N2_INLET_GAS_MTHD_OTHR, 
        C_CONTENT_BASIS_Y8 = C_CONTENT_BASIS_Y8, C_CONTENT_BASIS_Y8_OTHER = C_CONTENT_BASIS_Y8_OTHER, 
        COKE_BURN_OFF_QUANTITY = COKE_BURN_OFF_QUANTITY, COKE_BURN_OFF_QUANTITY_UOM = COKE_BURN_OFF_QUANTITY_UOM)
    ret <- envir_get("y_crackingcokingreforming_info", args)
    
    ret
} 
