#' Retrieve h no cems qrtr details data from ghg database
#' 
#' @param FACILITY_ID e.g. '1000243'. See Details.
#' @param REPORTING_YEAR e.g. '2010'. See Details.
#' @param FACILITY_NAME e.g. 'LAFARGE MIDWEST INC JOPPA PLANT'. See Details.
#' @param UNIT_NAME e.g. 'GHGK1Process'. See Details.
#' @param QUARTERNAME e.g. 'Third Quarter'. See Details.
#' @param CKDCO2EMISSIONSFACTOR e.g. 'NA'. See Details.
#' @param CEMENT_DUST_NOT_RECYCYLED_KILN e.g. 'N'. See Details.
#' @param MISS_DATA_FRAC_NON_CALCND_CAO e.g. 'N'. See Details.
#' @param MISS_DATA_FRAC_NON_CALCND_MGO e.g. 'N'. See Details.
#' @param DET_METHD_NON_CALCINED_CAO e.g. 'Other'. See Details.
#' @param OTHDETMTHDNONCALCAO e.g. 'Method ASTM 114-09'. See Details.
#' @param DET_METHD_NON_CALCINED_MAGNESI e.g. 'Other'. See Details.
#' @param OTHDETMTHDNONCALMGO e.g. 'Method ASTM 114-09'. See Details.
#' @export

ghg_h_no_cems_qrtr_details <- function(FACILITY_ID = NULL, REPORTING_YEAR = NULL, 
    FACILITY_NAME = NULL, UNIT_NAME = NULL, QUARTERNAME = NULL, CKDCO2EMISSIONSFACTOR = NULL, 
    CEMENT_DUST_NOT_RECYCYLED_KILN = NULL, MISS_DATA_FRAC_NON_CALCND_CAO = NULL, 
    MISS_DATA_FRAC_NON_CALCND_MGO = NULL, DET_METHD_NON_CALCINED_CAO = NULL, OTHDETMTHDNONCALCAO = NULL, 
    DET_METHD_NON_CALCINED_MAGNESI = NULL, OTHDETMTHDNONCALMGO = NULL) {
    
    args <- list(FACILITY_ID = FACILITY_ID, REPORTING_YEAR = REPORTING_YEAR, FACILITY_NAME = FACILITY_NAME, 
        UNIT_NAME = UNIT_NAME, QUARTERNAME = QUARTERNAME, CKDCO2EMISSIONSFACTOR = CKDCO2EMISSIONSFACTOR, 
        CEMENT_DUST_NOT_RECYCYLED_KILN = CEMENT_DUST_NOT_RECYCYLED_KILN, MISS_DATA_FRAC_NON_CALCND_CAO = MISS_DATA_FRAC_NON_CALCND_CAO, 
        MISS_DATA_FRAC_NON_CALCND_MGO = MISS_DATA_FRAC_NON_CALCND_MGO, DET_METHD_NON_CALCINED_CAO = DET_METHD_NON_CALCINED_CAO, 
        OTHDETMTHDNONCALCAO = OTHDETMTHDNONCALCAO, DET_METHD_NON_CALCINED_MAGNESI = DET_METHD_NON_CALCINED_MAGNESI, 
        OTHDETMTHDNONCALMGO = OTHDETMTHDNONCALMGO)
    ret <- envir_get(h_no_cems_qrtr_details, args)
    
    ret
} 
