#' Retrieve w pneumatic devices data from ghg database
#' 
#' @param FACILITY_ID e.g. '1000179'. See Details.
#' @param REPORTING_YEAR e.g. '2012'. See Details.
#' @param PNEUMATIC_DEVICES_TOT_CO2_EMM e.g. '0.3'. See Details.
#' @param SUB_IND_PNEUMATIC_DEVICES e.g. 'NO'. See Details.
#' @param FACILITY_NAME e.g. 'BERNVILLE STATION'. See Details.
#' @param PNEUMATIC_DEV_TOT_CH4_EMM_CO2E e.g. '188.5'. See Details.
#' @param PNEUM_DEVICES_TOT_N2O_EMM_CO2E e.g. 'NA'. See Details.
#' @param PNEUM_DEVICES_TOT_GHG_EMM_CO2E e.g. '188.8'. See Details.
#' @param DOES_FAC_HAVE_HIGH_BLEED_DEVIC e.g. 'YES'. See Details.
#' @param DOES_FAC_HAVE_INTR_BLEED_DEVIC e.g. 'NO'. See Details.
#' @param DOES_FAC_HAVE_LOW_BLEED_DEVICE e.g. 'NO'. See Details.
#' @param BAMM_IND_PNEUMATIC_DEVICES e.g. 'YES'. See Details.
#' @param BAMM_DESC_PNEUMATIC_DEVICES e.g. 'BAMM NEEDED TO OBTAIN TOTAL COUNT OF HIGH AND LOW BLEED DEVICES'. See Details.
#' @param INDUSTRY_SEGMENT e.g. 'ONSHORE NATURAL GAS TRANSMISSION COMPRESSION [98.230(A)(4)]'. See Details.
#' @export

ghg_w_pneumatic_devices <- function(FACILITY_ID = NULL, REPORTING_YEAR = NULL, PNEUMATIC_DEVICES_TOT_CO2_EMM = NULL, 
    SUB_IND_PNEUMATIC_DEVICES = NULL, FACILITY_NAME = NULL, PNEUMATIC_DEV_TOT_CH4_EMM_CO2E = NULL, 
    PNEUM_DEVICES_TOT_N2O_EMM_CO2E = NULL, PNEUM_DEVICES_TOT_GHG_EMM_CO2E = NULL, 
    DOES_FAC_HAVE_HIGH_BLEED_DEVIC = NULL, DOES_FAC_HAVE_INTR_BLEED_DEVIC = NULL, 
    DOES_FAC_HAVE_LOW_BLEED_DEVICE = NULL, BAMM_IND_PNEUMATIC_DEVICES = NULL, BAMM_DESC_PNEUMATIC_DEVICES = NULL, 
    INDUSTRY_SEGMENT = NULL) {
    
    args <- list(FACILITY_ID = FACILITY_ID, REPORTING_YEAR = REPORTING_YEAR, PNEUMATIC_DEVICES_TOT_CO2_EMM = PNEUMATIC_DEVICES_TOT_CO2_EMM, 
        SUB_IND_PNEUMATIC_DEVICES = SUB_IND_PNEUMATIC_DEVICES, FACILITY_NAME = FACILITY_NAME, 
        PNEUMATIC_DEV_TOT_CH4_EMM_CO2E = PNEUMATIC_DEV_TOT_CH4_EMM_CO2E, PNEUM_DEVICES_TOT_N2O_EMM_CO2E = PNEUM_DEVICES_TOT_N2O_EMM_CO2E, 
        PNEUM_DEVICES_TOT_GHG_EMM_CO2E = PNEUM_DEVICES_TOT_GHG_EMM_CO2E, DOES_FAC_HAVE_HIGH_BLEED_DEVIC = DOES_FAC_HAVE_HIGH_BLEED_DEVIC, 
        DOES_FAC_HAVE_INTR_BLEED_DEVIC = DOES_FAC_HAVE_INTR_BLEED_DEVIC, DOES_FAC_HAVE_LOW_BLEED_DEVICE = DOES_FAC_HAVE_LOW_BLEED_DEVICE, 
        BAMM_IND_PNEUMATIC_DEVICES = BAMM_IND_PNEUMATIC_DEVICES, BAMM_DESC_PNEUMATIC_DEVICES = BAMM_DESC_PNEUMATIC_DEVICES, 
        INDUSTRY_SEGMENT = INDUSTRY_SEGMENT)
    ret <- envir_get(w_pneumatic_devices, args)
    
    ret
} 
