#' Retrieve tt hist waste method data from ghg database
#' 
#' @param FACILITY_ID e.g. '1000093'. See Details.
#' @param REPORTING_YEAR e.g. '2014'. See Details.
#' @param DECAY_RATE e.g. '0.06'. See Details.
#' @param IS_BASED_ON_TOTAL_VOLIT_SOLIDS e.g. 'N'. See Details.
#' @param IS_DEFAULT_VAL_FROM_TABLE_TT1 e.g. 'Y'. See Details.
#' @param ANAEROB_60DAY_BIODEG_TEST_USED e.g. 'N'. See Details.
#' @param WASTEDISPOSEDQUANTITY e.g. '5365'. See Details.
#' @param WASTESTREAMDOCVALUE e.g. '0.2'. See Details.
#' @param FACILITY_NAME e.g. 'MOMENTIVE PERFORMANCE MATERIALS'. See Details.
#' @param WASTE_STREAM_NAME e.g. 'LANDFILL 1'. See Details.
#' @param HISTORICAL_WASTE_REPORTINGYEAR e.g. '1982'. See Details.
#' @param USE_MTHD1_FOR_HIST_WASTE_QUAN e.g. 'N'. See Details.
#' @param USE_MTHD2_FOR_HIST_WASTE_QUAN e.g. 'N'. See Details.
#' @param USE_MTHD3_FOR_HIST_WASTE_QUAN e.g. 'N'. See Details.
#' @param USE_MTHD4_FOR_HIST_WASTE_QUAN e.g. 'Y'. See Details.
#' @export

ghg_tt_hist_waste_method <- function(FACILITY_ID = NULL, REPORTING_YEAR = NULL, DECAY_RATE = NULL, 
    IS_BASED_ON_TOTAL_VOLIT_SOLIDS = NULL, IS_DEFAULT_VAL_FROM_TABLE_TT1 = NULL, 
    ANAEROB_60DAY_BIODEG_TEST_USED = NULL, WASTEDISPOSEDQUANTITY = NULL, WASTESTREAMDOCVALUE = NULL, 
    FACILITY_NAME = NULL, WASTE_STREAM_NAME = NULL, HISTORICAL_WASTE_REPORTINGYEAR = NULL, 
    USE_MTHD1_FOR_HIST_WASTE_QUAN = NULL, USE_MTHD2_FOR_HIST_WASTE_QUAN = NULL, USE_MTHD3_FOR_HIST_WASTE_QUAN = NULL, 
    USE_MTHD4_FOR_HIST_WASTE_QUAN = NULL) {
    
    args <- list(FACILITY_ID = FACILITY_ID, REPORTING_YEAR = REPORTING_YEAR, DECAY_RATE = DECAY_RATE, 
        IS_BASED_ON_TOTAL_VOLIT_SOLIDS = IS_BASED_ON_TOTAL_VOLIT_SOLIDS, IS_DEFAULT_VAL_FROM_TABLE_TT1 = IS_DEFAULT_VAL_FROM_TABLE_TT1, 
        ANAEROB_60DAY_BIODEG_TEST_USED = ANAEROB_60DAY_BIODEG_TEST_USED, WASTEDISPOSEDQUANTITY = WASTEDISPOSEDQUANTITY, 
        WASTESTREAMDOCVALUE = WASTESTREAMDOCVALUE, FACILITY_NAME = FACILITY_NAME, 
        WASTE_STREAM_NAME = WASTE_STREAM_NAME, HISTORICAL_WASTE_REPORTINGYEAR = HISTORICAL_WASTE_REPORTINGYEAR, 
        USE_MTHD1_FOR_HIST_WASTE_QUAN = USE_MTHD1_FOR_HIST_WASTE_QUAN, USE_MTHD2_FOR_HIST_WASTE_QUAN = USE_MTHD2_FOR_HIST_WASTE_QUAN, 
        USE_MTHD3_FOR_HIST_WASTE_QUAN = USE_MTHD3_FOR_HIST_WASTE_QUAN, USE_MTHD4_FOR_HIST_WASTE_QUAN = USE_MTHD4_FOR_HIST_WASTE_QUAN)
    ret <- envir_get("tt_hist_waste_method", args)
    
    ret
} 
