#' Retrieve s lime product details data from ghg database
#' 
#' @param FACILITY_ID e.g. '1000019'. See Details.
#' @param REPORTING_YEAR e.g. '2014'. See Details.
#' @param MASS_SOLD_ANALYSIS_METHOD_OTHR e.g. 'None Sold'. See Details.
#' @param MASS_PRODUCED_ANALYSIS_METHOD e.g. 'Other'. See Details.
#' @param MASS_PRODUCED_ANLS_METHD_OTHR e.g. 'Per October 2011 EPA Memo to Doug Emerson American Crystal Sugar'. See Details.
#' @param MASS_SOLD_ANALYSIS e.g. 'N'. See Details.
#' @param IS_CO2_USED_ONSITE_INDICATOR e.g. 'Y'. See Details.
#' @param AMOUNT_CO2_USED_ONSITE_METHOD e.g. 'Other method'. See Details.
#' @param AMT_CO2_USED_ONSITE_METHD_OTHR e.g. 'Industry process review of conversion back to calcium carbonate suggest 100% recovery (Beet Sugar Te'. See Details.
#' @param MONTH_NAME e.g. 'January'. See Details.
#' @param CAO_CHEMICAL_COMPO_ANALY e.g. 'N'. See Details.
#' @param CAO_CHEMICAL_COMPO_ANALY_METHD e.g. 'ASTM C25-06'. See Details.
#' @param CAO_CHEMICAL_COMPO_METHD_OTHR e.g. 'NA'. See Details.
#' @param MGO_CHEMICAL_COMPO_ANALY e.g. 'N'. See Details.
#' @param MGO_CHEMICAL_COMPO_ANALY_METHD e.g. 'ASTM C25-06'. See Details.
#' @param MGO_CHEMICAL_COMPO_METHD_OTHR e.g. 'NA'. See Details.
#' @param MASS_SOLD_ANALYSIS_METHOD e.g. 'Other'. See Details.
#' @export

ghg_s_lime_product_details <- function(FACILITY_ID = NULL, REPORTING_YEAR = NULL, 
    MASS_SOLD_ANALYSIS_METHOD_OTHR = NULL, MASS_PRODUCED_ANALYSIS_METHOD = NULL, 
    MASS_PRODUCED_ANLS_METHD_OTHR = NULL, MASS_SOLD_ANALYSIS = NULL, IS_CO2_USED_ONSITE_INDICATOR = NULL, 
    AMOUNT_CO2_USED_ONSITE_METHOD = NULL, AMT_CO2_USED_ONSITE_METHD_OTHR = NULL, 
    MONTH_NAME = NULL, CAO_CHEMICAL_COMPO_ANALY = NULL, CAO_CHEMICAL_COMPO_ANALY_METHD = NULL, 
    CAO_CHEMICAL_COMPO_METHD_OTHR = NULL, MGO_CHEMICAL_COMPO_ANALY = NULL, MGO_CHEMICAL_COMPO_ANALY_METHD = NULL, 
    MGO_CHEMICAL_COMPO_METHD_OTHR = NULL, MASS_SOLD_ANALYSIS_METHOD = NULL) {
    
    args <- list(FACILITY_ID = FACILITY_ID, REPORTING_YEAR = REPORTING_YEAR, MASS_SOLD_ANALYSIS_METHOD_OTHR = MASS_SOLD_ANALYSIS_METHOD_OTHR, 
        MASS_PRODUCED_ANALYSIS_METHOD = MASS_PRODUCED_ANALYSIS_METHOD, MASS_PRODUCED_ANLS_METHD_OTHR = MASS_PRODUCED_ANLS_METHD_OTHR, 
        MASS_SOLD_ANALYSIS = MASS_SOLD_ANALYSIS, IS_CO2_USED_ONSITE_INDICATOR = IS_CO2_USED_ONSITE_INDICATOR, 
        AMOUNT_CO2_USED_ONSITE_METHOD = AMOUNT_CO2_USED_ONSITE_METHOD, AMT_CO2_USED_ONSITE_METHD_OTHR = AMT_CO2_USED_ONSITE_METHD_OTHR, 
        MONTH_NAME = MONTH_NAME, CAO_CHEMICAL_COMPO_ANALY = CAO_CHEMICAL_COMPO_ANALY, 
        CAO_CHEMICAL_COMPO_ANALY_METHD = CAO_CHEMICAL_COMPO_ANALY_METHD, CAO_CHEMICAL_COMPO_METHD_OTHR = CAO_CHEMICAL_COMPO_METHD_OTHR, 
        MGO_CHEMICAL_COMPO_ANALY = MGO_CHEMICAL_COMPO_ANALY, MGO_CHEMICAL_COMPO_ANALY_METHD = MGO_CHEMICAL_COMPO_ANALY_METHD, 
        MGO_CHEMICAL_COMPO_METHD_OTHR = MGO_CHEMICAL_COMPO_METHD_OTHR, MASS_SOLD_ANALYSIS_METHOD = MASS_SOLD_ANALYSIS_METHOD)
    ret <- envir_get(s_lime_product_details, args)
    
    ret
} 
