#' Retrieve ii equation ii6 data from ghg database
#' 
#' @param FACILITY_ID e.g. '1000035'. See Details.
#' @param REPORTING_YEAR e.g. '2011'. See Details.
#' @param FACILITY_NAME e.g. 'ANDERSONS MARATHON ETHANOL LLC'. See Details.
#' @param ANAEROBIC_PROCESS_ID e.g. 'Greenville Methanator System'. See Details.
#' @param ANAEROBIC_PROCESS_LEAKAGE e.g. '2.5922222'. See Details.
#' @param ANNUAL_MASS_METHANE_EMISSIONS e.g. '11.74'. See Details.
#' @param ANNUAL_METHANE_RECOVERED e.g. '256.63'. See Details.
#' @param ANNUALOPHOURSBACKUPDESTRDEVICE e.g. '35'. See Details.
#' @param ANNUAL_OP_HOURS_PRIMARY_DEVICE e.g. '8585'. See Details.
#' @param FRACT_OP_HOURS_PRIMARY_DEVICE e.g. '0.9800228'. See Details.
#' @param FRACT_OP_HOURS_SECOND_DEVICE e.g. '0.0039954'. See Details.
#' @param IS_BACKUP_DESTR_DEVICE_PRESENT e.g. 'Yes'. See Details.
#' @param METHANE_COLLECTION_EFFICIENCY e.g. '0.99'. See Details.
#' @param METHANE_DESTRUCTION_LOCATION e.g. 'On-Site'. See Details.
#' @param PRIMARY_DEVICE_DESTRUCTION_EFF e.g. '0.98'. See Details.
#' @param SECOND_DEVICE_DESTRUCTION_EFF e.g. '0.98'. See Details.
#' @export

ghg_ii_equation_ii6 <- function(FACILITY_ID = NULL, REPORTING_YEAR = NULL, FACILITY_NAME = NULL, 
    ANAEROBIC_PROCESS_ID = NULL, ANAEROBIC_PROCESS_LEAKAGE = NULL, ANNUAL_MASS_METHANE_EMISSIONS = NULL, 
    ANNUAL_METHANE_RECOVERED = NULL, ANNUALOPHOURSBACKUPDESTRDEVICE = NULL, ANNUAL_OP_HOURS_PRIMARY_DEVICE = NULL, 
    FRACT_OP_HOURS_PRIMARY_DEVICE = NULL, FRACT_OP_HOURS_SECOND_DEVICE = NULL, IS_BACKUP_DESTR_DEVICE_PRESENT = NULL, 
    METHANE_COLLECTION_EFFICIENCY = NULL, METHANE_DESTRUCTION_LOCATION = NULL, PRIMARY_DEVICE_DESTRUCTION_EFF = NULL, 
    SECOND_DEVICE_DESTRUCTION_EFF = NULL) {
    
    args <- list(FACILITY_ID = FACILITY_ID, REPORTING_YEAR = REPORTING_YEAR, FACILITY_NAME = FACILITY_NAME, 
        ANAEROBIC_PROCESS_ID = ANAEROBIC_PROCESS_ID, ANAEROBIC_PROCESS_LEAKAGE = ANAEROBIC_PROCESS_LEAKAGE, 
        ANNUAL_MASS_METHANE_EMISSIONS = ANNUAL_MASS_METHANE_EMISSIONS, ANNUAL_METHANE_RECOVERED = ANNUAL_METHANE_RECOVERED, 
        ANNUALOPHOURSBACKUPDESTRDEVICE = ANNUALOPHOURSBACKUPDESTRDEVICE, ANNUAL_OP_HOURS_PRIMARY_DEVICE = ANNUAL_OP_HOURS_PRIMARY_DEVICE, 
        FRACT_OP_HOURS_PRIMARY_DEVICE = FRACT_OP_HOURS_PRIMARY_DEVICE, FRACT_OP_HOURS_SECOND_DEVICE = FRACT_OP_HOURS_SECOND_DEVICE, 
        IS_BACKUP_DESTR_DEVICE_PRESENT = IS_BACKUP_DESTR_DEVICE_PRESENT, METHANE_COLLECTION_EFFICIENCY = METHANE_COLLECTION_EFFICIENCY, 
        METHANE_DESTRUCTION_LOCATION = METHANE_DESTRUCTION_LOCATION, PRIMARY_DEVICE_DESTRUCTION_EFF = PRIMARY_DEVICE_DESTRUCTION_EFF, 
        SECOND_DEVICE_DESTRUCTION_EFF = SECOND_DEVICE_DESTRUCTION_EFF)
    ret <- envir_get("ii_equation_ii6", args)
    
    ret
} 
