#' Retrieve i facility details data from ghg database
#' 
#' @param FACILITY_ID e.g. '1000354'. See Details.
#' @param REPORTING_YEAR e.g. '2012'. See Details.
#' @param FAC_MAN_GREA_THAN_300ML_WAFERS e.g. 'NO'. See Details.
#' @param FAC_MANUFACTURE_300ML_WAFERS e.g. 'NO'. See Details.
#' @param FAC_MANUFACTURE_200ML_WAFERS e.g. 'YES'. See Details.
#' @param FAC_MANUFACTURE_150ML_WAFERS e.g. 'NO'. See Details.
#' @param FAC_MANUFACTURE_MEMS_PVS_LCDS e.g. 'NO'. See Details.
#' @param FAC_MANUFACTURE_SEMICONDUCTORS e.g. 'YES'. See Details.
#' @param FACILITY_NAME e.g. 'CYPRESS SEMICONDUCTOR MINNESOTA INC'. See Details.
#' @param APPORTIONING_MODEL_COMPARISON e.g. '0.2'. See Details.
#' @param VERIFICATION_START_DATE e.g. '01-JAN-12'. See Details.
#' @param VERIFICATION_END_DATE e.g. '31-DEC-12'. See Details.
#' @param CERT_OF_GASES_SELECTED e.g. 'CERTIFIED'. See Details.
#' @param FAC_MAN_LESS_THAN_150ML_WAFERS e.g. 'NA'. See Details.
#' @export

ghg_i_facility_details <- function(FACILITY_ID = NULL, REPORTING_YEAR = NULL, FAC_MAN_GREA_THAN_300ML_WAFERS = NULL, 
    FAC_MANUFACTURE_300ML_WAFERS = NULL, FAC_MANUFACTURE_200ML_WAFERS = NULL, FAC_MANUFACTURE_150ML_WAFERS = NULL, 
    FAC_MANUFACTURE_MEMS_PVS_LCDS = NULL, FAC_MANUFACTURE_SEMICONDUCTORS = NULL, 
    FACILITY_NAME = NULL, APPORTIONING_MODEL_COMPARISON = NULL, VERIFICATION_START_DATE = NULL, 
    VERIFICATION_END_DATE = NULL, CERT_OF_GASES_SELECTED = NULL, FAC_MAN_LESS_THAN_150ML_WAFERS = NULL) {
    
    args <- list(FACILITY_ID = FACILITY_ID, REPORTING_YEAR = REPORTING_YEAR, FAC_MAN_GREA_THAN_300ML_WAFERS = FAC_MAN_GREA_THAN_300ML_WAFERS, 
        FAC_MANUFACTURE_300ML_WAFERS = FAC_MANUFACTURE_300ML_WAFERS, FAC_MANUFACTURE_200ML_WAFERS = FAC_MANUFACTURE_200ML_WAFERS, 
        FAC_MANUFACTURE_150ML_WAFERS = FAC_MANUFACTURE_150ML_WAFERS, FAC_MANUFACTURE_MEMS_PVS_LCDS = FAC_MANUFACTURE_MEMS_PVS_LCDS, 
        FAC_MANUFACTURE_SEMICONDUCTORS = FAC_MANUFACTURE_SEMICONDUCTORS, FACILITY_NAME = FACILITY_NAME, 
        APPORTIONING_MODEL_COMPARISON = APPORTIONING_MODEL_COMPARISON, VERIFICATION_START_DATE = VERIFICATION_START_DATE, 
        VERIFICATION_END_DATE = VERIFICATION_END_DATE, CERT_OF_GASES_SELECTED = CERT_OF_GASES_SELECTED, 
        FAC_MAN_LESS_THAN_150ML_WAFERS = FAC_MAN_LESS_THAN_150ML_WAFERS)
    ret <- envir_get(i_facility_details, args)
    
    ret
} 
