#' Retrieve w eor hydrocarbon liq data from ghg database
#' 
#' @param FACILITY_ID e.g. '1000355'. See Details.
#' @param REPORTING_YEAR e.g. '2011'. See Details.
#' @param DOES_FAC_HAVE_EOR_LIQ_DISSOLVE e.g. 'NO'. See Details.
#' @param EOR_LIQ_DIS_TOTAL_GHG_EMM_CO2E e.g. '0'. See Details.
#' @param EOR_LIQ_DIS_TOTAL_N2O_EMM_CO2E e.g. 'NA'. See Details.
#' @param EOR_LIQ_DIS_TOTAL_CH4_EMM_CO2E e.g. 'NA'. See Details.
#' @param EOR_LIQ_DIS_TOTAL_CO2_EMM e.g. '0'. See Details.
#' @param INDUSTRY_SEGMENT e.g. 'ONSHORE PETROLEUM AND NATURAL GAS PRODUCTION [98.230(A)(2)]'. See Details.
#' @param FACILITY_NAME e.g. '#540 BONANZA CREEK ENERGY - DENVER BASIN'. See Details.
#' @param BAMM_INDICATOR_HYDROCARBON_LIQ e.g. 'NA'. See Details.
#' @param SUB_INDICATOR_HYDROCARBON_LIQ e.g. 'NA'. See Details.
#' @param BAMM_DESC_HYDROCARBON_LIQ e.g. 'NA'. See Details.
#' @export

ghg_w_eor_hydrocarbon_liq <- function(FACILITY_ID = NULL, REPORTING_YEAR = NULL, 
    DOES_FAC_HAVE_EOR_LIQ_DISSOLVE = NULL, EOR_LIQ_DIS_TOTAL_GHG_EMM_CO2E = NULL, 
    EOR_LIQ_DIS_TOTAL_N2O_EMM_CO2E = NULL, EOR_LIQ_DIS_TOTAL_CH4_EMM_CO2E = NULL, 
    EOR_LIQ_DIS_TOTAL_CO2_EMM = NULL, INDUSTRY_SEGMENT = NULL, FACILITY_NAME = NULL, 
    BAMM_INDICATOR_HYDROCARBON_LIQ = NULL, SUB_INDICATOR_HYDROCARBON_LIQ = NULL, 
    BAMM_DESC_HYDROCARBON_LIQ = NULL) {
    
    args <- list(FACILITY_ID = FACILITY_ID, REPORTING_YEAR = REPORTING_YEAR, DOES_FAC_HAVE_EOR_LIQ_DISSOLVE = DOES_FAC_HAVE_EOR_LIQ_DISSOLVE, 
        EOR_LIQ_DIS_TOTAL_GHG_EMM_CO2E = EOR_LIQ_DIS_TOTAL_GHG_EMM_CO2E, EOR_LIQ_DIS_TOTAL_N2O_EMM_CO2E = EOR_LIQ_DIS_TOTAL_N2O_EMM_CO2E, 
        EOR_LIQ_DIS_TOTAL_CH4_EMM_CO2E = EOR_LIQ_DIS_TOTAL_CH4_EMM_CO2E, EOR_LIQ_DIS_TOTAL_CO2_EMM = EOR_LIQ_DIS_TOTAL_CO2_EMM, 
        INDUSTRY_SEGMENT = INDUSTRY_SEGMENT, FACILITY_NAME = FACILITY_NAME, BAMM_INDICATOR_HYDROCARBON_LIQ = BAMM_INDICATOR_HYDROCARBON_LIQ, 
        SUB_INDICATOR_HYDROCARBON_LIQ = SUB_INDICATOR_HYDROCARBON_LIQ, BAMM_DESC_HYDROCARBON_LIQ = BAMM_DESC_HYDROCARBON_LIQ)
    ret <- envir_get(w_eor_hydrocarbon_liq, args)
    
    ret
} 
