#' Retrieve h cems details data from ghg database
#' 
#' @param FACILITY_ID e.g. '1000198'. See Details.
#' @param REPORTING_YEAR e.g. '2013'. See Details.
#' @param CEMS_CO2_COMBUSTION_EMISSIONS e.g. 'NA'. See Details.
#' @param TIER4_SUB_OPER_HRS_GAS_FLOW_RT e.g. '0'. See Details.
#' @param TIER4_SUB_OPER_HRS_MOIST_CONT e.g. '0'. See Details.
#' @param CEMS_METHODOLOGY_START_DATE e.g. '2013-01-01'. See Details.
#' @param CEMS_METHODOLOGY_END_DATE e.g. '2013-12-31'. See Details.
#' @param CEMS_FUEL e.g. 'natural gas, petroleum coke, and recycled plastics'. See Details.
#' @param UNIT_NAMES e.g. 'Lehigh Cement Co. LLC, York, PA 17404'. See Details.
#' @param CEMS_CO2_EMISSIONS_BY_QUARTER e.g. 'First Quarter-8061.4 Metric Tons'. See Details.
#' @param FACILITY_NAME e.g. 'LEHIGH CEMENT CO LLC'. See Details.
#' @param CML_NAME e.g. 'Lehigh Cement Co., York, PA 17404'. See Details.
#' @param CML_CONFIGURATION_TYPE e.g. 'Process/stationary combustion units share common stack'. See Details.
#' @param CEMS_BIOGENIC_CO2_EMISSIONS e.g. '0'. See Details.
#' @param CEMS_NON_BIOGENIC_CO2_EMISSION e.g. '74736.2'. See Details.
#' @param CEMS_CO2_EMISSIONS e.g. '74736.2'. See Details.
#' @param CEMS_CH4_EMISSIONS e.g. '3.11'. See Details.
#' @param CEMS_N2O_EMISSIONS e.g. '0.382'. See Details.
#' @param CML_TOTAL_OPERATING_HOURS e.g. '6781'. See Details.
#' @param TIER4_SUB_OPER_HRS_CO2_CONC e.g. '360'. See Details.
#' @export

ghg_h_cems_details <- function(FACILITY_ID = NULL, REPORTING_YEAR = NULL, CEMS_CO2_COMBUSTION_EMISSIONS = NULL, 
    TIER4_SUB_OPER_HRS_GAS_FLOW_RT = NULL, TIER4_SUB_OPER_HRS_MOIST_CONT = NULL, 
    CEMS_METHODOLOGY_START_DATE = NULL, CEMS_METHODOLOGY_END_DATE = NULL, CEMS_FUEL = NULL, 
    UNIT_NAMES = NULL, CEMS_CO2_EMISSIONS_BY_QUARTER = NULL, FACILITY_NAME = NULL, 
    CML_NAME = NULL, CML_CONFIGURATION_TYPE = NULL, CEMS_BIOGENIC_CO2_EMISSIONS = NULL, 
    CEMS_NON_BIOGENIC_CO2_EMISSION = NULL, CEMS_CO2_EMISSIONS = NULL, CEMS_CH4_EMISSIONS = NULL, 
    CEMS_N2O_EMISSIONS = NULL, CML_TOTAL_OPERATING_HOURS = NULL, TIER4_SUB_OPER_HRS_CO2_CONC = NULL) {
    
    args <- list(FACILITY_ID = FACILITY_ID, REPORTING_YEAR = REPORTING_YEAR, CEMS_CO2_COMBUSTION_EMISSIONS = CEMS_CO2_COMBUSTION_EMISSIONS, 
        TIER4_SUB_OPER_HRS_GAS_FLOW_RT = TIER4_SUB_OPER_HRS_GAS_FLOW_RT, TIER4_SUB_OPER_HRS_MOIST_CONT = TIER4_SUB_OPER_HRS_MOIST_CONT, 
        CEMS_METHODOLOGY_START_DATE = CEMS_METHODOLOGY_START_DATE, CEMS_METHODOLOGY_END_DATE = CEMS_METHODOLOGY_END_DATE, 
        CEMS_FUEL = CEMS_FUEL, UNIT_NAMES = UNIT_NAMES, CEMS_CO2_EMISSIONS_BY_QUARTER = CEMS_CO2_EMISSIONS_BY_QUARTER, 
        FACILITY_NAME = FACILITY_NAME, CML_NAME = CML_NAME, CML_CONFIGURATION_TYPE = CML_CONFIGURATION_TYPE, 
        CEMS_BIOGENIC_CO2_EMISSIONS = CEMS_BIOGENIC_CO2_EMISSIONS, CEMS_NON_BIOGENIC_CO2_EMISSION = CEMS_NON_BIOGENIC_CO2_EMISSION, 
        CEMS_CO2_EMISSIONS = CEMS_CO2_EMISSIONS, CEMS_CH4_EMISSIONS = CEMS_CH4_EMISSIONS, 
        CEMS_N2O_EMISSIONS = CEMS_N2O_EMISSIONS, CML_TOTAL_OPERATING_HOURS = CML_TOTAL_OPERATING_HOURS, 
        TIER4_SUB_OPER_HRS_CO2_CONC = TIER4_SUB_OPER_HRS_CO2_CONC)
    ret <- envir_get("h_cems_details", args)
    
    ret
} 
