#' Retrieve ss msng dta hose vlv data from ghg database
#' 
#' @param FACILITY_ID e.g. '1000039'. See Details.
#' @param REPORTING_YEAR e.g. '2013'. See Details.
#' @param FACILITY_NAME e.g. 'Alstom Grid Inc'. See Details.
#' @param HOSE_VALVE_COMBINATION_ID e.g. 'H1 Dilo Fill Hose'. See Details.
#' @param MTHD_TOT_FILL_OP_FLUOROBUTANE e.g. 'NA'. See Details.
#' @param MTHD_TOT_FILL_OP_FLUOCYCLOBUTA e.g. 'NA'. See Details.
#' @param MTHD_TOT_FILL_OP_FLUOCYCLOPROP e.g. 'NA'. See Details.
#' @param MTHD_TOT_FILL_OPFLUORODECALIN e.g. 'NA'. See Details.
#' @param MTHD_TOT_FILL_OP_FLUOROETHANE e.g. 'NA'. See Details.
#' @param MTHD_TOT_FILL_OP_FLUOROHEXANE e.g. 'NA'. See Details.
#' @param MTHD_TOT_FILL_OP_FLUOROMETHANE e.g. 'NA'. See Details.
#' @param MTHD_TOT_FILL_OP_FLUOROPENTANE e.g. 'NA'. See Details.
#' @param MTHD_TOT_FILL_OP_FLUOROPROPANE e.g. 'NA'. See Details.
#' @param MTHD_TOT_FILL_OP_SULFURHEXAFLU e.g. 'Assumed to be equal to units shipped x estimated filling and reclaiming operations'. See Details.
#' @param MTHD_EFC_VAL_FLUOROBUTANE e.g. 'NA'. See Details.
#' @param MTHD_EFC_VAL_FLUOROCYCLOBUTANE e.g. 'NA'. See Details.
#' @param MTHD_EFC_VAL_FLUOROCYCLOPROPAN e.g. 'NA'. See Details.
#' @param MTHD_EFC_VAL_FLUORODECALIN e.g. 'NA'. See Details.
#' @param MTHD_EFC_VAL_FLUOROETHANE e.g. 'NA'. See Details.
#' @param MTHD_EFC_VAL_FLUOROHEXANE e.g. 'NA'. See Details.
#' @param MTHD_EFC_VAL_FLUOROMETHANE e.g. 'NA'. See Details.
#' @param MTHD_EFC_VAL_FLUOROPENTANE e.g. 'NA'. See Details.
#' @param MISS_TOT_FILL_OP_FLUOROMETH_RE e.g. 'NA'. See Details.
#' @param MISS_TOT_FILL_OP_FLUOROPENTANE e.g. 'NA'. See Details.
#' @param MISS_TOT_FILL_OP_FLUORPENTA_RE e.g. 'NA'. See Details.
#' @param MISS_TOT_FILL_OP_FLUOROPROPANE e.g. 'NA'. See Details.
#' @param MISS_TOT_FILL_OP_FLUORROPAN_RE e.g. 'NA'. See Details.
#' @param MISS_TOT_FILL_OP_SULFURHXAFLUO e.g. 'Yes'. See Details.
#' @param MISS_TOT_FILL_OP_SULFURHXFL_RE e.g. 'Num'. See Details.
#' @param MTHD_EFC_VAL_FLUOROPROPANE e.g. 'NA'. See Details.
#' @param MTHD_EFC_VAL_SULFURHEXAFLUORID e.g. 'NA'. See Details.
#' @param MISSING_EFC_VAL_FLUOROBUTANE e.g. 'NA'. See Details.
#' @param MISS_EFC_VAL_FLUOROBUTANE_RE e.g. 'NA'. See Details.
#' @param MISS_EFC_VAL_FLUOROCYCLOBUTANE e.g. 'NA'. See Details.
#' @param MISS_EFC_VAL_FLUOCYCLOBUTA_RE e.g. 'NA'. See Details.
#' @param MISS_EFC_VAL_FLUOROCYCLOPROPAN e.g. 'NA'. See Details.
#' @param MISS_EFC_VAL_FLUOCYCLOPROPA_RE e.g. 'NA'. See Details.
#' @param MISSING_EFC_VAL_FLUORODECALIN e.g. 'NA'. See Details.
#' @param MISS_EFC_VAL_FLUORODECALIN_RE e.g. 'NA'. See Details.
#' @param MISSING_EFC_VAL_FLUOROETHANE e.g. 'NA'. See Details.
#' @param MISSING_EFC_VAL_FLUOROETHANE_R e.g. 'NA'. See Details.
#' @param MISSING_EFC_VAL_FLUOROHEXANE e.g. 'NA'. See Details.
#' @param MISSING_EFC_VAL_FLUOROHEXAN_RE e.g. 'NA'. See Details.
#' @param MISSING_EFC_VAL_FLUOROMETHANE e.g. 'No'. See Details.
#' @param MISS_EFC_VAL_FLUOROMETHANEREAS e.g. 'NA'. See Details.
#' @param MISSING_EFC_VAL_FLUOROPENTANE e.g. 'NA'. See Details.
#' @param MISS_EFC_VAL_FLUOROPENTANEREAS e.g. 'NA'. See Details.
#' @param MISSING_EFC_VAL_FLUOROPROPANE e.g. 'NA'. See Details.
#' @param MISS_EFC_VAL_FLUOROPROPANEREAS e.g. 'NA'. See Details.
#' @param MISS_EFC_VAL_SULFURHEXAFLUORID e.g. 'No'. See Details.
#' @param MISS_EFC_VAL_SULFURHEXAFLUO_RE e.g. 'NA'. See Details.
#' @param MISS_TOT_FILL_OP_FLUOROBUTANE e.g. 'NA'. See Details.
#' @param MISS_TOT_FILL_OP_FLUOROBUTA_RE e.g. 'NA'. See Details.
#' @param MISS_TOT_FILL_OP_FLUOCYCLOBUTA e.g. 'NA'. See Details.
#' @param MISS_TOT_FILL_OP_FLUOCYCLOA_RE e.g. 'NA'. See Details.
#' @param MISS_TOT_FILL_OPFLUOCYCLOPROPA e.g. 'NA'. See Details.
#' @param MISS_TOT_FILL_OP_FLUOCYCLOP_RE e.g. 'NA'. See Details.
#' @param MISS_TOT_FILL_OP_FLUORODECALIN e.g. 'NA'. See Details.
#' @param MISS_TOT_FILL_OP_FLUORODECA_RE e.g. 'NA'. See Details.
#' @param MISS_TOT_FILL_OP_FLUOROETHANE e.g. 'NA'. See Details.
#' @param MISS_TOT_FILL_OP_FLUOROETHA_RE e.g. 'NA'. See Details.
#' @param MISS_TOT_FILL_OP_FLUOROHEXANE e.g. 'NA'. See Details.
#' @param MISS_TOT_FILL_OP_FLUOROHEXA_RE e.g. 'NA'. See Details.
#' @param MISS_TOT_FILL_OP_FLUOROMETHANE e.g. 'No'. See Details.
#' @export

ghg_ss_msng_dta_hose_vlv <- function(FACILITY_ID = NULL, REPORTING_YEAR = NULL, FACILITY_NAME = NULL, 
    HOSE_VALVE_COMBINATION_ID = NULL, MTHD_TOT_FILL_OP_FLUOROBUTANE = NULL, MTHD_TOT_FILL_OP_FLUOCYCLOBUTA = NULL, 
    MTHD_TOT_FILL_OP_FLUOCYCLOPROP = NULL, MTHD_TOT_FILL_OPFLUORODECALIN = NULL, 
    MTHD_TOT_FILL_OP_FLUOROETHANE = NULL, MTHD_TOT_FILL_OP_FLUOROHEXANE = NULL, MTHD_TOT_FILL_OP_FLUOROMETHANE = NULL, 
    MTHD_TOT_FILL_OP_FLUOROPENTANE = NULL, MTHD_TOT_FILL_OP_FLUOROPROPANE = NULL, 
    MTHD_TOT_FILL_OP_SULFURHEXAFLU = NULL, MTHD_EFC_VAL_FLUOROBUTANE = NULL, MTHD_EFC_VAL_FLUOROCYCLOBUTANE = NULL, 
    MTHD_EFC_VAL_FLUOROCYCLOPROPAN = NULL, MTHD_EFC_VAL_FLUORODECALIN = NULL, MTHD_EFC_VAL_FLUOROETHANE = NULL, 
    MTHD_EFC_VAL_FLUOROHEXANE = NULL, MTHD_EFC_VAL_FLUOROMETHANE = NULL, MTHD_EFC_VAL_FLUOROPENTANE = NULL, 
    MISS_TOT_FILL_OP_FLUOROMETH_RE = NULL, MISS_TOT_FILL_OP_FLUOROPENTANE = NULL, 
    MISS_TOT_FILL_OP_FLUORPENTA_RE = NULL, MISS_TOT_FILL_OP_FLUOROPROPANE = NULL, 
    MISS_TOT_FILL_OP_FLUORROPAN_RE = NULL, MISS_TOT_FILL_OP_SULFURHXAFLUO = NULL, 
    MISS_TOT_FILL_OP_SULFURHXFL_RE = NULL, MTHD_EFC_VAL_FLUOROPROPANE = NULL, MTHD_EFC_VAL_SULFURHEXAFLUORID = NULL, 
    MISSING_EFC_VAL_FLUOROBUTANE = NULL, MISS_EFC_VAL_FLUOROBUTANE_RE = NULL, MISS_EFC_VAL_FLUOROCYCLOBUTANE = NULL, 
    MISS_EFC_VAL_FLUOCYCLOBUTA_RE = NULL, MISS_EFC_VAL_FLUOROCYCLOPROPAN = NULL, 
    MISS_EFC_VAL_FLUOCYCLOPROPA_RE = NULL, MISSING_EFC_VAL_FLUORODECALIN = NULL, 
    MISS_EFC_VAL_FLUORODECALIN_RE = NULL, MISSING_EFC_VAL_FLUOROETHANE = NULL, MISSING_EFC_VAL_FLUOROETHANE_R = NULL, 
    MISSING_EFC_VAL_FLUOROHEXANE = NULL, MISSING_EFC_VAL_FLUOROHEXAN_RE = NULL, MISSING_EFC_VAL_FLUOROMETHANE = NULL, 
    MISS_EFC_VAL_FLUOROMETHANEREAS = NULL, MISSING_EFC_VAL_FLUOROPENTANE = NULL, 
    MISS_EFC_VAL_FLUOROPENTANEREAS = NULL, MISSING_EFC_VAL_FLUOROPROPANE = NULL, 
    MISS_EFC_VAL_FLUOROPROPANEREAS = NULL, MISS_EFC_VAL_SULFURHEXAFLUORID = NULL, 
    MISS_EFC_VAL_SULFURHEXAFLUO_RE = NULL, MISS_TOT_FILL_OP_FLUOROBUTANE = NULL, 
    MISS_TOT_FILL_OP_FLUOROBUTA_RE = NULL, MISS_TOT_FILL_OP_FLUOCYCLOBUTA = NULL, 
    MISS_TOT_FILL_OP_FLUOCYCLOA_RE = NULL, MISS_TOT_FILL_OPFLUOCYCLOPROPA = NULL, 
    MISS_TOT_FILL_OP_FLUOCYCLOP_RE = NULL, MISS_TOT_FILL_OP_FLUORODECALIN = NULL, 
    MISS_TOT_FILL_OP_FLUORODECA_RE = NULL, MISS_TOT_FILL_OP_FLUOROETHANE = NULL, 
    MISS_TOT_FILL_OP_FLUOROETHA_RE = NULL, MISS_TOT_FILL_OP_FLUOROHEXANE = NULL, 
    MISS_TOT_FILL_OP_FLUOROHEXA_RE = NULL, MISS_TOT_FILL_OP_FLUOROMETHANE = NULL) {
    
    args <- list(FACILITY_ID = FACILITY_ID, REPORTING_YEAR = REPORTING_YEAR, FACILITY_NAME = FACILITY_NAME, 
        HOSE_VALVE_COMBINATION_ID = HOSE_VALVE_COMBINATION_ID, MTHD_TOT_FILL_OP_FLUOROBUTANE = MTHD_TOT_FILL_OP_FLUOROBUTANE, 
        MTHD_TOT_FILL_OP_FLUOCYCLOBUTA = MTHD_TOT_FILL_OP_FLUOCYCLOBUTA, MTHD_TOT_FILL_OP_FLUOCYCLOPROP = MTHD_TOT_FILL_OP_FLUOCYCLOPROP, 
        MTHD_TOT_FILL_OPFLUORODECALIN = MTHD_TOT_FILL_OPFLUORODECALIN, MTHD_TOT_FILL_OP_FLUOROETHANE = MTHD_TOT_FILL_OP_FLUOROETHANE, 
        MTHD_TOT_FILL_OP_FLUOROHEXANE = MTHD_TOT_FILL_OP_FLUOROHEXANE, MTHD_TOT_FILL_OP_FLUOROMETHANE = MTHD_TOT_FILL_OP_FLUOROMETHANE, 
        MTHD_TOT_FILL_OP_FLUOROPENTANE = MTHD_TOT_FILL_OP_FLUOROPENTANE, MTHD_TOT_FILL_OP_FLUOROPROPANE = MTHD_TOT_FILL_OP_FLUOROPROPANE, 
        MTHD_TOT_FILL_OP_SULFURHEXAFLU = MTHD_TOT_FILL_OP_SULFURHEXAFLU, MTHD_EFC_VAL_FLUOROBUTANE = MTHD_EFC_VAL_FLUOROBUTANE, 
        MTHD_EFC_VAL_FLUOROCYCLOBUTANE = MTHD_EFC_VAL_FLUOROCYCLOBUTANE, MTHD_EFC_VAL_FLUOROCYCLOPROPAN = MTHD_EFC_VAL_FLUOROCYCLOPROPAN, 
        MTHD_EFC_VAL_FLUORODECALIN = MTHD_EFC_VAL_FLUORODECALIN, MTHD_EFC_VAL_FLUOROETHANE = MTHD_EFC_VAL_FLUOROETHANE, 
        MTHD_EFC_VAL_FLUOROHEXANE = MTHD_EFC_VAL_FLUOROHEXANE, MTHD_EFC_VAL_FLUOROMETHANE = MTHD_EFC_VAL_FLUOROMETHANE, 
        MTHD_EFC_VAL_FLUOROPENTANE = MTHD_EFC_VAL_FLUOROPENTANE, MISS_TOT_FILL_OP_FLUOROMETH_RE = MISS_TOT_FILL_OP_FLUOROMETH_RE, 
        MISS_TOT_FILL_OP_FLUOROPENTANE = MISS_TOT_FILL_OP_FLUOROPENTANE, MISS_TOT_FILL_OP_FLUORPENTA_RE = MISS_TOT_FILL_OP_FLUORPENTA_RE, 
        MISS_TOT_FILL_OP_FLUOROPROPANE = MISS_TOT_FILL_OP_FLUOROPROPANE, MISS_TOT_FILL_OP_FLUORROPAN_RE = MISS_TOT_FILL_OP_FLUORROPAN_RE, 
        MISS_TOT_FILL_OP_SULFURHXAFLUO = MISS_TOT_FILL_OP_SULFURHXAFLUO, MISS_TOT_FILL_OP_SULFURHXFL_RE = MISS_TOT_FILL_OP_SULFURHXFL_RE, 
        MTHD_EFC_VAL_FLUOROPROPANE = MTHD_EFC_VAL_FLUOROPROPANE, MTHD_EFC_VAL_SULFURHEXAFLUORID = MTHD_EFC_VAL_SULFURHEXAFLUORID, 
        MISSING_EFC_VAL_FLUOROBUTANE = MISSING_EFC_VAL_FLUOROBUTANE, MISS_EFC_VAL_FLUOROBUTANE_RE = MISS_EFC_VAL_FLUOROBUTANE_RE, 
        MISS_EFC_VAL_FLUOROCYCLOBUTANE = MISS_EFC_VAL_FLUOROCYCLOBUTANE, MISS_EFC_VAL_FLUOCYCLOBUTA_RE = MISS_EFC_VAL_FLUOCYCLOBUTA_RE, 
        MISS_EFC_VAL_FLUOROCYCLOPROPAN = MISS_EFC_VAL_FLUOROCYCLOPROPAN, MISS_EFC_VAL_FLUOCYCLOPROPA_RE = MISS_EFC_VAL_FLUOCYCLOPROPA_RE, 
        MISSING_EFC_VAL_FLUORODECALIN = MISSING_EFC_VAL_FLUORODECALIN, MISS_EFC_VAL_FLUORODECALIN_RE = MISS_EFC_VAL_FLUORODECALIN_RE, 
        MISSING_EFC_VAL_FLUOROETHANE = MISSING_EFC_VAL_FLUOROETHANE, MISSING_EFC_VAL_FLUOROETHANE_R = MISSING_EFC_VAL_FLUOROETHANE_R, 
        MISSING_EFC_VAL_FLUOROHEXANE = MISSING_EFC_VAL_FLUOROHEXANE, MISSING_EFC_VAL_FLUOROHEXAN_RE = MISSING_EFC_VAL_FLUOROHEXAN_RE, 
        MISSING_EFC_VAL_FLUOROMETHANE = MISSING_EFC_VAL_FLUOROMETHANE, MISS_EFC_VAL_FLUOROMETHANEREAS = MISS_EFC_VAL_FLUOROMETHANEREAS, 
        MISSING_EFC_VAL_FLUOROPENTANE = MISSING_EFC_VAL_FLUOROPENTANE, MISS_EFC_VAL_FLUOROPENTANEREAS = MISS_EFC_VAL_FLUOROPENTANEREAS, 
        MISSING_EFC_VAL_FLUOROPROPANE = MISSING_EFC_VAL_FLUOROPROPANE, MISS_EFC_VAL_FLUOROPROPANEREAS = MISS_EFC_VAL_FLUOROPROPANEREAS, 
        MISS_EFC_VAL_SULFURHEXAFLUORID = MISS_EFC_VAL_SULFURHEXAFLUORID, MISS_EFC_VAL_SULFURHEXAFLUO_RE = MISS_EFC_VAL_SULFURHEXAFLUO_RE, 
        MISS_TOT_FILL_OP_FLUOROBUTANE = MISS_TOT_FILL_OP_FLUOROBUTANE, MISS_TOT_FILL_OP_FLUOROBUTA_RE = MISS_TOT_FILL_OP_FLUOROBUTA_RE, 
        MISS_TOT_FILL_OP_FLUOCYCLOBUTA = MISS_TOT_FILL_OP_FLUOCYCLOBUTA, MISS_TOT_FILL_OP_FLUOCYCLOA_RE = MISS_TOT_FILL_OP_FLUOCYCLOA_RE, 
        MISS_TOT_FILL_OPFLUOCYCLOPROPA = MISS_TOT_FILL_OPFLUOCYCLOPROPA, MISS_TOT_FILL_OP_FLUOCYCLOP_RE = MISS_TOT_FILL_OP_FLUOCYCLOP_RE, 
        MISS_TOT_FILL_OP_FLUORODECALIN = MISS_TOT_FILL_OP_FLUORODECALIN, MISS_TOT_FILL_OP_FLUORODECA_RE = MISS_TOT_FILL_OP_FLUORODECA_RE, 
        MISS_TOT_FILL_OP_FLUOROETHANE = MISS_TOT_FILL_OP_FLUOROETHANE, MISS_TOT_FILL_OP_FLUOROETHA_RE = MISS_TOT_FILL_OP_FLUOROETHA_RE, 
        MISS_TOT_FILL_OP_FLUOROHEXANE = MISS_TOT_FILL_OP_FLUOROHEXANE, MISS_TOT_FILL_OP_FLUOROHEXA_RE = MISS_TOT_FILL_OP_FLUOROHEXA_RE, 
        MISS_TOT_FILL_OP_FLUOROMETHANE = MISS_TOT_FILL_OP_FLUOROMETHANE)
    ret <- envir_get(ss_msng_dta_hose_vlv, args)
    
    ret
} 
