#' Retrieve tt landfill details data from ghg database
#' 
#' @param FACILITY_ID e.g. '1000093'. See Details.
#' @param REPORTING_YEAR e.g. '2011'. See Details.
#' @param FACILITY_NAME e.g. 'MOMENTIVE PERFORMANCE MATERIALS'. See Details.
#' @param LANDFILL_OPEN e.g. 'N'. See Details.
#' @param LANDFILL_GAS_COLL_SYSTEM_INDIC e.g. 'N'. See Details.
#' @param LEACHATE_RECIRCULATION_INDICA e.g. 'N'. See Details.
#' @param LEACHATE_RECIRCULATION_FREQ e.g. 'NOT USED FOR THE PAST TEN (10) YEARS'. See Details.
#' @param IS_MCF_VALUE_DEFAULT_INDICATOR e.g. 'N'. See Details.
#' @param PASSIVE_VENT_FLARE_INDICATOR e.g. 'Y'. See Details.
#' @param COVER_TYPE_NAME e.g. 'SAND COVER'. See Details.
#' @param LF_SURFACEAREA_BY_COVERTYPE e.g. '4550'. See Details.
#' @param ESTIMATED_YEAR_OF_LF_CLOSURE e.g. 'NA'. See Details.
#' @param LAST_YEAR_LF_RECEIVED_WASTE e.g. '1989'. See Details.
#' @param MCF_VALUE e.g. 'NA'. See Details.
#' @param AERATION_BLOWER_CAPACITY e.g. 'NA'. See Details.
#' @param LANDFILL_FRAC_AFFECT_AERATION e.g. 'NA'. See Details.
#' @param AERATION_BLOWER_OPERATING_HRS e.g. 'NA'. See Details.
#' @param FACTORS_USED_AS_BASIS_FOR_MCF e.g. 'NA'. See Details.
#' @param AERATION_SYSTEM_DESCRIPTION e.g. 'NA'. See Details.
#' @param ANNL_METHANE_EMISSIONS_EQ_TT6 e.g. '57.64'. See Details.
#' @param NUMBER_OF_WASTE_STREAMS e.g. '1'. See Details.
#' @param FRACTION_METHANE_IN_LF_GAS e.g. 'NA'. See Details.
#' @param FRCT_METHANE_LF_GAS_DTRM_IND e.g. 'DEFA'. See Details.
#' @param STARTINGYEARFORACCEPTINGWASTE e.g. '1972'. See Details.
#' @param DOESFACKNOWWHENLANDFILLOPENED e.g. 'NA'. See Details.
#' @param ISWASTEQUANTITYDATAAVAILIND e.g. 'NA'. See Details.
#' @param LANDFILLCAPACITY e.g. 'NA'. See Details.
#' @param LANDFILLFIRSTRECEIVEDWASTE e.g. 'NA'. See Details.
#' @param PRIORYRWASTEDISPDATAFIRSTAVAIL e.g. 'NA'. See Details.
#' @param YEARLASTRECEIVEDWASTE e.g. 'NA'. See Details.
#' @param ANNUALMODELEDCH4GENTT1 e.g. '64.05'. See Details.
#' @param ANNUAL_VOL_LANDFILL_GAS_FLOW e.g. 'NA'. See Details.
#' @param ANNUAL_AVERAGE_METHANE_CONCEN e.g. 'NA'. See Details.
#' @param ON_SITE_DESTRUCTION_INDICATOR e.g. 'NA'. See Details.
#' @param GAS_COLL_SYSTEM_MANUFACTURER e.g. 'NA'. See Details.
#' @param GAS_COLL_SYSTEM_CAPACITY e.g. 'NA'. See Details.
#' @param NUMBER_OF_WELLS e.g. 'NA'. See Details.
#' @param MEAS_METHANE_GEN_EQ_HH7 e.g. 'NA'. See Details.
#' @param BASIS_FOR_INPUT_METH_GEN_VALUE e.g. 'NA'. See Details.
#' @param METHANE_EMISSION_EQ_HH6 e.g. 'NA'. See Details.
#' @param METHANE_EMISSION_EQ_HH8 e.g. 'NA'. See Details.
#' @param GAS_COLL_SYSTEM_ANN_OPER_HRS e.g. 'NA'. See Details.
#' @param ANNUAL_QTY_RECOV_METHANE_HH4 e.g. 'NA'. See Details.
#' @param EST_GAS_COLLECTION_EFFICIENCY e.g. 'NA'. See Details.
#' @param IS_LFG_FLOW_WET_BASIS_INDICATR e.g. 'NA'. See Details.
#' @param IS_CH4_CONC_WET_BASIS_INDICATR e.g. 'NA'. See Details.
#' @param IS_PRESSURE_INCORP_INDICATOR e.g. 'NA'. See Details.
#' @param IS_TEMPERATURE_INCORP_INDICATR e.g. 'NA'. See Details.
#' @param MODELED_METHANE_GEN_EQ_HH5 e.g. 'NA'. See Details.
#' @param BACKUP_DEVICE_ANNUAL_OP_HOURS e.g. 'NA'. See Details.
#' @param DESTRUCTION_EFFICIENCY_PERCENT e.g. 'NA'. See Details.
#' @param BACKUP_DESTRUCTION_DEVICE e.g. 'NA'. See Details.
#' @param PRIMARY_DEVICE_ANNUAL_OP_HOURS e.g. 'NA'. See Details.
#' @param ANN_AVG_METHANE_CONC_MONTHS e.g. 'NA'. See Details.
#' @param ANN_AVG_METHANE_CONC_DAYS e.g. 'NA'. See Details.
#' @param ANN_VOL_LFGFLOW_DAYS e.g. 'NA'. See Details.
#' @param METHANE_OXIDATION_FRACTION_HH6 e.g. 'NA'. See Details.
#' @param METHANE_OXIDATION_FRACTION_HH7 e.g. 'NA'. See Details.
#' @param METHANE_OXIDATION_FRACTION_HH8 e.g. 'NA'. See Details.
#' @param METHANE_OXIDATION_FRACTION_TT6 e.g. 'NA'. See Details.
#' @param NGMETH_OXIDATION_FRACTION_TT6 e.g. 'NA'. See Details.
#' @param CUMULATIVE_WASTE_QUANTITY e.g. 'NA'. See Details.
#' @param DOES_FAC_KNW_WHN_LANDFILL_OPEN e.g. 'NA'. See Details.
#' @param IS_WASTE_IN_PLACE_QUAN_KNW_IND e.g. 'NA'. See Details.
#' @param LANDFILL_DESIGN_CAPACITY e.g. 'NA'. See Details.
#' @param LANDFILL_RECVD_WASTE_YEAR_LAST e.g. 'NA'. See Details.
#' @param LANDFILL_YEAR_OPEN e.g. 'NA'. See Details.
#' @param QUANTITY_AVAILABLE_YEARS e.g. 'NA'. See Details.
#' @param WASTE_IN_PLACE_QUANTITY e.g. 'NA'. See Details.
#' @export

ghg_tt_landfill_details <- function(FACILITY_ID = NULL, REPORTING_YEAR = NULL, FACILITY_NAME = NULL, 
    LANDFILL_OPEN = NULL, LANDFILL_GAS_COLL_SYSTEM_INDIC = NULL, LEACHATE_RECIRCULATION_INDICA = NULL, 
    LEACHATE_RECIRCULATION_FREQ = NULL, IS_MCF_VALUE_DEFAULT_INDICATOR = NULL, PASSIVE_VENT_FLARE_INDICATOR = NULL, 
    COVER_TYPE_NAME = NULL, LF_SURFACEAREA_BY_COVERTYPE = NULL, ESTIMATED_YEAR_OF_LF_CLOSURE = NULL, 
    LAST_YEAR_LF_RECEIVED_WASTE = NULL, MCF_VALUE = NULL, AERATION_BLOWER_CAPACITY = NULL, 
    LANDFILL_FRAC_AFFECT_AERATION = NULL, AERATION_BLOWER_OPERATING_HRS = NULL, FACTORS_USED_AS_BASIS_FOR_MCF = NULL, 
    AERATION_SYSTEM_DESCRIPTION = NULL, ANNL_METHANE_EMISSIONS_EQ_TT6 = NULL, NUMBER_OF_WASTE_STREAMS = NULL, 
    FRACTION_METHANE_IN_LF_GAS = NULL, FRCT_METHANE_LF_GAS_DTRM_IND = NULL, STARTINGYEARFORACCEPTINGWASTE = NULL, 
    DOESFACKNOWWHENLANDFILLOPENED = NULL, ISWASTEQUANTITYDATAAVAILIND = NULL, LANDFILLCAPACITY = NULL, 
    LANDFILLFIRSTRECEIVEDWASTE = NULL, PRIORYRWASTEDISPDATAFIRSTAVAIL = NULL, YEARLASTRECEIVEDWASTE = NULL, 
    ANNUALMODELEDCH4GENTT1 = NULL, ANNUAL_VOL_LANDFILL_GAS_FLOW = NULL, ANNUAL_AVERAGE_METHANE_CONCEN = NULL, 
    ON_SITE_DESTRUCTION_INDICATOR = NULL, GAS_COLL_SYSTEM_MANUFACTURER = NULL, GAS_COLL_SYSTEM_CAPACITY = NULL, 
    NUMBER_OF_WELLS = NULL, MEAS_METHANE_GEN_EQ_HH7 = NULL, BASIS_FOR_INPUT_METH_GEN_VALUE = NULL, 
    METHANE_EMISSION_EQ_HH6 = NULL, METHANE_EMISSION_EQ_HH8 = NULL, GAS_COLL_SYSTEM_ANN_OPER_HRS = NULL, 
    ANNUAL_QTY_RECOV_METHANE_HH4 = NULL, EST_GAS_COLLECTION_EFFICIENCY = NULL, IS_LFG_FLOW_WET_BASIS_INDICATR = NULL, 
    IS_CH4_CONC_WET_BASIS_INDICATR = NULL, IS_PRESSURE_INCORP_INDICATOR = NULL, IS_TEMPERATURE_INCORP_INDICATR = NULL, 
    MODELED_METHANE_GEN_EQ_HH5 = NULL, BACKUP_DEVICE_ANNUAL_OP_HOURS = NULL, DESTRUCTION_EFFICIENCY_PERCENT = NULL, 
    BACKUP_DESTRUCTION_DEVICE = NULL, PRIMARY_DEVICE_ANNUAL_OP_HOURS = NULL, ANN_AVG_METHANE_CONC_MONTHS = NULL, 
    ANN_AVG_METHANE_CONC_DAYS = NULL, ANN_VOL_LFGFLOW_DAYS = NULL, METHANE_OXIDATION_FRACTION_HH6 = NULL, 
    METHANE_OXIDATION_FRACTION_HH7 = NULL, METHANE_OXIDATION_FRACTION_HH8 = NULL, 
    METHANE_OXIDATION_FRACTION_TT6 = NULL, NGMETH_OXIDATION_FRACTION_TT6 = NULL, 
    CUMULATIVE_WASTE_QUANTITY = NULL, DOES_FAC_KNW_WHN_LANDFILL_OPEN = NULL, IS_WASTE_IN_PLACE_QUAN_KNW_IND = NULL, 
    LANDFILL_DESIGN_CAPACITY = NULL, LANDFILL_RECVD_WASTE_YEAR_LAST = NULL, LANDFILL_YEAR_OPEN = NULL, 
    QUANTITY_AVAILABLE_YEARS = NULL, WASTE_IN_PLACE_QUANTITY = NULL) {
    
    args <- list(FACILITY_ID = FACILITY_ID, REPORTING_YEAR = REPORTING_YEAR, FACILITY_NAME = FACILITY_NAME, 
        LANDFILL_OPEN = LANDFILL_OPEN, LANDFILL_GAS_COLL_SYSTEM_INDIC = LANDFILL_GAS_COLL_SYSTEM_INDIC, 
        LEACHATE_RECIRCULATION_INDICA = LEACHATE_RECIRCULATION_INDICA, LEACHATE_RECIRCULATION_FREQ = LEACHATE_RECIRCULATION_FREQ, 
        IS_MCF_VALUE_DEFAULT_INDICATOR = IS_MCF_VALUE_DEFAULT_INDICATOR, PASSIVE_VENT_FLARE_INDICATOR = PASSIVE_VENT_FLARE_INDICATOR, 
        COVER_TYPE_NAME = COVER_TYPE_NAME, LF_SURFACEAREA_BY_COVERTYPE = LF_SURFACEAREA_BY_COVERTYPE, 
        ESTIMATED_YEAR_OF_LF_CLOSURE = ESTIMATED_YEAR_OF_LF_CLOSURE, LAST_YEAR_LF_RECEIVED_WASTE = LAST_YEAR_LF_RECEIVED_WASTE, 
        MCF_VALUE = MCF_VALUE, AERATION_BLOWER_CAPACITY = AERATION_BLOWER_CAPACITY, 
        LANDFILL_FRAC_AFFECT_AERATION = LANDFILL_FRAC_AFFECT_AERATION, AERATION_BLOWER_OPERATING_HRS = AERATION_BLOWER_OPERATING_HRS, 
        FACTORS_USED_AS_BASIS_FOR_MCF = FACTORS_USED_AS_BASIS_FOR_MCF, AERATION_SYSTEM_DESCRIPTION = AERATION_SYSTEM_DESCRIPTION, 
        ANNL_METHANE_EMISSIONS_EQ_TT6 = ANNL_METHANE_EMISSIONS_EQ_TT6, NUMBER_OF_WASTE_STREAMS = NUMBER_OF_WASTE_STREAMS, 
        FRACTION_METHANE_IN_LF_GAS = FRACTION_METHANE_IN_LF_GAS, FRCT_METHANE_LF_GAS_DTRM_IND = FRCT_METHANE_LF_GAS_DTRM_IND, 
        STARTINGYEARFORACCEPTINGWASTE = STARTINGYEARFORACCEPTINGWASTE, DOESFACKNOWWHENLANDFILLOPENED = DOESFACKNOWWHENLANDFILLOPENED, 
        ISWASTEQUANTITYDATAAVAILIND = ISWASTEQUANTITYDATAAVAILIND, LANDFILLCAPACITY = LANDFILLCAPACITY, 
        LANDFILLFIRSTRECEIVEDWASTE = LANDFILLFIRSTRECEIVEDWASTE, PRIORYRWASTEDISPDATAFIRSTAVAIL = PRIORYRWASTEDISPDATAFIRSTAVAIL, 
        YEARLASTRECEIVEDWASTE = YEARLASTRECEIVEDWASTE, ANNUALMODELEDCH4GENTT1 = ANNUALMODELEDCH4GENTT1, 
        ANNUAL_VOL_LANDFILL_GAS_FLOW = ANNUAL_VOL_LANDFILL_GAS_FLOW, ANNUAL_AVERAGE_METHANE_CONCEN = ANNUAL_AVERAGE_METHANE_CONCEN, 
        ON_SITE_DESTRUCTION_INDICATOR = ON_SITE_DESTRUCTION_INDICATOR, GAS_COLL_SYSTEM_MANUFACTURER = GAS_COLL_SYSTEM_MANUFACTURER, 
        GAS_COLL_SYSTEM_CAPACITY = GAS_COLL_SYSTEM_CAPACITY, NUMBER_OF_WELLS = NUMBER_OF_WELLS, 
        MEAS_METHANE_GEN_EQ_HH7 = MEAS_METHANE_GEN_EQ_HH7, BASIS_FOR_INPUT_METH_GEN_VALUE = BASIS_FOR_INPUT_METH_GEN_VALUE, 
        METHANE_EMISSION_EQ_HH6 = METHANE_EMISSION_EQ_HH6, METHANE_EMISSION_EQ_HH8 = METHANE_EMISSION_EQ_HH8, 
        GAS_COLL_SYSTEM_ANN_OPER_HRS = GAS_COLL_SYSTEM_ANN_OPER_HRS, ANNUAL_QTY_RECOV_METHANE_HH4 = ANNUAL_QTY_RECOV_METHANE_HH4, 
        EST_GAS_COLLECTION_EFFICIENCY = EST_GAS_COLLECTION_EFFICIENCY, IS_LFG_FLOW_WET_BASIS_INDICATR = IS_LFG_FLOW_WET_BASIS_INDICATR, 
        IS_CH4_CONC_WET_BASIS_INDICATR = IS_CH4_CONC_WET_BASIS_INDICATR, IS_PRESSURE_INCORP_INDICATOR = IS_PRESSURE_INCORP_INDICATOR, 
        IS_TEMPERATURE_INCORP_INDICATR = IS_TEMPERATURE_INCORP_INDICATR, MODELED_METHANE_GEN_EQ_HH5 = MODELED_METHANE_GEN_EQ_HH5, 
        BACKUP_DEVICE_ANNUAL_OP_HOURS = BACKUP_DEVICE_ANNUAL_OP_HOURS, DESTRUCTION_EFFICIENCY_PERCENT = DESTRUCTION_EFFICIENCY_PERCENT, 
        BACKUP_DESTRUCTION_DEVICE = BACKUP_DESTRUCTION_DEVICE, PRIMARY_DEVICE_ANNUAL_OP_HOURS = PRIMARY_DEVICE_ANNUAL_OP_HOURS, 
        ANN_AVG_METHANE_CONC_MONTHS = ANN_AVG_METHANE_CONC_MONTHS, ANN_AVG_METHANE_CONC_DAYS = ANN_AVG_METHANE_CONC_DAYS, 
        ANN_VOL_LFGFLOW_DAYS = ANN_VOL_LFGFLOW_DAYS, METHANE_OXIDATION_FRACTION_HH6 = METHANE_OXIDATION_FRACTION_HH6, 
        METHANE_OXIDATION_FRACTION_HH7 = METHANE_OXIDATION_FRACTION_HH7, METHANE_OXIDATION_FRACTION_HH8 = METHANE_OXIDATION_FRACTION_HH8, 
        METHANE_OXIDATION_FRACTION_TT6 = METHANE_OXIDATION_FRACTION_TT6, NGMETH_OXIDATION_FRACTION_TT6 = NGMETH_OXIDATION_FRACTION_TT6, 
        CUMULATIVE_WASTE_QUANTITY = CUMULATIVE_WASTE_QUANTITY, DOES_FAC_KNW_WHN_LANDFILL_OPEN = DOES_FAC_KNW_WHN_LANDFILL_OPEN, 
        IS_WASTE_IN_PLACE_QUAN_KNW_IND = IS_WASTE_IN_PLACE_QUAN_KNW_IND, LANDFILL_DESIGN_CAPACITY = LANDFILL_DESIGN_CAPACITY, 
        LANDFILL_RECVD_WASTE_YEAR_LAST = LANDFILL_RECVD_WASTE_YEAR_LAST, LANDFILL_YEAR_OPEN = LANDFILL_YEAR_OPEN, 
        QUANTITY_AVAILABLE_YEARS = QUANTITY_AVAILABLE_YEARS, WASTE_IN_PLACE_QUANTITY = WASTE_IN_PLACE_QUANTITY)
    ret <- envir_get(tt_landfill_details, args)
    
    ret
} 
