#' Retrieve w enh oil rec inj pump bd data from ghg database
#' 
#' @param FACILITY_ID e.g. '1000355'. See Details.
#' @param REPORTING_YEAR e.g. '2011'. See Details.
#' @param DOES_FAC_EOR_INJ_PUMP_BLOWDOWN e.g. 'NO'. See Details.
#' @param EOR_INJ_PUMP_BD_GHG_EMM_CO2E e.g. '0'. See Details.
#' @param EOR_INJ_PUMP_BD_N2O_EMM_CO2E e.g. 'NA'. See Details.
#' @param EOR_INJ_PUMP_BD_CH4_EMM_CO2E e.g. 'NA'. See Details.
#' @param EOR_INJ_PUMP_BD_TOTAL_CO2_EMM e.g. '0'. See Details.
#' @param INDUSTRY_SEGMENT e.g. 'ONSHORE PETROLEUM AND NATURAL GAS PRODUCTION [98.230(A)(2)]'. See Details.
#' @param SUB_IND_ENH_OIL_REC_INJ_PUM_BD e.g. 'NA'. See Details.
#' @param FACILITY_NAME e.g. '#540 BONANZA CREEK ENERGY - DENVER BASIN'. See Details.
#' @param BAM_IND_ENH_OIL_REC_INJ_PUM_BD e.g. 'NA'. See Details.
#' @param BAM_DES_ENH_OIL_REC_INJ_PUM_BD e.g. 'NA'. See Details.
#' @export

ghg_w_enh_oil_rec_inj_pump_bd <- function(FACILITY_ID = NULL, REPORTING_YEAR = NULL, 
    DOES_FAC_EOR_INJ_PUMP_BLOWDOWN = NULL, EOR_INJ_PUMP_BD_GHG_EMM_CO2E = NULL, EOR_INJ_PUMP_BD_N2O_EMM_CO2E = NULL, 
    EOR_INJ_PUMP_BD_CH4_EMM_CO2E = NULL, EOR_INJ_PUMP_BD_TOTAL_CO2_EMM = NULL, INDUSTRY_SEGMENT = NULL, 
    SUB_IND_ENH_OIL_REC_INJ_PUM_BD = NULL, FACILITY_NAME = NULL, BAM_IND_ENH_OIL_REC_INJ_PUM_BD = NULL, 
    BAM_DES_ENH_OIL_REC_INJ_PUM_BD = NULL) {
    
    args <- list(FACILITY_ID = FACILITY_ID, REPORTING_YEAR = REPORTING_YEAR, DOES_FAC_EOR_INJ_PUMP_BLOWDOWN = DOES_FAC_EOR_INJ_PUMP_BLOWDOWN, 
        EOR_INJ_PUMP_BD_GHG_EMM_CO2E = EOR_INJ_PUMP_BD_GHG_EMM_CO2E, EOR_INJ_PUMP_BD_N2O_EMM_CO2E = EOR_INJ_PUMP_BD_N2O_EMM_CO2E, 
        EOR_INJ_PUMP_BD_CH4_EMM_CO2E = EOR_INJ_PUMP_BD_CH4_EMM_CO2E, EOR_INJ_PUMP_BD_TOTAL_CO2_EMM = EOR_INJ_PUMP_BD_TOTAL_CO2_EMM, 
        INDUSTRY_SEGMENT = INDUSTRY_SEGMENT, SUB_IND_ENH_OIL_REC_INJ_PUM_BD = SUB_IND_ENH_OIL_REC_INJ_PUM_BD, 
        FACILITY_NAME = FACILITY_NAME, BAM_IND_ENH_OIL_REC_INJ_PUM_BD = BAM_IND_ENH_OIL_REC_INJ_PUM_BD, 
        BAM_DES_ENH_OIL_REC_INJ_PUM_BD = BAM_DES_ENH_OIL_REC_INJ_PUM_BD)
    ret <- envir_get("w_enh_oil_rec_inj_pump_bd", args)
    
    ret
} 
