#' Retrieve hh active aeration sys detls data from ghg database
#' 
#' @param FACILITY_ID e.g. '1004073'. See Details.
#' @param REPORTING_YEAR e.g. '2011'. See Details.
#' @param FACILITY_NAME e.g. 'MARQUETTE CO-SOLID WASTE LF'. See Details.
#' @param AERATION_SYS_BLOWER_CAPACITY e.g. '3085'. See Details.
#' @param LNDFIL_FRAC_AFFECTED_AERATION e.g. '0.99'. See Details.
#' @param AERATION_SYS_BLOW_HRS_OF_OPRAT e.g. '8760'. See Details.
#' @param OTHER_MCF_FACTORS e.g. 'AERATION OCCURS BY UTILIZING INNOVATIVE TECHNOLOGY THAT IS NOT APPLICABLE TO THESE FORMS OR MODELS.'. See Details.
#' @param AERATION_SYS_ADD_DESCRIPTION e.g. 'AERATION OCCURS BY UTILIZING INNOVATIVE TECHNOLOGY THAT IS NOT APPLICABLE TO THESE FORMS OR MODELS.'. See Details.
#' @export

ghg_hh_active_aeration_sys_detls <- function(FACILITY_ID = NULL, REPORTING_YEAR = NULL, 
    FACILITY_NAME = NULL, AERATION_SYS_BLOWER_CAPACITY = NULL, LNDFIL_FRAC_AFFECTED_AERATION = NULL, 
    AERATION_SYS_BLOW_HRS_OF_OPRAT = NULL, OTHER_MCF_FACTORS = NULL, AERATION_SYS_ADD_DESCRIPTION = NULL) {
    
    args <- list(FACILITY_ID = FACILITY_ID, REPORTING_YEAR = REPORTING_YEAR, FACILITY_NAME = FACILITY_NAME, 
        AERATION_SYS_BLOWER_CAPACITY = AERATION_SYS_BLOWER_CAPACITY, LNDFIL_FRAC_AFFECTED_AERATION = LNDFIL_FRAC_AFFECTED_AERATION, 
        AERATION_SYS_BLOW_HRS_OF_OPRAT = AERATION_SYS_BLOW_HRS_OF_OPRAT, OTHER_MCF_FACTORS = OTHER_MCF_FACTORS, 
        AERATION_SYS_ADD_DESCRIPTION = AERATION_SYS_ADD_DESCRIPTION)
    ret <- envir_get(hh_active_aeration_sys_detls, args)
    
    ret
} 
