#' Retrieve y storagetank info data from ghg database
#' 
#' @param FACILITY_ID e.g. '1000025'. See Details.
#' @param REPORTING_YEAR e.g. '2012'. See Details.
#' @param CH4_VAPORCOMP_UNSTABCRUDE_MTHD e.g. 'NA'. See Details.
#' @param FACILITY_NAME e.g. 'PLACID REFINING CO LLC - PORT ALLEN REFINERY'. See Details.
#' @param CH4_MOLE_FRAC_BAS_UNSTCRD_OTHR e.g. 'NA'. See Details.
#' @param CH4_CALC_MTHD_STRGTANKS_GENL e.g. 'Equation Y-22'. See Details.
#' @param CH4_EMISSIONS_STRGTANKS_GENL e.g. '0'. See Details.
#' @param CH4_MOLE_FRAC_BAS_UNSTCRD e.g. 'NA'. See Details.
#' @param CH4_CALC_MTHD_UNSTABILIZEDCRD e.g. 'NA'. See Details.
#' @param CH4_EMISS_STRGTANKS_UNSTCRD e.g. 'NA'. See Details.
#' @param CH4_VPRCOMP_UNSTABILIZEDCRUDE e.g. 'NA'. See Details.
#' @param CH4_VPRCOMP_UNSTCRD_NUM_SUB e.g. 'NA'. See Details.
#' @param CH4_GASGENRATE_UNSTCRUDE e.g. 'NA'. See Details.
#' @param CH4_GASGENRATE_UNSTCRD_NUM_SUB e.g. 'NA'. See Details.
#' @param CH4_GASGENRATE_UNSTCRUDE_MTHD e.g. 'NA'. See Details.
#' @param CH4_GASGENRT_UNSTCRD_MTHD_OTHR e.g. 'NA'. See Details.
#' @param CH4_VPRCOMP_UNSTCRD_MTHD_OTHR e.g. 'NA'. See Details.
#' @export

ghg_y_storagetank_info <- function(FACILITY_ID = NULL, REPORTING_YEAR = NULL, CH4_VAPORCOMP_UNSTABCRUDE_MTHD = NULL, 
    FACILITY_NAME = NULL, CH4_MOLE_FRAC_BAS_UNSTCRD_OTHR = NULL, CH4_CALC_MTHD_STRGTANKS_GENL = NULL, 
    CH4_EMISSIONS_STRGTANKS_GENL = NULL, CH4_MOLE_FRAC_BAS_UNSTCRD = NULL, CH4_CALC_MTHD_UNSTABILIZEDCRD = NULL, 
    CH4_EMISS_STRGTANKS_UNSTCRD = NULL, CH4_VPRCOMP_UNSTABILIZEDCRUDE = NULL, CH4_VPRCOMP_UNSTCRD_NUM_SUB = NULL, 
    CH4_GASGENRATE_UNSTCRUDE = NULL, CH4_GASGENRATE_UNSTCRD_NUM_SUB = NULL, CH4_GASGENRATE_UNSTCRUDE_MTHD = NULL, 
    CH4_GASGENRT_UNSTCRD_MTHD_OTHR = NULL, CH4_VPRCOMP_UNSTCRD_MTHD_OTHR = NULL) {
    
    args <- list(FACILITY_ID = FACILITY_ID, REPORTING_YEAR = REPORTING_YEAR, CH4_VAPORCOMP_UNSTABCRUDE_MTHD = CH4_VAPORCOMP_UNSTABCRUDE_MTHD, 
        FACILITY_NAME = FACILITY_NAME, CH4_MOLE_FRAC_BAS_UNSTCRD_OTHR = CH4_MOLE_FRAC_BAS_UNSTCRD_OTHR, 
        CH4_CALC_MTHD_STRGTANKS_GENL = CH4_CALC_MTHD_STRGTANKS_GENL, CH4_EMISSIONS_STRGTANKS_GENL = CH4_EMISSIONS_STRGTANKS_GENL, 
        CH4_MOLE_FRAC_BAS_UNSTCRD = CH4_MOLE_FRAC_BAS_UNSTCRD, CH4_CALC_MTHD_UNSTABILIZEDCRD = CH4_CALC_MTHD_UNSTABILIZEDCRD, 
        CH4_EMISS_STRGTANKS_UNSTCRD = CH4_EMISS_STRGTANKS_UNSTCRD, CH4_VPRCOMP_UNSTABILIZEDCRUDE = CH4_VPRCOMP_UNSTABILIZEDCRUDE, 
        CH4_VPRCOMP_UNSTCRD_NUM_SUB = CH4_VPRCOMP_UNSTCRD_NUM_SUB, CH4_GASGENRATE_UNSTCRUDE = CH4_GASGENRATE_UNSTCRUDE, 
        CH4_GASGENRATE_UNSTCRD_NUM_SUB = CH4_GASGENRATE_UNSTCRD_NUM_SUB, CH4_GASGENRATE_UNSTCRUDE_MTHD = CH4_GASGENRATE_UNSTCRUDE_MTHD, 
        CH4_GASGENRT_UNSTCRD_MTHD_OTHR = CH4_GASGENRT_UNSTCRD_MTHD_OTHR, CH4_VPRCOMP_UNSTCRD_MTHD_OTHR = CH4_VPRCOMP_UNSTCRD_MTHD_OTHR)
    ret <- envir_get(y_storagetank_info, args)
    
    ret
} 
