#' Retrieve w local dist companies details data from ghg database
#' 
#' @param FACILITY_ID e.g. '1000011'. See Details.
#' @param REPORTING_YEAR e.g. '2012'. See Details.
#' @param BAMM_DESC_LOCAL_DIST_CMPNY e.g. 'NOT AVAILABLE'. See Details.
#' @param BAMM_IND_LOCAL_DIST_CMPNY e.g. 'NO'. See Details.
#' @param ABOVE_GRADE_TRANSFER_STATIONS e.g. '4'. See Details.
#' @param YEARS_TRANSFER_STATIONS_MONIT e.g. '2'. See Details.
#' @param STATIONS_MONIT_IN_CAL_YR e.g. '151'. See Details.
#' @param BELOW_GRADE_TRANSFER_STATIONS e.g. '7'. See Details.
#' @param ABOVE_GRADE_METERING_STATIONS e.g. '155'. See Details.
#' @param BELOW_GRADE_METERING_STATIONS e.g. '0'. See Details.
#' @param ANL_ABV_GRD_TRSFER_STN_CO2_EMM e.g. '0'. See Details.
#' @param ANL_ABV_GRD_TR_STN_CH4_EMMCO2E e.g. '46.5'. See Details.
#' @param ANL_BEL_GRDE_TRSFR_STN_CO2_EMM e.g. '0'. See Details.
#' @param ANL_BEL_GRD_TR_STN_CH4_EM_CO2E e.g. '0'. See Details.
#' @param ANL_ABV_GRDE_MTR_STN_CO2_EMM e.g. '0'. See Details.
#' @param ANL_BEL_GRDE_MTR_STNS_CO2_EMM e.g. '0'. See Details.
#' @param ANL_BEL_GRD_MT_STN_CH4_EMMCO2E e.g. '0'. See Details.
#' @param ANNUAL_DIST_MAINS_CO2_EMM e.g. '0'. See Details.
#' @param ANNUAL_DIST_MAINS_CH4_EMM_CO2E e.g. '18236'. See Details.
#' @param ANNUAL_DIST_SERVICES_CO2_EMM e.g. '0'. See Details.
#' @param ANL_DIST_SERVICES_CH4_EMM_CO2E e.g. '10936'. See Details.
#' @param FACILITY_NAME e.g. 'CENTRAL HUDSON GAS AND ELECTRIC CORPORATION'. See Details.
#' @param INDUSTRY_SEGMENT e.g. 'NATURAL GAS DISTRIBUTION [98.230(A)(8)]'. See Details.
#' @param LOCAL_DIST_CMPNY_CO2_EMISSIONS e.g. '0'. See Details.
#' @param LOCAL_DIST_CMPNY_CH4_EMISSIONS e.g. '29220.8'. See Details.
#' @param LOCAL_DIST_CMPNY_GHG_EMISSIONS e.g. '29220.8'. See Details.
#' @param SUB_INDICATOR_LOCAL_DIST_CMPNY e.g. 'NO'. See Details.
#' @param LOCAL_DIST_CMPNY_N2O_EMISSIONS e.g. 'NA'. See Details.
#' @param ANNUAL_CH4_ABV_GRD_MTRNG_STAT e.g. '48.8'. See Details.
#' @param MILES_OF_UNPR_STEEL_DIST_MAINS e.g. '156'. See Details.
#' @param PR_STEEL_DIST_SERVICES e.g. '7708'. See Details.
#' @param COPPER_DIST_SERVICES e.g. '78'. See Details.
#' @param MILES_OF_CAST_IRON_DIST_MAINS e.g. '88'. See Details.
#' @param MILES_OF_PLSTIC_DIST_MAINS e.g. '607'. See Details.
#' @param MILES_OF_PROT_STEEL_DIST_MAINS e.g. '342'. See Details.
#' @param MTR_REGULATOR_LEAK_FACTOR e.g. '0.05'. See Details.
#' @param PLASTIC_DISTRIBUTION_SERVICES e.g. '33750'. See Details.
#' @param UNPRSTEELDISTSERVICES e.g. '15467'. See Details.
#' @export

ghg_w_local_dist_companies_details <- function(FACILITY_ID = NULL, REPORTING_YEAR = NULL, 
    BAMM_DESC_LOCAL_DIST_CMPNY = NULL, BAMM_IND_LOCAL_DIST_CMPNY = NULL, ABOVE_GRADE_TRANSFER_STATIONS = NULL, 
    YEARS_TRANSFER_STATIONS_MONIT = NULL, STATIONS_MONIT_IN_CAL_YR = NULL, BELOW_GRADE_TRANSFER_STATIONS = NULL, 
    ABOVE_GRADE_METERING_STATIONS = NULL, BELOW_GRADE_METERING_STATIONS = NULL, ANL_ABV_GRD_TRSFER_STN_CO2_EMM = NULL, 
    ANL_ABV_GRD_TR_STN_CH4_EMMCO2E = NULL, ANL_BEL_GRDE_TRSFR_STN_CO2_EMM = NULL, 
    ANL_BEL_GRD_TR_STN_CH4_EM_CO2E = NULL, ANL_ABV_GRDE_MTR_STN_CO2_EMM = NULL, ANL_BEL_GRDE_MTR_STNS_CO2_EMM = NULL, 
    ANL_BEL_GRD_MT_STN_CH4_EMMCO2E = NULL, ANNUAL_DIST_MAINS_CO2_EMM = NULL, ANNUAL_DIST_MAINS_CH4_EMM_CO2E = NULL, 
    ANNUAL_DIST_SERVICES_CO2_EMM = NULL, ANL_DIST_SERVICES_CH4_EMM_CO2E = NULL, FACILITY_NAME = NULL, 
    INDUSTRY_SEGMENT = NULL, LOCAL_DIST_CMPNY_CO2_EMISSIONS = NULL, LOCAL_DIST_CMPNY_CH4_EMISSIONS = NULL, 
    LOCAL_DIST_CMPNY_GHG_EMISSIONS = NULL, SUB_INDICATOR_LOCAL_DIST_CMPNY = NULL, 
    LOCAL_DIST_CMPNY_N2O_EMISSIONS = NULL, ANNUAL_CH4_ABV_GRD_MTRNG_STAT = NULL, 
    MILES_OF_UNPR_STEEL_DIST_MAINS = NULL, PR_STEEL_DIST_SERVICES = NULL, COPPER_DIST_SERVICES = NULL, 
    MILES_OF_CAST_IRON_DIST_MAINS = NULL, MILES_OF_PLSTIC_DIST_MAINS = NULL, MILES_OF_PROT_STEEL_DIST_MAINS = NULL, 
    MTR_REGULATOR_LEAK_FACTOR = NULL, PLASTIC_DISTRIBUTION_SERVICES = NULL, UNPRSTEELDISTSERVICES = NULL) {
    
    args <- list(FACILITY_ID = FACILITY_ID, REPORTING_YEAR = REPORTING_YEAR, BAMM_DESC_LOCAL_DIST_CMPNY = BAMM_DESC_LOCAL_DIST_CMPNY, 
        BAMM_IND_LOCAL_DIST_CMPNY = BAMM_IND_LOCAL_DIST_CMPNY, ABOVE_GRADE_TRANSFER_STATIONS = ABOVE_GRADE_TRANSFER_STATIONS, 
        YEARS_TRANSFER_STATIONS_MONIT = YEARS_TRANSFER_STATIONS_MONIT, STATIONS_MONIT_IN_CAL_YR = STATIONS_MONIT_IN_CAL_YR, 
        BELOW_GRADE_TRANSFER_STATIONS = BELOW_GRADE_TRANSFER_STATIONS, ABOVE_GRADE_METERING_STATIONS = ABOVE_GRADE_METERING_STATIONS, 
        BELOW_GRADE_METERING_STATIONS = BELOW_GRADE_METERING_STATIONS, ANL_ABV_GRD_TRSFER_STN_CO2_EMM = ANL_ABV_GRD_TRSFER_STN_CO2_EMM, 
        ANL_ABV_GRD_TR_STN_CH4_EMMCO2E = ANL_ABV_GRD_TR_STN_CH4_EMMCO2E, ANL_BEL_GRDE_TRSFR_STN_CO2_EMM = ANL_BEL_GRDE_TRSFR_STN_CO2_EMM, 
        ANL_BEL_GRD_TR_STN_CH4_EM_CO2E = ANL_BEL_GRD_TR_STN_CH4_EM_CO2E, ANL_ABV_GRDE_MTR_STN_CO2_EMM = ANL_ABV_GRDE_MTR_STN_CO2_EMM, 
        ANL_BEL_GRDE_MTR_STNS_CO2_EMM = ANL_BEL_GRDE_MTR_STNS_CO2_EMM, ANL_BEL_GRD_MT_STN_CH4_EMMCO2E = ANL_BEL_GRD_MT_STN_CH4_EMMCO2E, 
        ANNUAL_DIST_MAINS_CO2_EMM = ANNUAL_DIST_MAINS_CO2_EMM, ANNUAL_DIST_MAINS_CH4_EMM_CO2E = ANNUAL_DIST_MAINS_CH4_EMM_CO2E, 
        ANNUAL_DIST_SERVICES_CO2_EMM = ANNUAL_DIST_SERVICES_CO2_EMM, ANL_DIST_SERVICES_CH4_EMM_CO2E = ANL_DIST_SERVICES_CH4_EMM_CO2E, 
        FACILITY_NAME = FACILITY_NAME, INDUSTRY_SEGMENT = INDUSTRY_SEGMENT, LOCAL_DIST_CMPNY_CO2_EMISSIONS = LOCAL_DIST_CMPNY_CO2_EMISSIONS, 
        LOCAL_DIST_CMPNY_CH4_EMISSIONS = LOCAL_DIST_CMPNY_CH4_EMISSIONS, LOCAL_DIST_CMPNY_GHG_EMISSIONS = LOCAL_DIST_CMPNY_GHG_EMISSIONS, 
        SUB_INDICATOR_LOCAL_DIST_CMPNY = SUB_INDICATOR_LOCAL_DIST_CMPNY, LOCAL_DIST_CMPNY_N2O_EMISSIONS = LOCAL_DIST_CMPNY_N2O_EMISSIONS, 
        ANNUAL_CH4_ABV_GRD_MTRNG_STAT = ANNUAL_CH4_ABV_GRD_MTRNG_STAT, MILES_OF_UNPR_STEEL_DIST_MAINS = MILES_OF_UNPR_STEEL_DIST_MAINS, 
        PR_STEEL_DIST_SERVICES = PR_STEEL_DIST_SERVICES, COPPER_DIST_SERVICES = COPPER_DIST_SERVICES, 
        MILES_OF_CAST_IRON_DIST_MAINS = MILES_OF_CAST_IRON_DIST_MAINS, MILES_OF_PLSTIC_DIST_MAINS = MILES_OF_PLSTIC_DIST_MAINS, 
        MILES_OF_PROT_STEEL_DIST_MAINS = MILES_OF_PROT_STEEL_DIST_MAINS, MTR_REGULATOR_LEAK_FACTOR = MTR_REGULATOR_LEAK_FACTOR, 
        PLASTIC_DISTRIBUTION_SERVICES = PLASTIC_DISTRIBUTION_SERVICES, UNPRSTEELDISTSERVICES = UNPRSTEELDISTSERVICES)
    ret <- envir_get(w_local_dist_companies_details, args)
    
    ret
} 
