#' Retrieve w well completion hydraulic data from ghg database
#' 
#' @param FACILITY_ID e.g. '1000355'. See Details.
#' @param REPORTING_YEAR e.g. '2012'. See Details.
#' @param FACILITY_NAME e.g. '#540 BONANZA CREEK ENERGY - DENVER BASIN'. See Details.
#' @param INDUSTRY_SEGMENT e.g. 'ONSHORE PETROLEUM AND NATURAL GAS PRODUCTION [98.230(A)(2)]'. See Details.
#' @param SUB_BASIN_IDENTIFIER e.g. '540 - WELD, CO (123) - OTHER TIGHT RESERVOIR ROCK'. See Details.
#' @param WORKOVERS_VENTING_CH4_EMM_CO2E e.g. '0'. See Details.
#' @param WORKOVERS_FLARING_CO2_EMM e.g. '0'. See Details.
#' @param WORKOVERS_FLARING_CH4_EMM_CO2E e.g. '0'. See Details.
#' @param WORKOVERS_FLARING_N2O_EMM_CO2E e.g. '0'. See Details.
#' @param SEPARATING_COMPLETIONS e.g. '23'. See Details.
#' @param SEPARATING_WORKOVERS e.g. '0'. See Details.
#' @param WELL_TYPE e.g. 'HORIZONTAL'. See Details.
#' @param COMPLETION_EQUATION e.g. 'EQUATION W-10B'. See Details.
#' @param WORKOVER_EQUATION e.g. 'EQUATION W-10B'. See Details.
#' @param TOTAL_COMPLETIONS e.g. '25'. See Details.
#' @param TOTAL_FLARE_GAS_WORKOVERS e.g. '0'. See Details.
#' @param TOTAL_VENT_GAS_WORKOVERS e.g. '0'. See Details.
#' @param COMPLETIONS_VENTING_CO2_EMM e.g. '0'. See Details.
#' @param COMPLETIONS_VENT_CH4_EMM_CO2E e.g. '0'. See Details.
#' @param COMPLETIONS_FLARING_CO2_EMM e.g. '16921'. See Details.
#' @param COMPLETIONS_FLRNG_CH4_EMM_CO2E e.g. '1340.5'. See Details.
#' @param COMPLETIONS_FLRNG_N2O_EMM_CO2E e.g. '8.9'. See Details.
#' @param WORKOVERS_VENTING_CO2_EMM e.g. '0'. See Details.
#' @param WORKOVER_BACKFLOW_FLOW_RATE e.g. '0'. See Details.
#' @param WORKOVERS_NMBR_OF_BKFLW_DAYS e.g. '0'. See Details.
#' @param COMPLETION_GAS_RECVRD_TO_SALES e.g. '145731000'. See Details.
#' @param COMPLETIONS_NMBR_BKFLW_DAYS e.g. '0'. See Details.
#' @param TWO_YEAR_DELAY_INDICATOR e.g. 'No'. See Details.
#' @param WORKOVER_GAS_RECVRD_TO_SALES e.g. '0'. See Details.
#' @param API_WELL_NUMBERS e.g. 'NA'. See Details.
#' @param COMPLETION_BACKFLOW_FLOW_RATE e.g. '0'. See Details.
#' @export

ghg_w_well_completion_hydraulic <- function(FACILITY_ID = NULL, REPORTING_YEAR = NULL, 
    FACILITY_NAME = NULL, INDUSTRY_SEGMENT = NULL, SUB_BASIN_IDENTIFIER = NULL, WORKOVERS_VENTING_CH4_EMM_CO2E = NULL, 
    WORKOVERS_FLARING_CO2_EMM = NULL, WORKOVERS_FLARING_CH4_EMM_CO2E = NULL, WORKOVERS_FLARING_N2O_EMM_CO2E = NULL, 
    SEPARATING_COMPLETIONS = NULL, SEPARATING_WORKOVERS = NULL, WELL_TYPE = NULL, 
    COMPLETION_EQUATION = NULL, WORKOVER_EQUATION = NULL, TOTAL_COMPLETIONS = NULL, 
    TOTAL_FLARE_GAS_WORKOVERS = NULL, TOTAL_VENT_GAS_WORKOVERS = NULL, COMPLETIONS_VENTING_CO2_EMM = NULL, 
    COMPLETIONS_VENT_CH4_EMM_CO2E = NULL, COMPLETIONS_FLARING_CO2_EMM = NULL, COMPLETIONS_FLRNG_CH4_EMM_CO2E = NULL, 
    COMPLETIONS_FLRNG_N2O_EMM_CO2E = NULL, WORKOVERS_VENTING_CO2_EMM = NULL, WORKOVER_BACKFLOW_FLOW_RATE = NULL, 
    WORKOVERS_NMBR_OF_BKFLW_DAYS = NULL, COMPLETION_GAS_RECVRD_TO_SALES = NULL, COMPLETIONS_NMBR_BKFLW_DAYS = NULL, 
    TWO_YEAR_DELAY_INDICATOR = NULL, WORKOVER_GAS_RECVRD_TO_SALES = NULL, API_WELL_NUMBERS = NULL, 
    COMPLETION_BACKFLOW_FLOW_RATE = NULL) {
    
    args <- list(FACILITY_ID = FACILITY_ID, REPORTING_YEAR = REPORTING_YEAR, FACILITY_NAME = FACILITY_NAME, 
        INDUSTRY_SEGMENT = INDUSTRY_SEGMENT, SUB_BASIN_IDENTIFIER = SUB_BASIN_IDENTIFIER, 
        WORKOVERS_VENTING_CH4_EMM_CO2E = WORKOVERS_VENTING_CH4_EMM_CO2E, WORKOVERS_FLARING_CO2_EMM = WORKOVERS_FLARING_CO2_EMM, 
        WORKOVERS_FLARING_CH4_EMM_CO2E = WORKOVERS_FLARING_CH4_EMM_CO2E, WORKOVERS_FLARING_N2O_EMM_CO2E = WORKOVERS_FLARING_N2O_EMM_CO2E, 
        SEPARATING_COMPLETIONS = SEPARATING_COMPLETIONS, SEPARATING_WORKOVERS = SEPARATING_WORKOVERS, 
        WELL_TYPE = WELL_TYPE, COMPLETION_EQUATION = COMPLETION_EQUATION, WORKOVER_EQUATION = WORKOVER_EQUATION, 
        TOTAL_COMPLETIONS = TOTAL_COMPLETIONS, TOTAL_FLARE_GAS_WORKOVERS = TOTAL_FLARE_GAS_WORKOVERS, 
        TOTAL_VENT_GAS_WORKOVERS = TOTAL_VENT_GAS_WORKOVERS, COMPLETIONS_VENTING_CO2_EMM = COMPLETIONS_VENTING_CO2_EMM, 
        COMPLETIONS_VENT_CH4_EMM_CO2E = COMPLETIONS_VENT_CH4_EMM_CO2E, COMPLETIONS_FLARING_CO2_EMM = COMPLETIONS_FLARING_CO2_EMM, 
        COMPLETIONS_FLRNG_CH4_EMM_CO2E = COMPLETIONS_FLRNG_CH4_EMM_CO2E, COMPLETIONS_FLRNG_N2O_EMM_CO2E = COMPLETIONS_FLRNG_N2O_EMM_CO2E, 
        WORKOVERS_VENTING_CO2_EMM = WORKOVERS_VENTING_CO2_EMM, WORKOVER_BACKFLOW_FLOW_RATE = WORKOVER_BACKFLOW_FLOW_RATE, 
        WORKOVERS_NMBR_OF_BKFLW_DAYS = WORKOVERS_NMBR_OF_BKFLW_DAYS, COMPLETION_GAS_RECVRD_TO_SALES = COMPLETION_GAS_RECVRD_TO_SALES, 
        COMPLETIONS_NMBR_BKFLW_DAYS = COMPLETIONS_NMBR_BKFLW_DAYS, TWO_YEAR_DELAY_INDICATOR = TWO_YEAR_DELAY_INDICATOR, 
        WORKOVER_GAS_RECVRD_TO_SALES = WORKOVER_GAS_RECVRD_TO_SALES, API_WELL_NUMBERS = API_WELL_NUMBERS, 
        COMPLETION_BACKFLOW_FLOW_RATE = COMPLETION_BACKFLOW_FLOW_RATE)
    ret <- envir_get(w_well_completion_hydraulic, args)
    
    ret
} 
