#' Retrieve w sub basin data from ghg database
#' 
#' @param FACILITY_ID e.g. '1000355'. See Details.
#' @param REPORTING_YEAR e.g. '2011'. See Details.
#' @param INDUSTRY_SEGMENT e.g. 'ONSHORE PETROLEUM AND NATURAL GAS PRODUCTION [98.230(A)(2)]'. See Details.
#' @param FACILITY_NAME e.g. '#540 BONANZA CREEK ENERGY - DENVER BASIN'. See Details.
#' @param SUB_BASIN_IDENTIFIER e.g. '540 - WELD, CO (123) - OTHER TIGHT RESERVOIR ROCK'. See Details.
#' @param AVERAGE_PRESSURE e.g. 'NA'. See Details.
#' @param GAS_TO_OIL_RATIO e.g. 'NA'. See Details.
#' @param API_GRAVITY e.g. 'NA'. See Details.
#' @param SUB_BASIN_FORMATION_TYPE e.g. 'OTHER TIGHT RESERVOIR ROCK'. See Details.
#' @param SUB_BASIN_COUNTY e.g. 'WELD, CO (123)'. See Details.
#' @param SELECTED_BASIN e.g. '540 - DENVER BASIN'. See Details.
#' @export

ghg_w_sub_basin <- function(FACILITY_ID = NULL, REPORTING_YEAR = NULL, INDUSTRY_SEGMENT = NULL, 
    FACILITY_NAME = NULL, SUB_BASIN_IDENTIFIER = NULL, AVERAGE_PRESSURE = NULL, GAS_TO_OIL_RATIO = NULL, 
    API_GRAVITY = NULL, SUB_BASIN_FORMATION_TYPE = NULL, SUB_BASIN_COUNTY = NULL, 
    SELECTED_BASIN = NULL) {
    
    args <- list(FACILITY_ID = FACILITY_ID, REPORTING_YEAR = REPORTING_YEAR, INDUSTRY_SEGMENT = INDUSTRY_SEGMENT, 
        FACILITY_NAME = FACILITY_NAME, SUB_BASIN_IDENTIFIER = SUB_BASIN_IDENTIFIER, 
        AVERAGE_PRESSURE = AVERAGE_PRESSURE, GAS_TO_OIL_RATIO = GAS_TO_OIL_RATIO, 
        API_GRAVITY = API_GRAVITY, SUB_BASIN_FORMATION_TYPE = SUB_BASIN_FORMATION_TYPE, 
        SUB_BASIN_COUNTY = SUB_BASIN_COUNTY, SELECTED_BASIN = SELECTED_BASIN)
    ret <- envir_get(w_sub_basin, args)
    
    ret
} 
