#' Retrieve w blowdown vent stacks data from ghg database
#' 
#' @param FACILITY_ID e.g. '1000064'. See Details.
#' @param REPORTING_YEAR e.g. '2013'. See Details.
#' @param TOT_BLOWDOWN_CH4_CO2E e.g. 'NA'. See Details.
#' @param TOT_BLOWDOWN_CO2_EMISSIONS e.g. 'NA'. See Details.
#' @param TOTAL_NUMBER_OF_BLOWDOWNS e.g. 'NA'. See Details.
#' @param SUB_INDICATOR_BLWDWN_VENT_STK e.g. 'NA'. See Details.
#' @param BAMM_DESC_BLWDWN_VENT_STACKS e.g. 'NA'. See Details.
#' @param BAMM_INDICATOR_BLWDWN_VENT_STK e.g. 'NO'. See Details.
#' @param DOES_FAC_BLOWDOWN_VENT_STACKS e.g. 'NO'. See Details.
#' @param BLDN_VENT_ST_TOT_GHG_EMM_CO2E e.g. '0'. See Details.
#' @param BLDN_VENT_ST_TOT_N2O_EMM_CO2E e.g. 'NA'. See Details.
#' @param BLDN_VENT_ST_TOT_CH4_EMM_CO2E e.g. '0'. See Details.
#' @param FACILITY_NAME e.g. 'LONE STAR GAS LIQUIDS'. See Details.
#' @param INDUSTRY_SEGMENT e.g. 'ONSHORE NATURAL GAS PROCESSING [98.230(A)(3)]'. See Details.
#' @param BLWDWN_VENT_ST_TOTAL_CO2_EMM e.g. '0'. See Details.
#' @export

ghg_w_blowdown_vent_stacks <- function(FACILITY_ID = NULL, REPORTING_YEAR = NULL, 
    TOT_BLOWDOWN_CH4_CO2E = NULL, TOT_BLOWDOWN_CO2_EMISSIONS = NULL, TOTAL_NUMBER_OF_BLOWDOWNS = NULL, 
    SUB_INDICATOR_BLWDWN_VENT_STK = NULL, BAMM_DESC_BLWDWN_VENT_STACKS = NULL, BAMM_INDICATOR_BLWDWN_VENT_STK = NULL, 
    DOES_FAC_BLOWDOWN_VENT_STACKS = NULL, BLDN_VENT_ST_TOT_GHG_EMM_CO2E = NULL, BLDN_VENT_ST_TOT_N2O_EMM_CO2E = NULL, 
    BLDN_VENT_ST_TOT_CH4_EMM_CO2E = NULL, FACILITY_NAME = NULL, INDUSTRY_SEGMENT = NULL, 
    BLWDWN_VENT_ST_TOTAL_CO2_EMM = NULL) {
    
    args <- list(FACILITY_ID = FACILITY_ID, REPORTING_YEAR = REPORTING_YEAR, TOT_BLOWDOWN_CH4_CO2E = TOT_BLOWDOWN_CH4_CO2E, 
        TOT_BLOWDOWN_CO2_EMISSIONS = TOT_BLOWDOWN_CO2_EMISSIONS, TOTAL_NUMBER_OF_BLOWDOWNS = TOTAL_NUMBER_OF_BLOWDOWNS, 
        SUB_INDICATOR_BLWDWN_VENT_STK = SUB_INDICATOR_BLWDWN_VENT_STK, BAMM_DESC_BLWDWN_VENT_STACKS = BAMM_DESC_BLWDWN_VENT_STACKS, 
        BAMM_INDICATOR_BLWDWN_VENT_STK = BAMM_INDICATOR_BLWDWN_VENT_STK, DOES_FAC_BLOWDOWN_VENT_STACKS = DOES_FAC_BLOWDOWN_VENT_STACKS, 
        BLDN_VENT_ST_TOT_GHG_EMM_CO2E = BLDN_VENT_ST_TOT_GHG_EMM_CO2E, BLDN_VENT_ST_TOT_N2O_EMM_CO2E = BLDN_VENT_ST_TOT_N2O_EMM_CO2E, 
        BLDN_VENT_ST_TOT_CH4_EMM_CO2E = BLDN_VENT_ST_TOT_CH4_EMM_CO2E, FACILITY_NAME = FACILITY_NAME, 
        INDUSTRY_SEGMENT = INDUSTRY_SEGMENT, BLWDWN_VENT_ST_TOTAL_CO2_EMM = BLWDWN_VENT_ST_TOTAL_CO2_EMM)
    ret <- envir_get("w_blowdown_vent_stacks", args)
    
    ret
} 
