#' Retrieve ii biogas rec proc data from ghg database
#' 
#' @param FACILITY_ID e.g. '1000035'. See Details.
#' @param REPORTING_YEAR e.g. '2011'. See Details.
#' @param FACILITY_NAME e.g. 'ANDERSONS MARATHON ETHANOL LLC'. See Details.
#' @param ANAEROBIC_PROCESS_ID e.g. 'Greenville Methanator System'. See Details.
#' @param IS_CH4_CONC_MONITORED_WEEKLY e.g. 'Yes'. See Details.
#' @param WEEK e.g. '1'. See Details.
#' @param IS_MISS_DATA_USED_BIOGAS_FLOW e.g. 'No'. See Details.
#' @param IS_MISS_DATA_USED_METHANE_CONC e.g. 'Yes'. See Details.
#' @param WEEK_AVG_BIOGAS_TEMPERATURE e.g. 'NA'. See Details.
#' @param IS_BIOGAS_TEMPERATURE_INCORP e.g. 'Yes'. See Details.
#' @param WEEK_AVG_BIOGAS_PRESSURE e.g. 'NA'. See Details.
#' @param IS_BIOGAS_PRESSURE_INCORP e.g. 'Yes'. See Details.
#' @param IS_MOISTURE_CONTENT_INCORP e.g. 'Yes'. See Details.
#' @param WEEK_AVG_BIOGAS_MOISTURE_CONT e.g. 'NA'. See Details.
#' @param IS_BIOGAS_FLOW_WET_DRY_BASIS e.g. 'NA'. See Details.
#' @param IS_BIOGAS_METHAN_WETDRY_BASIS e.g. 'NA'. See Details.
#' @export

ghg_ii_biogas_rec_proc <- function(FACILITY_ID = NULL, REPORTING_YEAR = NULL, FACILITY_NAME = NULL, 
    ANAEROBIC_PROCESS_ID = NULL, IS_CH4_CONC_MONITORED_WEEKLY = NULL, WEEK = NULL, 
    IS_MISS_DATA_USED_BIOGAS_FLOW = NULL, IS_MISS_DATA_USED_METHANE_CONC = NULL, 
    WEEK_AVG_BIOGAS_TEMPERATURE = NULL, IS_BIOGAS_TEMPERATURE_INCORP = NULL, WEEK_AVG_BIOGAS_PRESSURE = NULL, 
    IS_BIOGAS_PRESSURE_INCORP = NULL, IS_MOISTURE_CONTENT_INCORP = NULL, WEEK_AVG_BIOGAS_MOISTURE_CONT = NULL, 
    IS_BIOGAS_FLOW_WET_DRY_BASIS = NULL, IS_BIOGAS_METHAN_WETDRY_BASIS = NULL) {
    
    args <- list(FACILITY_ID = FACILITY_ID, REPORTING_YEAR = REPORTING_YEAR, FACILITY_NAME = FACILITY_NAME, 
        ANAEROBIC_PROCESS_ID = ANAEROBIC_PROCESS_ID, IS_CH4_CONC_MONITORED_WEEKLY = IS_CH4_CONC_MONITORED_WEEKLY, 
        WEEK = WEEK, IS_MISS_DATA_USED_BIOGAS_FLOW = IS_MISS_DATA_USED_BIOGAS_FLOW, 
        IS_MISS_DATA_USED_METHANE_CONC = IS_MISS_DATA_USED_METHANE_CONC, WEEK_AVG_BIOGAS_TEMPERATURE = WEEK_AVG_BIOGAS_TEMPERATURE, 
        IS_BIOGAS_TEMPERATURE_INCORP = IS_BIOGAS_TEMPERATURE_INCORP, WEEK_AVG_BIOGAS_PRESSURE = WEEK_AVG_BIOGAS_PRESSURE, 
        IS_BIOGAS_PRESSURE_INCORP = IS_BIOGAS_PRESSURE_INCORP, IS_MOISTURE_CONTENT_INCORP = IS_MOISTURE_CONTENT_INCORP, 
        WEEK_AVG_BIOGAS_MOISTURE_CONT = WEEK_AVG_BIOGAS_MOISTURE_CONT, IS_BIOGAS_FLOW_WET_DRY_BASIS = IS_BIOGAS_FLOW_WET_DRY_BASIS, 
        IS_BIOGAS_METHAN_WETDRY_BASIS = IS_BIOGAS_METHAN_WETDRY_BASIS)
    ret <- envir_get(ii_biogas_rec_proc, args)
    
    ret
} 
