#' Retrieve w combustion data from ghg database
#' 
#' @param FACILITY_ID e.g. '1000011'. See Details.
#' @param REPORTING_YEAR e.g. '2013'. See Details.
#' @param COMBUSTION_TOTAL_N2O_EMM_CO2E e.g. '0'. See Details.
#' @param COMBUSTION_TOTAL_CH4_EMM_CO2E e.g. '0'. See Details.
#' @param FACILITY_NAME e.g. 'CENTRAL HUDSON GAS AND ELECTRIC CORPORATION'. See Details.
#' @param COMBUSTION_TOTAL_GHG_EMM_CO2E e.g. '0'. See Details.
#' @param COMBUSTION_TOTAL_CO2_EMISSIONS e.g. '0'. See Details.
#' @param BAMMDESCRIPTION e.g. 'NA'. See Details.
#' @param INDUSTRY_SEGMENT e.g. 'NATURAL GAS DISTRIBUTION [98.230(A)(8)]'. See Details.
#' @param SUBSTITUTEDATAINDICATOR e.g. 'NO'. See Details.
#' @param DOES_FACILITY_HAVE_COMBUS_EMIS e.g. 'NO'. See Details.
#' @param BAMMINDICATOR e.g. 'NO'. See Details.
#' @export

ghg_w_combustion <- function(FACILITY_ID = NULL, REPORTING_YEAR = NULL, COMBUSTION_TOTAL_N2O_EMM_CO2E = NULL, 
    COMBUSTION_TOTAL_CH4_EMM_CO2E = NULL, FACILITY_NAME = NULL, COMBUSTION_TOTAL_GHG_EMM_CO2E = NULL, 
    COMBUSTION_TOTAL_CO2_EMISSIONS = NULL, BAMMDESCRIPTION = NULL, INDUSTRY_SEGMENT = NULL, 
    SUBSTITUTEDATAINDICATOR = NULL, DOES_FACILITY_HAVE_COMBUS_EMIS = NULL, BAMMINDICATOR = NULL) {
    
    args <- list(FACILITY_ID = FACILITY_ID, REPORTING_YEAR = REPORTING_YEAR, COMBUSTION_TOTAL_N2O_EMM_CO2E = COMBUSTION_TOTAL_N2O_EMM_CO2E, 
        COMBUSTION_TOTAL_CH4_EMM_CO2E = COMBUSTION_TOTAL_CH4_EMM_CO2E, FACILITY_NAME = FACILITY_NAME, 
        COMBUSTION_TOTAL_GHG_EMM_CO2E = COMBUSTION_TOTAL_GHG_EMM_CO2E, COMBUSTION_TOTAL_CO2_EMISSIONS = COMBUSTION_TOTAL_CO2_EMISSIONS, 
        BAMMDESCRIPTION = BAMMDESCRIPTION, INDUSTRY_SEGMENT = INDUSTRY_SEGMENT, SUBSTITUTEDATAINDICATOR = SUBSTITUTEDATAINDICATOR, 
        DOES_FACILITY_HAVE_COMBUS_EMIS = DOES_FACILITY_HAVE_COMBUS_EMIS, BAMMINDICATOR = BAMMINDICATOR)
    ret <- envir_get("w_combustion", args)
    
    ret
} 
