#' Retrieve y processvent info data from ghg database
#' 
#' @param FACILITY_ID e.g. '1000099'. See Details.
#' @param REPORTING_YEAR e.g. '2011'. See Details.
#' @param VOLUMETRIC_FLOW_IS_SUBSTITUTED e.g. 'NA'. See Details.
#' @param VOLUMETRIC_FLOW_DISCHARGED e.g. '13516583'. See Details.
#' @param VOLUMETRIC_FLOW_NUMBER_SUB e.g. 'NA'. See Details.
#' @param CH4_EMISSIONS e.g. '0.03'. See Details.
#' @param CO2_EMISSIONS e.g. '711'. See Details.
#' @param CONTROL_DEVICE_TYPE e.g. 'Other (specify)'. See Details.
#' @param N2O_EMISSIONS e.g. '0.004'. See Details.
#' @param ASSOCIATED_OPERATION e.g. 'Catalytic reforming unit - continuous regeneration'. See Details.
#' @param VOLUMETRIC_FLOW_METHOD_OTHER e.g. 'NA'. See Details.
#' @param CONTROL_DEVICE_TYPE_OTHER e.g. 'Heater firebox'. See Details.
#' @param ASSOCIATED_OPERATION_OTHER e.g. 'Catalytic reforming unit - continuous regeneration'. See Details.
#' @param UNIT_NAME e.g. 'Vent1'. See Details.
#' @param UNIT_TYPE e.g. 'Process Vent'. See Details.
#' @param CH4_MOLE_FRAC_IS_SUBSTITUTED e.g. 'NA'. See Details.
#' @param CH4_MOLE_FRACTION e.g. '1e-04'. See Details.
#' @param CH4_MOLE_FRAC_NUMBER_SUB e.g. 'NA'. See Details.
#' @param CH4_MOLE_FRACTION_METHOD e.g. 'Engineering estimates/process knowledge'. See Details.
#' @param CO2_MOLE_FRAC_IS_SUBSTITUTED e.g. 'NA'. See Details.
#' @param CO2_MOLE_FRACTION e.g. '0.9999'. See Details.
#' @param CO2_MOLE_FRAC_NUM_SUBSTITUTED e.g. 'NA'. See Details.
#' @param CO2_MOLE_FRACTION_METHOD e.g. 'Engineering estimates/process knowledge'. See Details.
#' @param N2O_MOLE_FRAC_IS_SUBSTITUTED e.g. 'NA'. See Details.
#' @param N2O_MOLE_FRACTION e.g. '1e-05'. See Details.
#' @param N2O_MOLE_FRAC_NUM_SUBSTITUTED e.g. 'NA'. See Details.
#' @param N2O_MOLE_FRACTION_METHOD e.g. 'Engineering estimates/process knowledge'. See Details.
#' @param CH4_MOLE_FRACTION_METHOD_OTHER e.g. 'NA'. See Details.
#' @param CO2_MOLE_FRACTION_METHOD_OTHER e.g. 'NA'. See Details.
#' @param N2O_MOLE_FRACTION_METHOD_OTHER e.g. 'NA'. See Details.
#' @param NUMBER_OF_VENTING_EVENTS e.g. '365'. See Details.
#' @param TOTAL_VENTING_TIME e.g. 'Hours'. See Details.
#' @param FACILITY_NAME e.g. 'Marathon Petroleum Company LP'. See Details.
#' @param VOLUMETRIC_FLOW_METHOD e.g. 'Engineering calculation'. See Details.
#' @export

ghg_y_processvent_info <- function(FACILITY_ID = NULL, REPORTING_YEAR = NULL, VOLUMETRIC_FLOW_IS_SUBSTITUTED = NULL, 
    VOLUMETRIC_FLOW_DISCHARGED = NULL, VOLUMETRIC_FLOW_NUMBER_SUB = NULL, CH4_EMISSIONS = NULL, 
    CO2_EMISSIONS = NULL, CONTROL_DEVICE_TYPE = NULL, N2O_EMISSIONS = NULL, ASSOCIATED_OPERATION = NULL, 
    VOLUMETRIC_FLOW_METHOD_OTHER = NULL, CONTROL_DEVICE_TYPE_OTHER = NULL, ASSOCIATED_OPERATION_OTHER = NULL, 
    UNIT_NAME = NULL, UNIT_TYPE = NULL, CH4_MOLE_FRAC_IS_SUBSTITUTED = NULL, CH4_MOLE_FRACTION = NULL, 
    CH4_MOLE_FRAC_NUMBER_SUB = NULL, CH4_MOLE_FRACTION_METHOD = NULL, CO2_MOLE_FRAC_IS_SUBSTITUTED = NULL, 
    CO2_MOLE_FRACTION = NULL, CO2_MOLE_FRAC_NUM_SUBSTITUTED = NULL, CO2_MOLE_FRACTION_METHOD = NULL, 
    N2O_MOLE_FRAC_IS_SUBSTITUTED = NULL, N2O_MOLE_FRACTION = NULL, N2O_MOLE_FRAC_NUM_SUBSTITUTED = NULL, 
    N2O_MOLE_FRACTION_METHOD = NULL, CH4_MOLE_FRACTION_METHOD_OTHER = NULL, CO2_MOLE_FRACTION_METHOD_OTHER = NULL, 
    N2O_MOLE_FRACTION_METHOD_OTHER = NULL, NUMBER_OF_VENTING_EVENTS = NULL, TOTAL_VENTING_TIME = NULL, 
    FACILITY_NAME = NULL, VOLUMETRIC_FLOW_METHOD = NULL) {
    
    args <- list(FACILITY_ID = FACILITY_ID, REPORTING_YEAR = REPORTING_YEAR, VOLUMETRIC_FLOW_IS_SUBSTITUTED = VOLUMETRIC_FLOW_IS_SUBSTITUTED, 
        VOLUMETRIC_FLOW_DISCHARGED = VOLUMETRIC_FLOW_DISCHARGED, VOLUMETRIC_FLOW_NUMBER_SUB = VOLUMETRIC_FLOW_NUMBER_SUB, 
        CH4_EMISSIONS = CH4_EMISSIONS, CO2_EMISSIONS = CO2_EMISSIONS, CONTROL_DEVICE_TYPE = CONTROL_DEVICE_TYPE, 
        N2O_EMISSIONS = N2O_EMISSIONS, ASSOCIATED_OPERATION = ASSOCIATED_OPERATION, 
        VOLUMETRIC_FLOW_METHOD_OTHER = VOLUMETRIC_FLOW_METHOD_OTHER, CONTROL_DEVICE_TYPE_OTHER = CONTROL_DEVICE_TYPE_OTHER, 
        ASSOCIATED_OPERATION_OTHER = ASSOCIATED_OPERATION_OTHER, UNIT_NAME = UNIT_NAME, 
        UNIT_TYPE = UNIT_TYPE, CH4_MOLE_FRAC_IS_SUBSTITUTED = CH4_MOLE_FRAC_IS_SUBSTITUTED, 
        CH4_MOLE_FRACTION = CH4_MOLE_FRACTION, CH4_MOLE_FRAC_NUMBER_SUB = CH4_MOLE_FRAC_NUMBER_SUB, 
        CH4_MOLE_FRACTION_METHOD = CH4_MOLE_FRACTION_METHOD, CO2_MOLE_FRAC_IS_SUBSTITUTED = CO2_MOLE_FRAC_IS_SUBSTITUTED, 
        CO2_MOLE_FRACTION = CO2_MOLE_FRACTION, CO2_MOLE_FRAC_NUM_SUBSTITUTED = CO2_MOLE_FRAC_NUM_SUBSTITUTED, 
        CO2_MOLE_FRACTION_METHOD = CO2_MOLE_FRACTION_METHOD, N2O_MOLE_FRAC_IS_SUBSTITUTED = N2O_MOLE_FRAC_IS_SUBSTITUTED, 
        N2O_MOLE_FRACTION = N2O_MOLE_FRACTION, N2O_MOLE_FRAC_NUM_SUBSTITUTED = N2O_MOLE_FRAC_NUM_SUBSTITUTED, 
        N2O_MOLE_FRACTION_METHOD = N2O_MOLE_FRACTION_METHOD, CH4_MOLE_FRACTION_METHOD_OTHER = CH4_MOLE_FRACTION_METHOD_OTHER, 
        CO2_MOLE_FRACTION_METHOD_OTHER = CO2_MOLE_FRACTION_METHOD_OTHER, N2O_MOLE_FRACTION_METHOD_OTHER = N2O_MOLE_FRACTION_METHOD_OTHER, 
        NUMBER_OF_VENTING_EVENTS = NUMBER_OF_VENTING_EVENTS, TOTAL_VENTING_TIME = TOTAL_VENTING_TIME, 
        FACILITY_NAME = FACILITY_NAME, VOLUMETRIC_FLOW_METHOD = VOLUMETRIC_FLOW_METHOD)
    ret <- envir_get("y_processvent_info", args)
    
    ret
} 
