#' Retrieve c fuel level information data from ghg database
#' 
#' @param FACILITY_ID e.g. '1000001'. See Details.
#' @param REPORTING_YEAR e.g. '2010'. See Details.
#' @param T3FREQUENCYOFCCDETERMINATION e.g. 'NA'. See Details.
#' @param T3OTHERFREQFCCDETERMINATION e.g. 'NA'. See Details.
#' @param T3TOTALNUMBERCCDETERMINATIONS e.g. 'NA'. See Details.
#' @param T3NUMBERVALIDCCDETERMINATIONS e.g. 'NA'. See Details.
#' @param T3FREQUENCYOFMWDETERMINATION e.g. 'NA'. See Details.
#' @param T3OTHERFREQOFMWDETERMINATION e.g. 'NA'. See Details.
#' @param T3TOTALNUMBERMWTDETERMINATIONS e.g. 'NA'. See Details.
#' @param T3NUMBERVALIDMWDETERMINATIONS e.g. 'NA'. See Details.
#' @param T3NUMOFOPTHOURSSUBFUELUSAGE e.g. 'NA'. See Details.
#' @param T4CH4COMBUSTIONEMISSIONS e.g. 'NA'. See Details.
#' @param T4N2OCOMBUSTIONEMISSIONS e.g. 'NA'. See Details.
#' @param TIER4_CH4_EMISSIONS_CO2E e.g. 'NA'. See Details.
#' @param TIER4_N2O_EMISSIONS_CO2E e.g. 'NA'. See Details.
#' @param PART_75_CH4_EMISSIONS_CO2E e.g. 'NA'. See Details.
#' @param PART_75_N2O_EMISSIONS_CO2E e.g. 'NA'. See Details.
#' @param PART_75_ANNUAL_HEAT_INPUT e.g. 'NA'. See Details.
#' @param FACILITY_NAME e.g. 'PSE Ferndale Generating Station'. See Details.
#' @param UNIT_NAME e.g. 'GT-1A'. See Details.
#' @param UNIT_TYPE e.g. 'CCCT (CC (Turbine, combined cycle))'. See Details.
#' @param FUEL_TYPE e.g. 'Distillate Fuel Oil No. 2'. See Details.
#' @param FUEL_TYPE_OTHER e.g. 'NA'. See Details.
#' @param FUEL_TYPE_BLEND e.g. 'NA'. See Details.
#' @param TIER_1_METHOD_EQUATION e.g. 'NA'. See Details.
#' @param TIER1_METHODOLOGY_START_DATE e.g. 'NA'. See Details.
#' @param TIER1_METHODOLOGY_END_DATE e.g. 'NA'. See Details.
#' @param TIER1_CO2_COMBUSTION_EMISSIONS e.g. 'NA'. See Details.
#' @param TIER1_CH4_COMBUSTION_EMISSIONS e.g. 'NA'. See Details.
#' @param TIER1_N2O_COMBUSTION_EMISSIONS e.g. 'NA'. See Details.
#' @param TIER1_CH4_EMISSIONS_CO2E e.g. 'NA'. See Details.
#' @param TIER1_N2O_EMISSIONS_CO2E e.g. 'NA'. See Details.
#' @param TIER_2_METHOD_EQUATION e.g. 'Tier 2 (Equation C-2a)'. See Details.
#' @param TIER2_METHODOLOGY_START_DATE e.g. '2010-01-01'. See Details.
#' @param TIER2_METHODOLOGY_END_DATE e.g. '2010-12-31'. See Details.
#' @param TIER2_FREQ_HHV_DETERMINATION e.g. 'Other (specify)'. See Details.
#' @param TIER2_OTH_FREQ_HHV_DETERMIN e.g. 'AP-42 Emission Factor'. See Details.
#' @param TIER2_CO2_COMBUSTION_EMISSIONS e.g. '44.1'. See Details.
#' @param TIER2_CH4_COMBUSTION_EMISSIONS e.g. '0'. See Details.
#' @param TIER2_N2O_COMBUSTION_EMISSIONS e.g. '0'. See Details.
#' @param TIER2_CH4_EMISSIONS_CO2E e.g. '0'. See Details.
#' @param TIER2_N2O_EMISSIONS_CO2E e.g. '0'. See Details.
#' @param TIER_3_METHOD_EQUATION e.g. 'NA'. See Details.
#' @param TIER3_METHODOLOGY_START_DATE e.g. 'NA'. See Details.
#' @param TIER3_METHODOLOGY_END_DATE e.g. 'NA'. See Details.
#' @param TIER3_CO2_COMBUSTION_EMISSIONS e.g. 'NA'. See Details.
#' @param TIER3_CH4_COMBUSTION_EMISSIONS e.g. 'NA'. See Details.
#' @param TIER3_N2O_COMBUSTION_EMISSIONS e.g. 'NA'. See Details.
#' @param TIER3_CH4_EMISSIONS_CO2E e.g. 'NA'. See Details.
#' @param TIER3_N2O_EMISSIONS_CO2E e.g. 'NA'. See Details.
#' @param T3MOLARVOLUMECONSTANTVALUE e.g. 'NA'. See Details.
#' @param OTHER_OR_BLEND_FUEL_TYPE e.g. 'NA'. See Details.
#' @export

ghg_c_fuel_level_information <- function(FACILITY_ID = NULL, REPORTING_YEAR = NULL, 
    T3FREQUENCYOFCCDETERMINATION = NULL, T3OTHERFREQFCCDETERMINATION = NULL, T3TOTALNUMBERCCDETERMINATIONS = NULL, 
    T3NUMBERVALIDCCDETERMINATIONS = NULL, T3FREQUENCYOFMWDETERMINATION = NULL, T3OTHERFREQOFMWDETERMINATION = NULL, 
    T3TOTALNUMBERMWTDETERMINATIONS = NULL, T3NUMBERVALIDMWDETERMINATIONS = NULL, 
    T3NUMOFOPTHOURSSUBFUELUSAGE = NULL, T4CH4COMBUSTIONEMISSIONS = NULL, T4N2OCOMBUSTIONEMISSIONS = NULL, 
    TIER4_CH4_EMISSIONS_CO2E = NULL, TIER4_N2O_EMISSIONS_CO2E = NULL, PART_75_CH4_EMISSIONS_CO2E = NULL, 
    PART_75_N2O_EMISSIONS_CO2E = NULL, PART_75_ANNUAL_HEAT_INPUT = NULL, FACILITY_NAME = NULL, 
    UNIT_NAME = NULL, UNIT_TYPE = NULL, FUEL_TYPE = NULL, FUEL_TYPE_OTHER = NULL, 
    FUEL_TYPE_BLEND = NULL, TIER_1_METHOD_EQUATION = NULL, TIER1_METHODOLOGY_START_DATE = NULL, 
    TIER1_METHODOLOGY_END_DATE = NULL, TIER1_CO2_COMBUSTION_EMISSIONS = NULL, TIER1_CH4_COMBUSTION_EMISSIONS = NULL, 
    TIER1_N2O_COMBUSTION_EMISSIONS = NULL, TIER1_CH4_EMISSIONS_CO2E = NULL, TIER1_N2O_EMISSIONS_CO2E = NULL, 
    TIER_2_METHOD_EQUATION = NULL, TIER2_METHODOLOGY_START_DATE = NULL, TIER2_METHODOLOGY_END_DATE = NULL, 
    TIER2_FREQ_HHV_DETERMINATION = NULL, TIER2_OTH_FREQ_HHV_DETERMIN = NULL, TIER2_CO2_COMBUSTION_EMISSIONS = NULL, 
    TIER2_CH4_COMBUSTION_EMISSIONS = NULL, TIER2_N2O_COMBUSTION_EMISSIONS = NULL, 
    TIER2_CH4_EMISSIONS_CO2E = NULL, TIER2_N2O_EMISSIONS_CO2E = NULL, TIER_3_METHOD_EQUATION = NULL, 
    TIER3_METHODOLOGY_START_DATE = NULL, TIER3_METHODOLOGY_END_DATE = NULL, TIER3_CO2_COMBUSTION_EMISSIONS = NULL, 
    TIER3_CH4_COMBUSTION_EMISSIONS = NULL, TIER3_N2O_COMBUSTION_EMISSIONS = NULL, 
    TIER3_CH4_EMISSIONS_CO2E = NULL, TIER3_N2O_EMISSIONS_CO2E = NULL, T3MOLARVOLUMECONSTANTVALUE = NULL, 
    OTHER_OR_BLEND_FUEL_TYPE = NULL) {
    
    args <- list(FACILITY_ID = FACILITY_ID, REPORTING_YEAR = REPORTING_YEAR, T3FREQUENCYOFCCDETERMINATION = T3FREQUENCYOFCCDETERMINATION, 
        T3OTHERFREQFCCDETERMINATION = T3OTHERFREQFCCDETERMINATION, T3TOTALNUMBERCCDETERMINATIONS = T3TOTALNUMBERCCDETERMINATIONS, 
        T3NUMBERVALIDCCDETERMINATIONS = T3NUMBERVALIDCCDETERMINATIONS, T3FREQUENCYOFMWDETERMINATION = T3FREQUENCYOFMWDETERMINATION, 
        T3OTHERFREQOFMWDETERMINATION = T3OTHERFREQOFMWDETERMINATION, T3TOTALNUMBERMWTDETERMINATIONS = T3TOTALNUMBERMWTDETERMINATIONS, 
        T3NUMBERVALIDMWDETERMINATIONS = T3NUMBERVALIDMWDETERMINATIONS, T3NUMOFOPTHOURSSUBFUELUSAGE = T3NUMOFOPTHOURSSUBFUELUSAGE, 
        T4CH4COMBUSTIONEMISSIONS = T4CH4COMBUSTIONEMISSIONS, T4N2OCOMBUSTIONEMISSIONS = T4N2OCOMBUSTIONEMISSIONS, 
        TIER4_CH4_EMISSIONS_CO2E = TIER4_CH4_EMISSIONS_CO2E, TIER4_N2O_EMISSIONS_CO2E = TIER4_N2O_EMISSIONS_CO2E, 
        PART_75_CH4_EMISSIONS_CO2E = PART_75_CH4_EMISSIONS_CO2E, PART_75_N2O_EMISSIONS_CO2E = PART_75_N2O_EMISSIONS_CO2E, 
        PART_75_ANNUAL_HEAT_INPUT = PART_75_ANNUAL_HEAT_INPUT, FACILITY_NAME = FACILITY_NAME, 
        UNIT_NAME = UNIT_NAME, UNIT_TYPE = UNIT_TYPE, FUEL_TYPE = FUEL_TYPE, FUEL_TYPE_OTHER = FUEL_TYPE_OTHER, 
        FUEL_TYPE_BLEND = FUEL_TYPE_BLEND, TIER_1_METHOD_EQUATION = TIER_1_METHOD_EQUATION, 
        TIER1_METHODOLOGY_START_DATE = TIER1_METHODOLOGY_START_DATE, TIER1_METHODOLOGY_END_DATE = TIER1_METHODOLOGY_END_DATE, 
        TIER1_CO2_COMBUSTION_EMISSIONS = TIER1_CO2_COMBUSTION_EMISSIONS, TIER1_CH4_COMBUSTION_EMISSIONS = TIER1_CH4_COMBUSTION_EMISSIONS, 
        TIER1_N2O_COMBUSTION_EMISSIONS = TIER1_N2O_COMBUSTION_EMISSIONS, TIER1_CH4_EMISSIONS_CO2E = TIER1_CH4_EMISSIONS_CO2E, 
        TIER1_N2O_EMISSIONS_CO2E = TIER1_N2O_EMISSIONS_CO2E, TIER_2_METHOD_EQUATION = TIER_2_METHOD_EQUATION, 
        TIER2_METHODOLOGY_START_DATE = TIER2_METHODOLOGY_START_DATE, TIER2_METHODOLOGY_END_DATE = TIER2_METHODOLOGY_END_DATE, 
        TIER2_FREQ_HHV_DETERMINATION = TIER2_FREQ_HHV_DETERMINATION, TIER2_OTH_FREQ_HHV_DETERMIN = TIER2_OTH_FREQ_HHV_DETERMIN, 
        TIER2_CO2_COMBUSTION_EMISSIONS = TIER2_CO2_COMBUSTION_EMISSIONS, TIER2_CH4_COMBUSTION_EMISSIONS = TIER2_CH4_COMBUSTION_EMISSIONS, 
        TIER2_N2O_COMBUSTION_EMISSIONS = TIER2_N2O_COMBUSTION_EMISSIONS, TIER2_CH4_EMISSIONS_CO2E = TIER2_CH4_EMISSIONS_CO2E, 
        TIER2_N2O_EMISSIONS_CO2E = TIER2_N2O_EMISSIONS_CO2E, TIER_3_METHOD_EQUATION = TIER_3_METHOD_EQUATION, 
        TIER3_METHODOLOGY_START_DATE = TIER3_METHODOLOGY_START_DATE, TIER3_METHODOLOGY_END_DATE = TIER3_METHODOLOGY_END_DATE, 
        TIER3_CO2_COMBUSTION_EMISSIONS = TIER3_CO2_COMBUSTION_EMISSIONS, TIER3_CH4_COMBUSTION_EMISSIONS = TIER3_CH4_COMBUSTION_EMISSIONS, 
        TIER3_N2O_COMBUSTION_EMISSIONS = TIER3_N2O_COMBUSTION_EMISSIONS, TIER3_CH4_EMISSIONS_CO2E = TIER3_CH4_EMISSIONS_CO2E, 
        TIER3_N2O_EMISSIONS_CO2E = TIER3_N2O_EMISSIONS_CO2E, T3MOLARVOLUMECONSTANTVALUE = T3MOLARVOLUMECONSTANTVALUE, 
        OTHER_OR_BLEND_FUEL_TYPE = OTHER_OR_BLEND_FUEL_TYPE)
    ret <- envir_get(c_fuel_level_information, args)
    
    ret
} 
