#' Retrieve w acid gas removal unit data from ghg database
#' 
#' @param FACILITY_ID e.g. '1000064'. See Details.
#' @param REPORTING_YEAR e.g. '2014'. See Details.
#' @param FACILITY_NAME e.g. 'LONE STAR GAS LIQUIDS'. See Details.
#' @param INDUSTRY_SEGMENT e.g. 'ONSHORE NATURAL GAS PROCESSING [98.230(A)(3)]'. See Details.
#' @param ACID_GAS_REMOVAL_CO2_EMISSIONS e.g. '0'. See Details.
#' @param ACID_GAS_REMOVAL_CH4_EMM_CO2E e.g. 'NA'. See Details.
#' @param ACID_GAS_REMOVAL_N2O_EMM_CO2E e.g. 'NA'. See Details.
#' @param ACID_GAS_REMOVAL_GHG_EMM_CO2E e.g. '0'. See Details.
#' @param DOES_FAC_HAVE_AGR_UNIT e.g. 'NO'. See Details.
#' @param BAMM_INDICATOR_ACID_GAS e.g. 'NO'. See Details.
#' @param SUB_INDICATOR_ACID_GAS e.g. 'NA'. See Details.
#' @param BAMM_DESCRIPTION_ACID_GAS e.g. 'NA'. See Details.
#' @export

ghg_w_acid_gas_removal_unit <- function(FACILITY_ID = NULL, REPORTING_YEAR = NULL, 
    FACILITY_NAME = NULL, INDUSTRY_SEGMENT = NULL, ACID_GAS_REMOVAL_CO2_EMISSIONS = NULL, 
    ACID_GAS_REMOVAL_CH4_EMM_CO2E = NULL, ACID_GAS_REMOVAL_N2O_EMM_CO2E = NULL, ACID_GAS_REMOVAL_GHG_EMM_CO2E = NULL, 
    DOES_FAC_HAVE_AGR_UNIT = NULL, BAMM_INDICATOR_ACID_GAS = NULL, SUB_INDICATOR_ACID_GAS = NULL, 
    BAMM_DESCRIPTION_ACID_GAS = NULL) {
    
    args <- list(FACILITY_ID = FACILITY_ID, REPORTING_YEAR = REPORTING_YEAR, FACILITY_NAME = FACILITY_NAME, 
        INDUSTRY_SEGMENT = INDUSTRY_SEGMENT, ACID_GAS_REMOVAL_CO2_EMISSIONS = ACID_GAS_REMOVAL_CO2_EMISSIONS, 
        ACID_GAS_REMOVAL_CH4_EMM_CO2E = ACID_GAS_REMOVAL_CH4_EMM_CO2E, ACID_GAS_REMOVAL_N2O_EMM_CO2E = ACID_GAS_REMOVAL_N2O_EMM_CO2E, 
        ACID_GAS_REMOVAL_GHG_EMM_CO2E = ACID_GAS_REMOVAL_GHG_EMM_CO2E, DOES_FAC_HAVE_AGR_UNIT = DOES_FAC_HAVE_AGR_UNIT, 
        BAMM_INDICATOR_ACID_GAS = BAMM_INDICATOR_ACID_GAS, SUB_INDICATOR_ACID_GAS = SUB_INDICATOR_ACID_GAS, 
        BAMM_DESCRIPTION_ACID_GAS = BAMM_DESCRIPTION_ACID_GAS)
    ret <- envir_get("w_acid_gas_removal_unit", args)
    
    ret
} 
