#' Retrieve pp calc method data quality data from ghg database
#' 
#' @param FACILITY_ID e.g. '1000035'. See Details.
#' @param REPORTING_YEAR e.g. '2013'. See Details.
#' @param FACILITY_NAME e.g. 'ANDERSONS MARATHON ETHANOL LLC'. See Details.
#' @param CALCULATION_METHODOLOGY e.g. 'Flow Meters 1'. See Details.
#' @param SUBSTITUTE_MASSVOLUME_DATA_USE e.g. 'NA'. See Details.
#' @param SUB_CONCENTRATION_DATA_USE e.g. 'NA'. See Details.
#' @param SUBSTITUTE_DENSITY_DATA_USE e.g. 'NA'. See Details.
#' @param IMPORTER_EXPORTER_TYPE e.g. 'NA'. See Details.
#' @export

ghg_pp_calc_method_data_quality <- function(FACILITY_ID = NULL, REPORTING_YEAR = NULL, 
    FACILITY_NAME = NULL, CALCULATION_METHODOLOGY = NULL, SUBSTITUTE_MASSVOLUME_DATA_USE = NULL, 
    SUB_CONCENTRATION_DATA_USE = NULL, SUBSTITUTE_DENSITY_DATA_USE = NULL, IMPORTER_EXPORTER_TYPE = NULL) {
    
    args <- list(FACILITY_ID = FACILITY_ID, REPORTING_YEAR = REPORTING_YEAR, FACILITY_NAME = FACILITY_NAME, 
        CALCULATION_METHODOLOGY = CALCULATION_METHODOLOGY, SUBSTITUTE_MASSVOLUME_DATA_USE = SUBSTITUTE_MASSVOLUME_DATA_USE, 
        SUB_CONCENTRATION_DATA_USE = SUB_CONCENTRATION_DATA_USE, SUBSTITUTE_DENSITY_DATA_USE = SUBSTITUTE_DENSITY_DATA_USE, 
        IMPORTER_EXPORTER_TYPE = IMPORTER_EXPORTER_TYPE)
    ret <- envir_get("pp_calc_method_data_quality", args)
    
    ret
} 
