#' Retrieve ff summary source data from ghg database
#' 
#' @param FACILITY_ID e.g. '1000386'. See Details.
#' @param REPORTING_YEAR e.g. '2011'. See Details.
#' @param FACILITY_NAME e.g. 'NO. 65'. See Details.
#' @param QUARTER e.g. 'QUARTER 1 (JAN-MAR)'. See Details.
#' @param QTR_METH_DEST_TRNS_OFFSTE_CALC e.g. '0'. See Details.
#' @param QTR_METH_DEST_TRNS_OFFSTE_USER e.g. 'N'. See Details.
#' @param QTR_METH_LIBER_DEGAS_CALC e.g. '0'. See Details.
#' @param QTR_METH_LIBER_DEGAS_USER e.g. 'N'. See Details.
#' @param QTR_METH_LIBER_VENT_CALC e.g. '154.19'. See Details.
#' @param QTR_METH_LIBER_VENT_USER e.g. 'N'. See Details.
#' @param NUMBER_OF_WELLS e.g. 'NA'. See Details.
#' @param NUM_OF_SHAFTS e.g. 'NA'. See Details.
#' @param IS_GAS_COLL_SYSTEM e.g. 'N'. See Details.
#' @param QUARTER_1_CO2_EMISSIONS e.g. '0'. See Details.
#' @param TOT_QRTLY_CH4 e.g. '154.19'. See Details.
#' @export

ghg_ff_summary_source <- function(FACILITY_ID = NULL, REPORTING_YEAR = NULL, FACILITY_NAME = NULL, 
    QUARTER = NULL, QTR_METH_DEST_TRNS_OFFSTE_CALC = NULL, QTR_METH_DEST_TRNS_OFFSTE_USER = NULL, 
    QTR_METH_LIBER_DEGAS_CALC = NULL, QTR_METH_LIBER_DEGAS_USER = NULL, QTR_METH_LIBER_VENT_CALC = NULL, 
    QTR_METH_LIBER_VENT_USER = NULL, NUMBER_OF_WELLS = NULL, NUM_OF_SHAFTS = NULL, 
    IS_GAS_COLL_SYSTEM = NULL, QUARTER_1_CO2_EMISSIONS = NULL, TOT_QRTLY_CH4 = NULL) {
    
    args <- list(FACILITY_ID = FACILITY_ID, REPORTING_YEAR = REPORTING_YEAR, FACILITY_NAME = FACILITY_NAME, 
        QUARTER = QUARTER, QTR_METH_DEST_TRNS_OFFSTE_CALC = QTR_METH_DEST_TRNS_OFFSTE_CALC, 
        QTR_METH_DEST_TRNS_OFFSTE_USER = QTR_METH_DEST_TRNS_OFFSTE_USER, QTR_METH_LIBER_DEGAS_CALC = QTR_METH_LIBER_DEGAS_CALC, 
        QTR_METH_LIBER_DEGAS_USER = QTR_METH_LIBER_DEGAS_USER, QTR_METH_LIBER_VENT_CALC = QTR_METH_LIBER_VENT_CALC, 
        QTR_METH_LIBER_VENT_USER = QTR_METH_LIBER_VENT_USER, NUMBER_OF_WELLS = NUMBER_OF_WELLS, 
        NUM_OF_SHAFTS = NUM_OF_SHAFTS, IS_GAS_COLL_SYSTEM = IS_GAS_COLL_SYSTEM, QUARTER_1_CO2_EMISSIONS = QUARTER_1_CO2_EMISSIONS, 
        TOT_QRTLY_CH4 = TOT_QRTLY_CH4)
    ret <- envir_get(ff_summary_source, args)
    
    ret
} 
