#' Retrieve w transmission tanks data from ghg database
#' 
#' @param FACILITY_ID e.g. '1000179'. See Details.
#' @param REPORTING_YEAR e.g. '2011'. See Details.
#' @param FACILITY_NAME e.g. 'BERNVILLE STATION'. See Details.
#' @param INDUSTRY_SEGMENT e.g. 'ONSHORE NATURAL GAS TRANSMISSION COMPRESSION [98.230(A)(4)]'. See Details.
#' @param TRANS_TANKS_TOTAL_CO2_EMM e.g. '0'. See Details.
#' @param TRANS_TANKS_TOTAL_CH4_EMM_CO2E e.g. '0'. See Details.
#' @param TRANS_TANKS_TOTAL_N2O_EMM_CO2E e.g. 'NA'. See Details.
#' @param TRANS_TANKS_TOTAL_GHG_EMM_CO2E e.g. '0'. See Details.
#' @param DID_FAC_VENT_STACK_EMISSIONS e.g. 'YES'. See Details.
#' @param BAMM_IND_TRANSMISSION_TANKS e.g. 'NO'. See Details.
#' @param BAMM_DESC_TRANSMISSION_TANKS e.g. 'NA'. See Details.
#' @param SUB_IND_TRANSMISSION_TANKS e.g. 'NO'. See Details.
#' @export

ghg_w_transmission_tanks <- function(FACILITY_ID = NULL, REPORTING_YEAR = NULL, FACILITY_NAME = NULL, 
    INDUSTRY_SEGMENT = NULL, TRANS_TANKS_TOTAL_CO2_EMM = NULL, TRANS_TANKS_TOTAL_CH4_EMM_CO2E = NULL, 
    TRANS_TANKS_TOTAL_N2O_EMM_CO2E = NULL, TRANS_TANKS_TOTAL_GHG_EMM_CO2E = NULL, 
    DID_FAC_VENT_STACK_EMISSIONS = NULL, BAMM_IND_TRANSMISSION_TANKS = NULL, BAMM_DESC_TRANSMISSION_TANKS = NULL, 
    SUB_IND_TRANSMISSION_TANKS = NULL) {
    
    args <- list(FACILITY_ID = FACILITY_ID, REPORTING_YEAR = REPORTING_YEAR, FACILITY_NAME = FACILITY_NAME, 
        INDUSTRY_SEGMENT = INDUSTRY_SEGMENT, TRANS_TANKS_TOTAL_CO2_EMM = TRANS_TANKS_TOTAL_CO2_EMM, 
        TRANS_TANKS_TOTAL_CH4_EMM_CO2E = TRANS_TANKS_TOTAL_CH4_EMM_CO2E, TRANS_TANKS_TOTAL_N2O_EMM_CO2E = TRANS_TANKS_TOTAL_N2O_EMM_CO2E, 
        TRANS_TANKS_TOTAL_GHG_EMM_CO2E = TRANS_TANKS_TOTAL_GHG_EMM_CO2E, DID_FAC_VENT_STACK_EMISSIONS = DID_FAC_VENT_STACK_EMISSIONS, 
        BAMM_IND_TRANSMISSION_TANKS = BAMM_IND_TRANSMISSION_TANKS, BAMM_DESC_TRANSMISSION_TANKS = BAMM_DESC_TRANSMISSION_TANKS, 
        SUB_IND_TRANSMISSION_TANKS = SUB_IND_TRANSMISSION_TANKS)
    ret <- envir_get(w_transmission_tanks, args)
    
    ret
} 
