#' Retrieve w pneumatic pumps data from ghg database
#' 
#' @param FACILITY_ID e.g. '1000355'. See Details.
#' @param REPORTING_YEAR e.g. '2012'. See Details.
#' @param SUB_INDICATOR_PNEUMATIC_PUMPS e.g. 'NO'. See Details.
#' @param BAMM_DESC_PNEUMATIC_PUMPS e.g. 'NA'. See Details.
#' @param BAMM_INDICATOR_PNEUMATIC_PUMPS e.g. 'NO'. See Details.
#' @param DOES_FAC_HAVE_PNEUMATIC_PUMPS e.g. 'YES'. See Details.
#' @param PNEUM_PUMP_TOTAL_GHG_EMM_CO2E e.g. '706.9'. See Details.
#' @param PNEUM_PUMP_TOTAL_N2O_EMM_CO2E e.g. 'NA'. See Details.
#' @param PNEUM_PUMP_TOTAL_CH4_EMM_CO2E e.g. '704'. See Details.
#' @param PNEUM_PUMP_TOTAL_CO2_EMISSIONS e.g. '2.9'. See Details.
#' @param FACILITY_NAME e.g. '#540 BONANZA CREEK ENERGY - DENVER BASIN'. See Details.
#' @param INDUSTRY_SEGMENT e.g. 'ONSHORE PETROLEUM AND NATURAL GAS PRODUCTION [98.230(A)(2)]'. See Details.
#' @export

ghg_w_pneumatic_pumps <- function(FACILITY_ID = NULL, REPORTING_YEAR = NULL, SUB_INDICATOR_PNEUMATIC_PUMPS = NULL, 
    BAMM_DESC_PNEUMATIC_PUMPS = NULL, BAMM_INDICATOR_PNEUMATIC_PUMPS = NULL, DOES_FAC_HAVE_PNEUMATIC_PUMPS = NULL, 
    PNEUM_PUMP_TOTAL_GHG_EMM_CO2E = NULL, PNEUM_PUMP_TOTAL_N2O_EMM_CO2E = NULL, PNEUM_PUMP_TOTAL_CH4_EMM_CO2E = NULL, 
    PNEUM_PUMP_TOTAL_CO2_EMISSIONS = NULL, FACILITY_NAME = NULL, INDUSTRY_SEGMENT = NULL) {
    
    args <- list(FACILITY_ID = FACILITY_ID, REPORTING_YEAR = REPORTING_YEAR, SUB_INDICATOR_PNEUMATIC_PUMPS = SUB_INDICATOR_PNEUMATIC_PUMPS, 
        BAMM_DESC_PNEUMATIC_PUMPS = BAMM_DESC_PNEUMATIC_PUMPS, BAMM_INDICATOR_PNEUMATIC_PUMPS = BAMM_INDICATOR_PNEUMATIC_PUMPS, 
        DOES_FAC_HAVE_PNEUMATIC_PUMPS = DOES_FAC_HAVE_PNEUMATIC_PUMPS, PNEUM_PUMP_TOTAL_GHG_EMM_CO2E = PNEUM_PUMP_TOTAL_GHG_EMM_CO2E, 
        PNEUM_PUMP_TOTAL_N2O_EMM_CO2E = PNEUM_PUMP_TOTAL_N2O_EMM_CO2E, PNEUM_PUMP_TOTAL_CH4_EMM_CO2E = PNEUM_PUMP_TOTAL_CH4_EMM_CO2E, 
        PNEUM_PUMP_TOTAL_CO2_EMISSIONS = PNEUM_PUMP_TOTAL_CO2_EMISSIONS, FACILITY_NAME = FACILITY_NAME, 
        INDUSTRY_SEGMENT = INDUSTRY_SEGMENT)
    ret <- envir_get("w_pneumatic_pumps", args)
    
    ret
} 
