#' Retrieve w wellcompl without hydraulic data from ghg database
#' 
#' @param FACILITY_ID e.g. '1000355'. See Details.
#' @param REPORTING_YEAR e.g. '2012'. See Details.
#' @param COMPLT_WO_HYD_FLAR_N2O_EMMCO2E e.g. '0'. See Details.
#' @param FACILITY_NAME e.g. '#540 BONANZA CREEK ENERGY - DENVER BASIN'. See Details.
#' @param INDUSTRY_SEGMENT e.g. 'ONSHORE PETROLEUM AND NATURAL GAS PRODUCTION [98.230(A)(2)]'. See Details.
#' @param COMPLT_WO_HYD_FLAR_CH4_EMMCO2E e.g. '0'. See Details.
#' @param TOTAL_GAS_VENTING_DAYS e.g. '0'. See Details.
#' @param COMPLT_WO_HYD_VENTING_CO2_EMM e.g. '0'. See Details.
#' @param COMPL_WO_HYD_VENT_CH4_EMM_CO2E e.g. '6.3'. See Details.
#' @param COMPLT_WO_HYD_FLARING_CO2_EMM e.g. '0'. See Details.
#' @param SUB_BASIN_IDENTIFIER e.g. '540 - WELD, CO (123) - OTHER TIGHT RESERVOIR ROCK'. See Details.
#' @param NUMBER_OF_COMPLETIONS e.g. '7'. See Details.
#' @param NUMBER_OF_WRKOVRS_FLR_OR_VNT e.g. '7'. See Details.
#' @export

ghg_w_wellcompl_without_hydraulic <- function(FACILITY_ID = NULL, REPORTING_YEAR = NULL, 
    COMPLT_WO_HYD_FLAR_N2O_EMMCO2E = NULL, FACILITY_NAME = NULL, INDUSTRY_SEGMENT = NULL, 
    COMPLT_WO_HYD_FLAR_CH4_EMMCO2E = NULL, TOTAL_GAS_VENTING_DAYS = NULL, COMPLT_WO_HYD_VENTING_CO2_EMM = NULL, 
    COMPL_WO_HYD_VENT_CH4_EMM_CO2E = NULL, COMPLT_WO_HYD_FLARING_CO2_EMM = NULL, 
    SUB_BASIN_IDENTIFIER = NULL, NUMBER_OF_COMPLETIONS = NULL, NUMBER_OF_WRKOVRS_FLR_OR_VNT = NULL) {
    
    args <- list(FACILITY_ID = FACILITY_ID, REPORTING_YEAR = REPORTING_YEAR, COMPLT_WO_HYD_FLAR_N2O_EMMCO2E = COMPLT_WO_HYD_FLAR_N2O_EMMCO2E, 
        FACILITY_NAME = FACILITY_NAME, INDUSTRY_SEGMENT = INDUSTRY_SEGMENT, COMPLT_WO_HYD_FLAR_CH4_EMMCO2E = COMPLT_WO_HYD_FLAR_CH4_EMMCO2E, 
        TOTAL_GAS_VENTING_DAYS = TOTAL_GAS_VENTING_DAYS, COMPLT_WO_HYD_VENTING_CO2_EMM = COMPLT_WO_HYD_VENTING_CO2_EMM, 
        COMPL_WO_HYD_VENT_CH4_EMM_CO2E = COMPL_WO_HYD_VENT_CH4_EMM_CO2E, COMPLT_WO_HYD_FLARING_CO2_EMM = COMPLT_WO_HYD_FLARING_CO2_EMM, 
        SUB_BASIN_IDENTIFIER = SUB_BASIN_IDENTIFIER, NUMBER_OF_COMPLETIONS = NUMBER_OF_COMPLETIONS, 
        NUMBER_OF_WRKOVRS_FLR_OR_VNT = NUMBER_OF_WRKOVRS_FLR_OR_VNT)
    ret <- envir_get(w_wellcompl_without_hydraulic, args)
    
    ret
} 
