#' Retrieve ff destroffsite weekly data from ghg database
#' 
#' @param FACILITY_ID e.g. '1001687'. See Details.
#' @param REPORTING_YEAR e.g. '2011'. See Details.
#' @param WEEKLY_DESTRUCTION_DEVICE_ID e.g. 'NONE'. See Details.
#' @param TIME_SUB_WKLY_VOL_FLOW_METH_DE e.g. '0'. See Details.
#' @param TIME_SUB_WKLY_METH_CON_METH_DE e.g. '0'. See Details.
#' @param WKLY_FLW_RT_USD_CALC_METH_DEST e.g. '0'. See Details.
#' @param WKLY_VOLUMETRIC_FLOW_RATE_UNIT e.g. 'NA'. See Details.
#' @param WEEKLY_METHANE_CONCENTRATION e.g. 'NA'. See Details.
#' @param FACILITY_NAME e.g. 'BLUE DIAMOND MINING MINE 77'. See Details.
#' @param QUARTER e.g. '1'. See Details.
#' @param WEEK e.g. '1'. See Details.
#' @export

ghg_ff_destroffsite_weekly <- function(FACILITY_ID = NULL, REPORTING_YEAR = NULL, 
    WEEKLY_DESTRUCTION_DEVICE_ID = NULL, TIME_SUB_WKLY_VOL_FLOW_METH_DE = NULL, TIME_SUB_WKLY_METH_CON_METH_DE = NULL, 
    WKLY_FLW_RT_USD_CALC_METH_DEST = NULL, WKLY_VOLUMETRIC_FLOW_RATE_UNIT = NULL, 
    WEEKLY_METHANE_CONCENTRATION = NULL, FACILITY_NAME = NULL, QUARTER = NULL, WEEK = NULL) {
    
    args <- list(FACILITY_ID = FACILITY_ID, REPORTING_YEAR = REPORTING_YEAR, WEEKLY_DESTRUCTION_DEVICE_ID = WEEKLY_DESTRUCTION_DEVICE_ID, 
        TIME_SUB_WKLY_VOL_FLOW_METH_DE = TIME_SUB_WKLY_VOL_FLOW_METH_DE, TIME_SUB_WKLY_METH_CON_METH_DE = TIME_SUB_WKLY_METH_CON_METH_DE, 
        WKLY_FLW_RT_USD_CALC_METH_DEST = WKLY_FLW_RT_USD_CALC_METH_DEST, WKLY_VOLUMETRIC_FLOW_RATE_UNIT = WKLY_VOLUMETRIC_FLOW_RATE_UNIT, 
        WEEKLY_METHANE_CONCENTRATION = WEEKLY_METHANE_CONCENTRATION, FACILITY_NAME = FACILITY_NAME, 
        QUARTER = QUARTER, WEEK = WEEK)
    ret <- envir_get("ff_destroffsite_weekly", args)
    
    ret
} 
