#' Retrieve tt wastestream detls data from ghg database
#' 
#' @param FACILITY_ID e.g. '1000093'. See Details.
#' @param REPORTING_YEAR e.g. '2011'. See Details.
#' @param FACILITY_NAME e.g. 'MOMENTIVE PERFORMANCE MATERIALS'. See Details.
#' @param WASTE_STREAM_NAME e.g. 'LANDFILL 1'. See Details.
#' @param WASTE_STREAM_DESCRIPTION e.g. 'DEWATERED SOLIDS FROM THE WASTEWATER TREATMENT PLANT, SPENT SILICON-COPPER SLURRY, INCINERATOR RESID'. See Details.
#' @param WASTE_STREAM_TYPE e.g. 'OTHER INDUSTRIAL SOLID WASTE'. See Details.
#' @param ANAEROBIC_BIODEG_TEST_METHOD e.g. 'NA'. See Details.
#' @param OTHER_ANAEROB_BIODEG_TEST_METH e.g. 'NA'. See Details.
#' @param RANGE_YRS_DISP_PRD_DATA_USED e.g. 'NA'. See Details.
#' @param WASTE_STREAM_FIRST_YR_IN_LF e.g. '1972'. See Details.
#' @param WASTE_STREAM_LAST_YR_IN_LF e.g. '1989'. See Details.
#' @export

ghg_tt_wastestream_detls <- function(FACILITY_ID = NULL, REPORTING_YEAR = NULL, FACILITY_NAME = NULL, 
    WASTE_STREAM_NAME = NULL, WASTE_STREAM_DESCRIPTION = NULL, WASTE_STREAM_TYPE = NULL, 
    ANAEROBIC_BIODEG_TEST_METHOD = NULL, OTHER_ANAEROB_BIODEG_TEST_METH = NULL, RANGE_YRS_DISP_PRD_DATA_USED = NULL, 
    WASTE_STREAM_FIRST_YR_IN_LF = NULL, WASTE_STREAM_LAST_YR_IN_LF = NULL) {
    
    args <- list(FACILITY_ID = FACILITY_ID, REPORTING_YEAR = REPORTING_YEAR, FACILITY_NAME = FACILITY_NAME, 
        WASTE_STREAM_NAME = WASTE_STREAM_NAME, WASTE_STREAM_DESCRIPTION = WASTE_STREAM_DESCRIPTION, 
        WASTE_STREAM_TYPE = WASTE_STREAM_TYPE, ANAEROBIC_BIODEG_TEST_METHOD = ANAEROBIC_BIODEG_TEST_METHOD, 
        OTHER_ANAEROB_BIODEG_TEST_METH = OTHER_ANAEROB_BIODEG_TEST_METH, RANGE_YRS_DISP_PRD_DATA_USED = RANGE_YRS_DISP_PRD_DATA_USED, 
        WASTE_STREAM_FIRST_YR_IN_LF = WASTE_STREAM_FIRST_YR_IN_LF, WASTE_STREAM_LAST_YR_IN_LF = WASTE_STREAM_LAST_YR_IN_LF)
    ret <- envir_get("tt_wastestream_detls", args)
    
    ret
} 
