#' Retrieve w dehydrators data from ghg database
#' 
#' @param FACILITY_ID e.g. '1000064'. See Details.
#' @param REPORTING_YEAR e.g. '2014'. See Details.
#' @param FACILITY_NAME e.g. 'LONE STAR GAS LIQUIDS'. See Details.
#' @param INDUSTRY_SEGMENT e.g. 'ONSHORE NATURAL GAS PROCESSING [98.230(A)(3)]'. See Details.
#' @param SUB_INDICATOR_DEHYDRATORS e.g. 'NA'. See Details.
#' @param BAMM_INDICATOR_DEHYDRATORS e.g. 'NO'. See Details.
#' @param BAMM_DESCRIPTION_DEHYDRATORS e.g. 'NA'. See Details.
#' @param DEHYDRATORS_CO2_EMISSIONS e.g. '0'. See Details.
#' @param DEHYDRATORS_CH4_EMISSIONS e.g. '0'. See Details.
#' @param DEHYDRATORS_N2O_EMISSIONS e.g. '0'. See Details.
#' @param DEHYDRATORS_GHG_EMISSIONS e.g. '0'. See Details.
#' @param FAC_HV_ACIDGAS_REMOVAL_UTS e.g. 'NO'. See Details.
#' @export

ghg_w_dehydrators <- function(FACILITY_ID = NULL, REPORTING_YEAR = NULL, FACILITY_NAME = NULL, 
    INDUSTRY_SEGMENT = NULL, SUB_INDICATOR_DEHYDRATORS = NULL, BAMM_INDICATOR_DEHYDRATORS = NULL, 
    BAMM_DESCRIPTION_DEHYDRATORS = NULL, DEHYDRATORS_CO2_EMISSIONS = NULL, DEHYDRATORS_CH4_EMISSIONS = NULL, 
    DEHYDRATORS_N2O_EMISSIONS = NULL, DEHYDRATORS_GHG_EMISSIONS = NULL, FAC_HV_ACIDGAS_REMOVAL_UTS = NULL) {
    
    args <- list(FACILITY_ID = FACILITY_ID, REPORTING_YEAR = REPORTING_YEAR, FACILITY_NAME = FACILITY_NAME, 
        INDUSTRY_SEGMENT = INDUSTRY_SEGMENT, SUB_INDICATOR_DEHYDRATORS = SUB_INDICATOR_DEHYDRATORS, 
        BAMM_INDICATOR_DEHYDRATORS = BAMM_INDICATOR_DEHYDRATORS, BAMM_DESCRIPTION_DEHYDRATORS = BAMM_DESCRIPTION_DEHYDRATORS, 
        DEHYDRATORS_CO2_EMISSIONS = DEHYDRATORS_CO2_EMISSIONS, DEHYDRATORS_CH4_EMISSIONS = DEHYDRATORS_CH4_EMISSIONS, 
        DEHYDRATORS_N2O_EMISSIONS = DEHYDRATORS_N2O_EMISSIONS, DEHYDRATORS_GHG_EMISSIONS = DEHYDRATORS_GHG_EMISSIONS, 
        FAC_HV_ACIDGAS_REMOVAL_UTS = FAC_HV_ACIDGAS_REMOVAL_UTS)
    ret <- envir_get(w_dehydrators, args)
    
    ret
} 
