#' Retrieve hh hist yr waste qty detl data from ghg database
#' 
#' @param FACILITY_ID e.g. '1000010'. See Details.
#' @param REPORTING_YEAR e.g. '2013'. See Details.
#' @param HISTYR_PERCENT_BY_WEIGHT e.g. '1'. See Details.
#' @param FACILITY_NAME e.g. 'SANTA ROSA CENTRAL LANDFILL'. See Details.
#' @param HIST_WASTE_DISPOSAL_YEAR e.g. '2009'. See Details.
#' @param HISTYR_DECAY_RATE e.g. '0.057'. See Details.
#' @param HISTYR_FRACTION_OF_DOC_DISS e.g. '0.5'. See Details.
#' @param HISTYR_DOC_VAL e.g. '0.2'. See Details.
#' @param HISTYR_IS_MCF_VALUE_DEFAULT_IN e.g. 'NA'. See Details.
#' @param HISTYR_METHANE_FRACT_DET_MTHD e.g. 'NA'. See Details.
#' @param HISTYR_ANN_WST_QTY_SUB_DATA_US e.g. 'N'. See Details.
#' @param HISTYR_ANNUAL_MCF_VALUE e.g. 'NA'. See Details.
#' @param HISTYR_METHANE_FRACTION e.g. 'NA'. See Details.
#' @param HISTYR_ANN_WST_QTY_NUM_DAY_SUB e.g. 'NA'. See Details.
#' @export

ghg_hh_hist_yr_waste_qty_detl <- function(FACILITY_ID = NULL, REPORTING_YEAR = NULL, 
    HISTYR_PERCENT_BY_WEIGHT = NULL, FACILITY_NAME = NULL, HIST_WASTE_DISPOSAL_YEAR = NULL, 
    HISTYR_DECAY_RATE = NULL, HISTYR_FRACTION_OF_DOC_DISS = NULL, HISTYR_DOC_VAL = NULL, 
    HISTYR_IS_MCF_VALUE_DEFAULT_IN = NULL, HISTYR_METHANE_FRACT_DET_MTHD = NULL, 
    HISTYR_ANN_WST_QTY_SUB_DATA_US = NULL, HISTYR_ANNUAL_MCF_VALUE = NULL, HISTYR_METHANE_FRACTION = NULL, 
    HISTYR_ANN_WST_QTY_NUM_DAY_SUB = NULL) {
    
    args <- list(FACILITY_ID = FACILITY_ID, REPORTING_YEAR = REPORTING_YEAR, HISTYR_PERCENT_BY_WEIGHT = HISTYR_PERCENT_BY_WEIGHT, 
        FACILITY_NAME = FACILITY_NAME, HIST_WASTE_DISPOSAL_YEAR = HIST_WASTE_DISPOSAL_YEAR, 
        HISTYR_DECAY_RATE = HISTYR_DECAY_RATE, HISTYR_FRACTION_OF_DOC_DISS = HISTYR_FRACTION_OF_DOC_DISS, 
        HISTYR_DOC_VAL = HISTYR_DOC_VAL, HISTYR_IS_MCF_VALUE_DEFAULT_IN = HISTYR_IS_MCF_VALUE_DEFAULT_IN, 
        HISTYR_METHANE_FRACT_DET_MTHD = HISTYR_METHANE_FRACT_DET_MTHD, HISTYR_ANN_WST_QTY_SUB_DATA_US = HISTYR_ANN_WST_QTY_SUB_DATA_US, 
        HISTYR_ANNUAL_MCF_VALUE = HISTYR_ANNUAL_MCF_VALUE, HISTYR_METHANE_FRACTION = HISTYR_METHANE_FRACTION, 
        HISTYR_ANN_WST_QTY_NUM_DAY_SUB = HISTYR_ANN_WST_QTY_NUM_DAY_SUB)
    ret <- envir_get(hh_hist_yr_waste_qty_detl, args)
    
    ret
} 
