#' Retrieve w liquids unloading data from ghg database
#' 
#' @param FACILITY_ID e.g. '1000355'. See Details.
#' @param REPORTING_YEAR e.g. '2014'. See Details.
#' @param LIQUID_UNLOAD_TOT_N2O_EMM_CO2E e.g. 'NA'. See Details.
#' @param LIQUIDS_UNLOADING_TOT_CO2_EMM e.g. '10'. See Details.
#' @param INDUSTRY_SEGMENT e.g. 'ONSHORE PETROLEUM AND NATURAL GAS PRODUCTION [98.230(A)(2)]'. See Details.
#' @param FACILITY_NAME e.g. '#540 BONANZA CREEK ENERGY - DENVER BASIN'. See Details.
#' @param LIQUID_UNLOAD_TOT_CH4_EMM_CO2E e.g. '2176.7'. See Details.
#' @param SUB_IND_LIQUIDS_UNLOADING e.g. 'NO'. See Details.
#' @param BAMM_DESC_LIQUIDS_UNLOADING e.g. 'NA'. See Details.
#' @param BAMM_IND_LIQUIDS_UNLOADING e.g. 'NO'. See Details.
#' @param LIQUID_UNLOAD_TOT_GHG_EMM_CO2E e.g. '2186.7'. See Details.
#' @export

ghg_w_liquids_unloading <- function(FACILITY_ID = NULL, REPORTING_YEAR = NULL, LIQUID_UNLOAD_TOT_N2O_EMM_CO2E = NULL, 
    LIQUIDS_UNLOADING_TOT_CO2_EMM = NULL, INDUSTRY_SEGMENT = NULL, FACILITY_NAME = NULL, 
    LIQUID_UNLOAD_TOT_CH4_EMM_CO2E = NULL, SUB_IND_LIQUIDS_UNLOADING = NULL, BAMM_DESC_LIQUIDS_UNLOADING = NULL, 
    BAMM_IND_LIQUIDS_UNLOADING = NULL, LIQUID_UNLOAD_TOT_GHG_EMM_CO2E = NULL) {
    
    args <- list(FACILITY_ID = FACILITY_ID, REPORTING_YEAR = REPORTING_YEAR, LIQUID_UNLOAD_TOT_N2O_EMM_CO2E = LIQUID_UNLOAD_TOT_N2O_EMM_CO2E, 
        LIQUIDS_UNLOADING_TOT_CO2_EMM = LIQUIDS_UNLOADING_TOT_CO2_EMM, INDUSTRY_SEGMENT = INDUSTRY_SEGMENT, 
        FACILITY_NAME = FACILITY_NAME, LIQUID_UNLOAD_TOT_CH4_EMM_CO2E = LIQUID_UNLOAD_TOT_CH4_EMM_CO2E, 
        SUB_IND_LIQUIDS_UNLOADING = SUB_IND_LIQUIDS_UNLOADING, BAMM_DESC_LIQUIDS_UNLOADING = BAMM_DESC_LIQUIDS_UNLOADING, 
        BAMM_IND_LIQUIDS_UNLOADING = BAMM_IND_LIQUIDS_UNLOADING, LIQUID_UNLOAD_TOT_GHG_EMM_CO2E = LIQUID_UNLOAD_TOT_GHG_EMM_CO2E)
    ret <- envir_get(w_liquids_unloading, args)
    
    ret
} 
