#' Retrieve w flare stacks details data from ghg database
#' 
#' @param FACILITY_ID e.g. '1000064'. See Details.
#' @param REPORTING_YEAR e.g. '2014'. See Details.
#' @param INDUSTRY_SEGMENT e.g. 'ONSHORE NATURAL GAS PROCESSING [98.230(A)(3)]'. See Details.
#' @param SUB_INDICATOR_FLARE_STACKS e.g. 'NA'. See Details.
#' @param FLARE_STACKS_CH4_EMISSIONS e.g. '0'. See Details.
#' @param FLARE_STACKS_N2O_EMISSIONS e.g. '0'. See Details.
#' @param FLARE_STACKS_TOT_GHG_EMM_CO2E e.g. '0'. See Details.
#' @param DOES_FAC_HAVE_FLARE_STACKS e.g. 'NO'. See Details.
#' @param BAMM_IND_FLARE_STK_DETAILS e.g. 'NO'. See Details.
#' @param BAMM_DESCRIPTION_FLARE_STACKS e.g. 'NA'. See Details.
#' @param FLARE_STACKS_CO2_EMISSIONS e.g. '0'. See Details.
#' @param FACILITY_NAME e.g. 'LONE STAR GAS LIQUIDS'. See Details.
#' @export

ghg_w_flare_stacks_details <- function(FACILITY_ID = NULL, REPORTING_YEAR = NULL, 
    INDUSTRY_SEGMENT = NULL, SUB_INDICATOR_FLARE_STACKS = NULL, FLARE_STACKS_CH4_EMISSIONS = NULL, 
    FLARE_STACKS_N2O_EMISSIONS = NULL, FLARE_STACKS_TOT_GHG_EMM_CO2E = NULL, DOES_FAC_HAVE_FLARE_STACKS = NULL, 
    BAMM_IND_FLARE_STK_DETAILS = NULL, BAMM_DESCRIPTION_FLARE_STACKS = NULL, FLARE_STACKS_CO2_EMISSIONS = NULL, 
    FACILITY_NAME = NULL) {
    
    args <- list(FACILITY_ID = FACILITY_ID, REPORTING_YEAR = REPORTING_YEAR, INDUSTRY_SEGMENT = INDUSTRY_SEGMENT, 
        SUB_INDICATOR_FLARE_STACKS = SUB_INDICATOR_FLARE_STACKS, FLARE_STACKS_CH4_EMISSIONS = FLARE_STACKS_CH4_EMISSIONS, 
        FLARE_STACKS_N2O_EMISSIONS = FLARE_STACKS_N2O_EMISSIONS, FLARE_STACKS_TOT_GHG_EMM_CO2E = FLARE_STACKS_TOT_GHG_EMM_CO2E, 
        DOES_FAC_HAVE_FLARE_STACKS = DOES_FAC_HAVE_FLARE_STACKS, BAMM_IND_FLARE_STK_DETAILS = BAMM_IND_FLARE_STK_DETAILS, 
        BAMM_DESCRIPTION_FLARE_STACKS = BAMM_DESCRIPTION_FLARE_STACKS, FLARE_STACKS_CO2_EMISSIONS = FLARE_STACKS_CO2_EMISSIONS, 
        FACILITY_NAME = FACILITY_NAME)
    ret <- envir_get(w_flare_stacks_details, args)
    
    ret
} 
