#' Retrieve dd user emissions calc data from ghg database
#' 
#' @param FACILITY_ID e.g. '1000068'. See Details.
#' @param REPORTING_YEAR e.g. '2011'. See Details.
#' @param USE_REMISSIONS_CALCULATED e.g. '0'. See Details.
#' @param FACILITY_NAME e.g. 'Apex Generating Station'. See Details.
#' @param GAS_NAME_SF6_OR_PFC e.g. 'Sulfur hexafluoride'. See Details.
#' @param ACQUISITIONS_OF_GAS_CALCULATED e.g. '0'. See Details.
#' @param DECREASE_IN_GAS_INVENTORY_CALC e.g. '0'. See Details.
#' @param DISBURSEMENTS_OF_GAS_CALCULATE e.g. '0'. See Details.
#' @param NET_INCREASE_NAMEPLATE_CAP_CAL e.g. '0'. See Details.
#' @export

ghg_dd_user_emissions_calc <- function(FACILITY_ID = NULL, REPORTING_YEAR = NULL, 
    USE_REMISSIONS_CALCULATED = NULL, FACILITY_NAME = NULL, GAS_NAME_SF6_OR_PFC = NULL, 
    ACQUISITIONS_OF_GAS_CALCULATED = NULL, DECREASE_IN_GAS_INVENTORY_CALC = NULL, 
    DISBURSEMENTS_OF_GAS_CALCULATE = NULL, NET_INCREASE_NAMEPLATE_CAP_CAL = NULL) {
    
    args <- list(FACILITY_ID = FACILITY_ID, REPORTING_YEAR = REPORTING_YEAR, USE_REMISSIONS_CALCULATED = USE_REMISSIONS_CALCULATED, 
        FACILITY_NAME = FACILITY_NAME, GAS_NAME_SF6_OR_PFC = GAS_NAME_SF6_OR_PFC, 
        ACQUISITIONS_OF_GAS_CALCULATED = ACQUISITIONS_OF_GAS_CALCULATED, DECREASE_IN_GAS_INVENTORY_CALC = DECREASE_IN_GAS_INVENTORY_CALC, 
        DISBURSEMENTS_OF_GAS_CALCULATE = DISBURSEMENTS_OF_GAS_CALCULATE, NET_INCREASE_NAMEPLATE_CAP_CAL = NET_INCREASE_NAMEPLATE_CAP_CAL)
    ret <- envir_get("dd_user_emissions_calc", args)
    
    ret
} 
