#' Retrieve hh landfill info data from ghg database
#' 
#' @param FACILITY_ID e.g. '1000010'. See Details.
#' @param REPORTING_YEAR e.g. '2014'. See Details.
#' @param ESTIMATED_YR_OF_LNDFIL_CLOSURE e.g. '2034'. See Details.
#' @param FIRST_YR_LNDFIL_ACCEPTED_WASTE e.g. '1978'. See Details.
#' @param LAST_YR_LNDFIL_ACCEPTED_WASTE e.g. 'NA'. See Details.
#' @param LEACHATE_RECIRCULATION_FREQ e.g. 'NOT USED FOR THE PAST 10 YEARS'. See Details.
#' @param IS_LANDFILL_OPEN e.g. 'Y'. See Details.
#' @param DOES_LNDFIL_HAVE_GAS_CLCT e.g. 'Y'. See Details.
#' @param LEACHATE_RECIRCULATION_USED e.g. 'N'. See Details.
#' @param PASSIVE_VENTS_OR_FLARES e.g. 'Y'. See Details.
#' @param LANDFILL_CAPACITY e.g. '3169311'. See Details.
#' @param SCALES_PRESENT e.g. 'Y'. See Details.
#' @param LNDFIL_SURFACE_CONTAINING_WSTE e.g. '314445'. See Details.
#' @param ANNUAL_MODELED_CH4_GENERATION e.g. '5141.68'. See Details.
#' @param FIRST_YEAR_EMISSIONS_REPORTING e.g. '2010'. See Details.
#' @param FACILITY_NAME e.g. 'SANTA ROSA CENTRAL LANDFILL'. See Details.
#' @param ANNUAL_MCF_VALUE e.g. '1'. See Details.
#' @param IS_MCF_VALUE_DEFAULT_INDICATOR e.g. 'N'. See Details.
#' @param METHANE_FRAC_DETER_ANNUAL_VALU e.g. '0.5'. See Details.
#' @param METHANE_FRACTION_DETER_METHOD e.g. 'DEFAULT'. See Details.
#' @export

ghg_hh_landfill_info <- function(FACILITY_ID = NULL, REPORTING_YEAR = NULL, ESTIMATED_YR_OF_LNDFIL_CLOSURE = NULL, 
    FIRST_YR_LNDFIL_ACCEPTED_WASTE = NULL, LAST_YR_LNDFIL_ACCEPTED_WASTE = NULL, 
    LEACHATE_RECIRCULATION_FREQ = NULL, IS_LANDFILL_OPEN = NULL, DOES_LNDFIL_HAVE_GAS_CLCT = NULL, 
    LEACHATE_RECIRCULATION_USED = NULL, PASSIVE_VENTS_OR_FLARES = NULL, LANDFILL_CAPACITY = NULL, 
    SCALES_PRESENT = NULL, LNDFIL_SURFACE_CONTAINING_WSTE = NULL, ANNUAL_MODELED_CH4_GENERATION = NULL, 
    FIRST_YEAR_EMISSIONS_REPORTING = NULL, FACILITY_NAME = NULL, ANNUAL_MCF_VALUE = NULL, 
    IS_MCF_VALUE_DEFAULT_INDICATOR = NULL, METHANE_FRAC_DETER_ANNUAL_VALU = NULL, 
    METHANE_FRACTION_DETER_METHOD = NULL) {
    
    args <- list(FACILITY_ID = FACILITY_ID, REPORTING_YEAR = REPORTING_YEAR, ESTIMATED_YR_OF_LNDFIL_CLOSURE = ESTIMATED_YR_OF_LNDFIL_CLOSURE, 
        FIRST_YR_LNDFIL_ACCEPTED_WASTE = FIRST_YR_LNDFIL_ACCEPTED_WASTE, LAST_YR_LNDFIL_ACCEPTED_WASTE = LAST_YR_LNDFIL_ACCEPTED_WASTE, 
        LEACHATE_RECIRCULATION_FREQ = LEACHATE_RECIRCULATION_FREQ, IS_LANDFILL_OPEN = IS_LANDFILL_OPEN, 
        DOES_LNDFIL_HAVE_GAS_CLCT = DOES_LNDFIL_HAVE_GAS_CLCT, LEACHATE_RECIRCULATION_USED = LEACHATE_RECIRCULATION_USED, 
        PASSIVE_VENTS_OR_FLARES = PASSIVE_VENTS_OR_FLARES, LANDFILL_CAPACITY = LANDFILL_CAPACITY, 
        SCALES_PRESENT = SCALES_PRESENT, LNDFIL_SURFACE_CONTAINING_WSTE = LNDFIL_SURFACE_CONTAINING_WSTE, 
        ANNUAL_MODELED_CH4_GENERATION = ANNUAL_MODELED_CH4_GENERATION, FIRST_YEAR_EMISSIONS_REPORTING = FIRST_YEAR_EMISSIONS_REPORTING, 
        FACILITY_NAME = FACILITY_NAME, ANNUAL_MCF_VALUE = ANNUAL_MCF_VALUE, IS_MCF_VALUE_DEFAULT_INDICATOR = IS_MCF_VALUE_DEFAULT_INDICATOR, 
        METHANE_FRAC_DETER_ANNUAL_VALU = METHANE_FRAC_DETER_ANNUAL_VALU, METHANE_FRACTION_DETER_METHOD = METHANE_FRACTION_DETER_METHOD)
    ret <- envir_get("hh_landfill_info", args)
    
    ret
} 
