#' Retrieve w atmospheric tanks data from ghg database
#' 
#' @param FACILITY_ID e.g. '1000355'. See Details.
#' @param REPORTING_YEAR e.g. '2014'. See Details.
#' @param FACILITY_NAME e.g. '#540 BONANZA CREEK ENERGY - DENVER BASIN'. See Details.
#' @param INDUSTRY_SEGMENT e.g. 'ONSHORE PETROLEUM AND NATURAL GAS PRODUCTION [98.230(A)(2)]'. See Details.
#' @param ATMOS_TANKS_TOTAL_CO2_EMM e.g. '4730.8'. See Details.
#' @param ATMOS_TANKS_TOTAL_CH4_EMM_CO2E e.g. '1204.8'. See Details.
#' @param ATMOS_TANKS_TOTAL_N2O_EMM_CO2E e.g. '2.4'. See Details.
#' @param ATMOS_TANKS_TOTAL_GHG_EMM_CO2E e.g. '5938'. See Details.
#' @param DID_FAC_HAVE_GAS_FRM_PRODU_OIL e.g. 'YES'. See Details.
#' @param BAMM_INDICATOR_ATMOS_TANKS e.g. 'NO'. See Details.
#' @param BAMM_DESCRIPTION_ATMOS_TANKS e.g. 'NA'. See Details.
#' @param SUB_INDICATOR_ATMOS_TANKS e.g. 'NO'. See Details.
#' @param CAL_METH_FIVE_PROD_FRAC_VAPREC e.g. '0.001'. See Details.
#' @param CALC_METH_FIVE_PROD_FRAC_FLRNG e.g. '0.9989'. See Details.
#' @param CALC_METH_FIVE_TANKS_WELLPADS e.g. '474'. See Details.
#' @param IMPROP_FUNC_DUMP_WELLHD_SEP_CT e.g. '0'. See Details.
#' @export

ghg_w_atmospheric_tanks <- function(FACILITY_ID = NULL, REPORTING_YEAR = NULL, FACILITY_NAME = NULL, 
    INDUSTRY_SEGMENT = NULL, ATMOS_TANKS_TOTAL_CO2_EMM = NULL, ATMOS_TANKS_TOTAL_CH4_EMM_CO2E = NULL, 
    ATMOS_TANKS_TOTAL_N2O_EMM_CO2E = NULL, ATMOS_TANKS_TOTAL_GHG_EMM_CO2E = NULL, 
    DID_FAC_HAVE_GAS_FRM_PRODU_OIL = NULL, BAMM_INDICATOR_ATMOS_TANKS = NULL, BAMM_DESCRIPTION_ATMOS_TANKS = NULL, 
    SUB_INDICATOR_ATMOS_TANKS = NULL, CAL_METH_FIVE_PROD_FRAC_VAPREC = NULL, CALC_METH_FIVE_PROD_FRAC_FLRNG = NULL, 
    CALC_METH_FIVE_TANKS_WELLPADS = NULL, IMPROP_FUNC_DUMP_WELLHD_SEP_CT = NULL) {
    
    args <- list(FACILITY_ID = FACILITY_ID, REPORTING_YEAR = REPORTING_YEAR, FACILITY_NAME = FACILITY_NAME, 
        INDUSTRY_SEGMENT = INDUSTRY_SEGMENT, ATMOS_TANKS_TOTAL_CO2_EMM = ATMOS_TANKS_TOTAL_CO2_EMM, 
        ATMOS_TANKS_TOTAL_CH4_EMM_CO2E = ATMOS_TANKS_TOTAL_CH4_EMM_CO2E, ATMOS_TANKS_TOTAL_N2O_EMM_CO2E = ATMOS_TANKS_TOTAL_N2O_EMM_CO2E, 
        ATMOS_TANKS_TOTAL_GHG_EMM_CO2E = ATMOS_TANKS_TOTAL_GHG_EMM_CO2E, DID_FAC_HAVE_GAS_FRM_PRODU_OIL = DID_FAC_HAVE_GAS_FRM_PRODU_OIL, 
        BAMM_INDICATOR_ATMOS_TANKS = BAMM_INDICATOR_ATMOS_TANKS, BAMM_DESCRIPTION_ATMOS_TANKS = BAMM_DESCRIPTION_ATMOS_TANKS, 
        SUB_INDICATOR_ATMOS_TANKS = SUB_INDICATOR_ATMOS_TANKS, CAL_METH_FIVE_PROD_FRAC_VAPREC = CAL_METH_FIVE_PROD_FRAC_VAPREC, 
        CALC_METH_FIVE_PROD_FRAC_FLRNG = CALC_METH_FIVE_PROD_FRAC_FLRNG, CALC_METH_FIVE_TANKS_WELLPADS = CALC_METH_FIVE_TANKS_WELLPADS, 
        IMPROP_FUNC_DUMP_WELLHD_SEP_CT = IMPROP_FUNC_DUMP_WELLHD_SEP_CT)
    ret <- envir_get(w_atmospheric_tanks, args)
    
    ret
} 
