#' Retrieve w centrifugal cmps onshore data from ghg database
#' 
#' @param FACILITY_ID e.g. '1000064'. See Details.
#' @param REPORTING_YEAR e.g. '2013'. See Details.
#' @param CENF_CMP_ONSH_TOT_CH4_EM_CO2E e.g. 'NA'. See Details.
#' @param INDUSTRY_SEGMENT e.g. 'ONSHORE NATURAL GAS PROCESSING [98.230(A)(3)]'. See Details.
#' @param CENF_CMPS_ONSHR_TOT_CO2_EMM e.g. 'NA'. See Details.
#' @param FACILITY_NAME e.g. 'LONE STAR GAS LIQUIDS'. See Details.
#' @param CENF_CMPS_GRTOT_N2O_EMM_CO2E e.g. '0'. See Details.
#' @param CENF_CMPS_GRTOT_GHG_EMM_CO2E e.g. '0'. See Details.
#' @param DOES_FAC_HAVE_CENTG_COMPRESSOR e.g. 'YES'. See Details.
#' @param BAMM_INDICATOR_COMPRESSORS e.g. 'NO'. See Details.
#' @param BAMM_DESCRIPTION_COMPRESSORS e.g. 'NA'. See Details.
#' @param SUB_IND_CENTRIFUGAL_COMPRESSOR e.g. 'NO'. See Details.
#' @param CENF_CMPS_GRTOTAL_CO2_EMM e.g. '0'. See Details.
#' @param CENF_CMPS_GRTOT_CH4_EMM_CO2E e.g. '0'. See Details.
#' @param COMPRESSOR_COUNT e.g. 'NA'. See Details.
#' @export

ghg_w_centrifugal_cmps_onshore <- function(FACILITY_ID = NULL, REPORTING_YEAR = NULL, 
    CENF_CMP_ONSH_TOT_CH4_EM_CO2E = NULL, INDUSTRY_SEGMENT = NULL, CENF_CMPS_ONSHR_TOT_CO2_EMM = NULL, 
    FACILITY_NAME = NULL, CENF_CMPS_GRTOT_N2O_EMM_CO2E = NULL, CENF_CMPS_GRTOT_GHG_EMM_CO2E = NULL, 
    DOES_FAC_HAVE_CENTG_COMPRESSOR = NULL, BAMM_INDICATOR_COMPRESSORS = NULL, BAMM_DESCRIPTION_COMPRESSORS = NULL, 
    SUB_IND_CENTRIFUGAL_COMPRESSOR = NULL, CENF_CMPS_GRTOTAL_CO2_EMM = NULL, CENF_CMPS_GRTOT_CH4_EMM_CO2E = NULL, 
    COMPRESSOR_COUNT = NULL) {
    
    args <- list(FACILITY_ID = FACILITY_ID, REPORTING_YEAR = REPORTING_YEAR, CENF_CMP_ONSH_TOT_CH4_EM_CO2E = CENF_CMP_ONSH_TOT_CH4_EM_CO2E, 
        INDUSTRY_SEGMENT = INDUSTRY_SEGMENT, CENF_CMPS_ONSHR_TOT_CO2_EMM = CENF_CMPS_ONSHR_TOT_CO2_EMM, 
        FACILITY_NAME = FACILITY_NAME, CENF_CMPS_GRTOT_N2O_EMM_CO2E = CENF_CMPS_GRTOT_N2O_EMM_CO2E, 
        CENF_CMPS_GRTOT_GHG_EMM_CO2E = CENF_CMPS_GRTOT_GHG_EMM_CO2E, DOES_FAC_HAVE_CENTG_COMPRESSOR = DOES_FAC_HAVE_CENTG_COMPRESSOR, 
        BAMM_INDICATOR_COMPRESSORS = BAMM_INDICATOR_COMPRESSORS, BAMM_DESCRIPTION_COMPRESSORS = BAMM_DESCRIPTION_COMPRESSORS, 
        SUB_IND_CENTRIFUGAL_COMPRESSOR = SUB_IND_CENTRIFUGAL_COMPRESSOR, CENF_CMPS_GRTOTAL_CO2_EMM = CENF_CMPS_GRTOTAL_CO2_EMM, 
        CENF_CMPS_GRTOT_CH4_EMM_CO2E = CENF_CMPS_GRTOT_CH4_EMM_CO2E, COMPRESSOR_COUNT = COMPRESSOR_COUNT)
    ret <- envir_get("w_centrifugal_cmps_onshore", args)
    
    ret
} 
