#' Retrieve ss eq ss5 data from ghg database
#' 
#' @param FACILITY_ID e.g. '1000039'. See Details.
#' @param REPORTING_YEAR e.g. '2011'. See Details.
#' @param FACILITY_NAME e.g. 'Alstom Grid Inc'. See Details.
#' @param TOTAL_EMIT_PERFLUOROCYCLOPROPA e.g. 'NA'. See Details.
#' @param TOTAL_EMIT_FLUOROCYCLOBUTANE e.g. '0'. See Details.
#' @param TOTAL_EMIT_PERFLUOROETHANE e.g. 'NA'. See Details.
#' @param TOTAL_EMIT_PERFLUOROMETHANE e.g. 'NA'. See Details.
#' @param TOTAL_EMIT_PERFLUOROPROPANE e.g. 'NA'. See Details.
#' @param TOTAL_EMIT_PERFLUOROBUTANE e.g. 'NA'. See Details.
#' @param TOTAL_EMIT_PERFLUOROPENTANE e.g. 'NA'. See Details.
#' @param TOTAL_EMIT_PERFLUOROHEXANE e.g. 'NA'. See Details.
#' @param TOTAL_EMITTED_PFC_9_1_18 e.g. 'NA'. See Details.
#' @param TOTAL_EMITTED_SF6 e.g. 'NA'. See Details.
#' @export

ghg_ss_eq_ss5 <- function(FACILITY_ID = NULL, REPORTING_YEAR = NULL, FACILITY_NAME = NULL, 
    TOTAL_EMIT_PERFLUOROCYCLOPROPA = NULL, TOTAL_EMIT_FLUOROCYCLOBUTANE = NULL, TOTAL_EMIT_PERFLUOROETHANE = NULL, 
    TOTAL_EMIT_PERFLUOROMETHANE = NULL, TOTAL_EMIT_PERFLUOROPROPANE = NULL, TOTAL_EMIT_PERFLUOROBUTANE = NULL, 
    TOTAL_EMIT_PERFLUOROPENTANE = NULL, TOTAL_EMIT_PERFLUOROHEXANE = NULL, TOTAL_EMITTED_PFC_9_1_18 = NULL, 
    TOTAL_EMITTED_SF6 = NULL) {
    
    args <- list(FACILITY_ID = FACILITY_ID, REPORTING_YEAR = REPORTING_YEAR, FACILITY_NAME = FACILITY_NAME, 
        TOTAL_EMIT_PERFLUOROCYCLOPROPA = TOTAL_EMIT_PERFLUOROCYCLOPROPA, TOTAL_EMIT_FLUOROCYCLOBUTANE = TOTAL_EMIT_FLUOROCYCLOBUTANE, 
        TOTAL_EMIT_PERFLUOROETHANE = TOTAL_EMIT_PERFLUOROETHANE, TOTAL_EMIT_PERFLUOROMETHANE = TOTAL_EMIT_PERFLUOROMETHANE, 
        TOTAL_EMIT_PERFLUOROPROPANE = TOTAL_EMIT_PERFLUOROPROPANE, TOTAL_EMIT_PERFLUOROBUTANE = TOTAL_EMIT_PERFLUOROBUTANE, 
        TOTAL_EMIT_PERFLUOROPENTANE = TOTAL_EMIT_PERFLUOROPENTANE, TOTAL_EMIT_PERFLUOROHEXANE = TOTAL_EMIT_PERFLUOROHEXANE, 
        TOTAL_EMITTED_PFC_9_1_18 = TOTAL_EMITTED_PFC_9_1_18, TOTAL_EMITTED_SF6 = TOTAL_EMITTED_SF6)
    ret <- envir_get(ss_eq_ss5, args)
    
    ret
} 
