#' Retrieve n cems details data from ghg database
#' 
#' @param FACILITY_ID e.g. '1004085'. See Details.
#' @param REPORTING_YEAR e.g. '2012'. See Details.
#' @param CML_NAME e.g. 'ES-67 Glass Melting Furnace Poll Control'. See Details.
#' @param CML_DESCRIPTION e.g. 'Idled in December 2008; but remains covered by Title V Air Permit'. See Details.
#' @param CML_CONFIGURATION_TYPE e.g. 'Single process/process unit exhausts to dedicated stack'. See Details.
#' @param CEMS_BIOGENIC_CO2_EMISSIONS e.g. '0'. See Details.
#' @param CEMS_NON_BIOGENIC_CO2_EMISSION e.g. '0'. See Details.
#' @param CEMS_ANNUAL_CO2_EMISSIONS e.g. '0'. See Details.
#' @param CEMS_CH4_EMISSIONS e.g. '0'. See Details.
#' @param CEMS_N2O_EMISSIONS e.g. '0'. See Details.
#' @param CML_TOTAL_OPERATING_HOURS e.g. '0'. See Details.
#' @param TIER4_SUB_OPER_HRS_CO2_CONC e.g. '0'. See Details.
#' @param TIER4_SUB_OPER_HRS_GAS_FLOW_RT e.g. '0'. See Details.
#' @param TIER4_SUB_OPER_HRS_MOIST_CONT e.g. '0'. See Details.
#' @param CEMS_CO2_COMBUSTION_EMISSIONS e.g. 'NA'. See Details.
#' @param CEMS_METHODOLOGY_START_DATE e.g. '2012-01-01'. See Details.
#' @param CEMS_METHODOLOGY_END_DATE e.g. '2012-12-31'. See Details.
#' @param CEMS_FUEL e.g. 'Natural Gas Fired with Propane Backup'. See Details.
#' @param CEMS_QUARTER_NAME e.g. 'Third Quarter'. See Details.
#' @param CEMS_CO2_EMISSIONS_BY_QUARTER e.g. '0'. See Details.
#' @param CEMS_GLASS_FURNACE_NAME e.g. 'ES67 Glass Melting Furnace #2'. See Details.
#' @export

ghg_n_cems_details <- function(FACILITY_ID = NULL, REPORTING_YEAR = NULL, CML_NAME = NULL, 
    CML_DESCRIPTION = NULL, CML_CONFIGURATION_TYPE = NULL, CEMS_BIOGENIC_CO2_EMISSIONS = NULL, 
    CEMS_NON_BIOGENIC_CO2_EMISSION = NULL, CEMS_ANNUAL_CO2_EMISSIONS = NULL, CEMS_CH4_EMISSIONS = NULL, 
    CEMS_N2O_EMISSIONS = NULL, CML_TOTAL_OPERATING_HOURS = NULL, TIER4_SUB_OPER_HRS_CO2_CONC = NULL, 
    TIER4_SUB_OPER_HRS_GAS_FLOW_RT = NULL, TIER4_SUB_OPER_HRS_MOIST_CONT = NULL, 
    CEMS_CO2_COMBUSTION_EMISSIONS = NULL, CEMS_METHODOLOGY_START_DATE = NULL, CEMS_METHODOLOGY_END_DATE = NULL, 
    CEMS_FUEL = NULL, CEMS_QUARTER_NAME = NULL, CEMS_CO2_EMISSIONS_BY_QUARTER = NULL, 
    CEMS_GLASS_FURNACE_NAME = NULL) {
    
    args <- list(FACILITY_ID = FACILITY_ID, REPORTING_YEAR = REPORTING_YEAR, CML_NAME = CML_NAME, 
        CML_DESCRIPTION = CML_DESCRIPTION, CML_CONFIGURATION_TYPE = CML_CONFIGURATION_TYPE, 
        CEMS_BIOGENIC_CO2_EMISSIONS = CEMS_BIOGENIC_CO2_EMISSIONS, CEMS_NON_BIOGENIC_CO2_EMISSION = CEMS_NON_BIOGENIC_CO2_EMISSION, 
        CEMS_ANNUAL_CO2_EMISSIONS = CEMS_ANNUAL_CO2_EMISSIONS, CEMS_CH4_EMISSIONS = CEMS_CH4_EMISSIONS, 
        CEMS_N2O_EMISSIONS = CEMS_N2O_EMISSIONS, CML_TOTAL_OPERATING_HOURS = CML_TOTAL_OPERATING_HOURS, 
        TIER4_SUB_OPER_HRS_CO2_CONC = TIER4_SUB_OPER_HRS_CO2_CONC, TIER4_SUB_OPER_HRS_GAS_FLOW_RT = TIER4_SUB_OPER_HRS_GAS_FLOW_RT, 
        TIER4_SUB_OPER_HRS_MOIST_CONT = TIER4_SUB_OPER_HRS_MOIST_CONT, CEMS_CO2_COMBUSTION_EMISSIONS = CEMS_CO2_COMBUSTION_EMISSIONS, 
        CEMS_METHODOLOGY_START_DATE = CEMS_METHODOLOGY_START_DATE, CEMS_METHODOLOGY_END_DATE = CEMS_METHODOLOGY_END_DATE, 
        CEMS_FUEL = CEMS_FUEL, CEMS_QUARTER_NAME = CEMS_QUARTER_NAME, CEMS_CO2_EMISSIONS_BY_QUARTER = CEMS_CO2_EMISSIONS_BY_QUARTER, 
        CEMS_GLASS_FURNACE_NAME = CEMS_GLASS_FURNACE_NAME)
    ret <- envir_get("n_cems_details", args)
    
    ret
} 
