#' Retrieve w other emissions equip leaks data from ghg database
#' 
#' @param FACILITY_ID e.g. '1000011'. See Details.
#' @param REPORTING_YEAR e.g. '2011'. See Details.
#' @param BAMM_DESCRIPTION_EQUIP_LEAKS e.g. 'NO'. See Details.
#' @param BAMM_INDICATOR_EQUIP_LEAKS e.g. 'NO'. See Details.
#' @param EQUIP_LEAKS_TOTAL_GHG_EMM_CO2E e.g. '0'. See Details.
#' @param EQUIP_LEAKS_N2O_EMISSIONS_CO2E e.g. 'NA'. See Details.
#' @param EQUIP_LEAKS_CH4_EMISSIONS_CO2E e.g. '0'. See Details.
#' @param SUB_INDICATOR_EQUIP_LEAKS e.g. 'NO'. See Details.
#' @param INDUSTRY_SEGMENT e.g. 'NATURAL GAS DISTRIBUTION [98.230(A)(8)]'. See Details.
#' @param FACILITY_NAME e.g. 'CENTRAL HUDSON GAS AND ELECTRIC CORPORATION'. See Details.
#' @param EQUIP_LEAKS_CO2_EMISSIONS e.g. '0'. See Details.
#' @param DOES_FAC_HAVE_EQUIPMENT_LEAKS e.g. 'YES'. See Details.
#' @export

ghg_w_other_emissions_equip_leaks <- function(FACILITY_ID = NULL, REPORTING_YEAR = NULL, 
    BAMM_DESCRIPTION_EQUIP_LEAKS = NULL, BAMM_INDICATOR_EQUIP_LEAKS = NULL, EQUIP_LEAKS_TOTAL_GHG_EMM_CO2E = NULL, 
    EQUIP_LEAKS_N2O_EMISSIONS_CO2E = NULL, EQUIP_LEAKS_CH4_EMISSIONS_CO2E = NULL, 
    SUB_INDICATOR_EQUIP_LEAKS = NULL, INDUSTRY_SEGMENT = NULL, FACILITY_NAME = NULL, 
    EQUIP_LEAKS_CO2_EMISSIONS = NULL, DOES_FAC_HAVE_EQUIPMENT_LEAKS = NULL) {
    
    args <- list(FACILITY_ID = FACILITY_ID, REPORTING_YEAR = REPORTING_YEAR, BAMM_DESCRIPTION_EQUIP_LEAKS = BAMM_DESCRIPTION_EQUIP_LEAKS, 
        BAMM_INDICATOR_EQUIP_LEAKS = BAMM_INDICATOR_EQUIP_LEAKS, EQUIP_LEAKS_TOTAL_GHG_EMM_CO2E = EQUIP_LEAKS_TOTAL_GHG_EMM_CO2E, 
        EQUIP_LEAKS_N2O_EMISSIONS_CO2E = EQUIP_LEAKS_N2O_EMISSIONS_CO2E, EQUIP_LEAKS_CH4_EMISSIONS_CO2E = EQUIP_LEAKS_CH4_EMISSIONS_CO2E, 
        SUB_INDICATOR_EQUIP_LEAKS = SUB_INDICATOR_EQUIP_LEAKS, INDUSTRY_SEGMENT = INDUSTRY_SEGMENT, 
        FACILITY_NAME = FACILITY_NAME, EQUIP_LEAKS_CO2_EMISSIONS = EQUIP_LEAKS_CO2_EMISSIONS, 
        DOES_FAC_HAVE_EQUIPMENT_LEAKS = DOES_FAC_HAVE_EQUIPMENT_LEAKS)
    ret <- envir_get(w_other_emissions_equip_leaks, args)
    
    ret
} 
