#' Retrieve nn ldc details data from ghg database
#' 
#' @param FACILITY_ID e.g. '1000008'. See Details.
#' @param REPORTING_YEAR e.g. '2010'. See Details.
#' @param GAS_DELIV_OTHR_LDCS_DWNS_PIPE e.g. '0'. See Details.
#' @param OTHINDSTRYSTDFORVOL e.g. 'NA'. See Details.
#' @param LDC_NN1_CO2 e.g. 'NA'. See Details.
#' @param LDC_NN2_CO2 e.g. '391676.1'. See Details.
#' @param NN3_CO2 e.g. '0'. See Details.
#' @param NN4_CO2 e.g. '86036'. See Details.
#' @param NN5_CO2 e.g. '0'. See Details.
#' @param NN3_EF_INDUSTRY_STNDRD e.g. 'NA'. See Details.
#' @param NN3_EF_OTHER_INDUSTRY_STNDRD e.g. 'NA'. See Details.
#' @param NN4_EF_INDUSTRY_STNDRD e.g. 'NA'. See Details.
#' @param NN4_EF_OTHER_INDUSTRY_STNDRD e.g. 'NA'. See Details.
#' @param NN5_EF_INDUSTRY_STNDRD e.g. 'NA'. See Details.
#' @param NN5_EF_OTHER_INDUSTRY_STNDRD e.g. 'NA'. See Details.
#' @param LDC_NN1_HHV_INDUSTRY_STNDRD e.g. 'NA'. See Details.
#' @param LDC_NN1_HHV_OTH_INDUSTRY_STD e.g. 'NA'. See Details.
#' @param LDC_NN1_EF_INDUSTRY_STNDRD e.g. 'NA'. See Details.
#' @param LDC_NN1_EF_OTH_INDUSTRY_STD e.g. 'NA'. See Details.
#' @param LDC_NN2_EF_INDUSTRY_STNDRD e.g. 'NA'. See Details.
#' @param LDC_NN2_EF_OTH_INDUSTRY_STD e.g. 'NA'. See Details.
#' @param FACILITY_NAME e.g. 'St. Lawrence Gas Co., Inc.'. See Details.
#' @param CITY_GATE_VOLUME_INDUSTRY_STND e.g. 'Industry standard practices'. See Details.
#' @param GAS_STORED e.g. '0'. See Details.
#' @param GASBP_CITYGATE_NO_DAYS_SUBDATA e.g. 'NA'. See Details.
#' @param LDC_NN5B_CO2_MASS_QUANTITY e.g. 'NA'. See Details.
#' @param LDC_NN5A_CO2_MASS_QUANTITY e.g. 'NA'. See Details.
#' @param ANNVOLGASRMVDFRMSTRG e.g. 'NA'. See Details.
#' @export

ghg_nn_ldc_details <- function(FACILITY_ID = NULL, REPORTING_YEAR = NULL, GAS_DELIV_OTHR_LDCS_DWNS_PIPE = NULL, 
    OTHINDSTRYSTDFORVOL = NULL, LDC_NN1_CO2 = NULL, LDC_NN2_CO2 = NULL, NN3_CO2 = NULL, 
    NN4_CO2 = NULL, NN5_CO2 = NULL, NN3_EF_INDUSTRY_STNDRD = NULL, NN3_EF_OTHER_INDUSTRY_STNDRD = NULL, 
    NN4_EF_INDUSTRY_STNDRD = NULL, NN4_EF_OTHER_INDUSTRY_STNDRD = NULL, NN5_EF_INDUSTRY_STNDRD = NULL, 
    NN5_EF_OTHER_INDUSTRY_STNDRD = NULL, LDC_NN1_HHV_INDUSTRY_STNDRD = NULL, LDC_NN1_HHV_OTH_INDUSTRY_STD = NULL, 
    LDC_NN1_EF_INDUSTRY_STNDRD = NULL, LDC_NN1_EF_OTH_INDUSTRY_STD = NULL, LDC_NN2_EF_INDUSTRY_STNDRD = NULL, 
    LDC_NN2_EF_OTH_INDUSTRY_STD = NULL, FACILITY_NAME = NULL, CITY_GATE_VOLUME_INDUSTRY_STND = NULL, 
    GAS_STORED = NULL, GASBP_CITYGATE_NO_DAYS_SUBDATA = NULL, LDC_NN5B_CO2_MASS_QUANTITY = NULL, 
    LDC_NN5A_CO2_MASS_QUANTITY = NULL, ANNVOLGASRMVDFRMSTRG = NULL) {
    
    args <- list(FACILITY_ID = FACILITY_ID, REPORTING_YEAR = REPORTING_YEAR, GAS_DELIV_OTHR_LDCS_DWNS_PIPE = GAS_DELIV_OTHR_LDCS_DWNS_PIPE, 
        OTHINDSTRYSTDFORVOL = OTHINDSTRYSTDFORVOL, LDC_NN1_CO2 = LDC_NN1_CO2, LDC_NN2_CO2 = LDC_NN2_CO2, 
        NN3_CO2 = NN3_CO2, NN4_CO2 = NN4_CO2, NN5_CO2 = NN5_CO2, NN3_EF_INDUSTRY_STNDRD = NN3_EF_INDUSTRY_STNDRD, 
        NN3_EF_OTHER_INDUSTRY_STNDRD = NN3_EF_OTHER_INDUSTRY_STNDRD, NN4_EF_INDUSTRY_STNDRD = NN4_EF_INDUSTRY_STNDRD, 
        NN4_EF_OTHER_INDUSTRY_STNDRD = NN4_EF_OTHER_INDUSTRY_STNDRD, NN5_EF_INDUSTRY_STNDRD = NN5_EF_INDUSTRY_STNDRD, 
        NN5_EF_OTHER_INDUSTRY_STNDRD = NN5_EF_OTHER_INDUSTRY_STNDRD, LDC_NN1_HHV_INDUSTRY_STNDRD = LDC_NN1_HHV_INDUSTRY_STNDRD, 
        LDC_NN1_HHV_OTH_INDUSTRY_STD = LDC_NN1_HHV_OTH_INDUSTRY_STD, LDC_NN1_EF_INDUSTRY_STNDRD = LDC_NN1_EF_INDUSTRY_STNDRD, 
        LDC_NN1_EF_OTH_INDUSTRY_STD = LDC_NN1_EF_OTH_INDUSTRY_STD, LDC_NN2_EF_INDUSTRY_STNDRD = LDC_NN2_EF_INDUSTRY_STNDRD, 
        LDC_NN2_EF_OTH_INDUSTRY_STD = LDC_NN2_EF_OTH_INDUSTRY_STD, FACILITY_NAME = FACILITY_NAME, 
        CITY_GATE_VOLUME_INDUSTRY_STND = CITY_GATE_VOLUME_INDUSTRY_STND, GAS_STORED = GAS_STORED, 
        GASBP_CITYGATE_NO_DAYS_SUBDATA = GASBP_CITYGATE_NO_DAYS_SUBDATA, LDC_NN5B_CO2_MASS_QUANTITY = LDC_NN5B_CO2_MASS_QUANTITY, 
        LDC_NN5A_CO2_MASS_QUANTITY = LDC_NN5A_CO2_MASS_QUANTITY, ANNVOLGASRMVDFRMSTRG = ANNVOLGASRMVDFRMSTRG)
    ret <- envir_get("nn_ldc_details", args)
    
    ret
} 
