#' Retrieve ss ghg disbursement data from ghg database
#' 
#' @param FACILITY_ID e.g. '1000039'. See Details.
#' @param REPORTING_YEAR e.g. '2013'. See Details.
#' @param FACILITY_NAME e.g. 'Alstom Grid Inc'. See Details.
#' @param GAS_NAME e.g. 'Sulfur hexafluoride'. See Details.
#' @param DISBURSEMENT_CALCULATED e.g. '79730.33'. See Details.
#' @param DISBURSEMENT_OVERRIDE e.g. 'N'. See Details.
#' @param LBS_CONTAINED_NEW_EQUIP_DELIV e.g. '9650.5'. See Details.
#' @param LBS_DELIV_EQUIP_IN_CONTAINERS e.g. '69349'. See Details.
#' @param LBS_OFFSITE_RECYCLING e.g. '0'. See Details.
#' @param LBS_RETURNED_TO_SUPPLIERS e.g. '730.83'. See Details.
#' @param LBS_SENT_OFFSITE_DESTRUCTION e.g. '0'. See Details.
#' @export

ghg_ss_ghg_disbursement <- function(FACILITY_ID = NULL, REPORTING_YEAR = NULL, FACILITY_NAME = NULL, 
    GAS_NAME = NULL, DISBURSEMENT_CALCULATED = NULL, DISBURSEMENT_OVERRIDE = NULL, 
    LBS_CONTAINED_NEW_EQUIP_DELIV = NULL, LBS_DELIV_EQUIP_IN_CONTAINERS = NULL, LBS_OFFSITE_RECYCLING = NULL, 
    LBS_RETURNED_TO_SUPPLIERS = NULL, LBS_SENT_OFFSITE_DESTRUCTION = NULL) {
    
    args <- list(FACILITY_ID = FACILITY_ID, REPORTING_YEAR = REPORTING_YEAR, FACILITY_NAME = FACILITY_NAME, 
        GAS_NAME = GAS_NAME, DISBURSEMENT_CALCULATED = DISBURSEMENT_CALCULATED, DISBURSEMENT_OVERRIDE = DISBURSEMENT_OVERRIDE, 
        LBS_CONTAINED_NEW_EQUIP_DELIV = LBS_CONTAINED_NEW_EQUIP_DELIV, LBS_DELIV_EQUIP_IN_CONTAINERS = LBS_DELIV_EQUIP_IN_CONTAINERS, 
        LBS_OFFSITE_RECYCLING = LBS_OFFSITE_RECYCLING, LBS_RETURNED_TO_SUPPLIERS = LBS_RETURNED_TO_SUPPLIERS, 
        LBS_SENT_OFFSITE_DESTRUCTION = LBS_SENT_OFFSITE_DESTRUCTION)
    ret <- envir_get("ss_ghg_disbursement", args)
    
    ret
} 
