#' Retrieve hh hist waste qty method data from ghg database
#' 
#' @param FACILITY_ID e.g. '1000010'. See Details.
#' @param REPORTING_YEAR e.g. '2013'. See Details.
#' @param FACILITY_NAME e.g. 'SANTA ROSA CENTRAL LANDFILL'. See Details.
#' @param SCALES_USED_FOR_HIST_WSTE_QTY e.g. 'Y'. See Details.
#' @param TIPPING_RCPT_USED_HIST_WST_QTY e.g. 'N'. See Details.
#' @param TIPNG_RCP_HIST_WSTE_QTY_STR_YR e.g. 'NA'. See Details.
#' @param TIPNG_RCP_HIST_WSTE_QTY_END_YR e.g. 'NA'. See Details.
#' @param HIST_WASTE_QUANTITY_EST_METHOD e.g. 'METHOD #1:  ASSUME ALL PRIOR YEAR’S WASTE DISPOSAL QUANTITIES ARE THE SAME AS THE WASTE QUANTITY IN '. See Details.
#' @param HIST_WSTE_QTY_EST_MTHD_STRT_YR e.g. '1978'. See Details.
#' @param HIST_WSTE_QTY_EST_MTHD_END_YR e.g. '1997'. See Details.
#' @param HIST_WSTE_QTY_EST_MTHD_RSN_USE e.g. 'BEST FIT FOR AVAILABLE INFORMATION'. See Details.
#' @param LANDFILL_CAPACITY_IN_MTHD_3 e.g. 'NA'. See Details.
#' @param WKG_CAP_HIST_WSTE_QTY_START_YR e.g. 'NA'. See Details.
#' @param WKG_CAP_HIST_WSTE_QTY_END_YR e.g. 'NA'. See Details.
#' @param IS_WORKING_CAPACITY_USED_IND e.g. 'N'. See Details.
#' @param YEAR_FOR_METHOD_2 e.g. 'NA'. See Details.
#' @param EST_POP_SERVD_BY_LANDFL_MTHD_2 e.g. 'NA'. See Details.
#' @export

ghg_hh_hist_waste_qty_method <- function(FACILITY_ID = NULL, REPORTING_YEAR = NULL, 
    FACILITY_NAME = NULL, SCALES_USED_FOR_HIST_WSTE_QTY = NULL, TIPPING_RCPT_USED_HIST_WST_QTY = NULL, 
    TIPNG_RCP_HIST_WSTE_QTY_STR_YR = NULL, TIPNG_RCP_HIST_WSTE_QTY_END_YR = NULL, 
    HIST_WASTE_QUANTITY_EST_METHOD = NULL, HIST_WSTE_QTY_EST_MTHD_STRT_YR = NULL, 
    HIST_WSTE_QTY_EST_MTHD_END_YR = NULL, HIST_WSTE_QTY_EST_MTHD_RSN_USE = NULL, 
    LANDFILL_CAPACITY_IN_MTHD_3 = NULL, WKG_CAP_HIST_WSTE_QTY_START_YR = NULL, WKG_CAP_HIST_WSTE_QTY_END_YR = NULL, 
    IS_WORKING_CAPACITY_USED_IND = NULL, YEAR_FOR_METHOD_2 = NULL, EST_POP_SERVD_BY_LANDFL_MTHD_2 = NULL) {
    
    args <- list(FACILITY_ID = FACILITY_ID, REPORTING_YEAR = REPORTING_YEAR, FACILITY_NAME = FACILITY_NAME, 
        SCALES_USED_FOR_HIST_WSTE_QTY = SCALES_USED_FOR_HIST_WSTE_QTY, TIPPING_RCPT_USED_HIST_WST_QTY = TIPPING_RCPT_USED_HIST_WST_QTY, 
        TIPNG_RCP_HIST_WSTE_QTY_STR_YR = TIPNG_RCP_HIST_WSTE_QTY_STR_YR, TIPNG_RCP_HIST_WSTE_QTY_END_YR = TIPNG_RCP_HIST_WSTE_QTY_END_YR, 
        HIST_WASTE_QUANTITY_EST_METHOD = HIST_WASTE_QUANTITY_EST_METHOD, HIST_WSTE_QTY_EST_MTHD_STRT_YR = HIST_WSTE_QTY_EST_MTHD_STRT_YR, 
        HIST_WSTE_QTY_EST_MTHD_END_YR = HIST_WSTE_QTY_EST_MTHD_END_YR, HIST_WSTE_QTY_EST_MTHD_RSN_USE = HIST_WSTE_QTY_EST_MTHD_RSN_USE, 
        LANDFILL_CAPACITY_IN_MTHD_3 = LANDFILL_CAPACITY_IN_MTHD_3, WKG_CAP_HIST_WSTE_QTY_START_YR = WKG_CAP_HIST_WSTE_QTY_START_YR, 
        WKG_CAP_HIST_WSTE_QTY_END_YR = WKG_CAP_HIST_WSTE_QTY_END_YR, IS_WORKING_CAPACITY_USED_IND = IS_WORKING_CAPACITY_USED_IND, 
        YEAR_FOR_METHOD_2 = YEAR_FOR_METHOD_2, EST_POP_SERVD_BY_LANDFL_MTHD_2 = EST_POP_SERVD_BY_LANDFL_MTHD_2)
    ret <- envir_get(hh_hist_waste_qty_method, args)
    
    ret
} 
