#' Retrieve y emissions by source data from ghg database
#' 
#' @param FACILITY_ID e.g. '1000025'. See Details.
#' @param REPORTING_YEAR e.g. '2012'. See Details.
#' @param FACILITY_NAME e.g. 'PLACID REFINING CO LLC - PORT ALLEN REFINERY'. See Details.
#' @param BLOWDOWN_CH4_EMISSIONS e.g. 'NA'. See Details.
#' @param EQUIP_LEAK_CH4_EMISSIONS e.g. '10.5'. See Details.
#' @param LOADINGOPS_CH4_EMISSIONS e.g. '0'. See Details.
#' @param UNSTABALIZEDCRUDE_CH4_EMISS e.g. 'NA'. See Details.
#' @param STORAGETANKS_CH4_EMISSIONS e.g. '0'. See Details.
#' @param SOUR_GAS_CO2_EMISSIONS e.g. 'NA'. See Details.
#' @param DELAYED_COKING_CH4_EMISSIONS e.g. '0'. See Details.
#' @export

ghg_y_emissions_by_source <- function(FACILITY_ID = NULL, REPORTING_YEAR = NULL, 
    FACILITY_NAME = NULL, BLOWDOWN_CH4_EMISSIONS = NULL, EQUIP_LEAK_CH4_EMISSIONS = NULL, 
    LOADINGOPS_CH4_EMISSIONS = NULL, UNSTABALIZEDCRUDE_CH4_EMISS = NULL, STORAGETANKS_CH4_EMISSIONS = NULL, 
    SOUR_GAS_CO2_EMISSIONS = NULL, DELAYED_COKING_CH4_EMISSIONS = NULL) {
    
    args <- list(FACILITY_ID = FACILITY_ID, REPORTING_YEAR = REPORTING_YEAR, FACILITY_NAME = FACILITY_NAME, 
        BLOWDOWN_CH4_EMISSIONS = BLOWDOWN_CH4_EMISSIONS, EQUIP_LEAK_CH4_EMISSIONS = EQUIP_LEAK_CH4_EMISSIONS, 
        LOADINGOPS_CH4_EMISSIONS = LOADINGOPS_CH4_EMISSIONS, UNSTABALIZEDCRUDE_CH4_EMISS = UNSTABALIZEDCRUDE_CH4_EMISS, 
        STORAGETANKS_CH4_EMISSIONS = STORAGETANKS_CH4_EMISSIONS, SOUR_GAS_CO2_EMISSIONS = SOUR_GAS_CO2_EMISSIONS, 
        DELAYED_COKING_CH4_EMISSIONS = DELAYED_COKING_CH4_EMISSIONS)
    ret <- envir_get(y_emissions_by_source, args)
    
    ret
} 
