#' Retrieve w well testing data from ghg database
#' 
#' @param FACILITY_ID e.g. '1000355'. See Details.
#' @param REPORTING_YEAR e.g. '2011'. See Details.
#' @param SUB_INDICATOR_WELL_TESTING e.g. 'NA'. See Details.
#' @param BAMM_DESCRIPTION_WELL_TESTING e.g. 'NA'. See Details.
#' @param BAMM_INDICATOR_WELL_TESTING e.g. 'NA'. See Details.
#' @param DID_FAC_PERFORM_WELL_TESTING e.g. 'NO'. See Details.
#' @param WELL_TEST_TOTAL_GHG_EMM_CO2E e.g. '0'. See Details.
#' @param WELL_TEST_TOTAL_N2O_EMM_CO2E e.g. '0'. See Details.
#' @param WELL_TEST_TOTAL_CO2_EMISSIONS e.g. '0'. See Details.
#' @param INDUSTRY_SEGMENT e.g. 'ONSHORE PETROLEUM AND NATURAL GAS PRODUCTION [98.230(A)(2)]'. See Details.
#' @param FACILITY_NAME e.g. '#540 BONANZA CREEK ENERGY - DENVER BASIN'. See Details.
#' @param WELL_TEST_TOTAL_CH4_EMM_CO2E e.g. '0'. See Details.
#' @export

ghg_w_well_testing <- function(FACILITY_ID = NULL, REPORTING_YEAR = NULL, SUB_INDICATOR_WELL_TESTING = NULL, 
    BAMM_DESCRIPTION_WELL_TESTING = NULL, BAMM_INDICATOR_WELL_TESTING = NULL, DID_FAC_PERFORM_WELL_TESTING = NULL, 
    WELL_TEST_TOTAL_GHG_EMM_CO2E = NULL, WELL_TEST_TOTAL_N2O_EMM_CO2E = NULL, WELL_TEST_TOTAL_CO2_EMISSIONS = NULL, 
    INDUSTRY_SEGMENT = NULL, FACILITY_NAME = NULL, WELL_TEST_TOTAL_CH4_EMM_CO2E = NULL) {
    
    args <- list(FACILITY_ID = FACILITY_ID, REPORTING_YEAR = REPORTING_YEAR, SUB_INDICATOR_WELL_TESTING = SUB_INDICATOR_WELL_TESTING, 
        BAMM_DESCRIPTION_WELL_TESTING = BAMM_DESCRIPTION_WELL_TESTING, BAMM_INDICATOR_WELL_TESTING = BAMM_INDICATOR_WELL_TESTING, 
        DID_FAC_PERFORM_WELL_TESTING = DID_FAC_PERFORM_WELL_TESTING, WELL_TEST_TOTAL_GHG_EMM_CO2E = WELL_TEST_TOTAL_GHG_EMM_CO2E, 
        WELL_TEST_TOTAL_N2O_EMM_CO2E = WELL_TEST_TOTAL_N2O_EMM_CO2E, WELL_TEST_TOTAL_CO2_EMISSIONS = WELL_TEST_TOTAL_CO2_EMISSIONS, 
        INDUSTRY_SEGMENT = INDUSTRY_SEGMENT, FACILITY_NAME = FACILITY_NAME, WELL_TEST_TOTAL_CH4_EMM_CO2E = WELL_TEST_TOTAL_CH4_EMM_CO2E)
    ret <- envir_get(w_well_testing, args)
    
    ret
} 
