#' Retrieve uu inj co2 facility data from ghg database
#' 
#' @param FACILITY_ID e.g. '1001052'. See Details.
#' @param REPORTING_YEAR e.g. '2011'. See Details.
#' @param CO2_SOURCES e.g. 'ELECTRIC GENERATING UNIT'. See Details.
#' @param FACILITY_NAME e.g. 'MOUNTAINEER (1301)'. See Details.
#' @param CO2_SRC_SPEC_ANTHROPOGENIC_SRC e.g. 'NA'. See Details.
#' @param PURPOSE_OF_CO2_INJECTION e.g. 'NA'. See Details.
#' @param PURPOSE_OF_CO2_INJECTION_OTHER e.g. 'NA'. See Details.
#' @param PURP_OF_CO2_INJEC_END_DATE e.g. 'NA'. See Details.
#' @param PURP_OF_CO2_INJEC_START_DATE e.g. 'NA'. See Details.
#' @export

ghg_uu_inj_co2_facility <- function(FACILITY_ID = NULL, REPORTING_YEAR = NULL, CO2_SOURCES = NULL, 
    FACILITY_NAME = NULL, CO2_SRC_SPEC_ANTHROPOGENIC_SRC = NULL, PURPOSE_OF_CO2_INJECTION = NULL, 
    PURPOSE_OF_CO2_INJECTION_OTHER = NULL, PURP_OF_CO2_INJEC_END_DATE = NULL, PURP_OF_CO2_INJEC_START_DATE = NULL) {
    
    args <- list(FACILITY_ID = FACILITY_ID, REPORTING_YEAR = REPORTING_YEAR, CO2_SOURCES = CO2_SOURCES, 
        FACILITY_NAME = FACILITY_NAME, CO2_SRC_SPEC_ANTHROPOGENIC_SRC = CO2_SRC_SPEC_ANTHROPOGENIC_SRC, 
        PURPOSE_OF_CO2_INJECTION = PURPOSE_OF_CO2_INJECTION, PURPOSE_OF_CO2_INJECTION_OTHER = PURPOSE_OF_CO2_INJECTION_OTHER, 
        PURP_OF_CO2_INJEC_END_DATE = PURP_OF_CO2_INJEC_END_DATE, PURP_OF_CO2_INJEC_START_DATE = PURP_OF_CO2_INJEC_START_DATE)
    ret <- envir_get(uu_inj_co2_facility, args)
    
    ret
} 
