#' Retrieve i fhtf info data from ghg database
#' 
#' @param FACILITY_ID e.g. '1000354'. See Details.
#' @param REPORTING_YEAR e.g. '2013'. See Details.
#' @param FHTF_EMISSION_CALC_METHOD e.g. 'EQUATION I-16 (MASS BALANCE)'. See Details.
#' @param ANNUAL_FHTF_EMISSIONS e.g. '0.4547'. See Details.
#' @param OTHER_FHTF_CAS_NUMBER e.g. '163702-06-5, 163702-05-4'. See Details.
#' @param OTHER_FHTF_NAME e.g. 'HFE-7200'. See Details.
#' @param FACILITY_NAME e.g. 'CYPRESS SEMICONDUCTOR MINNESOTA INC'. See Details.
#' @param FHTF_NAME e.g. 'OTHER F-HTF (SPECIFY)'. See Details.
#' @param FHTF_CAS_NUMBER e.g. '163702-06-5, 163702-05-4'. See Details.
#' @param OTHER_FHTF_FORMULA e.g. 'C4F9OC2H5'. See Details.
#' @export

ghg_i_fhtf_info <- function(FACILITY_ID = NULL, REPORTING_YEAR = NULL, FHTF_EMISSION_CALC_METHOD = NULL, 
    ANNUAL_FHTF_EMISSIONS = NULL, OTHER_FHTF_CAS_NUMBER = NULL, OTHER_FHTF_NAME = NULL, 
    FACILITY_NAME = NULL, FHTF_NAME = NULL, FHTF_CAS_NUMBER = NULL, OTHER_FHTF_FORMULA = NULL) {
    
    args <- list(FACILITY_ID = FACILITY_ID, REPORTING_YEAR = REPORTING_YEAR, FHTF_EMISSION_CALC_METHOD = FHTF_EMISSION_CALC_METHOD, 
        ANNUAL_FHTF_EMISSIONS = ANNUAL_FHTF_EMISSIONS, OTHER_FHTF_CAS_NUMBER = OTHER_FHTF_CAS_NUMBER, 
        OTHER_FHTF_NAME = OTHER_FHTF_NAME, FACILITY_NAME = FACILITY_NAME, FHTF_NAME = FHTF_NAME, 
        FHTF_CAS_NUMBER = FHTF_CAS_NUMBER, OTHER_FHTF_FORMULA = OTHER_FHTF_FORMULA)
    ret <- envir_get("i_fhtf_info", args)
    
    ret
} 
