#' Retrieve hh gas collection system detls data from ghg database
#'
#' @param FACILITY_ID e.g. '1000010'. See Details.
#' @param REPORTING_YEAR e.g. '2014'. See Details.
#' @param FACILITY_NAME e.g. 'SANTA ROSA CENTRAL LANDFILL'. See Details.
#' @param ANNUAL_LANDFILL_GAS_FLOW e.g. '7144560'. See Details.
#' @param ANNL_AVG_METHANE_CONCENTRATION e.g. '55.9'. See Details.
#' @param ANNL_AVG_METHANE_CONC_DAYS_SUB e.g. '61'. See Details.
#' @param ANNL_AVG_METHANE_CONC_WK_SUB e.g. 'NA'. See Details.
#' @param GAS_COLLECTION_SYS_MANUFACTURE e.g. 'C B & I'. See Details.
#' @param GAS_COLLECTION_SYSTEM_CAPACITY e.g. '750'. See Details.
#' @param NUMBER_OF_WELLS e.g. '30'. See Details.
#' @param EQUATION_HH5_RESULT e.g. '4627.51'. See Details.
#' @param EQUATION_HH7_RESULT e.g. '9650.83'. See Details.
#' @param EQUATION_HH6_RESULT e.g. '1510.76'. See Details.
#' @param EQUATION_HH8_RESULT e.g. '6534.09'. See Details.
#' @param CH4_GEN_INPUT_TO_EQUATION_HH6 e.g. 'EQUATION HH-1'. See Details.
#' @param CH4_DESTRUCTION_LOCATION e.g. 'ON-SITE'. See Details.
#' @param GCS_ANNUAL_OPERATING_HOURS e.g. 'NA'. See Details.
#' @param ANNUAL_QTY_RECOVERD_CH4_EQ_HH4 e.g. '504.7'. See Details.
#' @param EST_GAS_COLLECTION_EFFICIENCY e.g. '0.3'. See Details.
#' @param LNDFIL_GAS_FLOW_MESR_WET_BASIS e.g. 'Y'. See Details.
#' @param CH4_CONC_MEASURED_WET_BASIS e.g. 'Y'. See Details.
#' @param BACKUP_DESTRUCTION_DEVICE e.g. 'NA'. See Details.
#' @param BACKUP_DESTR_DEVICE_ANN_OP_HRS e.g. 'NA'. See Details.
#' @param DESTRUCTION_EFFICIENCY_PCT e.g. 'NA'. See Details.
#' @param PRIMARY_DESTR_DEVICE_ANN_OP_HR e.g. 'NA'. See Details.
#' @param IS_PRESSURE_INCORPORATED e.g. 'Y'. See Details.
#' @param IS_TEMPERATURE_INCORPORATED e.g. 'Y'. See Details.
#' @param ANNL_AVG_METHANE_CONC_MONS_SUB e.g. 'NA'. See Details.
#' @export

ghg_hh_gas_collection_system_detls <- function(FACILITY_ID = NULL, REPORTING_YEAR = NULL,
    FACILITY_NAME = NULL, ANNUAL_LANDFILL_GAS_FLOW = NULL, ANNL_AVG_METHANE_CONCENTRATION = NULL,
    ANNL_AVG_METHANE_CONC_DAYS_SUB = NULL, ANNL_AVG_METHANE_CONC_WK_SUB = NULL, GAS_COLLECTION_SYS_MANUFACTURE = NULL,
    GAS_COLLECTION_SYSTEM_CAPACITY = NULL, NUMBER_OF_WELLS = NULL, EQUATION_HH5_RESULT = NULL,
    EQUATION_HH7_RESULT = NULL, EQUATION_HH6_RESULT = NULL, EQUATION_HH8_RESULT = NULL,
    CH4_GEN_INPUT_TO_EQUATION_HH6 = NULL, CH4_DESTRUCTION_LOCATION = NULL, GCS_ANNUAL_OPERATING_HOURS = NULL,
    ANNUAL_QTY_RECOVERD_CH4_EQ_HH4 = NULL, EST_GAS_COLLECTION_EFFICIENCY = NULL,
    LNDFIL_GAS_FLOW_MESR_WET_BASIS = NULL, CH4_CONC_MEASURED_WET_BASIS = NULL, BACKUP_DESTRUCTION_DEVICE = NULL,
    BACKUP_DESTR_DEVICE_ANN_OP_HRS = NULL, DESTRUCTION_EFFICIENCY_PCT = NULL, PRIMARY_DESTR_DEVICE_ANN_OP_HR = NULL,
    IS_PRESSURE_INCORPORATED = NULL, IS_TEMPERATURE_INCORPORATED = NULL, ANNL_AVG_METHANE_CONC_MONS_SUB = NULL) {

    args <- list(FACILITY_ID = FACILITY_ID, REPORTING_YEAR = REPORTING_YEAR, FACILITY_NAME = FACILITY_NAME,
        ANNUAL_LANDFILL_GAS_FLOW = ANNUAL_LANDFILL_GAS_FLOW, ANNL_AVG_METHANE_CONCENTRATION = ANNL_AVG_METHANE_CONCENTRATION,
        ANNL_AVG_METHANE_CONC_DAYS_SUB = ANNL_AVG_METHANE_CONC_DAYS_SUB, ANNL_AVG_METHANE_CONC_WK_SUB = ANNL_AVG_METHANE_CONC_WK_SUB,
        GAS_COLLECTION_SYS_MANUFACTURE = GAS_COLLECTION_SYS_MANUFACTURE, GAS_COLLECTION_SYSTEM_CAPACITY = GAS_COLLECTION_SYSTEM_CAPACITY,
        NUMBER_OF_WELLS = NUMBER_OF_WELLS, EQUATION_HH5_RESULT = EQUATION_HH5_RESULT,
        EQUATION_HH7_RESULT = EQUATION_HH7_RESULT, EQUATION_HH6_RESULT = EQUATION_HH6_RESULT,
        EQUATION_HH8_RESULT = EQUATION_HH8_RESULT, CH4_GEN_INPUT_TO_EQUATION_HH6 = CH4_GEN_INPUT_TO_EQUATION_HH6,
        CH4_DESTRUCTION_LOCATION = CH4_DESTRUCTION_LOCATION, GCS_ANNUAL_OPERATING_HOURS = GCS_ANNUAL_OPERATING_HOURS,
        ANNUAL_QTY_RECOVERD_CH4_EQ_HH4 = ANNUAL_QTY_RECOVERD_CH4_EQ_HH4, EST_GAS_COLLECTION_EFFICIENCY = EST_GAS_COLLECTION_EFFICIENCY,
        LNDFIL_GAS_FLOW_MESR_WET_BASIS = LNDFIL_GAS_FLOW_MESR_WET_BASIS, CH4_CONC_MEASURED_WET_BASIS = CH4_CONC_MEASURED_WET_BASIS,
        BACKUP_DESTRUCTION_DEVICE = BACKUP_DESTRUCTION_DEVICE, BACKUP_DESTR_DEVICE_ANN_OP_HRS = BACKUP_DESTR_DEVICE_ANN_OP_HRS,
        DESTRUCTION_EFFICIENCY_PCT = DESTRUCTION_EFFICIENCY_PCT, PRIMARY_DESTR_DEVICE_ANN_OP_HR = PRIMARY_DESTR_DEVICE_ANN_OP_HR,
        IS_PRESSURE_INCORPORATED = IS_PRESSURE_INCORPORATED, IS_TEMPERATURE_INCORPORATED = IS_TEMPERATURE_INCORPORATED,
        ANNL_AVG_METHANE_CONC_MONS_SUB = ANNL_AVG_METHANE_CONC_MONS_SUB)
    ret <- envir_get("hh_gas_collection_system_detls", args)

    ret
}
