#' Retrieve ff destroffsite backup data from ghg database
#' 
#' @param FACILITY_ID e.g. '1001687'. See Details.
#' @param REPORTING_YEAR e.g. '2011'. See Details.
#' @param INDV_WEL_SHFT_DSTR_OFFST_TRNS9 e.g. 'NA'. See Details.
#' @param INDV_WEL_SHFT_DSTR_OFST_TRNS10 e.g. 'NA'. See Details.
#' @param DEVICE_DESCRIPTION e.g. 'NA'. See Details.
#' @param ADDITIONAL_DESCRIPTION e.g. 'NA'. See Details.
#' @param BACKUP_DESTRUC_DEVICE_PRESENCE e.g. 'NA'. See Details.
#' @param ANNUAL_OP_HRS_DESTRUC_DEVICE e.g. 'NA'. See Details.
#' @param ANNU_OP_HRS_BCKUP1_DEST_DEVICE e.g. 'NA'. See Details.
#' @param ANNU_OP_HRS_BCKUP2_DEST_DEVICE e.g. 'NA'. See Details.
#' @param DESTRUCTION_DEVICE_ID e.g. 'NONE'. See Details.
#' @param FACILITY_NAME e.g. 'BLUE DIAMOND MINING MINE 77'. See Details.
#' @param IS_GAS_DESTROYED_OFFSITE e.g. 'NA'. See Details.
#' @param GAS_DESTR_MINE_TRANS_OFFSTE e.g. 'NA'. See Details.
#' @param DESTR_EFFICIEN_BACKUP_1_DEVICE e.g. 'NA'. See Details.
#' @param DESTR_EFFICIEN_BACKUP_2_DEVICE e.g. 'NA'. See Details.
#' @param DESTR_EFFICIEN_PRIMARY_DEVICE e.g. 'NA'. See Details.
#' @param INDV_WEL_SHFT_DSTR_OFFST_TRNS1 e.g. 'NA'. See Details.
#' @param INDV_WEL_SHFT_DSTR_OFFST_TRNS2 e.g. 'NA'. See Details.
#' @param INDV_WEL_SHFT_DSTR_OFFST_TRNS3 e.g. 'NA'. See Details.
#' @param INDV_WEL_SHFT_DSTR_OFFST_TRNS4 e.g. 'NA'. See Details.
#' @param INDV_WEL_SHFT_DSTR_OFFST_TRNS5 e.g. 'NA'. See Details.
#' @param INDV_WEL_SHFT_DSTR_OFFST_TRNS6 e.g. 'NA'. See Details.
#' @param INDV_WEL_SHFT_DSTR_OFFST_TRNS7 e.g. 'NA'. See Details.
#' @param INDV_WEL_SHFT_DSTR_OFFST_TRNS8 e.g. 'NA'. See Details.
#' @export

ghg_ff_destroffsite_backup <- function(FACILITY_ID = NULL, REPORTING_YEAR = NULL, 
    INDV_WEL_SHFT_DSTR_OFFST_TRNS9 = NULL, INDV_WEL_SHFT_DSTR_OFST_TRNS10 = NULL, 
    DEVICE_DESCRIPTION = NULL, ADDITIONAL_DESCRIPTION = NULL, BACKUP_DESTRUC_DEVICE_PRESENCE = NULL, 
    ANNUAL_OP_HRS_DESTRUC_DEVICE = NULL, ANNU_OP_HRS_BCKUP1_DEST_DEVICE = NULL, ANNU_OP_HRS_BCKUP2_DEST_DEVICE = NULL, 
    DESTRUCTION_DEVICE_ID = NULL, FACILITY_NAME = NULL, IS_GAS_DESTROYED_OFFSITE = NULL, 
    GAS_DESTR_MINE_TRANS_OFFSTE = NULL, DESTR_EFFICIEN_BACKUP_1_DEVICE = NULL, DESTR_EFFICIEN_BACKUP_2_DEVICE = NULL, 
    DESTR_EFFICIEN_PRIMARY_DEVICE = NULL, INDV_WEL_SHFT_DSTR_OFFST_TRNS1 = NULL, 
    INDV_WEL_SHFT_DSTR_OFFST_TRNS2 = NULL, INDV_WEL_SHFT_DSTR_OFFST_TRNS3 = NULL, 
    INDV_WEL_SHFT_DSTR_OFFST_TRNS4 = NULL, INDV_WEL_SHFT_DSTR_OFFST_TRNS5 = NULL, 
    INDV_WEL_SHFT_DSTR_OFFST_TRNS6 = NULL, INDV_WEL_SHFT_DSTR_OFFST_TRNS7 = NULL, 
    INDV_WEL_SHFT_DSTR_OFFST_TRNS8 = NULL) {
    
    args <- list(FACILITY_ID = FACILITY_ID, REPORTING_YEAR = REPORTING_YEAR, INDV_WEL_SHFT_DSTR_OFFST_TRNS9 = INDV_WEL_SHFT_DSTR_OFFST_TRNS9, 
        INDV_WEL_SHFT_DSTR_OFST_TRNS10 = INDV_WEL_SHFT_DSTR_OFST_TRNS10, DEVICE_DESCRIPTION = DEVICE_DESCRIPTION, 
        ADDITIONAL_DESCRIPTION = ADDITIONAL_DESCRIPTION, BACKUP_DESTRUC_DEVICE_PRESENCE = BACKUP_DESTRUC_DEVICE_PRESENCE, 
        ANNUAL_OP_HRS_DESTRUC_DEVICE = ANNUAL_OP_HRS_DESTRUC_DEVICE, ANNU_OP_HRS_BCKUP1_DEST_DEVICE = ANNU_OP_HRS_BCKUP1_DEST_DEVICE, 
        ANNU_OP_HRS_BCKUP2_DEST_DEVICE = ANNU_OP_HRS_BCKUP2_DEST_DEVICE, DESTRUCTION_DEVICE_ID = DESTRUCTION_DEVICE_ID, 
        FACILITY_NAME = FACILITY_NAME, IS_GAS_DESTROYED_OFFSITE = IS_GAS_DESTROYED_OFFSITE, 
        GAS_DESTR_MINE_TRANS_OFFSTE = GAS_DESTR_MINE_TRANS_OFFSTE, DESTR_EFFICIEN_BACKUP_1_DEVICE = DESTR_EFFICIEN_BACKUP_1_DEVICE, 
        DESTR_EFFICIEN_BACKUP_2_DEVICE = DESTR_EFFICIEN_BACKUP_2_DEVICE, DESTR_EFFICIEN_PRIMARY_DEVICE = DESTR_EFFICIEN_PRIMARY_DEVICE, 
        INDV_WEL_SHFT_DSTR_OFFST_TRNS1 = INDV_WEL_SHFT_DSTR_OFFST_TRNS1, INDV_WEL_SHFT_DSTR_OFFST_TRNS2 = INDV_WEL_SHFT_DSTR_OFFST_TRNS2, 
        INDV_WEL_SHFT_DSTR_OFFST_TRNS3 = INDV_WEL_SHFT_DSTR_OFFST_TRNS3, INDV_WEL_SHFT_DSTR_OFFST_TRNS4 = INDV_WEL_SHFT_DSTR_OFFST_TRNS4, 
        INDV_WEL_SHFT_DSTR_OFFST_TRNS5 = INDV_WEL_SHFT_DSTR_OFFST_TRNS5, INDV_WEL_SHFT_DSTR_OFFST_TRNS6 = INDV_WEL_SHFT_DSTR_OFFST_TRNS6, 
        INDV_WEL_SHFT_DSTR_OFFST_TRNS7 = INDV_WEL_SHFT_DSTR_OFFST_TRNS7, INDV_WEL_SHFT_DSTR_OFFST_TRNS8 = INDV_WEL_SHFT_DSTR_OFFST_TRNS8)
    ret <- envir_get("ff_destroffsite_backup", args)
    
    ret
} 
