#' Retrieve ss install emissions data from ghg database
#' 
#' @param FACILITY_ID e.g. '1000039'. See Details.
#' @param REPORTING_YEAR e.g. '2013'. See Details.
#' @param FACILITY_NAME e.g. 'Alstom Grid Inc'. See Details.
#' @param GAS_NAME e.g. 'PFC-4-1-12 (Perfluoropentane)'. See Details.
#' @param TOTAL_EMISSIONS_RPT_ROUND e.g. '0'. See Details.
#' @param TOTAL_EMISSIONS_RPT_ROUND_OVR e.g. 'N'. See Details.
#' @param TOTAL_MASS_CHARGE_EQUIPMENT e.g. 'NA'. See Details.
#' @param TOTAL_MASS_FILL_EQUIPMENT e.g. 'NA'. See Details.
#' @param TOTAL_NAMEPLATE_CAPACITY e.g. 'NA'. See Details.
#' @param CHARGE_EQ_MISSING_DATA_METHOD e.g. 'NA'. See Details.
#' @param OFFSITE_FILL_MISSING_DATA_MTHD e.g. 'NA'. See Details.
#' @param NC_MISSING_DATA_METHOD e.g. 'NA'. See Details.
#' @param CHARGE_EQ_MISSING_DATA e.g. 'NA'. See Details.
#' @param CHARGE_EQ_MISSING_DATA_REASON e.g. 'NA'. See Details.
#' @param OFFSITE_FILL_MISSING_DATA e.g. 'NA'. See Details.
#' @param OFFSITE_FILL_MISSING_DATA_REAS e.g. 'NA'. See Details.
#' @param NC_MISSING_DATA e.g. 'NA'. See Details.
#' @param NC_MISSING_DATA_REASON e.g. 'NA'. See Details.
#' @export

ghg_ss_install_emissions <- function(FACILITY_ID = NULL, REPORTING_YEAR = NULL, FACILITY_NAME = NULL, 
    GAS_NAME = NULL, TOTAL_EMISSIONS_RPT_ROUND = NULL, TOTAL_EMISSIONS_RPT_ROUND_OVR = NULL, 
    TOTAL_MASS_CHARGE_EQUIPMENT = NULL, TOTAL_MASS_FILL_EQUIPMENT = NULL, TOTAL_NAMEPLATE_CAPACITY = NULL, 
    CHARGE_EQ_MISSING_DATA_METHOD = NULL, OFFSITE_FILL_MISSING_DATA_MTHD = NULL, 
    NC_MISSING_DATA_METHOD = NULL, CHARGE_EQ_MISSING_DATA = NULL, CHARGE_EQ_MISSING_DATA_REASON = NULL, 
    OFFSITE_FILL_MISSING_DATA = NULL, OFFSITE_FILL_MISSING_DATA_REAS = NULL, NC_MISSING_DATA = NULL, 
    NC_MISSING_DATA_REASON = NULL) {
    
    args <- list(FACILITY_ID = FACILITY_ID, REPORTING_YEAR = REPORTING_YEAR, FACILITY_NAME = FACILITY_NAME, 
        GAS_NAME = GAS_NAME, TOTAL_EMISSIONS_RPT_ROUND = TOTAL_EMISSIONS_RPT_ROUND, 
        TOTAL_EMISSIONS_RPT_ROUND_OVR = TOTAL_EMISSIONS_RPT_ROUND_OVR, TOTAL_MASS_CHARGE_EQUIPMENT = TOTAL_MASS_CHARGE_EQUIPMENT, 
        TOTAL_MASS_FILL_EQUIPMENT = TOTAL_MASS_FILL_EQUIPMENT, TOTAL_NAMEPLATE_CAPACITY = TOTAL_NAMEPLATE_CAPACITY, 
        CHARGE_EQ_MISSING_DATA_METHOD = CHARGE_EQ_MISSING_DATA_METHOD, OFFSITE_FILL_MISSING_DATA_MTHD = OFFSITE_FILL_MISSING_DATA_MTHD, 
        NC_MISSING_DATA_METHOD = NC_MISSING_DATA_METHOD, CHARGE_EQ_MISSING_DATA = CHARGE_EQ_MISSING_DATA, 
        CHARGE_EQ_MISSING_DATA_REASON = CHARGE_EQ_MISSING_DATA_REASON, OFFSITE_FILL_MISSING_DATA = OFFSITE_FILL_MISSING_DATA, 
        OFFSITE_FILL_MISSING_DATA_REAS = OFFSITE_FILL_MISSING_DATA_REAS, NC_MISSING_DATA = NC_MISSING_DATA, 
        NC_MISSING_DATA_REASON = NC_MISSING_DATA_REASON)
    ret <- envir_get(ss_install_emissions, args)
    
    ret
} 
