#' Retrieve u calcination frac methods data from ghg database
#' 
#' @param FACILITY_ID e.g. '1001072'. See Details.
#' @param REPORTING_YEAR e.g. '2013'. See Details.
#' @param OTHER_CARBONATE_MASS_MEAS_MTHD e.g. 'NA'. See Details.
#' @param OTHER_CALCINAT_FRAC_DETRM_MTHD e.g. 'NA'. See Details.
#' @param SUB_MONTHLY_MASS_CONSUMED e.g. '0'. See Details.
#' @param CARBONATE_MASS_MEASR_MTHD e.g. 'PURCHASE RECORDS'. See Details.
#' @param CALCINATION_FRAC_DETRM_MTHD e.g. 'DEFAULT OF 1.0'. See Details.
#' @param FACILITY_NAME e.g. 'OCCIDENTAL CHEMICAL DALLAS SILICATE PLANT'. See Details.
#' @export

ghg_u_calcination_frac_methods <- function(FACILITY_ID = NULL, REPORTING_YEAR = NULL, 
    OTHER_CARBONATE_MASS_MEAS_MTHD = NULL, OTHER_CALCINAT_FRAC_DETRM_MTHD = NULL, 
    SUB_MONTHLY_MASS_CONSUMED = NULL, CARBONATE_MASS_MEASR_MTHD = NULL, CALCINATION_FRAC_DETRM_MTHD = NULL, 
    FACILITY_NAME = NULL) {
    
    args <- list(FACILITY_ID = FACILITY_ID, REPORTING_YEAR = REPORTING_YEAR, OTHER_CARBONATE_MASS_MEAS_MTHD = OTHER_CARBONATE_MASS_MEAS_MTHD, 
        OTHER_CALCINAT_FRAC_DETRM_MTHD = OTHER_CALCINAT_FRAC_DETRM_MTHD, SUB_MONTHLY_MASS_CONSUMED = SUB_MONTHLY_MASS_CONSUMED, 
        CARBONATE_MASS_MEASR_MTHD = CARBONATE_MASS_MEASR_MTHD, CALCINATION_FRAC_DETRM_MTHD = CALCINATION_FRAC_DETRM_MTHD, 
        FACILITY_NAME = FACILITY_NAME)
    ret <- envir_get("u_calcination_frac_methods", args)
    
    ret
} 
