#' Retrieve q cems details data from ghg database
#' 
#' @param FACILITY_ID e.g. '1000156'. See Details.
#' @param REPORTING_YEAR e.g. '2013'. See Details.
#' @param CML_NAME e.g. 'UTC_Sinter Plant_CEMS'. See Details.
#' @param CML_CONFIGURATION_TYPE e.g. 'Single process/process unit exhausts to dedicated stack'. See Details.
#' @param CEMS_BIOGENIC_CO2_EMISSIONS e.g. '0'. See Details.
#' @param CEMS_NON_BIOGENIC_CO2_EMISSION e.g. '150219'. See Details.
#' @param CEMS_ANNUAL_CO2_EMISSIONS e.g. '150219'. See Details.
#' @param CEMS_CH4_EMISSIONS e.g. 'NA'. See Details.
#' @param CEMS_N2O_EMISSIONS e.g. 'NA'. See Details.
#' @param CML_TOTAL_OPERATING_HOURS e.g. '6029'. See Details.
#' @param TIER4_SUB_OPER_HRS_CO2_CONC e.g. '2'. See Details.
#' @param TIER4_SUB_OPER_HRS_GAS_FLOW_RT e.g. '2'. See Details.
#' @param TIER4_SUB_OPER_HRS_MOIST_CONT e.g. '2'. See Details.
#' @param CEMS_CO2_COMBUSTION_EMISSIONS e.g. 'NA'. See Details.
#' @param CEMS_METHODOLOGY_START_DATE e.g. '2013-01-01'. See Details.
#' @param CEMS_METHODOLOGY_END_DATE e.g. '2013-12-31'. See Details.
#' @param CEMS_FUEL e.g. 'NA'. See Details.
#' @param CEMS_QUARTER_NAME e.g. 'First Quarter'. See Details.
#' @param CEMS_CO2_EMISSIONS_BY_QUARTER e.g. '48759'. See Details.
#' @export

ghg_q_cems_details <- function(FACILITY_ID = NULL, REPORTING_YEAR = NULL, CML_NAME = NULL, 
    CML_CONFIGURATION_TYPE = NULL, CEMS_BIOGENIC_CO2_EMISSIONS = NULL, CEMS_NON_BIOGENIC_CO2_EMISSION = NULL, 
    CEMS_ANNUAL_CO2_EMISSIONS = NULL, CEMS_CH4_EMISSIONS = NULL, CEMS_N2O_EMISSIONS = NULL, 
    CML_TOTAL_OPERATING_HOURS = NULL, TIER4_SUB_OPER_HRS_CO2_CONC = NULL, TIER4_SUB_OPER_HRS_GAS_FLOW_RT = NULL, 
    TIER4_SUB_OPER_HRS_MOIST_CONT = NULL, CEMS_CO2_COMBUSTION_EMISSIONS = NULL, CEMS_METHODOLOGY_START_DATE = NULL, 
    CEMS_METHODOLOGY_END_DATE = NULL, CEMS_FUEL = NULL, CEMS_QUARTER_NAME = NULL, 
    CEMS_CO2_EMISSIONS_BY_QUARTER = NULL) {
    
    args <- list(FACILITY_ID = FACILITY_ID, REPORTING_YEAR = REPORTING_YEAR, CML_NAME = CML_NAME, 
        CML_CONFIGURATION_TYPE = CML_CONFIGURATION_TYPE, CEMS_BIOGENIC_CO2_EMISSIONS = CEMS_BIOGENIC_CO2_EMISSIONS, 
        CEMS_NON_BIOGENIC_CO2_EMISSION = CEMS_NON_BIOGENIC_CO2_EMISSION, CEMS_ANNUAL_CO2_EMISSIONS = CEMS_ANNUAL_CO2_EMISSIONS, 
        CEMS_CH4_EMISSIONS = CEMS_CH4_EMISSIONS, CEMS_N2O_EMISSIONS = CEMS_N2O_EMISSIONS, 
        CML_TOTAL_OPERATING_HOURS = CML_TOTAL_OPERATING_HOURS, TIER4_SUB_OPER_HRS_CO2_CONC = TIER4_SUB_OPER_HRS_CO2_CONC, 
        TIER4_SUB_OPER_HRS_GAS_FLOW_RT = TIER4_SUB_OPER_HRS_GAS_FLOW_RT, TIER4_SUB_OPER_HRS_MOIST_CONT = TIER4_SUB_OPER_HRS_MOIST_CONT, 
        CEMS_CO2_COMBUSTION_EMISSIONS = CEMS_CO2_COMBUSTION_EMISSIONS, CEMS_METHODOLOGY_START_DATE = CEMS_METHODOLOGY_START_DATE, 
        CEMS_METHODOLOGY_END_DATE = CEMS_METHODOLOGY_END_DATE, CEMS_FUEL = CEMS_FUEL, 
        CEMS_QUARTER_NAME = CEMS_QUARTER_NAME, CEMS_CO2_EMISSIONS_BY_QUARTER = CEMS_CO2_EMISSIONS_BY_QUARTER)
    ret <- envir_get("q_cems_details", args)
    
    ret
} 
