#' Retrieve hh hist yr waste qty data from ghg database
#' 
#' @param FACILITY_ID e.g. '1000010'. See Details.
#' @param REPORTING_YEAR e.g. '2013'. See Details.
#' @param FACILITY_NAME e.g. 'SANTA ROSA CENTRAL LANDFILL'. See Details.
#' @param HIST_WASTE_DISPOSAL_YEAR e.g. '1997'. See Details.
#' @param HISTYR_ANN_WSTE_DISPOSAL_QTY e.g. '46586'. See Details.
#' @param HISTYR_ANN_WSTE_QTY_BY_MTHD e.g. 'NA'. See Details.
#' @param HISTYR_ANN_WSTE_QTY_MTHD_USED e.g. 'USED WORKING CAPACITY FOR EACH VEHICLE/CONTAINER'. See Details.
#' @export

ghg_hh_hist_yr_waste_qty <- function(FACILITY_ID = NULL, REPORTING_YEAR = NULL, FACILITY_NAME = NULL, 
    HIST_WASTE_DISPOSAL_YEAR = NULL, HISTYR_ANN_WSTE_DISPOSAL_QTY = NULL, HISTYR_ANN_WSTE_QTY_BY_MTHD = NULL, 
    HISTYR_ANN_WSTE_QTY_MTHD_USED = NULL) {
    
    args <- list(FACILITY_ID = FACILITY_ID, REPORTING_YEAR = REPORTING_YEAR, FACILITY_NAME = FACILITY_NAME, 
        HIST_WASTE_DISPOSAL_YEAR = HIST_WASTE_DISPOSAL_YEAR, HISTYR_ANN_WSTE_DISPOSAL_QTY = HISTYR_ANN_WSTE_DISPOSAL_QTY, 
        HISTYR_ANN_WSTE_QTY_BY_MTHD = HISTYR_ANN_WSTE_QTY_BY_MTHD, HISTYR_ANN_WSTE_QTY_MTHD_USED = HISTYR_ANN_WSTE_QTY_MTHD_USED)
    ret <- envir_get(hh_hist_yr_waste_qty, args)
    
    ret
} 
