#' Retrieve ii ch4 gen process data from ghg database
#' 
#' @param FACILITY_ID e.g. '1000035'. See Details.
#' @param REPORTING_YEAR e.g. '2011'. See Details.
#' @param FACILITY_NAME e.g. 'ANDERSONS MARATHON ETHANOL LLC'. See Details.
#' @param ANAEROBIC_PROCESS_ID e.g. 'Greenville Methanator System'. See Details.
#' @param WEEK e.g. '1'. See Details.
#' @param DOES_FAC_MEASURE_COD_BOD_CONC e.g. 'COD'. See Details.
#' @param WEEKLY_AVG_COD_BOD_CONC e.g. '3.67'. See Details.
#' @param IS_MISS_DATA_USED_COD_BOD_CONC e.g. 'No'. See Details.
#' @param WEEKLY_VOLUME_OF_WASTEWATER e.g. '3038.65'. See Details.
#' @param METHANE_PRODUCTION_POTENTIAL e.g. '0.25'. See Details.
#' @param IS_MISS_DATA_USED_VOL_WSTWATER e.g. 'NA'. See Details.
#' @param METHANE_CONVERSION_FACTOR e.g. '0.8'. See Details.
#' @param ANNUAL_MASS_METHANE_GEN_BOD5 e.g. 'NA'. See Details.
#' @param ANNUAL_MASS_METHANE_GEN_COD e.g. '2.2303691'. See Details.
#' @export

ghg_ii_ch4_gen_process <- function(FACILITY_ID = NULL, REPORTING_YEAR = NULL, FACILITY_NAME = NULL, 
    ANAEROBIC_PROCESS_ID = NULL, WEEK = NULL, DOES_FAC_MEASURE_COD_BOD_CONC = NULL, 
    WEEKLY_AVG_COD_BOD_CONC = NULL, IS_MISS_DATA_USED_COD_BOD_CONC = NULL, WEEKLY_VOLUME_OF_WASTEWATER = NULL, 
    METHANE_PRODUCTION_POTENTIAL = NULL, IS_MISS_DATA_USED_VOL_WSTWATER = NULL, METHANE_CONVERSION_FACTOR = NULL, 
    ANNUAL_MASS_METHANE_GEN_BOD5 = NULL, ANNUAL_MASS_METHANE_GEN_COD = NULL) {
    
    args <- list(FACILITY_ID = FACILITY_ID, REPORTING_YEAR = REPORTING_YEAR, FACILITY_NAME = FACILITY_NAME, 
        ANAEROBIC_PROCESS_ID = ANAEROBIC_PROCESS_ID, WEEK = WEEK, DOES_FAC_MEASURE_COD_BOD_CONC = DOES_FAC_MEASURE_COD_BOD_CONC, 
        WEEKLY_AVG_COD_BOD_CONC = WEEKLY_AVG_COD_BOD_CONC, IS_MISS_DATA_USED_COD_BOD_CONC = IS_MISS_DATA_USED_COD_BOD_CONC, 
        WEEKLY_VOLUME_OF_WASTEWATER = WEEKLY_VOLUME_OF_WASTEWATER, METHANE_PRODUCTION_POTENTIAL = METHANE_PRODUCTION_POTENTIAL, 
        IS_MISS_DATA_USED_VOL_WSTWATER = IS_MISS_DATA_USED_VOL_WSTWATER, METHANE_CONVERSION_FACTOR = METHANE_CONVERSION_FACTOR, 
        ANNUAL_MASS_METHANE_GEN_BOD5 = ANNUAL_MASS_METHANE_GEN_BOD5, ANNUAL_MASS_METHANE_GEN_COD = ANNUAL_MASS_METHANE_GEN_COD)
    ret <- envir_get("ii_ch4_gen_process", args)
    
    ret
} 
