#' Retrieve ff degas qtrly data from ghg database
#' 
#' @param FACILITY_ID e.g. '1004441'. See Details.
#' @param REPORTING_YEAR e.g. '2011'. See Details.
#' @param TIME_SUB_DATA_USED_PRESSURE e.g. 'NA'. See Details.
#' @param TIME_SUB_DATA_USED_MOISTURE e.g. 'NA'. See Details.
#' @param START_DATE_FOR_DEGAS_SYSTEM e.g. 'NA'. See Details.
#' @param START_DATE_EQUIP_NOT_FUNC e.g. 'NA'. See Details.
#' @param END_DATE_EQUIP_NOT_FUNC e.g. 'NA'. See Details.
#' @param GAS_SYSTEM_UNIT_ID e.g. 'NO DEGASIFICATION GAS COLLECTION '. See Details.
#' @param QUARTER e.g. 'NA'. See Details.
#' @param TIME_SUB_DATA_USED_TEMPERATURE e.g. 'NA'. See Details.
#' @param DEGAS_MINING_OPERAT_STOP_DATE e.g. 'NA'. See Details.
#' @param METHOD_USED_CH4_CONC e.g. 'NA'. See Details.
#' @param QTRLY_CEMS_METHANE_CONCENTRATI e.g. 'NA'. See Details.
#' @param TIME_SUB_DATA_USD_QTR_CEMS_CH4 e.g. 'NA'. See Details.
#' @param QTRLY_METHANE_CONC_WEEKLY e.g. 'NA'. See Details.
#' @param TIME_SUB_DATA_USD_QTR_WKLY_CH4 e.g. 'NA'. See Details.
#' @param IS_EQ_FF9_REQ e.g. 'NA'. See Details.
#' @param GAS_ORGANIC_CONC_CORRCTN_FACTR e.g. 'NA'. See Details.
#' @param MOISTURE_CONTENT_WKLY_CH4 e.g. 'NA'. See Details.
#' @param PRESSURE_WKLY_CH4 e.g. 'NA'. See Details.
#' @param TEMPERATURE_USED_WKLY_CH4 e.g. 'NA'. See Details.
#' @param FACILITY_NAME e.g. 'COAL RIVER MINING, LLC'. See Details.
#' @param TIME_SUBSTITUTED_DATA_FOR_MCF e.g. 'NA'. See Details.
#' @export

ghg_ff_degas_qtrly <- function(FACILITY_ID = NULL, REPORTING_YEAR = NULL, TIME_SUB_DATA_USED_PRESSURE = NULL, 
    TIME_SUB_DATA_USED_MOISTURE = NULL, START_DATE_FOR_DEGAS_SYSTEM = NULL, START_DATE_EQUIP_NOT_FUNC = NULL, 
    END_DATE_EQUIP_NOT_FUNC = NULL, GAS_SYSTEM_UNIT_ID = NULL, QUARTER = NULL, TIME_SUB_DATA_USED_TEMPERATURE = NULL, 
    DEGAS_MINING_OPERAT_STOP_DATE = NULL, METHOD_USED_CH4_CONC = NULL, QTRLY_CEMS_METHANE_CONCENTRATI = NULL, 
    TIME_SUB_DATA_USD_QTR_CEMS_CH4 = NULL, QTRLY_METHANE_CONC_WEEKLY = NULL, TIME_SUB_DATA_USD_QTR_WKLY_CH4 = NULL, 
    IS_EQ_FF9_REQ = NULL, GAS_ORGANIC_CONC_CORRCTN_FACTR = NULL, MOISTURE_CONTENT_WKLY_CH4 = NULL, 
    PRESSURE_WKLY_CH4 = NULL, TEMPERATURE_USED_WKLY_CH4 = NULL, FACILITY_NAME = NULL, 
    TIME_SUBSTITUTED_DATA_FOR_MCF = NULL) {
    
    args <- list(FACILITY_ID = FACILITY_ID, REPORTING_YEAR = REPORTING_YEAR, TIME_SUB_DATA_USED_PRESSURE = TIME_SUB_DATA_USED_PRESSURE, 
        TIME_SUB_DATA_USED_MOISTURE = TIME_SUB_DATA_USED_MOISTURE, START_DATE_FOR_DEGAS_SYSTEM = START_DATE_FOR_DEGAS_SYSTEM, 
        START_DATE_EQUIP_NOT_FUNC = START_DATE_EQUIP_NOT_FUNC, END_DATE_EQUIP_NOT_FUNC = END_DATE_EQUIP_NOT_FUNC, 
        GAS_SYSTEM_UNIT_ID = GAS_SYSTEM_UNIT_ID, QUARTER = QUARTER, TIME_SUB_DATA_USED_TEMPERATURE = TIME_SUB_DATA_USED_TEMPERATURE, 
        DEGAS_MINING_OPERAT_STOP_DATE = DEGAS_MINING_OPERAT_STOP_DATE, METHOD_USED_CH4_CONC = METHOD_USED_CH4_CONC, 
        QTRLY_CEMS_METHANE_CONCENTRATI = QTRLY_CEMS_METHANE_CONCENTRATI, TIME_SUB_DATA_USD_QTR_CEMS_CH4 = TIME_SUB_DATA_USD_QTR_CEMS_CH4, 
        QTRLY_METHANE_CONC_WEEKLY = QTRLY_METHANE_CONC_WEEKLY, TIME_SUB_DATA_USD_QTR_WKLY_CH4 = TIME_SUB_DATA_USD_QTR_WKLY_CH4, 
        IS_EQ_FF9_REQ = IS_EQ_FF9_REQ, GAS_ORGANIC_CONC_CORRCTN_FACTR = GAS_ORGANIC_CONC_CORRCTN_FACTR, 
        MOISTURE_CONTENT_WKLY_CH4 = MOISTURE_CONTENT_WKLY_CH4, PRESSURE_WKLY_CH4 = PRESSURE_WKLY_CH4, 
        TEMPERATURE_USED_WKLY_CH4 = TEMPERATURE_USED_WKLY_CH4, FACILITY_NAME = FACILITY_NAME, 
        TIME_SUBSTITUTED_DATA_FOR_MCF = TIME_SUBSTITUTED_DATA_FOR_MCF)
    ret <- envir_get("ff_degas_qtrly", args)
    
    ret
} 
