#' Retrieve pp meter and equipment details data from ghg database
#' 
#' @param FACILITY_ID e.g. '1000035'. See Details.
#' @param REPORTING_YEAR e.g. '2013'. See Details.
#' @param METER_NAME e.g. 'FL-3805'. See Details.
#' @param METER_TYPE e.g. 'CO2 Flow Meter'. See Details.
#' @param FACILITY_NAME e.g. 'ANDERSONS MARATHON ETHANOL LLC'. See Details.
#' @param BIOMASS_PERCENTAGE e.g. '100'. See Details.
#' @param UPSTREAM_DEHYDRATION_EQUIPMENT e.g. 'N'. See Details.
#' @param DOWNSTREAM_DEHYDRATION_EQUIP e.g. 'N'. See Details.
#' @param UPSTREAM_COMPRESSION_EQUIPMENT e.g. 'N'. See Details.
#' @param DOWNSTREAM_COMPRESSION_EQUIP e.g. 'N'. See Details.
#' @param OTHER_EQUIPMENT_UPSTREAM e.g. 'N'. See Details.
#' @param OTHER_EQUIPMENT_DOWNSTREAM e.g. 'N'. See Details.
#' @param UPSTREAM_CAPTURE_EQUIPMENT e.g. 'NA'. See Details.
#' @param DOWNSTREAM_CAPTURE_EQUIPMENT e.g. 'NA'. See Details.
#' @param DESC_OTHR_PROCESS_EQUIP e.g. 'NA'. See Details.
#' @param MASSORVOLUME e.g. 'NA'. See Details.
#' @param METERSEGREGATIONLOCATION e.g. 'NA'. See Details.
#' @param METERIMPORTEXPORT e.g. 'NA'. See Details.
#' @export

ghg_pp_meter_and_equipment_details <- function(FACILITY_ID = NULL, REPORTING_YEAR = NULL, 
    METER_NAME = NULL, METER_TYPE = NULL, FACILITY_NAME = NULL, BIOMASS_PERCENTAGE = NULL, 
    UPSTREAM_DEHYDRATION_EQUIPMENT = NULL, DOWNSTREAM_DEHYDRATION_EQUIP = NULL, UPSTREAM_COMPRESSION_EQUIPMENT = NULL, 
    DOWNSTREAM_COMPRESSION_EQUIP = NULL, OTHER_EQUIPMENT_UPSTREAM = NULL, OTHER_EQUIPMENT_DOWNSTREAM = NULL, 
    UPSTREAM_CAPTURE_EQUIPMENT = NULL, DOWNSTREAM_CAPTURE_EQUIPMENT = NULL, DESC_OTHR_PROCESS_EQUIP = NULL, 
    MASSORVOLUME = NULL, METERSEGREGATIONLOCATION = NULL, METERIMPORTEXPORT = NULL) {
    
    args <- list(FACILITY_ID = FACILITY_ID, REPORTING_YEAR = REPORTING_YEAR, METER_NAME = METER_NAME, 
        METER_TYPE = METER_TYPE, FACILITY_NAME = FACILITY_NAME, BIOMASS_PERCENTAGE = BIOMASS_PERCENTAGE, 
        UPSTREAM_DEHYDRATION_EQUIPMENT = UPSTREAM_DEHYDRATION_EQUIPMENT, DOWNSTREAM_DEHYDRATION_EQUIP = DOWNSTREAM_DEHYDRATION_EQUIP, 
        UPSTREAM_COMPRESSION_EQUIPMENT = UPSTREAM_COMPRESSION_EQUIPMENT, DOWNSTREAM_COMPRESSION_EQUIP = DOWNSTREAM_COMPRESSION_EQUIP, 
        OTHER_EQUIPMENT_UPSTREAM = OTHER_EQUIPMENT_UPSTREAM, OTHER_EQUIPMENT_DOWNSTREAM = OTHER_EQUIPMENT_DOWNSTREAM, 
        UPSTREAM_CAPTURE_EQUIPMENT = UPSTREAM_CAPTURE_EQUIPMENT, DOWNSTREAM_CAPTURE_EQUIPMENT = DOWNSTREAM_CAPTURE_EQUIPMENT, 
        DESC_OTHR_PROCESS_EQUIP = DESC_OTHR_PROCESS_EQUIP, MASSORVOLUME = MASSORVOLUME, 
        METERSEGREGATIONLOCATION = METERSEGREGATIONLOCATION, METERIMPORTEXPORT = METERIMPORTEXPORT)
    ret <- envir_get(pp_meter_and_equipment_details, args)
    
    ret
} 
