#' Retrieve pcs admin penalty order data from pcs-icis database
#' 
#' @param NPDES e.g. 'AK0000272'. See Details.
#' @param ENFOR_ACTION_CODE e.g. '21'. See Details.
#' @param ENFOR_ACTION_TYPE e.g. 'E'. See Details.
#' @param ENFOR_ACTION_DATE e.g. '25-NOV-91'. See Details.
#' @param PROPOSED_ORDER_ISSUED_DATE e.g. 'NA'. See Details.
#' @param ADMINISTRATIVE_PENALTY_CLASS e.g. 'NA'. See Details.
#' @param HEARING_REQUEST e.g. 'NA'. See Details.
#' @param FINAL_ORDER_DATE e.g. 'NA'. See Details.
#' @param PENALTY_AMOUNT_ASSESSED e.g. '0'. See Details.
#' @param CLASS_II_APPEAL_FILED e.g. 'NA'. See Details.
#' @param JUDICIAL_APPEAL_FILED_DATE e.g. 'NA'. See Details.
#' @param PENALTY_COLLECTED_DATE e.g. 'NA'. See Details.
#' @export

pcs.icis_pcs_admin_penalty_order <- function(NPDES = NULL, ENFOR_ACTION_CODE = NULL, 
    ENFOR_ACTION_TYPE = NULL, ENFOR_ACTION_DATE = NULL, PROPOSED_ORDER_ISSUED_DATE = NULL, 
    ADMINISTRATIVE_PENALTY_CLASS = NULL, HEARING_REQUEST = NULL, FINAL_ORDER_DATE = NULL, 
    PENALTY_AMOUNT_ASSESSED = NULL, CLASS_II_APPEAL_FILED = NULL, JUDICIAL_APPEAL_FILED_DATE = NULL, 
    PENALTY_COLLECTED_DATE = NULL) {
    
    args <- list(NPDES = NPDES, ENFOR_ACTION_CODE = ENFOR_ACTION_CODE, ENFOR_ACTION_TYPE = ENFOR_ACTION_TYPE, 
        ENFOR_ACTION_DATE = ENFOR_ACTION_DATE, PROPOSED_ORDER_ISSUED_DATE = PROPOSED_ORDER_ISSUED_DATE, 
        ADMINISTRATIVE_PENALTY_CLASS = ADMINISTRATIVE_PENALTY_CLASS, HEARING_REQUEST = HEARING_REQUEST, 
        FINAL_ORDER_DATE = FINAL_ORDER_DATE, PENALTY_AMOUNT_ASSESSED = PENALTY_AMOUNT_ASSESSED, 
        CLASS_II_APPEAL_FILED = CLASS_II_APPEAL_FILED, JUDICIAL_APPEAL_FILED_DATE = JUDICIAL_APPEAL_FILED_DATE, 
        PENALTY_COLLECTED_DATE = PENALTY_COLLECTED_DATE)
    ret <- envir_get("pcs_admin_penalty_order", args)
    
    ret
} 
