#' Retrieve pcs permit facility data from pcs-icis database
#' 
#' @param NPDES e.g. 'AK0000272'. See Details.
#' @param NAME_1 e.g. 'ALYESKA SEAFOODS INC'. See Details.
#' @param NAME_2 e.g. 'S: UNALASKA (FISH MEAL/SURIMI)'. See Details.
#' @param MAJOR_DISCHARGE_INDICATOR e.g. 'M'. See Details.
#' @param REGION e.g. '10'. See Details.
#' @param CITY_CODE e.g. '92820'. See Details.
#' @param CITY_NAME e.g. 'UNALASKA'. See Details.
#' @param COUNTY_CODE e.g. '010'. See Details.
#' @param COUNTY_NAME e.g. 'ALEUTIAN ISLANDS DI'. See Details.
#' @param SIC_CODE e.g. '2091'. See Details.
#' @param LOCATION_NAME e.g. 'ALYESKA SEAFOODS INC'. See Details.
#' @param LOCATION_STREET_1 e.g. 'S: UNALASKA (FISH MEAL/SURIMI)'. See Details.
#' @param LOCATION_STREET_2 e.g. '551 WEST BROADWAY AVE'. See Details.
#' @param LOCATION_CITY e.g. 'UNALASKA'. See Details.
#' @param LOCATION_STATE e.g. 'AK'. See Details.
#' @param LOCATION_ZIP_CODE e.g. '99685'. See Details.
#' @param LOCATION_TELEPHONE_NUMBER e.g. '9075811211'. See Details.
#' @param MAILING_NAME e.g. 'ALYESKA SEAFOODS INC'. See Details.
#' @param MAILING_STREET_1 e.g. 'P.O. BOX 31359'. See Details.
#' @param MAILING_STREET_2 e.g. 'NA'. See Details.
#' @param MAILING_CITY e.g. 'SEATTLE'. See Details.
#' @param MAILING_STATE e.g. 'WA'. See Details.
#' @param MAILING_ZIP_CODE e.g. '98103'. See Details.
#' @param INACTIVE_CODE e.g. 'A'. See Details.
#' @param PERMIT_EXPIRED_DATE e.g. '31-MAR-08'. See Details.
#' @param PERMIT_ISSUED_DATE e.g. '05-FEB-03'. See Details.
#' @param DRAFT_PERM_PUB_NOTIF_DATE e.g. '21-SEP-01'. See Details.
#' @param APPL_RECEIVED_DATE e.g. '27-NOV-00'. See Details.
#' @param INACTIVE_DATE e.g. 'NA'. See Details.
#' @param TYPE_OF_OWNERSHIP e.g. 'PRI'. See Details.
#' @param COGN_OFFICIAL e.g. 'WINN BRINDLE, GENERAL MANAGER'. See Details.
#' @param COGN_OFFICIAL_TELE_NUMBER e.g. '2065472100'. See Details.
#' @param INDUSTRY_CLASS e.g. 'R'. See Details.
#' @param ORIGINL_PERMIT_ISSUE_DATE e.g. '14-APR-75'. See Details.
#' @param TYPE_OF_PERMIT_ISSUED e.g. 'E'. See Details.
#' @param RIVER_BASIN e.g. '160600'. See Details.
#' @param RECEIVING_WATERS e.g. 'UNALASKA BAY, ILIULIUK HARBOR'. See Details.
#' @param CURR_YEAR_MANL_QNCR_STAT e.g. 'NA'. See Details.
#' @param CURR_YEAR_AUTO_QNCR_STAT e.g. 'NA'. See Details.
#' @param PREV_YEAR_MANL_QNCR_STAT e.g. 'NA'. See Details.
#' @param PREV_YEAR_AUTO_QNCR_STAT e.g. 'NA'. See Details.
#' @param FEDERAL_GRANT_IND e.g. 'NA'. See Details.
#' @param FINAL_LIMITS_IND e.g. 'F'. See Details.
#' @param FLOW_RATE e.g. 'NA'. See Details.
#' @param PRETREATMENT_CODE e.g. 'NA'. See Details.
#' @param NMP_FINAN_STAT_CODE e.g. 'NA'. See Details.
#' @param NMP_FINAL_SCHED e.g. 'NA'. See Details.
#' @param NMP_QUARTER e.g. 'NA'. See Details.
#' @param LATITUDE e.g. '+5352440'. See Details.
#' @param LONGITUDE e.g. '-16632250'. See Details.
#' @param CODE_OF_ACCURACY e.g. 'NA'. See Details.
#' @param METHOD e.g. 'A'. See Details.
#' @param DATUM e.g. '1'. See Details.
#' @param SCALE e.g. 'U'. See Details.
#' @param DESCRIPT e.g. '01099'. See Details.
#' @param USGS_HYDRO_BASIN_CODE e.g. 'NA'. See Details.
#' @param STREAM_SEGMENT e.g. 'NA'. See Details.
#' @param MILEAGE_IND e.g. 'NA'. See Details.
#' @param RECVNG_STREAM_CLASS_CODE e.g. 'NA'. See Details.
#' @export

pcs.icis_pcs_permit_facility <- function(NPDES = NULL, NAME_1 = NULL, NAME_2 = NULL, 
    MAJOR_DISCHARGE_INDICATOR = NULL, REGION = NULL, CITY_CODE = NULL, CITY_NAME = NULL, 
    COUNTY_CODE = NULL, COUNTY_NAME = NULL, SIC_CODE = NULL, LOCATION_NAME = NULL, 
    LOCATION_STREET_1 = NULL, LOCATION_STREET_2 = NULL, LOCATION_CITY = NULL, LOCATION_STATE = NULL, 
    LOCATION_ZIP_CODE = NULL, LOCATION_TELEPHONE_NUMBER = NULL, MAILING_NAME = NULL, 
    MAILING_STREET_1 = NULL, MAILING_STREET_2 = NULL, MAILING_CITY = NULL, MAILING_STATE = NULL, 
    MAILING_ZIP_CODE = NULL, INACTIVE_CODE = NULL, PERMIT_EXPIRED_DATE = NULL, PERMIT_ISSUED_DATE = NULL, 
    DRAFT_PERM_PUB_NOTIF_DATE = NULL, APPL_RECEIVED_DATE = NULL, INACTIVE_DATE = NULL, 
    TYPE_OF_OWNERSHIP = NULL, COGN_OFFICIAL = NULL, COGN_OFFICIAL_TELE_NUMBER = NULL, 
    INDUSTRY_CLASS = NULL, ORIGINL_PERMIT_ISSUE_DATE = NULL, TYPE_OF_PERMIT_ISSUED = NULL, 
    RIVER_BASIN = NULL, RECEIVING_WATERS = NULL, CURR_YEAR_MANL_QNCR_STAT = NULL, 
    CURR_YEAR_AUTO_QNCR_STAT = NULL, PREV_YEAR_MANL_QNCR_STAT = NULL, PREV_YEAR_AUTO_QNCR_STAT = NULL, 
    FEDERAL_GRANT_IND = NULL, FINAL_LIMITS_IND = NULL, FLOW_RATE = NULL, PRETREATMENT_CODE = NULL, 
    NMP_FINAN_STAT_CODE = NULL, NMP_FINAL_SCHED = NULL, NMP_QUARTER = NULL, LATITUDE = NULL, 
    LONGITUDE = NULL, CODE_OF_ACCURACY = NULL, METHOD = NULL, DATUM = NULL, SCALE = NULL, 
    DESCRIPT = NULL, USGS_HYDRO_BASIN_CODE = NULL, STREAM_SEGMENT = NULL, MILEAGE_IND = NULL, 
    RECVNG_STREAM_CLASS_CODE = NULL) {
    
    args <- list(NPDES = NPDES, NAME_1 = NAME_1, NAME_2 = NAME_2, MAJOR_DISCHARGE_INDICATOR = MAJOR_DISCHARGE_INDICATOR, 
        REGION = REGION, CITY_CODE = CITY_CODE, CITY_NAME = CITY_NAME, COUNTY_CODE = COUNTY_CODE, 
        COUNTY_NAME = COUNTY_NAME, SIC_CODE = SIC_CODE, LOCATION_NAME = LOCATION_NAME, 
        LOCATION_STREET_1 = LOCATION_STREET_1, LOCATION_STREET_2 = LOCATION_STREET_2, 
        LOCATION_CITY = LOCATION_CITY, LOCATION_STATE = LOCATION_STATE, LOCATION_ZIP_CODE = LOCATION_ZIP_CODE, 
        LOCATION_TELEPHONE_NUMBER = LOCATION_TELEPHONE_NUMBER, MAILING_NAME = MAILING_NAME, 
        MAILING_STREET_1 = MAILING_STREET_1, MAILING_STREET_2 = MAILING_STREET_2, 
        MAILING_CITY = MAILING_CITY, MAILING_STATE = MAILING_STATE, MAILING_ZIP_CODE = MAILING_ZIP_CODE, 
        INACTIVE_CODE = INACTIVE_CODE, PERMIT_EXPIRED_DATE = PERMIT_EXPIRED_DATE, 
        PERMIT_ISSUED_DATE = PERMIT_ISSUED_DATE, DRAFT_PERM_PUB_NOTIF_DATE = DRAFT_PERM_PUB_NOTIF_DATE, 
        APPL_RECEIVED_DATE = APPL_RECEIVED_DATE, INACTIVE_DATE = INACTIVE_DATE, TYPE_OF_OWNERSHIP = TYPE_OF_OWNERSHIP, 
        COGN_OFFICIAL = COGN_OFFICIAL, COGN_OFFICIAL_TELE_NUMBER = COGN_OFFICIAL_TELE_NUMBER, 
        INDUSTRY_CLASS = INDUSTRY_CLASS, ORIGINL_PERMIT_ISSUE_DATE = ORIGINL_PERMIT_ISSUE_DATE, 
        TYPE_OF_PERMIT_ISSUED = TYPE_OF_PERMIT_ISSUED, RIVER_BASIN = RIVER_BASIN, 
        RECEIVING_WATERS = RECEIVING_WATERS, CURR_YEAR_MANL_QNCR_STAT = CURR_YEAR_MANL_QNCR_STAT, 
        CURR_YEAR_AUTO_QNCR_STAT = CURR_YEAR_AUTO_QNCR_STAT, PREV_YEAR_MANL_QNCR_STAT = PREV_YEAR_MANL_QNCR_STAT, 
        PREV_YEAR_AUTO_QNCR_STAT = PREV_YEAR_AUTO_QNCR_STAT, FEDERAL_GRANT_IND = FEDERAL_GRANT_IND, 
        FINAL_LIMITS_IND = FINAL_LIMITS_IND, FLOW_RATE = FLOW_RATE, PRETREATMENT_CODE = PRETREATMENT_CODE, 
        NMP_FINAN_STAT_CODE = NMP_FINAN_STAT_CODE, NMP_FINAL_SCHED = NMP_FINAL_SCHED, 
        NMP_QUARTER = NMP_QUARTER, LATITUDE = LATITUDE, LONGITUDE = LONGITUDE, CODE_OF_ACCURACY = CODE_OF_ACCURACY, 
        METHOD = METHOD, DATUM = DATUM, SCALE = SCALE, DESCRIPT = DESCRIPT, USGS_HYDRO_BASIN_CODE = USGS_HYDRO_BASIN_CODE, 
        STREAM_SEGMENT = STREAM_SEGMENT, MILEAGE_IND = MILEAGE_IND, RECVNG_STREAM_CLASS_CODE = RECVNG_STREAM_CLASS_CODE)
    ret <- envir_get(pcs_permit_facility, args)
    
    ret
} 
