#' Retrieve pcs pipe sched data from pcs-icis database
#' 
#' @param NPDES e.g. 'AK0000272'. See Details.
#' @param DISCHARGE_NUM e.g. 'SUM'. See Details.
#' @param REPORT_DESIG e.g. 'A'. See Details.
#' @param PIPE_SET_QUALIFIER e.g. '2'. See Details.
#' @param OUTFALL_TYPE_CODE e.g. 'NA'. See Details.
#' @param INIT_LIMITS_START_DATE e.g. 'NA'. See Details.
#' @param INIT_LIMITS_END_DATE e.g. 'NA'. See Details.
#' @param INTERIM_LIMITS_START_DATE e.g. 'NA'. See Details.
#' @param INTERIM_LIMITS_END_DATE e.g. 'NA'. See Details.
#' @param FINAL_LIMITS_START_DATE e.g. '31-MAY-96'. See Details.
#' @param FINAL_LIMITS_END_DATE e.g. '30-MAY-01'. See Details.
#' @param PIPE_DESC e.g. 'COMBINED BOD OF ALL STREAMS'. See Details.
#' @param INIT_RPT_DATE e.g. '01-JUN-96'. See Details.
#' @param UNITS_IN_RPT_PERIOD e.g. '1'. See Details.
#' @param REPORTING_UNITS e.g. 'M'. See Details.
#' @param PIPE_INACTIVE_CODE e.g. 'A'. See Details.
#' @param PIPE_INACTIVE_DATE e.g. 'NA'. See Details.
#' @param INIT_EPA_SUBMISSION_DATE e.g. '10-JUL-96'. See Details.
#' @param UNITS_IN_EPA_SUBM_PERIOD e.g. '1'. See Details.
#' @param EPA_SUBMISSION_UNITS e.g. 'M'. See Details.
#' @param INIT_STATE_SUBMISSION_DATE e.g. 'NA'. See Details.
#' @param UNITS_IN_STATE_SUBM_PERIOD e.g. '0'. See Details.
#' @param STATE_SUBMISSION_UNITS e.g. 'NA'. See Details.
#' @export

pcs.icis_pcs_pipe_sched <- function(NPDES = NULL, DISCHARGE_NUM = NULL, REPORT_DESIG = NULL, 
    PIPE_SET_QUALIFIER = NULL, OUTFALL_TYPE_CODE = NULL, INIT_LIMITS_START_DATE = NULL, 
    INIT_LIMITS_END_DATE = NULL, INTERIM_LIMITS_START_DATE = NULL, INTERIM_LIMITS_END_DATE = NULL, 
    FINAL_LIMITS_START_DATE = NULL, FINAL_LIMITS_END_DATE = NULL, PIPE_DESC = NULL, 
    INIT_RPT_DATE = NULL, UNITS_IN_RPT_PERIOD = NULL, REPORTING_UNITS = NULL, PIPE_INACTIVE_CODE = NULL, 
    PIPE_INACTIVE_DATE = NULL, INIT_EPA_SUBMISSION_DATE = NULL, UNITS_IN_EPA_SUBM_PERIOD = NULL, 
    EPA_SUBMISSION_UNITS = NULL, INIT_STATE_SUBMISSION_DATE = NULL, UNITS_IN_STATE_SUBM_PERIOD = NULL, 
    STATE_SUBMISSION_UNITS = NULL) {
    
    args <- list(NPDES = NPDES, DISCHARGE_NUM = DISCHARGE_NUM, REPORT_DESIG = REPORT_DESIG, 
        PIPE_SET_QUALIFIER = PIPE_SET_QUALIFIER, OUTFALL_TYPE_CODE = OUTFALL_TYPE_CODE, 
        INIT_LIMITS_START_DATE = INIT_LIMITS_START_DATE, INIT_LIMITS_END_DATE = INIT_LIMITS_END_DATE, 
        INTERIM_LIMITS_START_DATE = INTERIM_LIMITS_START_DATE, INTERIM_LIMITS_END_DATE = INTERIM_LIMITS_END_DATE, 
        FINAL_LIMITS_START_DATE = FINAL_LIMITS_START_DATE, FINAL_LIMITS_END_DATE = FINAL_LIMITS_END_DATE, 
        PIPE_DESC = PIPE_DESC, INIT_RPT_DATE = INIT_RPT_DATE, UNITS_IN_RPT_PERIOD = UNITS_IN_RPT_PERIOD, 
        REPORTING_UNITS = REPORTING_UNITS, PIPE_INACTIVE_CODE = PIPE_INACTIVE_CODE, 
        PIPE_INACTIVE_DATE = PIPE_INACTIVE_DATE, INIT_EPA_SUBMISSION_DATE = INIT_EPA_SUBMISSION_DATE, 
        UNITS_IN_EPA_SUBM_PERIOD = UNITS_IN_EPA_SUBM_PERIOD, EPA_SUBMISSION_UNITS = EPA_SUBMISSION_UNITS, 
        INIT_STATE_SUBMISSION_DATE = INIT_STATE_SUBMISSION_DATE, UNITS_IN_STATE_SUBM_PERIOD = UNITS_IN_STATE_SUBM_PERIOD, 
        STATE_SUBMISSION_UNITS = STATE_SUBMISSION_UNITS)
    ret <- envir_get(pcs_pipe_sched, args)
    
    ret
} 
