#' Retrieve rcr lu legal operating status data from rcrainfo database
#' 
#' @param OWNER e.g. 'HQ'. See Details.
#' @param LEG_OP_STATUS_CODE e.g. 'DLCP'. See Details.
#' @param ACTIVE_STATUS e.g. 'N'. See Details.
#' @param LEG_OP_STATUS_DESC e.g. 'DELISTED - CLOSED WITH WASTE IN PLACE'. See Details.
#' @param STRANGE_BUT_TRUE_FLAG e.g. 'N'. See Details.
#' @param SUBJECT_TO_INSPECTION e.g. 'N'. See Details.
#' @param PERMIT_PROGRESS e.g. '4'. See Details.
#' @param PERMITTING_WRKLD e.g. 'N'. See Details.
#' @param CLOSURE_WRKLD e.g. 'N'. See Details.
#' @param POST_CLOSURE_WRKLD e.g. 'N'. See Details.
#' @param SUBJECT_TO_CORRECTIVE_ACT e.g. 'N'. See Details.
#' @param CORRECTIVE_ACTION_WRKLD e.g. 'N'. See Details.
#' @param FULL_ENFORCEMENT e.g. 'N'. See Details.
#' @param OPERATING_TSDF e.g. 'N'. See Details.
#' @param SUBJCA_TSD_3004 e.g. 'N'. See Details.
#' @param SUBJCA_TSD_DISCRETION e.g. 'N'. See Details.
#' @param SUBJCA_NON_TSD e.g. '4'. See Details.
#' @param GPRA_PERMIT_2006_ACCOMPLISHED e.g. 'N'. See Details.
#' @param AS_FEDERALLY_REGULATED_TSDF e.g. 'N'. See Details.
#' @param AS_CONVERTER_TSDF e.g. 'N'. See Details.
#' @param AS_STATE_REGULATED_TSDF e.g. 'N'. See Details.
#' @param PERMIT_RENEWAL_WRKLD e.g. 'N'. See Details.
#' @export

rcrainfo_rcr_lu_legal_operating_status <- function(OWNER = NULL, LEG_OP_STATUS_CODE = NULL, 
    ACTIVE_STATUS = NULL, LEG_OP_STATUS_DESC = NULL, STRANGE_BUT_TRUE_FLAG = NULL, 
    SUBJECT_TO_INSPECTION = NULL, PERMIT_PROGRESS = NULL, PERMITTING_WRKLD = NULL, 
    CLOSURE_WRKLD = NULL, POST_CLOSURE_WRKLD = NULL, SUBJECT_TO_CORRECTIVE_ACT = NULL, 
    CORRECTIVE_ACTION_WRKLD = NULL, FULL_ENFORCEMENT = NULL, OPERATING_TSDF = NULL, 
    SUBJCA_TSD_3004 = NULL, SUBJCA_TSD_DISCRETION = NULL, SUBJCA_NON_TSD = NULL, 
    GPRA_PERMIT_2006_ACCOMPLISHED = NULL, AS_FEDERALLY_REGULATED_TSDF = NULL, AS_CONVERTER_TSDF = NULL, 
    AS_STATE_REGULATED_TSDF = NULL, PERMIT_RENEWAL_WRKLD = NULL) {
    
    args <- list(OWNER = OWNER, LEG_OP_STATUS_CODE = LEG_OP_STATUS_CODE, ACTIVE_STATUS = ACTIVE_STATUS, 
        LEG_OP_STATUS_DESC = LEG_OP_STATUS_DESC, STRANGE_BUT_TRUE_FLAG = STRANGE_BUT_TRUE_FLAG, 
        SUBJECT_TO_INSPECTION = SUBJECT_TO_INSPECTION, PERMIT_PROGRESS = PERMIT_PROGRESS, 
        PERMITTING_WRKLD = PERMITTING_WRKLD, CLOSURE_WRKLD = CLOSURE_WRKLD, POST_CLOSURE_WRKLD = POST_CLOSURE_WRKLD, 
        SUBJECT_TO_CORRECTIVE_ACT = SUBJECT_TO_CORRECTIVE_ACT, CORRECTIVE_ACTION_WRKLD = CORRECTIVE_ACTION_WRKLD, 
        FULL_ENFORCEMENT = FULL_ENFORCEMENT, OPERATING_TSDF = OPERATING_TSDF, SUBJCA_TSD_3004 = SUBJCA_TSD_3004, 
        SUBJCA_TSD_DISCRETION = SUBJCA_TSD_DISCRETION, SUBJCA_NON_TSD = SUBJCA_NON_TSD, 
        GPRA_PERMIT_2006_ACCOMPLISHED = GPRA_PERMIT_2006_ACCOMPLISHED, AS_FEDERALLY_REGULATED_TSDF = AS_FEDERALLY_REGULATED_TSDF, 
        AS_CONVERTER_TSDF = AS_CONVERTER_TSDF, AS_STATE_REGULATED_TSDF = AS_STATE_REGULATED_TSDF, 
        PERMIT_RENEWAL_WRKLD = PERMIT_RENEWAL_WRKLD)
    ret <- envir_get(rcr_lu_legal_operating_status, args)
    
    ret
} 
