#' Retrieve rcr hreport univ data from rcrainfo database
#' 
#' @param HANDLER_ID e.g. 'AK0000000323'. See Details.
#' @param ACTIVITY_LOCATION e.g. 'AK'. See Details.
#' @param SOURCE_TYPE e.g. 'N'. See Details.
#' @param SEQ_NUMBER e.g. '1'. See Details.
#' @param HANDLER_NAME e.g. 'USDA FS CHUGACH NF CORDOVA FOREST WORK C'. See Details.
#' @param NON_NOTIFIER e.g. 'NA'. See Details.
#' @param RECEIVE_DATE e.g. '17-SEP-93'. See Details.
#' @param REPORT_CYCLE e.g. 'NA'. See Details.
#' @param ACCESSIBILITY e.g. 'NA'. See Details.
#' @param REGION e.g. '10'. See Details.
#' @param STATE e.g. 'AK'. See Details.
#' @param EXTRACT_FLAG e.g. 'X'. See Details.
#' @param ACTIVE_SITE e.g. 'H----'. See Details.
#' @param LOCATION_STREET_NO e.g. 'NA'. See Details.
#' @param LOCATION_STREET1 e.g. 'COR LEFEVRE ST %26 COPPER RIV HW'. See Details.
#' @param LOCATION_STREET2 e.g. 'Y'. See Details.
#' @param LOCATION_CITY e.g. 'CORDOVA'. See Details.
#' @param LOCATION_STATE e.g. 'AK'. See Details.
#' @param LOCATION_ZIP e.g. '99574'. See Details.
#' @param LOCATION_COUNTY_CODE e.g. 'AK261'. See Details.
#' @param LOCATION_COUNTY_NAME e.g. 'VALDEZ-CORDOVA'. See Details.
#' @param LOCATION_COUNTRY e.g. 'NA'. See Details.
#' @param STATE_DISTRICT_OWNER e.g. 'NA'. See Details.
#' @param STATE_DISTRICT e.g. 'NA'. See Details.
#' @param LAND_TYPE e.g. 'F'. See Details.
#' @param MAIL_STREET_NO e.g. 'NA'. See Details.
#' @param MAIL_STREET1 e.g. 'PO BOX 280'. See Details.
#' @param MAIL_STREET2 e.g. 'NA'. See Details.
#' @param MAIL_CITY e.g. 'CORDOVA'. See Details.
#' @param MAIL_STATE e.g. 'AK'. See Details.
#' @param MAIL_ZIP e.g. '99574'. See Details.
#' @param MAIL_COUNTRY e.g. 'NA'. See Details.
#' @param CONTACT_NAME e.g. 'SARAH  BAKER'. See Details.
#' @param CONTACT_STREET_NO e.g. 'NA'. See Details.
#' @param CONTACT_STREET1 e.g. '3301 C ST STE 300'. See Details.
#' @param CONTACT_STREET2 e.g. 'NA'. See Details.
#' @param CONTACT_CITY e.g. 'ANCHORAGE'. See Details.
#' @param CONTACT_STATE e.g. 'AK'. See Details.
#' @param CONTACT_ZIP e.g. '995033998'. See Details.
#' @param CONTACT_COUNTRY e.g. 'US'. See Details.
#' @param CONTACT_PHONE_AND_EXT e.g. '9072712556'. See Details.
#' @param CONTACT_FAX e.g. 'NA'. See Details.
#' @param CONTACT_EMAIL_ADDRESS e.g. 'NA'. See Details.
#' @param CONTACT_TITLE e.g. 'NA'. See Details.
#' @param OWNER_NAME e.g. 'US FOREST SERVICE CHUGACH NF'. See Details.
#' @param OWNER_TYPE e.g. 'F'. See Details.
#' @param OWNER_SEQ e.g. '1'. See Details.
#' @param OPERATOR_NAME e.g. 'NA'. See Details.
#' @param OPERATOR_TYPE e.g. 'NA'. See Details.
#' @param OPERATOR_SEQ e.g. 'NA'. See Details.
#' @param NAIC1 e.g. 'NA'. See Details.
#' @param NAIC2 e.g. 'NA'. See Details.
#' @param NAIC3 e.g. 'NA'. See Details.
#' @param NAIC4 e.g. 'NA'. See Details.
#' @param IN_HANDLER_UNIVERSES e.g. 'Y'. See Details.
#' @param IN_A_UNIVERSE e.g. 'Y'. See Details.
#' @param FED_WASTE_GENERATOR_OWNER e.g. 'HQ'. See Details.
#' @param FED_WASTE_GENERATOR e.g. '3'. See Details.
#' @param STATE_WASTE_GENERATOR_OWNER e.g. 'NA'. See Details.
#' @param STATE_WASTE_GENERATOR e.g. 'NA'. See Details.
#' @param GENSTATUS e.g. 'CEG'. See Details.
#' @param SHORT_TERM_GENERATOR e.g. 'N'. See Details.
#' @param IMPORTER e.g. 'N'. See Details.
#' @param MIXED_WASTE_GENERATOR e.g. 'N'. See Details.
#' @param TRANSPORTER e.g. 'N'. See Details.
#' @param TRANSFER_FACILITY e.g. 'N'. See Details.
#' @param RECYCLER e.g. 'N'. See Details.
#' @param ONSITE_BURNER_EXEMPT e.g. 'N'. See Details.
#' @param FURNACE_EXEMPTION e.g. 'N'. See Details.
#' @param UNDERGROUND_INJECTION e.g. 'N'. See Details.
#' @param OFF_SITE_RECEIPT e.g. 'N'. See Details.
#' @param UNIVWASTE e.g. 'N'. See Details.
#' @param UNIVERSAL_WASTE_DEST_FACILITY e.g. 'N'. See Details.
#' @param USED_OIL e.g. 'NNNNNNN'. See Details.
#' @param FEDERAL_UNIVERSAL_WASTE e.g. 'N'. See Details.
#' @param AS_FEDERALLY_REGULATED_TSDF e.g. '------'. See Details.
#' @param AS_CONVERTER_TSDF e.g. '------'. See Details.
#' @param AS_STATE_REGULATED_TSDF e.g. '---------'. See Details.
#' @param FEDERAL_INDICATOR e.g. 'LO-'. See Details.
#' @param HSM e.g. 'N'. See Details.
#' @param SUBPART_K e.g. '----'. See Details.
#' @param COMMERCIAL_TSD e.g. 'N'. See Details.
#' @param TSD_TYPE e.g. '-----'. See Details.
#' @param GPRA_PERMIT e.g. 'N'. See Details.
#' @param GPRA_RENEWAL e.g. 'N'. See Details.
#' @param PERMIT_RENEWAL_WRKLD e.g. '------'. See Details.
#' @param PERMWRKLD e.g. '------'. See Details.
#' @param PERMPROG e.g. '------'. See Details.
#' @param PCWRKLD e.g. '------'. See Details.
#' @param CLOSWRKLD e.g. '------'. See Details.
#' @param GPRA_CA e.g. 'N'. See Details.
#' @param CAWRKLD e.g. 'N'. See Details.
#' @param SUBJCA e.g. 'N'. See Details.
#' @param SUBJCA_NON_TSD e.g. 'N'. See Details.
#' @param SUBJCA_TSD_3004 e.g. 'N'. See Details.
#' @param SUBJCA_TSD_DISCRETION e.g. 'N'. See Details.
#' @param NCAPS e.g. 'N'. See Details.
#' @param EC_INDICATOR e.g. 'N'. See Details.
#' @param IC_INDICATOR e.g. 'N'. See Details.
#' @param CA725_INDICATOR e.g. 'N'. See Details.
#' @param CA750_INDICATOR e.g. 'N'. See Details.
#' @param OPERATING_TSDF e.g. '------'. See Details.
#' @param FULL_ENFORCEMENT e.g. '------'. See Details.
#' @param SNC e.g. 'N'. See Details.
#' @param UNADDRESSED_SNC e.g. 'N'. See Details.
#' @param ADDRESSED_SNC e.g. 'N'. See Details.
#' @param SNC_WITH_COMP_SCHED e.g. 'N'. See Details.
#' @param FA_REQUIRED e.g. '-----'. See Details.
#' @param HHANDLER_LAST_CHANGE e.g. '15-SEP-00'. See Details.
#' @export

rcrainfo_rcr_hreport_univ <- function(HANDLER_ID = NULL, ACTIVITY_LOCATION = NULL, 
    SOURCE_TYPE = NULL, SEQ_NUMBER = NULL, HANDLER_NAME = NULL, NON_NOTIFIER = NULL, 
    RECEIVE_DATE = NULL, REPORT_CYCLE = NULL, ACCESSIBILITY = NULL, REGION = NULL, 
    STATE = NULL, EXTRACT_FLAG = NULL, ACTIVE_SITE = NULL, LOCATION_STREET_NO = NULL, 
    LOCATION_STREET1 = NULL, LOCATION_STREET2 = NULL, LOCATION_CITY = NULL, LOCATION_STATE = NULL, 
    LOCATION_ZIP = NULL, LOCATION_COUNTY_CODE = NULL, LOCATION_COUNTY_NAME = NULL, 
    LOCATION_COUNTRY = NULL, STATE_DISTRICT_OWNER = NULL, STATE_DISTRICT = NULL, 
    LAND_TYPE = NULL, MAIL_STREET_NO = NULL, MAIL_STREET1 = NULL, MAIL_STREET2 = NULL, 
    MAIL_CITY = NULL, MAIL_STATE = NULL, MAIL_ZIP = NULL, MAIL_COUNTRY = NULL, CONTACT_NAME = NULL, 
    CONTACT_STREET_NO = NULL, CONTACT_STREET1 = NULL, CONTACT_STREET2 = NULL, CONTACT_CITY = NULL, 
    CONTACT_STATE = NULL, CONTACT_ZIP = NULL, CONTACT_COUNTRY = NULL, CONTACT_PHONE_AND_EXT = NULL, 
    CONTACT_FAX = NULL, CONTACT_EMAIL_ADDRESS = NULL, CONTACT_TITLE = NULL, OWNER_NAME = NULL, 
    OWNER_TYPE = NULL, OWNER_SEQ = NULL, OPERATOR_NAME = NULL, OPERATOR_TYPE = NULL, 
    OPERATOR_SEQ = NULL, NAIC1 = NULL, NAIC2 = NULL, NAIC3 = NULL, NAIC4 = NULL, 
    IN_HANDLER_UNIVERSES = NULL, IN_A_UNIVERSE = NULL, FED_WASTE_GENERATOR_OWNER = NULL, 
    FED_WASTE_GENERATOR = NULL, STATE_WASTE_GENERATOR_OWNER = NULL, STATE_WASTE_GENERATOR = NULL, 
    GENSTATUS = NULL, SHORT_TERM_GENERATOR = NULL, IMPORTER = NULL, MIXED_WASTE_GENERATOR = NULL, 
    TRANSPORTER = NULL, TRANSFER_FACILITY = NULL, RECYCLER = NULL, ONSITE_BURNER_EXEMPT = NULL, 
    FURNACE_EXEMPTION = NULL, UNDERGROUND_INJECTION = NULL, OFF_SITE_RECEIPT = NULL, 
    UNIVWASTE = NULL, UNIVERSAL_WASTE_DEST_FACILITY = NULL, USED_OIL = NULL, FEDERAL_UNIVERSAL_WASTE = NULL, 
    AS_FEDERALLY_REGULATED_TSDF = NULL, AS_CONVERTER_TSDF = NULL, AS_STATE_REGULATED_TSDF = NULL, 
    FEDERAL_INDICATOR = NULL, HSM = NULL, SUBPART_K = NULL, COMMERCIAL_TSD = NULL, 
    TSD_TYPE = NULL, GPRA_PERMIT = NULL, GPRA_RENEWAL = NULL, PERMIT_RENEWAL_WRKLD = NULL, 
    PERMWRKLD = NULL, PERMPROG = NULL, PCWRKLD = NULL, CLOSWRKLD = NULL, GPRA_CA = NULL, 
    CAWRKLD = NULL, SUBJCA = NULL, SUBJCA_NON_TSD = NULL, SUBJCA_TSD_3004 = NULL, 
    SUBJCA_TSD_DISCRETION = NULL, NCAPS = NULL, EC_INDICATOR = NULL, IC_INDICATOR = NULL, 
    CA725_INDICATOR = NULL, CA750_INDICATOR = NULL, OPERATING_TSDF = NULL, FULL_ENFORCEMENT = NULL, 
    SNC = NULL, UNADDRESSED_SNC = NULL, ADDRESSED_SNC = NULL, SNC_WITH_COMP_SCHED = NULL, 
    FA_REQUIRED = NULL, HHANDLER_LAST_CHANGE = NULL) {
    
    args <- list(HANDLER_ID = HANDLER_ID, ACTIVITY_LOCATION = ACTIVITY_LOCATION, 
        SOURCE_TYPE = SOURCE_TYPE, SEQ_NUMBER = SEQ_NUMBER, HANDLER_NAME = HANDLER_NAME, 
        NON_NOTIFIER = NON_NOTIFIER, RECEIVE_DATE = RECEIVE_DATE, REPORT_CYCLE = REPORT_CYCLE, 
        ACCESSIBILITY = ACCESSIBILITY, REGION = REGION, STATE = STATE, EXTRACT_FLAG = EXTRACT_FLAG, 
        ACTIVE_SITE = ACTIVE_SITE, LOCATION_STREET_NO = LOCATION_STREET_NO, LOCATION_STREET1 = LOCATION_STREET1, 
        LOCATION_STREET2 = LOCATION_STREET2, LOCATION_CITY = LOCATION_CITY, LOCATION_STATE = LOCATION_STATE, 
        LOCATION_ZIP = LOCATION_ZIP, LOCATION_COUNTY_CODE = LOCATION_COUNTY_CODE, 
        LOCATION_COUNTY_NAME = LOCATION_COUNTY_NAME, LOCATION_COUNTRY = LOCATION_COUNTRY, 
        STATE_DISTRICT_OWNER = STATE_DISTRICT_OWNER, STATE_DISTRICT = STATE_DISTRICT, 
        LAND_TYPE = LAND_TYPE, MAIL_STREET_NO = MAIL_STREET_NO, MAIL_STREET1 = MAIL_STREET1, 
        MAIL_STREET2 = MAIL_STREET2, MAIL_CITY = MAIL_CITY, MAIL_STATE = MAIL_STATE, 
        MAIL_ZIP = MAIL_ZIP, MAIL_COUNTRY = MAIL_COUNTRY, CONTACT_NAME = CONTACT_NAME, 
        CONTACT_STREET_NO = CONTACT_STREET_NO, CONTACT_STREET1 = CONTACT_STREET1, 
        CONTACT_STREET2 = CONTACT_STREET2, CONTACT_CITY = CONTACT_CITY, CONTACT_STATE = CONTACT_STATE, 
        CONTACT_ZIP = CONTACT_ZIP, CONTACT_COUNTRY = CONTACT_COUNTRY, CONTACT_PHONE_AND_EXT = CONTACT_PHONE_AND_EXT, 
        CONTACT_FAX = CONTACT_FAX, CONTACT_EMAIL_ADDRESS = CONTACT_EMAIL_ADDRESS, 
        CONTACT_TITLE = CONTACT_TITLE, OWNER_NAME = OWNER_NAME, OWNER_TYPE = OWNER_TYPE, 
        OWNER_SEQ = OWNER_SEQ, OPERATOR_NAME = OPERATOR_NAME, OPERATOR_TYPE = OPERATOR_TYPE, 
        OPERATOR_SEQ = OPERATOR_SEQ, NAIC1 = NAIC1, NAIC2 = NAIC2, NAIC3 = NAIC3, 
        NAIC4 = NAIC4, IN_HANDLER_UNIVERSES = IN_HANDLER_UNIVERSES, IN_A_UNIVERSE = IN_A_UNIVERSE, 
        FED_WASTE_GENERATOR_OWNER = FED_WASTE_GENERATOR_OWNER, FED_WASTE_GENERATOR = FED_WASTE_GENERATOR, 
        STATE_WASTE_GENERATOR_OWNER = STATE_WASTE_GENERATOR_OWNER, STATE_WASTE_GENERATOR = STATE_WASTE_GENERATOR, 
        GENSTATUS = GENSTATUS, SHORT_TERM_GENERATOR = SHORT_TERM_GENERATOR, IMPORTER = IMPORTER, 
        MIXED_WASTE_GENERATOR = MIXED_WASTE_GENERATOR, TRANSPORTER = TRANSPORTER, 
        TRANSFER_FACILITY = TRANSFER_FACILITY, RECYCLER = RECYCLER, ONSITE_BURNER_EXEMPT = ONSITE_BURNER_EXEMPT, 
        FURNACE_EXEMPTION = FURNACE_EXEMPTION, UNDERGROUND_INJECTION = UNDERGROUND_INJECTION, 
        OFF_SITE_RECEIPT = OFF_SITE_RECEIPT, UNIVWASTE = UNIVWASTE, UNIVERSAL_WASTE_DEST_FACILITY = UNIVERSAL_WASTE_DEST_FACILITY, 
        USED_OIL = USED_OIL, FEDERAL_UNIVERSAL_WASTE = FEDERAL_UNIVERSAL_WASTE, AS_FEDERALLY_REGULATED_TSDF = AS_FEDERALLY_REGULATED_TSDF, 
        AS_CONVERTER_TSDF = AS_CONVERTER_TSDF, AS_STATE_REGULATED_TSDF = AS_STATE_REGULATED_TSDF, 
        FEDERAL_INDICATOR = FEDERAL_INDICATOR, HSM = HSM, SUBPART_K = SUBPART_K, 
        COMMERCIAL_TSD = COMMERCIAL_TSD, TSD_TYPE = TSD_TYPE, GPRA_PERMIT = GPRA_PERMIT, 
        GPRA_RENEWAL = GPRA_RENEWAL, PERMIT_RENEWAL_WRKLD = PERMIT_RENEWAL_WRKLD, 
        PERMWRKLD = PERMWRKLD, PERMPROG = PERMPROG, PCWRKLD = PCWRKLD, CLOSWRKLD = CLOSWRKLD, 
        GPRA_CA = GPRA_CA, CAWRKLD = CAWRKLD, SUBJCA = SUBJCA, SUBJCA_NON_TSD = SUBJCA_NON_TSD, 
        SUBJCA_TSD_3004 = SUBJCA_TSD_3004, SUBJCA_TSD_DISCRETION = SUBJCA_TSD_DISCRETION, 
        NCAPS = NCAPS, EC_INDICATOR = EC_INDICATOR, IC_INDICATOR = IC_INDICATOR, 
        CA725_INDICATOR = CA725_INDICATOR, CA750_INDICATOR = CA750_INDICATOR, OPERATING_TSDF = OPERATING_TSDF, 
        FULL_ENFORCEMENT = FULL_ENFORCEMENT, SNC = SNC, UNADDRESSED_SNC = UNADDRESSED_SNC, 
        ADDRESSED_SNC = ADDRESSED_SNC, SNC_WITH_COMP_SCHED = SNC_WITH_COMP_SCHED, 
        FA_REQUIRED = FA_REQUIRED, HHANDLER_LAST_CHANGE = HHANDLER_LAST_CHANGE)
    ret <- envir_get(rcr_hreport_univ, args)
    
    ret
} 
