#' Retrieve water system data from sdwis database
#' 
#' @param PWSID e.g. '010106001'. See Details.
#' @param PWS_NAME e.g. 'Mashantucket Pequot Water System'. See Details.
#' @param NPM_CANDIDATE e.g. 'Y'. See Details.
#' @param PRIMACY_AGENCY_CODE e.g. '01'. See Details.
#' @param EPA_REGION e.g. '01'. See Details.
#' @param SEASON_BEGIN_DATE e.g. 'NA'. See Details.
#' @param SEASON_END_DATE e.g. 'NA'. See Details.
#' @param PWS_ACTIVITY_CODE e.g. 'A'. See Details.
#' @param PWS_DEACTIVATION_DATE e.g. 'NA'. See Details.
#' @param PWS_TYPE_CODE e.g. 'CWS'. See Details.
#' @param DBPR_SCHEDULE_CAT_CODE e.g. 'NA'. See Details.
#' @param CDS_ID e.g. 'NA'. See Details.
#' @param GW_SW_CODE e.g. 'SW'. See Details.
#' @param LT2_SCHEDULE_CAT_CODE e.g. 'NA'. See Details.
#' @param OWNER_TYPE_CODE e.g. 'N'. See Details.
#' @param POPULATION_SERVED_COUNT e.g. '39552'. See Details.
#' @param POP_CAT_2_CODE e.g. '2'. See Details.
#' @param POP_CAT_3_CODE e.g. '2'. See Details.
#' @param POP_CAT_4_CODE e.g. '2'. See Details.
#' @param POP_CAT_5_CODE e.g. '4'. See Details.
#' @param POP_CAT_11_CODE e.g. '6'. See Details.
#' @param PRIMACY_TYPE e.g. 'Tribal'. See Details.
#' @param PRIMARY_SOURCE_CODE e.g. 'GU'. See Details.
#' @param IS_GRANT_ELIGIBLE_IND e.g. 'Y'. See Details.
#' @param IS_WHOLESALER_IND e.g. 'Y'. See Details.
#' @param IS_SCHOOL_OR_DAYCARE_IND e.g. 'N'. See Details.
#' @param SERVICE_CONNECTIONS_COUNT e.g. '143'. See Details.
#' @param SUBMISSION_STATUS_CODE e.g. 'Y'. See Details.
#' @param ORG_NAME e.g. 'Mashantucket Pequot Tribal Utilities'. See Details.
#' @param ADMIN_NAME e.g. 'Rodney Butler'. See Details.
#' @param EMAIL_ADDR e.g. 'NA'. See Details.
#' @param PHONE_NUMBER e.g. '8603966740'. See Details.
#' @param PHONE_EXT_NUMBER e.g. 'NA'. See Details.
#' @param FAX_NUMBER e.g. 'NA'. See Details.
#' @param ALT_PHONE_NUMBER e.g. 'NA'. See Details.
#' @param ADDRESS_LINE1 e.g. 'Tribal Office'. See Details.
#' @param ADDRESS_LINE2 e.g. 'Indiantown Rd, - PO BOX 3060'. See Details.
#' @param CITY_NAME e.g. 'MASHANTUCKET'. See Details.
#' @param ZIP_CODE e.g. '06339-3060'. See Details.
#' @param COUNTRY_CODE e.g. 'US'. See Details.
#' @param STATE_CODE e.g. 'CT'. See Details.
#' @param SOURCE_WATER_PROTECTION_CODE e.g. 'NA'. See Details.
#' @param SOURCE_PROTECTION_BEGIN_DATE e.g. 'NA'. See Details.
#' @param OUTSTANDING_PERFORMER e.g. 'NA'. See Details.
#' @param OUTSTANDING_PERFORM_BEGIN_DATE e.g. 'NA'. See Details.
#' @param CITIES_SERVED e.g. 'Not Reported'. See Details.
#' @param COUNTIES_SERVED e.g. 'Not Reported'. See Details.
#' @export

sdwis_water_system <- function(PWSID = NULL, PWS_NAME = NULL, NPM_CANDIDATE = NULL, 
    PRIMACY_AGENCY_CODE = NULL, EPA_REGION = NULL, SEASON_BEGIN_DATE = NULL, SEASON_END_DATE = NULL, 
    PWS_ACTIVITY_CODE = NULL, PWS_DEACTIVATION_DATE = NULL, PWS_TYPE_CODE = NULL, 
    DBPR_SCHEDULE_CAT_CODE = NULL, CDS_ID = NULL, GW_SW_CODE = NULL, LT2_SCHEDULE_CAT_CODE = NULL, 
    OWNER_TYPE_CODE = NULL, POPULATION_SERVED_COUNT = NULL, POP_CAT_2_CODE = NULL, 
    POP_CAT_3_CODE = NULL, POP_CAT_4_CODE = NULL, POP_CAT_5_CODE = NULL, POP_CAT_11_CODE = NULL, 
    PRIMACY_TYPE = NULL, PRIMARY_SOURCE_CODE = NULL, IS_GRANT_ELIGIBLE_IND = NULL, 
    IS_WHOLESALER_IND = NULL, IS_SCHOOL_OR_DAYCARE_IND = NULL, SERVICE_CONNECTIONS_COUNT = NULL, 
    SUBMISSION_STATUS_CODE = NULL, ORG_NAME = NULL, ADMIN_NAME = NULL, EMAIL_ADDR = NULL, 
    PHONE_NUMBER = NULL, PHONE_EXT_NUMBER = NULL, FAX_NUMBER = NULL, ALT_PHONE_NUMBER = NULL, 
    ADDRESS_LINE1 = NULL, ADDRESS_LINE2 = NULL, CITY_NAME = NULL, ZIP_CODE = NULL, 
    COUNTRY_CODE = NULL, STATE_CODE = NULL, SOURCE_WATER_PROTECTION_CODE = NULL, 
    SOURCE_PROTECTION_BEGIN_DATE = NULL, OUTSTANDING_PERFORMER = NULL, OUTSTANDING_PERFORM_BEGIN_DATE = NULL, 
    CITIES_SERVED = NULL, COUNTIES_SERVED = NULL) {
    
    args <- list(PWSID = PWSID, PWS_NAME = PWS_NAME, NPM_CANDIDATE = NPM_CANDIDATE, 
        PRIMACY_AGENCY_CODE = PRIMACY_AGENCY_CODE, EPA_REGION = EPA_REGION, SEASON_BEGIN_DATE = SEASON_BEGIN_DATE, 
        SEASON_END_DATE = SEASON_END_DATE, PWS_ACTIVITY_CODE = PWS_ACTIVITY_CODE, 
        PWS_DEACTIVATION_DATE = PWS_DEACTIVATION_DATE, PWS_TYPE_CODE = PWS_TYPE_CODE, 
        DBPR_SCHEDULE_CAT_CODE = DBPR_SCHEDULE_CAT_CODE, CDS_ID = CDS_ID, GW_SW_CODE = GW_SW_CODE, 
        LT2_SCHEDULE_CAT_CODE = LT2_SCHEDULE_CAT_CODE, OWNER_TYPE_CODE = OWNER_TYPE_CODE, 
        POPULATION_SERVED_COUNT = POPULATION_SERVED_COUNT, POP_CAT_2_CODE = POP_CAT_2_CODE, 
        POP_CAT_3_CODE = POP_CAT_3_CODE, POP_CAT_4_CODE = POP_CAT_4_CODE, POP_CAT_5_CODE = POP_CAT_5_CODE, 
        POP_CAT_11_CODE = POP_CAT_11_CODE, PRIMACY_TYPE = PRIMACY_TYPE, PRIMARY_SOURCE_CODE = PRIMARY_SOURCE_CODE, 
        IS_GRANT_ELIGIBLE_IND = IS_GRANT_ELIGIBLE_IND, IS_WHOLESALER_IND = IS_WHOLESALER_IND, 
        IS_SCHOOL_OR_DAYCARE_IND = IS_SCHOOL_OR_DAYCARE_IND, SERVICE_CONNECTIONS_COUNT = SERVICE_CONNECTIONS_COUNT, 
        SUBMISSION_STATUS_CODE = SUBMISSION_STATUS_CODE, ORG_NAME = ORG_NAME, ADMIN_NAME = ADMIN_NAME, 
        EMAIL_ADDR = EMAIL_ADDR, PHONE_NUMBER = PHONE_NUMBER, PHONE_EXT_NUMBER = PHONE_EXT_NUMBER, 
        FAX_NUMBER = FAX_NUMBER, ALT_PHONE_NUMBER = ALT_PHONE_NUMBER, ADDRESS_LINE1 = ADDRESS_LINE1, 
        ADDRESS_LINE2 = ADDRESS_LINE2, CITY_NAME = CITY_NAME, ZIP_CODE = ZIP_CODE, 
        COUNTRY_CODE = COUNTRY_CODE, STATE_CODE = STATE_CODE, SOURCE_WATER_PROTECTION_CODE = SOURCE_WATER_PROTECTION_CODE, 
        SOURCE_PROTECTION_BEGIN_DATE = SOURCE_PROTECTION_BEGIN_DATE, OUTSTANDING_PERFORMER = OUTSTANDING_PERFORMER, 
        OUTSTANDING_PERFORM_BEGIN_DATE = OUTSTANDING_PERFORM_BEGIN_DATE, CITIES_SERVED = CITIES_SERVED, 
        COUNTIES_SERVED = COUNTIES_SERVED)
    ret <- envir_get("water_system", args)
    
    ret
} 
