#' Retrieve enforcement action data from sdwis database
#' 
#' @param PWSID e.g. '010106001'. See Details.
#' @param ENFORCEMENT_ID e.g. '0106001IF9/27/2010'. See Details.
#' @param ORIGINATOR_CODE e.g. 'R'. See Details.
#' @param ENFORCEMENT_DATE e.g. '27-SEP-10'. See Details.
#' @param ENFORCEMENT_ACTION_TYPE_CODE e.g. 'EIF'. See Details.
#' @param ENFORCEMENT_COMMENT_TEXT e.g. 'Lead and Copper Results Notification - Action auto-generated by DIME based upon Public Notice records.'. See Details.
#' @export

sdwis_enforcement_action <- function(PWSID = NULL, ENFORCEMENT_ID = NULL, ORIGINATOR_CODE = NULL, 
    ENFORCEMENT_DATE = NULL, ENFORCEMENT_ACTION_TYPE_CODE = NULL, ENFORCEMENT_COMMENT_TEXT = NULL) {
    
    args <- list(PWSID = PWSID, ENFORCEMENT_ID = ENFORCEMENT_ID, ORIGINATOR_CODE = ORIGINATOR_CODE, 
        ENFORCEMENT_DATE = ENFORCEMENT_DATE, ENFORCEMENT_ACTION_TYPE_CODE = ENFORCEMENT_ACTION_TYPE_CODE, 
        ENFORCEMENT_COMMENT_TEXT = ENFORCEMENT_COMMENT_TEXT)
    ret <- envir_get(enforcement_action, args)
    
    ret
} 
