#' Retrieve water system facility data from sdwis database
#' 
#' @param PWSID e.g. '010106001'. See Details.
#' @param PRIMACY_AGENCY_CODE e.g. '01'. See Details.
#' @param EPA_REGION e.g. '01'. See Details.
#' @param FACILITY_ID e.g. '0106001GW007'. See Details.
#' @param FACILITY_NAME e.g. 'Well #2a (Southern Wellfield)'. See Details.
#' @param STATE_FACILITY_ID e.g. '010106001GW007'. See Details.
#' @param FACILITY_ACTIVITY_CODE e.g. 'A'. See Details.
#' @param FACILITY_DEACTIVATION_DATE e.g. 'NA'. See Details.
#' @param FACILITY_TYPE_CODE e.g. 'WL'. See Details.
#' @param SUBMISSION_STATUS_CODE e.g. 'Y'. See Details.
#' @param IS_SOURCE_IND e.g. 'Y'. See Details.
#' @param WATER_TYPE_CODE e.g. 'GW'. See Details.
#' @param AVAILABILITY_CODE e.g. 'P'. See Details.
#' @param SELLER_TREATMENT_CODE e.g. 'NA'. See Details.
#' @param SELLER_PWSID e.g. 'NA'. See Details.
#' @param SELLER_PWS_NAME e.g. 'NA'. See Details.
#' @param FILTRATION_STATUS_CODE e.g. 'NA'. See Details.
#' @param PWS_ACTIVITY_CODE e.g. 'A'. See Details.
#' @param PWS_DEACTIVATION_DATE e.g. 'NA'. See Details.
#' @param PWS_TYPE_CODE e.g. 'CWS'. See Details.
#' @param IS_SOURCE_TREATED_IND e.g. 'NA'. See Details.
#' @export

sdwis_water_system_facility <- function(PWSID = NULL, PRIMACY_AGENCY_CODE = NULL, 
    EPA_REGION = NULL, FACILITY_ID = NULL, FACILITY_NAME = NULL, STATE_FACILITY_ID = NULL, 
    FACILITY_ACTIVITY_CODE = NULL, FACILITY_DEACTIVATION_DATE = NULL, FACILITY_TYPE_CODE = NULL, 
    SUBMISSION_STATUS_CODE = NULL, IS_SOURCE_IND = NULL, WATER_TYPE_CODE = NULL, 
    AVAILABILITY_CODE = NULL, SELLER_TREATMENT_CODE = NULL, SELLER_PWSID = NULL, 
    SELLER_PWS_NAME = NULL, FILTRATION_STATUS_CODE = NULL, PWS_ACTIVITY_CODE = NULL, 
    PWS_DEACTIVATION_DATE = NULL, PWS_TYPE_CODE = NULL, IS_SOURCE_TREATED_IND = NULL) {
    
    args <- list(PWSID = PWSID, PRIMACY_AGENCY_CODE = PRIMACY_AGENCY_CODE, EPA_REGION = EPA_REGION, 
        FACILITY_ID = FACILITY_ID, FACILITY_NAME = FACILITY_NAME, STATE_FACILITY_ID = STATE_FACILITY_ID, 
        FACILITY_ACTIVITY_CODE = FACILITY_ACTIVITY_CODE, FACILITY_DEACTIVATION_DATE = FACILITY_DEACTIVATION_DATE, 
        FACILITY_TYPE_CODE = FACILITY_TYPE_CODE, SUBMISSION_STATUS_CODE = SUBMISSION_STATUS_CODE, 
        IS_SOURCE_IND = IS_SOURCE_IND, WATER_TYPE_CODE = WATER_TYPE_CODE, AVAILABILITY_CODE = AVAILABILITY_CODE, 
        SELLER_TREATMENT_CODE = SELLER_TREATMENT_CODE, SELLER_PWSID = SELLER_PWSID, 
        SELLER_PWS_NAME = SELLER_PWS_NAME, FILTRATION_STATUS_CODE = FILTRATION_STATUS_CODE, 
        PWS_ACTIVITY_CODE = PWS_ACTIVITY_CODE, PWS_DEACTIVATION_DATE = PWS_DEACTIVATION_DATE, 
        PWS_TYPE_CODE = PWS_TYPE_CODE, IS_SOURCE_TREATED_IND = IS_SOURCE_TREATED_IND)
    ret <- envir_get("water_system_facility", args)
    
    ret
} 
