#' Retrieve tri form r schedule one data from tri database
#' 
#' @param DOC_CTRL_NUM e.g. '1307209856564'. See Details.
#' @param ENVIRONMENTAL_MEDIUM e.g. 'POTW'. See Details.
#' @param SEQUENCE_NUM e.g. '1'. See Details.
#' @param OFF_SITE_AMOUNT_SEQUENCE e.g. '1'. See Details.
#' @param TYPE_OF_WASTE_MANAGEMENT e.g. 'NA'. See Details.
#' @param TOTAL_RELEASE e.g. 'NA'. See Details.
#' @param RELEASE_NA e.g. '1'. See Details.
#' @param CALCULATED_TEQ e.g. '0'. See Details.
#' @param DIOXIN_CONGENER1 e.g. 'NA'. See Details.
#' @param DIOXIN_CONGENER2 e.g. 'NA'. See Details.
#' @param DIOXIN_CONGENER3 e.g. 'NA'. See Details.
#' @param DIOXIN_CONGENER4 e.g. 'NA'. See Details.
#' @param DIOXIN_CONGENER5 e.g. 'NA'. See Details.
#' @param DIOXIN_CONGENER6 e.g. 'NA'. See Details.
#' @param DIOXIN_CONGENER7 e.g. 'NA'. See Details.
#' @param DIOXIN_CONGENER8 e.g. 'NA'. See Details.
#' @param DIOXIN_CONGENER9 e.g. 'NA'. See Details.
#' @param DIOXIN_CONGENER10 e.g. 'NA'. See Details.
#' @param DIOXIN_CONGENER11 e.g. 'NA'. See Details.
#' @param DIOXIN_CONGENER12 e.g. 'NA'. See Details.
#' @param DIOXIN_CONGENER13 e.g. 'NA'. See Details.
#' @param DIOXIN_CONGENER14 e.g. 'NA'. See Details.
#' @param DIOXIN_CONGENER15 e.g. 'NA'. See Details.
#' @param DIOXIN_CONGENER16 e.g. 'NA'. See Details.
#' @param DIOXIN_CONGENER17 e.g. 'NA'. See Details.
#' @export

tri_tri_form_r_schedule_one <- function(DOC_CTRL_NUM = NULL, ENVIRONMENTAL_MEDIUM = NULL, SEQUENCE_NUM = NULL, OFF_SITE_AMOUNT_SEQUENCE = NULL, 
    TYPE_OF_WASTE_MANAGEMENT = NULL, TOTAL_RELEASE = NULL, RELEASE_NA = NULL, CALCULATED_TEQ = NULL, DIOXIN_CONGENER1 = NULL, 
    DIOXIN_CONGENER2 = NULL, DIOXIN_CONGENER3 = NULL, DIOXIN_CONGENER4 = NULL, DIOXIN_CONGENER5 = NULL, DIOXIN_CONGENER6 = NULL, 
    DIOXIN_CONGENER7 = NULL, DIOXIN_CONGENER8 = NULL, DIOXIN_CONGENER9 = NULL, DIOXIN_CONGENER10 = NULL, DIOXIN_CONGENER11 = NULL, 
    DIOXIN_CONGENER12 = NULL, DIOXIN_CONGENER13 = NULL, DIOXIN_CONGENER14 = NULL, DIOXIN_CONGENER15 = NULL, DIOXIN_CONGENER16 = NULL, 
    DIOXIN_CONGENER17 = NULL) {
    
    args <- list(DOC_CTRL_NUM = DOC_CTRL_NUM, ENVIRONMENTAL_MEDIUM = ENVIRONMENTAL_MEDIUM, SEQUENCE_NUM = SEQUENCE_NUM, 
        OFF_SITE_AMOUNT_SEQUENCE = OFF_SITE_AMOUNT_SEQUENCE, TYPE_OF_WASTE_MANAGEMENT = TYPE_OF_WASTE_MANAGEMENT, TOTAL_RELEASE = TOTAL_RELEASE, 
        RELEASE_NA = RELEASE_NA, CALCULATED_TEQ = CALCULATED_TEQ, DIOXIN_CONGENER1 = DIOXIN_CONGENER1, DIOXIN_CONGENER2 = DIOXIN_CONGENER2, 
        DIOXIN_CONGENER3 = DIOXIN_CONGENER3, DIOXIN_CONGENER4 = DIOXIN_CONGENER4, DIOXIN_CONGENER5 = DIOXIN_CONGENER5, 
        DIOXIN_CONGENER6 = DIOXIN_CONGENER6, DIOXIN_CONGENER7 = DIOXIN_CONGENER7, DIOXIN_CONGENER8 = DIOXIN_CONGENER8, 
        DIOXIN_CONGENER9 = DIOXIN_CONGENER9, DIOXIN_CONGENER10 = DIOXIN_CONGENER10, DIOXIN_CONGENER11 = DIOXIN_CONGENER11, 
        DIOXIN_CONGENER12 = DIOXIN_CONGENER12, DIOXIN_CONGENER13 = DIOXIN_CONGENER13, DIOXIN_CONGENER14 = DIOXIN_CONGENER14, 
        DIOXIN_CONGENER15 = DIOXIN_CONGENER15, DIOXIN_CONGENER16 = DIOXIN_CONGENER16, DIOXIN_CONGENER17 = DIOXIN_CONGENER17)
    ret <- envir_get("tri_form_r_schedule_one", args)
    
    ret
} 
