#' Retrieve tri facility data from tri database
#' 
#' @param TRI_FACILITY_ID e.g. '00602BXTRF111CO'. See Details.
#' @param FACILITY_NAME e.g. 'BAXTER HEALTHCARE CORP., FENWAL DIV.'. See Details.
#' @param STREET_ADDRESS e.g. '111 COLON ST.'. See Details.
#' @param CITY_NAME e.g. 'AGUADA'. See Details.
#' @param COUNTY_NAME e.g. 'AGUADA'. See Details.
#' @param STATE_COUNTY_FIPS_CODE e.g. '72003'. See Details.
#' @param STATE_ABBR e.g. 'PR'. See Details.
#' @param ZIP_CODE e.g. '00602'. See Details.
#' @param REGION e.g. '2'. See Details.
#' @param FAC_CLOSED_IND e.g. '1'. See Details.
#' @param MAIL_NAME e.g. 'BAXTER HEALTHCARE CORP., FENWAL DIV.'. See Details.
#' @param MAIL_STREET_ADDRESS e.g. '111 COLON ST.'. See Details.
#' @param MAIL_CITY e.g. 'AGUADA'. See Details.
#' @param MAIL_STATE_ABBR e.g. 'PR'. See Details.
#' @param MAIL_PROVINCE e.g. 'NA'. See Details.
#' @param MAIL_COUNTRY e.g. 'NA'. See Details.
#' @param MAIL_ZIP_CODE e.g. '00602-'. See Details.
#' @param ASGN_FEDERAL_IND e.g. 'C'. See Details.
#' @param ASGN_AGENCY e.g. 'NA'. See Details.
#' @param FRS_ID e.g. 'NA'. See Details.
#' @param PARENT_CO_DB_NUM e.g. '080532250'. See Details.
#' @param PARENT_CO_NAME e.g. 'BAXTER SALES CORP'. See Details.
#' @param FAC_LATITUDE e.g. '182848'. See Details.
#' @param FAC_LONGITUDE e.g. '671106'. See Details.
#' @param PREF_LATITUDE e.g. '18.48'. See Details.
#' @param PREF_LONGITUDE e.g. '67.185'. See Details.
#' @param PREF_ACCURACY e.g. '11000'. See Details.
#' @param PREF_COLLECT_METH e.g. 'UN'. See Details.
#' @param PREF_DESC_CATEGORY e.g. 'UN'. See Details.
#' @param PREF_HORIZONTAL_DATUM e.g. '1'. See Details.
#' @param PREF_SOURCE_SCALE e.g. 'U'. See Details.
#' @param PREF_QA_CODE e.g. '0100'. See Details.
#' @param ASGN_PARTIAL_IND e.g. '0'. See Details.
#' @param ASGN_PUBLIC_CONTACT e.g. 'MARIO LUCENA'. See Details.
#' @param ASGN_PUBLIC_PHONE e.g. '8098383000'. See Details.
#' @param ASGN_PUBLIC_CONTACT_EMAIL e.g. 'NA'. See Details.
#' @param BIA_CODE e.g. 'NA'. See Details.
#' @param STANDARDIZED_PARENT_COMPANY e.g. 'NA'. See Details.
#' @param ASGN_PUBLIC_PHONE_EXT e.g. 'NA'. See Details.
#' @export

tri_tri_facility <- function(TRI_FACILITY_ID = NULL, FACILITY_NAME = NULL, STREET_ADDRESS = NULL, 
    CITY_NAME = NULL, COUNTY_NAME = NULL, STATE_COUNTY_FIPS_CODE = NULL, STATE_ABBR = NULL, 
    ZIP_CODE = NULL, REGION = NULL, FAC_CLOSED_IND = NULL, MAIL_NAME = NULL, MAIL_STREET_ADDRESS = NULL, 
    MAIL_CITY = NULL, MAIL_STATE_ABBR = NULL, MAIL_PROVINCE = NULL, MAIL_COUNTRY = NULL, 
    MAIL_ZIP_CODE = NULL, ASGN_FEDERAL_IND = NULL, ASGN_AGENCY = NULL, FRS_ID = NULL, 
    PARENT_CO_DB_NUM = NULL, PARENT_CO_NAME = NULL, FAC_LATITUDE = NULL, FAC_LONGITUDE = NULL, 
    PREF_LATITUDE = NULL, PREF_LONGITUDE = NULL, PREF_ACCURACY = NULL, PREF_COLLECT_METH = NULL, 
    PREF_DESC_CATEGORY = NULL, PREF_HORIZONTAL_DATUM = NULL, PREF_SOURCE_SCALE = NULL, 
    PREF_QA_CODE = NULL, ASGN_PARTIAL_IND = NULL, ASGN_PUBLIC_CONTACT = NULL, ASGN_PUBLIC_PHONE = NULL, 
    ASGN_PUBLIC_CONTACT_EMAIL = NULL, BIA_CODE = NULL, STANDARDIZED_PARENT_COMPANY = NULL, 
    ASGN_PUBLIC_PHONE_EXT = NULL) {
    
    args <- list(TRI_FACILITY_ID = TRI_FACILITY_ID, FACILITY_NAME = FACILITY_NAME, 
        STREET_ADDRESS = STREET_ADDRESS, CITY_NAME = CITY_NAME, COUNTY_NAME = COUNTY_NAME, 
        STATE_COUNTY_FIPS_CODE = STATE_COUNTY_FIPS_CODE, STATE_ABBR = STATE_ABBR, 
        ZIP_CODE = ZIP_CODE, REGION = REGION, FAC_CLOSED_IND = FAC_CLOSED_IND, MAIL_NAME = MAIL_NAME, 
        MAIL_STREET_ADDRESS = MAIL_STREET_ADDRESS, MAIL_CITY = MAIL_CITY, MAIL_STATE_ABBR = MAIL_STATE_ABBR, 
        MAIL_PROVINCE = MAIL_PROVINCE, MAIL_COUNTRY = MAIL_COUNTRY, MAIL_ZIP_CODE = MAIL_ZIP_CODE, 
        ASGN_FEDERAL_IND = ASGN_FEDERAL_IND, ASGN_AGENCY = ASGN_AGENCY, FRS_ID = FRS_ID, 
        PARENT_CO_DB_NUM = PARENT_CO_DB_NUM, PARENT_CO_NAME = PARENT_CO_NAME, FAC_LATITUDE = FAC_LATITUDE, 
        FAC_LONGITUDE = FAC_LONGITUDE, PREF_LATITUDE = PREF_LATITUDE, PREF_LONGITUDE = PREF_LONGITUDE, 
        PREF_ACCURACY = PREF_ACCURACY, PREF_COLLECT_METH = PREF_COLLECT_METH, PREF_DESC_CATEGORY = PREF_DESC_CATEGORY, 
        PREF_HORIZONTAL_DATUM = PREF_HORIZONTAL_DATUM, PREF_SOURCE_SCALE = PREF_SOURCE_SCALE, 
        PREF_QA_CODE = PREF_QA_CODE, ASGN_PARTIAL_IND = ASGN_PARTIAL_IND, ASGN_PUBLIC_CONTACT = ASGN_PUBLIC_CONTACT, 
        ASGN_PUBLIC_PHONE = ASGN_PUBLIC_PHONE, ASGN_PUBLIC_CONTACT_EMAIL = ASGN_PUBLIC_CONTACT_EMAIL, 
        BIA_CODE = BIA_CODE, STANDARDIZED_PARENT_COMPANY = STANDARDIZED_PARENT_COMPANY, 
        ASGN_PUBLIC_PHONE_EXT = ASGN_PUBLIC_PHONE_EXT)
    ret <- envir_get(tri_facility, args)
    
    ret
} 
