#' Retrieve tri reporting form data from tri database
#' 
#' @param DOC_CTRL_NUM e.g. '1300140000011'. See Details.
#' @param ACTIVE_STATUS e.g. '1'. See Details.
#' @param TRI_FACILITY_ID e.g. '15902CCKRN75BRI'. See Details.
#' @param TRI_CHEM_ID e.g. 'N982'. See Details.
#' @param FORM_TYPE_IND e.g. 'L'. See Details.
#' @param REPORTING_YEAR e.g. '2000'. See Details.
#' @param CERTIF_NAME e.g. 'LARRY E. CAPROUS'. See Details.
#' @param CERTIF_OFFICIAL_TITLE e.g. 'PRESIDENT'. See Details.
#' @param PARTIAL_FAC e.g. '0'. See Details.
#' @param ENTIRE_FAC e.g. '1'. See Details.
#' @param MAX_AMOUNT_OF_CHEM e.g. '04'. See Details.
#' @param CERTIF_SIGNATURE e.g. 'O'. See Details.
#' @param CERTIF_DATE_SIGNED e.g. '23-FEB-01'. See Details.
#' @param POSTMARK_DATE e.g. '26-FEB-01'. See Details.
#' @param PUBLIC_CONTACT_PERSON e.g. 'BARRY R. HEIDER'. See Details.
#' @param PUBLIC_CONTACT_PHONE e.g. '814 535 3293'. See Details.
#' @param ADDITIONAL_DATA_IND e.g. '0'. See Details.
#' @param ONE_TIME_RELEASE_QTY e.g. '0'. See Details.
#' @param ONE_TIME_RELEASE_QTY_NA e.g. '0'. See Details.
#' @param PRODUCTION_RATIO e.g. '1.25'. See Details.
#' @param PRODUCTION_RATIO_NA e.g. '0'. See Details.
#' @param MIXTURE_NAME e.g. 'NA'. See Details.
#' @param RECEIVED_DATE e.g. '28-FEB-01'. See Details.
#' @param REVISION_NA e.g. '0'. See Details.
#' @param ORIG_POSTMARK e.g. '26-FEB-01'. See Details.
#' @param ORIG_RECEIVED e.g. '28-FEB-01'. See Details.
#' @param FEDERAL_FAC_IND e.g. '0'. See Details.
#' @param GOCO_FLAG e.g. '0'. See Details.
#' @param GENERIC_CHEM_NAME e.g. 'NA'. See Details.
#' @param CAS_CHEM_NAME e.g. 'ZINC COMPOUNDS'. See Details.
#' @param TRADE_SECRET_IND e.g. '0'. See Details.
#' @param SANITIZED_IND e.g. '0'. See Details.
#' @param DIOXIN_DISTRIBUTION_NA e.g. '0'. See Details.
#' @param DIOXIN_DISTRIBUTION_1 e.g. 'NA'. See Details.
#' @param DIOXIN_DISTRIBUTION_2 e.g. 'NA'. See Details.
#' @param DIOXIN_DISTRIBUTION_3 e.g. 'NA'. See Details.
#' @param DIOXIN_DISTRIBUTION_4 e.g. 'NA'. See Details.
#' @param DIOXIN_DISTRIBUTION_5 e.g. 'NA'. See Details.
#' @param DIOXIN_DISTRIBUTION_6 e.g. 'NA'. See Details.
#' @param DIOXIN_DISTRIBUTION_7 e.g. 'NA'. See Details.
#' @param DIOXIN_DISTRIBUTION_8 e.g. 'NA'. See Details.
#' @param DIOXIN_DISTRIBUTION_9 e.g. 'NA'. See Details.
#' @param DIOXIN_DISTRIBUTION_10 e.g. 'NA'. See Details.
#' @param DIOXIN_DISTRIBUTION_11 e.g. 'NA'. See Details.
#' @param DIOXIN_DISTRIBUTION_12 e.g. 'NA'. See Details.
#' @param DIOXIN_DISTRIBUTION_13 e.g. 'NA'. See Details.
#' @param DIOXIN_DISTRIBUTION_14 e.g. 'NA'. See Details.
#' @param DIOXIN_DISTRIBUTION_15 e.g. 'NA'. See Details.
#' @param DIOXIN_DISTRIBUTION_16 e.g. 'NA'. See Details.
#' @param DIOXIN_DISTRIBUTION_17 e.g. 'NA'. See Details.
#' @param PUBLIC_CONTACT_EMAIL e.g. 'NA'. See Details.
#' @param REVISION_CODE_1 e.g. 'NA'. See Details.
#' @param REVISION_CODE_2 e.g. 'NA'. See Details.
#' @param MEDIA_TYPE e.g. 'M'. See Details.
#' @param PUBLIC_PHONE_EXT e.g. 'NA'. See Details.
#' @param PROD_RATIO_OR_ACTIVITY e.g. 'NA'. See Details.
#' @export

tri_tri_reporting_form <- function(DOC_CTRL_NUM = NULL, ACTIVE_STATUS = NULL, TRI_FACILITY_ID = NULL, 
    TRI_CHEM_ID = NULL, FORM_TYPE_IND = NULL, REPORTING_YEAR = NULL, CERTIF_NAME = NULL, 
    CERTIF_OFFICIAL_TITLE = NULL, PARTIAL_FAC = NULL, ENTIRE_FAC = NULL, MAX_AMOUNT_OF_CHEM = NULL, 
    CERTIF_SIGNATURE = NULL, CERTIF_DATE_SIGNED = NULL, POSTMARK_DATE = NULL, PUBLIC_CONTACT_PERSON = NULL, 
    PUBLIC_CONTACT_PHONE = NULL, ADDITIONAL_DATA_IND = NULL, ONE_TIME_RELEASE_QTY = NULL, 
    ONE_TIME_RELEASE_QTY_NA = NULL, PRODUCTION_RATIO = NULL, PRODUCTION_RATIO_NA = NULL, 
    MIXTURE_NAME = NULL, RECEIVED_DATE = NULL, REVISION_NA = NULL, ORIG_POSTMARK = NULL, 
    ORIG_RECEIVED = NULL, FEDERAL_FAC_IND = NULL, GOCO_FLAG = NULL, GENERIC_CHEM_NAME = NULL, 
    CAS_CHEM_NAME = NULL, TRADE_SECRET_IND = NULL, SANITIZED_IND = NULL, DIOXIN_DISTRIBUTION_NA = NULL, 
    DIOXIN_DISTRIBUTION_1 = NULL, DIOXIN_DISTRIBUTION_2 = NULL, DIOXIN_DISTRIBUTION_3 = NULL, 
    DIOXIN_DISTRIBUTION_4 = NULL, DIOXIN_DISTRIBUTION_5 = NULL, DIOXIN_DISTRIBUTION_6 = NULL, 
    DIOXIN_DISTRIBUTION_7 = NULL, DIOXIN_DISTRIBUTION_8 = NULL, DIOXIN_DISTRIBUTION_9 = NULL, 
    DIOXIN_DISTRIBUTION_10 = NULL, DIOXIN_DISTRIBUTION_11 = NULL, DIOXIN_DISTRIBUTION_12 = NULL, 
    DIOXIN_DISTRIBUTION_13 = NULL, DIOXIN_DISTRIBUTION_14 = NULL, DIOXIN_DISTRIBUTION_15 = NULL, 
    DIOXIN_DISTRIBUTION_16 = NULL, DIOXIN_DISTRIBUTION_17 = NULL, PUBLIC_CONTACT_EMAIL = NULL, 
    REVISION_CODE_1 = NULL, REVISION_CODE_2 = NULL, MEDIA_TYPE = NULL, PUBLIC_PHONE_EXT = NULL, 
    PROD_RATIO_OR_ACTIVITY = NULL) {
    
    args <- list(DOC_CTRL_NUM = DOC_CTRL_NUM, ACTIVE_STATUS = ACTIVE_STATUS, TRI_FACILITY_ID = TRI_FACILITY_ID, 
        TRI_CHEM_ID = TRI_CHEM_ID, FORM_TYPE_IND = FORM_TYPE_IND, REPORTING_YEAR = REPORTING_YEAR, 
        CERTIF_NAME = CERTIF_NAME, CERTIF_OFFICIAL_TITLE = CERTIF_OFFICIAL_TITLE, 
        PARTIAL_FAC = PARTIAL_FAC, ENTIRE_FAC = ENTIRE_FAC, MAX_AMOUNT_OF_CHEM = MAX_AMOUNT_OF_CHEM, 
        CERTIF_SIGNATURE = CERTIF_SIGNATURE, CERTIF_DATE_SIGNED = CERTIF_DATE_SIGNED, 
        POSTMARK_DATE = POSTMARK_DATE, PUBLIC_CONTACT_PERSON = PUBLIC_CONTACT_PERSON, 
        PUBLIC_CONTACT_PHONE = PUBLIC_CONTACT_PHONE, ADDITIONAL_DATA_IND = ADDITIONAL_DATA_IND, 
        ONE_TIME_RELEASE_QTY = ONE_TIME_RELEASE_QTY, ONE_TIME_RELEASE_QTY_NA = ONE_TIME_RELEASE_QTY_NA, 
        PRODUCTION_RATIO = PRODUCTION_RATIO, PRODUCTION_RATIO_NA = PRODUCTION_RATIO_NA, 
        MIXTURE_NAME = MIXTURE_NAME, RECEIVED_DATE = RECEIVED_DATE, REVISION_NA = REVISION_NA, 
        ORIG_POSTMARK = ORIG_POSTMARK, ORIG_RECEIVED = ORIG_RECEIVED, FEDERAL_FAC_IND = FEDERAL_FAC_IND, 
        GOCO_FLAG = GOCO_FLAG, GENERIC_CHEM_NAME = GENERIC_CHEM_NAME, CAS_CHEM_NAME = CAS_CHEM_NAME, 
        TRADE_SECRET_IND = TRADE_SECRET_IND, SANITIZED_IND = SANITIZED_IND, DIOXIN_DISTRIBUTION_NA = DIOXIN_DISTRIBUTION_NA, 
        DIOXIN_DISTRIBUTION_1 = DIOXIN_DISTRIBUTION_1, DIOXIN_DISTRIBUTION_2 = DIOXIN_DISTRIBUTION_2, 
        DIOXIN_DISTRIBUTION_3 = DIOXIN_DISTRIBUTION_3, DIOXIN_DISTRIBUTION_4 = DIOXIN_DISTRIBUTION_4, 
        DIOXIN_DISTRIBUTION_5 = DIOXIN_DISTRIBUTION_5, DIOXIN_DISTRIBUTION_6 = DIOXIN_DISTRIBUTION_6, 
        DIOXIN_DISTRIBUTION_7 = DIOXIN_DISTRIBUTION_7, DIOXIN_DISTRIBUTION_8 = DIOXIN_DISTRIBUTION_8, 
        DIOXIN_DISTRIBUTION_9 = DIOXIN_DISTRIBUTION_9, DIOXIN_DISTRIBUTION_10 = DIOXIN_DISTRIBUTION_10, 
        DIOXIN_DISTRIBUTION_11 = DIOXIN_DISTRIBUTION_11, DIOXIN_DISTRIBUTION_12 = DIOXIN_DISTRIBUTION_12, 
        DIOXIN_DISTRIBUTION_13 = DIOXIN_DISTRIBUTION_13, DIOXIN_DISTRIBUTION_14 = DIOXIN_DISTRIBUTION_14, 
        DIOXIN_DISTRIBUTION_15 = DIOXIN_DISTRIBUTION_15, DIOXIN_DISTRIBUTION_16 = DIOXIN_DISTRIBUTION_16, 
        DIOXIN_DISTRIBUTION_17 = DIOXIN_DISTRIBUTION_17, PUBLIC_CONTACT_EMAIL = PUBLIC_CONTACT_EMAIL, 
        REVISION_CODE_1 = REVISION_CODE_1, REVISION_CODE_2 = REVISION_CODE_2, MEDIA_TYPE = MEDIA_TYPE, 
        PUBLIC_PHONE_EXT = PUBLIC_PHONE_EXT, PROD_RATIO_OR_ACTIVITY = PROD_RATIO_OR_ACTIVITY)
    ret <- envir_get("tri_reporting_form", args)
    
    ret
} 
