#' Retrieve tri transfer qty data from tri database
#' 
#' @param DOC_CTRL_NUM e.g. '1300140000011'. See Details.
#' @param TRANSFER_LOC_NUM e.g. '0'. See Details.
#' @param OFF_SITE_AMOUNT_SEQUENCE e.g. '0'. See Details.
#' @param TYPE_OF_WASTE_MANAGEMENT e.g. 'P91'. See Details.
#' @param TRANSFER_RANGE_CODE e.g. '3'. See Details.
#' @param TOTAL_TRANSFER e.g. 'NA'. See Details.
#' @param TRANSFER_EST_NA e.g. '0'. See Details.
#' @param TRANSFER_BASIS_EST_CODE e.g. 'M '. See Details.
#' @param POTW_PERCENTAGE_TO_81C e.g. 'NA'. See Details.
#' @param POTW_PERCENTAGE_TO_81D e.g. 'NA'. See Details.
#' @param POTW_PERCENTAGE_TO_87 e.g. 'NA'. See Details.
#' @param POTW_PERCENTAGE_PROVIDED e.g. 'NA'. See Details.
#' @export

tri_tri_transfer_qty <- function(DOC_CTRL_NUM = NULL, TRANSFER_LOC_NUM = NULL, OFF_SITE_AMOUNT_SEQUENCE = NULL, 
    TYPE_OF_WASTE_MANAGEMENT = NULL, TRANSFER_RANGE_CODE = NULL, TOTAL_TRANSFER = NULL, 
    TRANSFER_EST_NA = NULL, TRANSFER_BASIS_EST_CODE = NULL, POTW_PERCENTAGE_TO_81C = NULL, 
    POTW_PERCENTAGE_TO_81D = NULL, POTW_PERCENTAGE_TO_87 = NULL, POTW_PERCENTAGE_PROVIDED = NULL) {
    
    args <- list(DOC_CTRL_NUM = DOC_CTRL_NUM, TRANSFER_LOC_NUM = TRANSFER_LOC_NUM, 
        OFF_SITE_AMOUNT_SEQUENCE = OFF_SITE_AMOUNT_SEQUENCE, TYPE_OF_WASTE_MANAGEMENT = TYPE_OF_WASTE_MANAGEMENT, 
        TRANSFER_RANGE_CODE = TRANSFER_RANGE_CODE, TOTAL_TRANSFER = TOTAL_TRANSFER, 
        TRANSFER_EST_NA = TRANSFER_EST_NA, TRANSFER_BASIS_EST_CODE = TRANSFER_BASIS_EST_CODE, 
        POTW_PERCENTAGE_TO_81C = POTW_PERCENTAGE_TO_81C, POTW_PERCENTAGE_TO_81D = POTW_PERCENTAGE_TO_81D, 
        POTW_PERCENTAGE_TO_87 = POTW_PERCENTAGE_TO_87, POTW_PERCENTAGE_PROVIDED = POTW_PERCENTAGE_PROVIDED)
    ret <- envir_get("tri_transfer_qty", args)
    
    ret
} 
